### ISSUE TITLE
Add ability to set prices for different classes of storage in my on prem environment.

### ISSUE THREAD

**Issue by srpomeroy** [opencost/opencost#1008]
**What problem are you trying to solve?**
The ability to assign different prices for different classes of storage for the PVs in my on-prem environment.

**Describe the solution you'd like**
To be able to assign different prices for storage classes based on names and/or labels.

**Describe alternatives you've considered**
None.

**How would users interact with this feature?**
Using the custom CSV provider pipeline to build a price list for storage classes.

**Comment by AjayTripathy** [comment]
This has yet to be prioritized, @srpomeroy please let me know if this is pressing or blocking.

**Comment by philimonoff** [comment]
+1 to this issue. It blocks from using opencost in on-prem or non-GCP/AWS/Azure clusters with different storage classes.

**Comment by Adam-Stack-PM** [comment]
@philimonoff, Thanks for the up vote. This is a very helpful signal to what is important to the Opencost community.

**Comment by dwbrown2** [comment]
The ability to configure complex discounts or tiered pricing like this is accessible Free/Community Kubecost. It's a fair amount amount of configuration/integration code, docs, etc that would need to be brought to OpenCost. 

Early community discussion felt this was beyond the needs of most teams, so I think we need to revisit this decision.
