### ISSUE TITLE
Ability to filter out project-level information at the time of CUR ingestion

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#1033]
We would like to filter out data at the project level.  As opposed to filtering it out from the front end, we would prefer to have it filtered out at the time of CUR ingestion.

**Comment by dwbrown2** [comment]
Thanks for submitting, @kirbsauce! Can you share more about why this would be valuable? 

cc @Sean-Holcomb and @AjayTripathy for further input

**Comment by kirbsauce** [comment]
Sure @dwbrown2 .  There are simply those projects they're never interested in seeing. You could constantly filter everything on the UI, or preprocess the CUR before KC processing, or have it filtered while importing. @AjayTripathy , am I capturing the spirit of the ask?

**Comment by Sean-Holcomb** [comment]
A short term fix for this for AWS users is to put their data into a view which excludes the accounts they are not interested in. For a more general solution, assets could be filtered by Kubecost properties (account, project, label), this wouldn't help with build times, but hopefully helpful with query times. As some push back, isn't this functionality what reports are supposed to accomplish?

**Comment by dwbrown2** [comment]
I like this suggestion! @kirbsauce any feedback?

**Comment by AjayTripathy** [comment]
That works short term for a class of users not using our beta "no-athena" mode. We still likely want to do this.

**Comment by Adam-Stack-PM** [comment]
@kirbsauce @dwbrown2 I'm still learning here, but two concerns. 

1) What is essential to one stakeholder may differ from another.  As we expand in an organization, IT may want something very from finance. 

2) Having the full CUR could make auditing numbers much simpler.

To accomplish the spirit of the ask.  We could allow the user to set up groups and configure a pre-filter in the settings.

**Comment by dwbrown2** [comment]
Based on my understanding of these requirements, is that a combinations of 1) advanced reporting and 2) CUR views would help address but let me know if that's overlooking a core need

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
