### ISSUE TITLE
[Suggestion] Support storage class in cost model

### ISSUE THREAD

**Issue by behofer** [opencost/opencost#1067]
## Summary
We are working with different, partially on-prem, storage providers that have different pricing models (e.g. NFS and longhorn storage).

## Suggestions:
Add support for different storage classes in cost model

## Goal
The user has the ability to have different prices for storage, dependent on the storage classes in a cluster.

This can also be regarded as discussion if similar features exist or are already plant.

gz#1413

**Comment by AjayTripathy** [comment]
Hi @behofer have you seen:
https://github.com/kubecost/cost-model/issues/1008

Would that satisfy your usecase? If so could you +1 that issue and we can merge the two?

**Comment by behofer** [comment]
Hi @AjayTripathy yes, I haven't seen #1008 - it indeed addresses our requirements.
So you can link those two.

**Comment by ivankube** [comment]
These issues are linked now.
