### ISSUE TITLE
kubecost.com fails to render in Firefox

### ISSUE THREAD

**Issue by MarkSRobinson** [opencost/opencost#1068]
Going to https://www.kubecost.com/ renders a blank page when viewed with Firefox.  Disabling extensions does not solve the issue.  Visiting with a private tab also does not fix the issue.  The page renders correctly in Chrome.

gz#1418

**Comment by kbrwn** [comment]
@MarkSRobinson Thanks for reporting this. We will get it looked at right away.

**Comment by dwbrown2** [comment]
@AjayTripathy @nealormsbee can you please review this morning? 

Thanks for reporting @MarkSRobinson

**Comment by dwbrown2** [comment]
This should now be addressed, Thanks, @nealormsbee!

All good for you @MarkSRobinson? Thanks again for reporting.

**Comment by MarkSRobinson** [comment]
Yup, it's rendering correctly now

**Comment by dwbrown2** [comment]
Great, thank you again!
