### ISSUE TITLE
More flexible node pricing for On-Prem use-case

### ISSUE THREAD

**Issue by everpeace** [opencost/opencost#1095]
## The Problem

Currently, kubecost supports multiple [pricing providers](https://github.com/kubecost/cost-model/tree/develop/pkg/cloud). I think [CSVProvider](https://github.com/kubecost/cost-model/blob/develop/pkg/cloud/csvprovider.go) or [CustomProvider](https://github.com/kubecost/cost-model/blob/develop/pkg/cloud/customprovider.go) would be options for On-Prem use-cases.

In my on-prem cluster, there are several generations of nodes and they have their own cpu-types, memory-size and gpu-types. Thus, I would like to set prices on each resource type(CPU, RAM, GPU) in each generation of node independently. 

For example:
- 1st-gen nodes
  - cpu: $C1/core*hour
  - mem: $M1/GiB*hour
  - gpu: $G1/hour
- 2nd-gen nodes
  - cpu: $C2/core*hour
  - mem: $M1/GiB*hour (I think memory price would be the same in our case)
  - gpu: $G2/hour
- 3rd-gen nodes
  - …

If I understood correctly, it looks like both providers can not cover the case. CustomProvider can set price on [CPU,RAM,GPU but only support three node types (i.e. "default", "default,spot", "default,gpu")](https://github.com/kubecost/cost-model/blob/v1.91.0-rc.2/pkg/cloud/customprovider.go#L168-L180). CSVProvider can support [multiple types of nodes by `instanceType` or `instanceIdField`](https://github.com/kubecost/cost-model/blob/v1.91.0-rc.2/pkg/cloud/csvprovider.go#L45-L46) but can only set [MarketPriceHourly](https://github.com/kubecost/cost-model/blob/v1.91.0-rc.2/pkg/cloud/csvprovider.go#L47). Am I correct?

## Proposal

How about introducing a flexible node pricing provider such that it extracts node price information for each resource from node labels or annotations? For other price information(network, loadbalancers, etc.) the provider can rely on CustomProvider like CSVProvider. Then, the user can have full control to configure the price for each node like this:

```yaml
kind: Node
metadata
  name: node-a
  annotations:
    price.kubecost.com/cpu: "xx"
    price.kubecost.com/ram: "yy"
    price.kubecost.com/gpu: "zz"
```

In this case, I suppose users will set `USE_NODE_ANNOTATION_PROVIDER` envvar at cost-model startup like [`USE_CSV_PROVIDER`](https://github.com/kubecost/cost-model/blob/v1.91.0-rc.2/pkg/cloud/provider.go#L473-L475).

gz#1456

**Comment by keithhand** [comment]
Hi @everpeace, for some added context, I think you have a solid understanding of how the CustomProviders and CSVProvider classes work. If you have a set pricing model, you can assign catch-all categories for custom CPU, RAM, and GPU costs. Then, if you need multiple types of nodes, you would use the CSVProvider to load a CSV with your on-prem node data. To calculate the MarketPriceHourly for that CSV, you use [this formula](https://github.com/kubecost/cost-model#how-do-you-determine-ramcpu-costs-for-a-node-when-this-data-isnt-provided-by-a-cloud-provider), which should help to get you accurate per-node pricing. Would this fit your use case?

**Comment by everpeace** [comment]
Thanks, @keithhand for your quick reply.

> To calculate the MarketPriceHourly for that CSV, you use [this formula](https://github.com/kubecost/cost-model#how-do-you-determine-ramcpu-costs-for-a-node-when-this-data-isnt-provided-by-a-cloud-provider), which should help to get you accurate per-node pricing. Would this fit your use case?

In our cluster, both CPU pods (that requests no GPUs) and GPU pods (that requests some GPUs) are scheduled to GPU nodes. 

For example:
- node-A: 36 CPU, 380Gi, 8 GPUs
- two pods are running on node-A
  - pod-X: 10CPU, 100Gi, 0GPUs
  - pod-Y: 26CPU, 280Gi, 8GPUs

In this case, [the mentioned formula](https://github.com/kubecost/cost-model#how-do-you-determine-ramcpu-costs-for-a-node-when-this-data-isnt-provided-by-a-cloud-provider) would not be enough because the formula normalizes the hourly cost of the node.  We would not like to cost pod-X for GPUs.

**Comment by keithhand** [comment]
@everpeace, I think that shows a perfect use case for us extending this support; thank you! I'm going to tag this issue to ensure our engineering team can also look at how we might better prioritize this.

**Comment by everpeace** [comment]
@keithhand I noticed an example described in https://github.com/kubecost/cost-model/issues/1095#issuecomment-1058743730 can be applied in GPU instances in public cloud.  
 Even in a public cloud environment, if users scheduled CPU pods (requesting no GPUs) to GPU nodes, price information per resource type will be required.

**Comment by AjayTripathy** [comment]
Hi @everpeace we've updated documentation to note that gpu requests are taken into account. While we understand the label -> resource cost mapping and it's an interesting feature, your current use case should be covered by the automatic distribution of node costs into resources. Pods on the node don't share prices evenly, but by resource allocation so in your example pod x won't be costed for gpu.

**Comment by keithhand** [comment]
Hi @everpeace, I wanted to check back in to see if Ajay's comment cleared things up for you regarding the distribution of GPU prices. Let me know if there's anything else I can help clarify.

**Comment by keithhand** [comment]
Hey @everpeace, just circling back on this to see if there was anything else we can do to clear things up. If not, let me know, and I can get this issue closed out for you.

**Comment by keithhand** [comment]
Hi @everpeace. I'm going to mark this as closed, as I believe Ajay was able to answer your questions here. If you still need any assistance, please feel free to re-open this, join our [Slack community](https://join.slack.com/t/kubecost/shared_invite/enQtNTA2MjQ1NDUyODE5LWFjYzIzNWE4MDkzMmUyZGU4NjkwMzMyMjIyM2E0NGNmYjExZjBiNjk1YzY5ZDI0ZTNhZDg4NjlkMGRkYzFlZTU), or email us at support@kubecost.com, and someone will be happy to assist. Have a great day!
