### ISSUE TITLE
Pricing on extended resource other than GPUs

### ISSUE THREAD

**Issue by everpeace** [opencost/opencost#1096]
Do you have a plan to support pricing [extended resources](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/#assign-an-extended-resource-to-a-pod) other than GPUs in cost-model? It seems that the current node cost model is somewhat [static (CPU, RAM, GPU)](https://github.com/kubecost/cost-model/blob/v1.91.0-rc.2/pkg/costmodel/aggregation.go#L55-L76).

We have on-prem clusters that　equip our own accelerator devices that are available on our k8s clusters as an extended resource by our own custom device plugin.

I would be glad to hear your plan for supporting the price for extended resources.

**Comment by AjayTripathy** [comment]
Hi @everpeace this sounds like a great feature request. Maybe we'd create a mapping of pod: request and then import a pricing sheet for those definitions?

**Comment by everpeace** [comment]
> Maybe we'd create a mapping of pod: request and then import a pricing sheet for those definitions?

Yes, I think so overall.  But I think price information should be loaded from various methods (because I'm not sure what 'sheet' means).

And, for a long-term goal, I think GPU would be treated as this mechanism, too.

**Comment by AjayTripathy** [comment]
A pricing sheet is a CSV as defined here: 
https://github.com/kubecost/cost-model/blob/develop/configs/pricing_schema.csv

We could adapt the AssetClass field to be arbitrary, but we'd still need to know a prometheus metric that is emitted to capture which pod requested it.

**Comment by everpeace** [comment]
> A pricing sheet is a CSV as defined here:

AS I mentioned in https://github.com/kubecost/cost-model/issues/1095#issuecomment-1058743730, there is a case in which normalized `MarketPriceHourly` does not fit. So, I suppose that a more generic method that can configure prices per resource would be needed (for example, my proposal described in #1095).

**Comment by AjayTripathy** [comment]
Hey @everpeace the documentation is a little out of date-- that formula extends to GPUs. We should update the documentation. I've filed https://github.com/kubecost/cost-model/issues/1105

**Comment by mattray** [comment]
We'll be discussing external asset costs and forming a working group to write a specification at tomorrow's OpenCost Working Group meeting: 
https://docs.google.com/document/d/1ZCMdRfP0DUCU5Ygk6Epy3tLJhscv46HvnU3Uez4HtQQ/edit#

**Comment by boniek83** [comment]
I'm not sure if this is a good place to mention this but currently only nvidia gpus are supported. What about amd and intel (both have datacenter gpu's for ML workloads with kubernetes device plugins).

**Comment by AjayTripathy** [comment]
Hey @boniek83 happy to support this. Want to open a separate issue to track and so we can add more information?

**Comment by AjayTripathy** [comment]
As some additional context @boniek83 when we first added gpu support there weren't amd/intel k8s device plugins, but would love to find out more if there are!

**Comment by mattray** [comment]
Removing the `stale` tag, work is being done and we hope to have something relatively soon.

**Comment by onlygo** [comment]
Will the new feature also support different pricing for different GPU types? Even within Nvidia GPUs, the actual pricing can be vastly different (e.g. H100 vs A40).
