### ISSUE TITLE
Outlier detection can prevent ingesting new data

### ISSUE THREAD

**Issue by nikovacevic** [opencost/opencost#1098]
We check "outlier" data by comparing one datum to the average of recent data, dropping a datum if its value exceeds 30x the average of historic values. (I don't know any more details, but @nealormsbee can possibly help.) It seems that sometimes that will prevent ingestion of real data, especially after configuration changes are made that will cause such an anticipated spike.

Proposed solutions include:
* make the algorithm for outlier detection more sophisticated
* make outlier detection optional, defaulting to OFF, but with the possibility to turn ON easily

**Comment by nealormsbee** [comment]
^ No additional info really. a 30x price spike on node CPU or RAM cost relative to an in-memory running average results in dropping the data point.

PR for that code is https://github.com/kubecost/cost-model/pull/935
Written to address https://github.com/kubecost/cost-model/issues/927

I'm all for both proposed solutions

**Comment by kirbsauce** [comment]
@srpomeroy , the current plan is for @nealormsbee to build an image early next week which disables outlier detection.  At that point, you can test out if outlier detection is the culprit.  Sound good?

**Comment by srpomeroy** [comment]
Thanks, @kirbsauce! @nealormsbee I[ tweaked the code](https://github.com/kubecost/cost-model/blob/spom-outlier-removal-test/pkg/costmodel/metrics.go#L538-L556) and [rolled an image](https://hub.docker.com/r/srpomeroy/cost-model/tags) today and have it running in our AWS dev cluster. I would appreciate a second set of eyes to be sure I disabled it properly. Hopefully, it saves you some cycles as well.

**Comment by nealormsbee** [comment]
Those code changes look correct to me, @srpomeroy !

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
