### ISSUE TITLE
How do you get the cost allocation

### ISSUE THREAD

**Issue by hyj-github** [opencost/opencost#1101]
I can see the Cost of the pod on the Cost Allocation page. I want to know how does this work out exactly?
For example, using Kubecost to monitor the cost of an AWS cluster, there are two pods on one EC2, the first using 40% of EC2's resources, and the second using 10% of EC2's resources. Is the cost data ratio between them 4:1?
@kbrwn

gz#1459

**Comment by kbrwn** [comment]
Hi @hyj-github, in the scenario you describe kubecost collects pricing data about EC2 nodes from AWS then based on node price each container/pod is allocated cost per CPU-hour, GPU-hour, RAM-Gb-hour. This allocated cost reflects a percentage of the cost from the node where the workload was running. So yes the 4:1 ratio would be correct although other factors such as external costs or idle cost allocation could alter this cost ratio in the UI fairly easily.

**Comment by kbrwn** [comment]
@hyj-github Closing this issue out. Please email support@kubecost.com in the future with any follow up questions.
