### ISSUE TITLE
Update node->resource breakdown formula documentation to note GPUs are accounted for

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#1105]
https://github.com/kubecost/cost-model#how-do-you-determine-ramcpu-costs-for-a-node-when-this-data-isnt-provided-by-a-cloud-provider

We've already extended this forumla to cover GPUs-- we should update the docs.

**Comment by dwbrown2** [comment]
This feels really quick. Do you plan to tackle @AjayTripathy?

**Comment by AjayTripathy** [comment]
@biancaburtoiu and I are working on this one!
