### ISSUE TITLE
Using Kubecost with an Openstack infrastructure (custom prices)

### ISSUE THREAD

**Issue by maxime-sourdin** [opencost/opencost#1109]
Hello,
At my company, we are starting to implement a Kubecost, however part of our infrastructure is based on Openstack.

Kubestack does not support flavor billing, which results in correct usage patterns, but incorrect pricing.

I know that cloud providers offering openstack (like infomaniak: https://docs.infomaniak.cloud/user-guide/Billing_Metering_and_Rating/), are based on calculation modes similar to Kubecost (using metrics returned via openstack gnocchi), and convert to a fictitious currency, then to a real currency.

Are there any developments planned in kubecost to support flavor pricing? Possibly CSV loading of flavors or different network/disk/S3/Volume costs? (this seems to be complementary to #1095).

Best regards

gz#1498

**Comment by AjayTripathy** [comment]
Curious @maxime-sourdin is the flavor of the node written anywhere in the node label?  If so I think this becomes a lot easier to support, or even already possible with the CSV provider.

**Comment by maxime-sourdin** [comment]
From what I see on the infrastructure, I have labels like this:


```
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
failure-domain.beta.kubernetes.io/is-baremetal=false
failure-domain.beta.kubernetes.io/region=eu-west-0
failure-domain.beta.kubernetes.io/zone=eu-west0b
kubernetes.io/arch=amd64
kubernetes.io/availablezone=eu-west0b
topology.kubernetes.io/zone=eu-west-0b
type=small-node
node.kubernetes.io/instance-type=s3.4xlarge.4
```


with indeed the flavor indicated in labels

**Comment by AjayTripathy** [comment]
In that case, we should already be able to use custom pricing with flavors. Take a look at how the pricing CSV works:
https://github.com/kubecost/cost-model/blob/develop/configs/pricing_schema.csv

You can set InstanceID to the flavor and InstanceIDField to the label where you're reading flavor, eg:
InstanceID: small-node
InstanceIDField: spec.metadata.label.type

**Comment by ivankube** [comment]
@maxime-sourdin were you able to make custom pricing work with flavors?

**Comment by maxime-sourdin** [comment]
Hello @ivankube,
I was able to create a csv file with the flavors (approximately 200 lines!!!). As expected, there are some internal problems with the labels that made it difficult to create the csv file.

I have not yet been able to test the integration due to lack of time, sorry

**Comment by ivankube** [comment]
@maxime-sourdin it sounds like you can theoretically make custom pricing work with flavors. Thus, I'm going to close this issue. Please feel free to re-open if you'll face any issues.
