### ISSUE TITLE
Job costs attributed to the wrong namespace

### ISSUE THREAD

**Issue by mac-chaffee** [opencost/opencost#1110]
I have a strange bug where an old job (which doesn't use that many resources) in one namespace is showing up in kubecost with really high costs and in the wrong namespace.

Here is the job appearing in kubecost associated with the "monitoring" namespace (that's where kubecost is running, for the record)
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/7581860/157976521-bcc1f546-62ab-4af7-9b73-f232c1270709.png">

But that job is actually in the "translator-dev" namespace:

```
$ kubectl get job -A | grep nn-load-node-normalization-loader-con-0-job
translator-dev   nn-load-node-normalization-loader-con-0-job     1/1           15m        15d
```

Here is the job:

```
$ kubectl get job -n translator-dev nn-load-node-normalization-loader-con-0-job -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: nn-load
    meta.helm.sh/release-namespace: translator-dev
  creationTimestamp: "2022-02-24T13:20:56Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nn-load-node-normalization-loader-con-0-job
  namespace: translator-dev
  resourceVersion: "76419107"
  uid: 05ba3fe3-f34f-472d-8a8c-607845c26ac7
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 05ba3fe3-f34f-472d-8a8c-607845c26ac7
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 05ba3fe3-f34f-472d-8a8c-607845c26ac7
        job-name: nn-load-node-normalization-loader-con-0-job
      name: nn-load-node-normalization-loader-con-0-job
    spec:
      containers:
      - args:
        - GeneProtein.txt
        command:
        - /code/run_loader.sh
        image: renciorg/r3_nodenorm:2.0.5
        imagePullPolicy: IfNotPresent
        name: loader-container
        resources:
          limits:
            cpu: "2"
            memory: 10Gi
          requests:
            cpu: 250m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /code/run_loader.sh
          name: loader-config
          subPath: run_loader_conflation.sh
        - mountPath: /data
          name: data-dir
        - mountPath: /code/redis_config.yaml
          name: loader-config
          subPath: redis_config.yaml
        - mountPath: /code/config.json
          name: loader-config
          subPath: config-conflation0.json
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          name: nn-load-node-normalization-loader-loader-config
        name: loader-config
      - name: data-dir
        persistentVolumeClaim:
          claimName: nn-load-node-normalization-loader-conflation-0-pvc
status:
  completionTime: "2022-02-24T13:36:34Z"
  conditions:
  - lastProbeTime: "2022-02-24T13:36:34Z"
    lastTransitionTime: "2022-02-24T13:36:34Z"
    status: "True"
    type: Complete
  startTime: "2022-02-24T13:20:57Z"
  succeeded: 1
```

Also note that the job hasn't run in 15 days, but it still shows an exorbitant cost. The pod does still exist in a "Completed" state in the translator-dev namespace.

Any ideas?

Expand the box below for more info.

<details>
Kubecost version: 1.90.1

License: Community edition

values.yaml:

```
cost-analyzer:
  enabled: true
  readonly: true
  reporting:
    productAnalytics: false
    logCollection: false
    errorReporting: false
    valuesReporting: false
  prometheus:
    # Provided by kube-prometheus-stack
    kube-state-metrics:
      disabled: true
  global:
    grafana:
      enabled: false
      domainName: monitoring-grafana.monitoring
    prometheus:
      enabled: false
      fqdn: http://monitoring-kube-prometheus-prometheus.monitoring:9090
    notifications:
      alertmanager:
        enabled: false
        fqdn: http://monitoring-kube-prometheus-alertmanager.monitoring:9093
  kubecostToken: ""
  kubecost:
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
  kubecostModel:
    resources:
      requests:
        cpu: 500m
        memory: 2000Mi
      limits:
        cpu: 500m
        memory: 2000Mi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/auth-secret: monitoring-basicauth
      nginx.ingress.kubernetes.io/auth-type: basic
    hosts:
      - "<omitted>"
    tls:
      - hosts:
        - "<omitted>"
        secretName: "<omitted>-tls"
```
</details>

gz#1506

**Comment by mac-chaffee** [comment]
This may hint at the issue: It looks like something thinks every pod in the cluster is owned by this job's controller:

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/7581860/157983129-d1ef0036-fd2e-4e53-9925-53c5556e216a.png">

**Comment by mac-chaffee** [comment]
Oh I see that kubecost pulls that info from this query: https://github.com/kubecost/cost-model/blob/d5a0730b156656b26485298326e0f3bc61e1bb08/pkg/costmodel/allocation.go#L57

When I check the raw output of `kube_pod_owner{owner_kind="Job"}`, I see duplicate metrics, which lead me to finding this article: https://guide.kubecost.com/hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission

I'll try to fix the duplicate metrics, and see if it resolves this issue.

**Comment by AjayTripathy** [comment]
Hm. Thanks for this detailed bug report. It's surprising that every single pod, or a bunch of pods, shows up as having the same owner there on duplication. What does the raw output look like?

**Comment by mac-chaffee** [comment]
The raw output shows two copies of every job, one from my standalone kube-state-metrics (v2) and one from kubecost:

```
kube_pod_owner{container="kube-state-metrics", endpoint="http", instance="10.11.151.216:8080", job="kube-state-metrics", namespace="eds", owner_is_controller="true", owner_kind="Job", owner_name="compute-mbtiles-job-0-10-3994-2022031118-namforecast", pod="compute-mbtiles-job-0-10-3994-2022031118-namforecast-kfbbx", service="monitoring-kube-state-metrics", uid="39ce2cd8-d3f3-4526-9b7f-458a636593e0"}
...
kube_pod_owner{endpoint="tcp-model", exported_namespace="eds", exported_pod="compute-mbtiles-job-0-10-3994-2022031118-namforecast-kfbbx", instance="10.10.127.159:9003", job="monitoring-cost-analyzer", namespace="monitoring", owner_is_controller="true", owner_kind="Job", owner_name="compute-mbtiles-job-0-10-3994-2022031118-namforecast", pod="monitoring-cost-analyzer-9465d5545-vjw89", service="monitoring-cost-analyzer"}
```

**Comment by AjayTripathy** [comment]
I think I see the issue in your raw output here. the "pod" in kube_pod_owner here in the metric we emit is

`pod="monitoring-cost-analyzer-9465d5545-vjw89"`

...that is our pod. All emitted kube_pod_owners would emit that messing up our keying algorithm:

https://github.com/kubecost/cost-model/blob/d5a0730b156656b26485298326e0f3bc61e1bb08/pkg/costmodel/allocation.go#L1424

ie all pods would be given that controller. Is there some sort of relabeling going on causing pod to be set to that while exported_pod looks correct?

**Comment by AjayTripathy** [comment]
We can see if it's some sort of recording rule interfering by viewing our raw emitted metric at

<kubecost-url>/model/metrics and searching for kube_pod_owner.

**Comment by mac-chaffee** [comment]
Ah yes, I am scraping metrics from kubecost using a ServiceMonitor from https://prometheus-operator.dev/ , which does insert extra stuff in the metrics, including overwriting the value of "pod" to be the pod that Prometheus-operator scraped the metric from. Looks like I've forgotten to include `honorLabels: true` as mentioned in the docs: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "monitoring-kubecost"
spec:
  endpoints:
  - path: /metrics
    port: tcp-model
    interval: 1m
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: cost-analyzer
```

Setting `honorLabels: true` should fix the issue after that old data rotates out. Thanks!

**Comment by AjayTripathy** [comment]
Honor labels work out for you here?
