### ISSUE TITLE
Aggregating by label is not working in v1.91.2

### ISSUE THREAD

**Issue by ivankube** [opencost/opencost#1120]
Steps to reproduce:

1. - Add label to any pod.
2. - Aggregate by this label or by Pod and this label.

v.1.91.2
![Screen Shot 2022-03-16 at 5 38 46 PM](https://user-images.githubusercontent.com/97049075/158695659-4a88659b-80d9-42cb-b8cd-182a03a0cc90.png)

v.1.90.1
![Screen Shot 2022-03-16 at 5 22 47 PM](https://user-images.githubusercontent.com/97049075/158695735-aa939658-edaa-439b-aa56-52d25c4a81f8.png)

gz#1518

**Comment by AjayTripathy** [comment]
Seems to work for me?
![Screen Shot 2022-03-16 at 2 51 08 PM](https://user-images.githubusercontent.com/453512/158697348-d26b2fd3-24f5-4971-afb9-845f7105516a.png)

**Comment by ivankube** [comment]
Closing: It took some time for Kubecost to pick up the label.

![Screen Shot 2022-03-16 at 6 57 03 PM](https://user-images.githubusercontent.com/97049075/158704895-2581d1d0-f577-470e-b8b1-a19a864d4445.png)
