### ISSUE TITLE
Proxies when deploying kubecost

### ISSUE THREAD

**Issue by rumstead** [opencost/opencost#1139]
Hello,

We set [proxies](https://github.com/kubecost/cost-analyzer-helm-chart/blob/c98f4856bc96d50c5a8a775547ac8ce539e7037b/cost-analyzer/values.yaml#L179) on our kubecost deployment so it can access our central Prometheus running outside of our clusters. 

What we quickly realized is, if we rebuild the cluster and the internal IP of the API server changes, our deployment doesn't work. 

Could we set the no_proxy to include the APIServer IP by default in the code? We can do something similar [as the rest clients](https://github.com/kubernetes/kubernetes/blob/9c97ae286c4dbce137a35fdb3dd79dd2866e71f8/staging/src/k8s.io/client-go/rest/config.go#L517). Happy to submit a PR.

Or is there a better way of doing this?

**Comment by ErnestG4** [comment]
@rumstead thanks for reaching out. It would indeed be helpful to submit a PR if you have a moment to do so. Even if it's not the solution we ultimately go with, it's something we need to consider.

Will

**Comment by rumstead** [comment]
Added a WIP PR. I will add tests and such if the overall approach is ok.

**Comment by dramich** [comment]
Hey @rumstead, this can be addressed by setting the no_proxy value to a CIDR notation for your cluster network range. This usually defaults to `10.43. 0.0/16` but depends on how you provisioned your cluster, the provider and if it was overridden when the cluster was created. If you are unsure [this answer](https://stackoverflow.com/a/61685899) has a reliable way to see what your CIDR is. 

Usually, when setting PROXY and NO_PROXY there are multiple values that should be added to NO_PROXY to ensure the pod is able to communicate with things as expected i.e. `localhost`

We don't want to hard-code this value as it will break other users who intend to proxy API calls.

**Comment by rumstead** [comment]
> Hey @rumstead, this can be addressed by setting the no_proxy value to a CIDR notation for your cluster network range. This usually defaults to 10.43. 0.0/16 but depends on how you provisioned your cluster, the provider and if it was overridden when the cluster was created. If you are unsure [this answer](https://stackoverflow.com/a/61685899) has a reliable way to see what your CIDR is.

Yup that will definitely work. If you have clusters that span different cloud providers and have some onprem, that CIDR range isn't always the same. It results in many `value.yaml` overrides. 

> Usually, when setting PROXY and NO_PROXY there are multiple values that should be added to NO_PROXY to ensure the pod is able to communicate with things as expected i.e. localhost

Completely agree, the PR respects whatever additional `NO_PROXY` is set. 

> We don't want to hard-code this value as it will break other users who intend to proxy API calls.

Makes sense

**Comment by dramich** [comment]
> Yup that will definitely work. If you have clusters that span different cloud providers and have some onprem, that CIDR range isn't always the same. It results in many `value.yaml` overrides.

It would be 1 per cluster being deployed into, yes. If you are rolling through clusters that often I would hope there is some automation behind cluster creation/deletion. 

Does this work for your use case? If so can we close this issue?

**Comment by rumstead** [comment]
Gitops and capi is our automation 🙂
