### ISSUE TITLE
Kubecost is miscalculating storage costs when using gp3 volumes

### ISSUE THREAD

**Issue by gkaskonas** [opencost/opencost#1145]
GP3 volumes can be configured to have higher throughput and IOPS count which costs more money. This is not reflected in kubecost analysis at all making costs inacurate, especially when using large volumes.

For example:
If you have a 4TB gp3 volume, daily costs with default IOPS/throughput is ~11$ but with max IOPS/througput it becomes ~14$. That is a big difference, especially at scale.

Is there a way kubecost could get the information from AWS more accurately?

gz#1627

**Comment by kbrwn** [comment]
HI @gkaskonas There may be some hardcoded disk prices in the frontend that are related to this issue. I will request one of our engineers review how this may be resulting in inconsistent disk prices. 

cc @nealormsbee @mbolt35

**Comment by nealormsbee** [comment]
That is indeed what's happening. Self-assigning this issue and will investigate what it would take to use more nuanced / correct disk pricing pulled from cloud providers

**Comment by dwbrown2** [comment]
@nealormsbee why would reconciliation not be correctly attributing?

**Comment by nealormsbee** [comment]
Reconciliation should be attributing correctly. It might be that I misunderstand the original issue or should ask for clarity.

The frontend-coded prices are used in specific places -- savings, audit.html, metric.html, real-time.html.

In places like Allocation / Asset views, we're just be reading reconciled costs, which should be accurate. Or at least, I don't know why they wouldn't be accurate.

**Comment by dwbrown2** [comment]
@gkaskonas can you clarify where you're seeing this behavior and if you have a completed a cloud integration with your AWS account?

**Comment by gkaskonas** [comment]
I see it in the Assets page.

Below is a disk that uses gp3, 16000IOPS and 1000 Mb/s throughput. This should cost about 14$ a day but it's showing 10.77$.
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/57504623/162377377-bf5ee36b-9eab-4e17-8821-7e7a89ef8df7.png">

The Cloud Integration tab shows everything is good except the Spot instances feed (We don't use spot instances at this time)
<img width="757" alt="image" src="https://user-images.githubusercontent.com/57504623/162377655-df16b59c-8ab8-4bbc-8c35-d5efe5891f9e.png">

We have not set up CUR integration as of yet but it's something we are considering.

**Comment by gkaskonas** [comment]
On the cost allocation page, I see the same figure.

We have 14 pods using the same EBS volume type.

Kubecost reports $150.82 cost for 1 day for that stateful set.

$150.82 / 14 = $10.77 which is not correct because it's assuming that we are using default gp3 IOPS/Throughput settings.

**Comment by kbrwn** [comment]
@gkaskonas The green check next to Savings Plan, Reserved Instances, and Out-Of-Cluster data available is usually an indication that you have set up the CUR integration.

Would it be possible for you to show the price of this EBS volume in the aws cost explorer?

**Comment by gkaskonas** [comment]
Hi, I was away on a holiday for the past couple of weeks. I will get back to you as soon as I can.

**Comment by gkaskonas** [comment]
![image](https://user-images.githubusercontent.com/57504623/164454391-5b5a8fd6-02c0-443b-b3fe-d57d7f7a959b.png)

This is the price of the volume in 1 day (01/04/2022)

**Comment by AjayTripathy** [comment]
Hi @gkaskonas just want to note one possibility-- though I'm not sure it's the issue. I see no "Adjustment" figure in the kubecost report, which means the data wasn't available in the AWS CUR. AWS CUR data can lag by up to two days. Can I see a single disk cost for 1d from >48h ago?

**Comment by gkaskonas** [comment]
@AjayTripathy You want this from kubecost report?
![image](https://user-images.githubusercontent.com/57504623/165701353-1560ed62-e2f3-48b2-b942-79978f1a2741.png)
Here is a report for the disk over 7 days.
In Cost explorer the same volume is $92.66 over 7 days

**Comment by AjayTripathy** [comment]
Hi @gkaskonas what would be most useful is looking at a single PV for a single day older than 48h on the assets page with the adjustment column, and that same PV in the cost explorer for the same day. You can find that PV in kubecost by going to Assets > Kubernetes > Disks and modifying the window as well as filtering by a relevant provider ID.

**Comment by gkaskonas** [comment]
These PVs are months old and no adjustments have been made.
Like I said, I did not configure CUR integration so Kubecost is most likely misreporting the fact that it can read CUR reports

**Comment by AjayTripathy** [comment]
Thanks @gkaskonas ... I'll look into the reason for the misconfiguration. We would basically expect that these prices would not be accurate without configuring the cost and usage report-- our recommendation for accurate pricing for your gp3 volumes would be to integrate the CUR.

**Comment by AjayTripathy** [comment]
To be clear-- could you set up the CUR and let me know if the issue still persists for disk costs > 48h old with reconciliation data? On our side we're investigating why the the diagnostics appear to be wrong for you. https://github.com/kubecost/cost-model/issues/1190

**Comment by gkaskonas** [comment]
I will let you know once the CUR integration is set up

**Comment by gkaskonas** [comment]
With CUR enabled, Kubecost is reporting the volume as US$14.26 per day which is correct. I think this can be closed
