### ISSUE TITLE
opentelemetry integration

### ISSUE THREAD

**Issue by smitthakkar96** [opencost/opencost#1146]
In order to monitor kubecost it's better if kubecost is instrumented with opentelemetry. We can then export this to services like Datadog or jager

gz#1630

**Comment by dwbrown2** [comment]
Hi @smitthakkar96, can you share more on a particular use case you have in mind? Do you have a specific data set you want to export? My understanding is that we support the OpenTelemetry spec in our Prom metrics but can take a closer look in specific areas of interest to you.

**Comment by smitthakkar96** [comment]
I would like to monitor kube-cost like an application running in production, monitoring based on logs isn't great and I am looking to have traces so I can export this to tools like datadog or elasticsearch and see it in APM. 

Basically something like this https://opentelemetry.io/docs/instrumentation/go/

PS: I am happy to contribute if it's something the maintainers see value in having

**Comment by smitthakkar96** [comment]
@dwbrown2 regarding metrics I left a comment in another issue https://github.com/kubecost/cost-model/issues/264#issuecomment-1091665054
