### ISSUE TITLE
Add configurable profile to Request Sizing Recommendations

### ISSUE THREAD

**Issue by ivankube** [opencost/opencost#1153]
There are three available profiles: dev, prod, and HA.  Can we add custom profile where user can configure any aim for resource utilization?

gz #1650

**Comment by srpomeroy** [comment]
Or even be able to adjust the target utilization for the existing profiles.

**Comment by dwbrown2** [comment]
Thanks for reporting, have a particular situation in mind? This can already be done in the backing APIs in case that helps anyone's immediate need. 

I see the obvious desire to have more flexibility, but think we need to get this some closer thought ahead of 1.94

**Comment by kbrwn** [comment]
We have received this feedback in a customer call: "The savings tool is not useful to teams who have specific resource utilization targets that do not match the default. Having hardcoded numbers on this page is too simplistic an I feel that my engineering/devops teams will not take the recommendations seriously without the ability to provide a custom profile"

**Comment by dwbrown2** [comment]
Hoping to have this reviewed in next release! I think it fits nicely with the work being done there.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).

**Comment by pierluigilenoci** [comment]
OpenCost's (formerly KubeCost) approach to handling open tickets never disappoints (I'm ironic).

**Comment by srpomeroy** [comment]
FWIW Kubecost supports a custom profile.
