### ISSUE TITLE
AWS External resource label matching fails

### ISSUE THREAD

**Issue by jonerer** [opencost/opencost#1154]
Thanks for a great project! It's given us great insights. But I have a question: How can we get AWS external resource tagging to work? We're trying to get Department to work. We've followed the guide at https://guide.kubecost.com/hc/en-us/articles/4407596810519-AWS-Out-of-Cluster-

In General settings, we've set up "Department Label" to "app.kubernetes.io/part-of",
Our k8s resources have the label app.kubernetes.io/part-of: winter-road-insights.
Our S3 bucket has the tag kubernetes_label_app.kubernetes.io/part-of	winter-road-insights

And if we check the "Assets" page for the bucket, it shows up with "kubernetes_label_app_kubernetes_io_part_of=winter-road-insights" (see screenshot)

But on the "Cost allocation" page, when sorting by Department, only the k8s resources show up. External shows as 0. Is there anything we should change?

![Screenshot 2022-04-13 at 09 49 36](https://user-images.githubusercontent.com/130371/163129461-43fbd7de-1257-4e1b-8c61-7be068275436.png)
![Screenshot 2022-04-13 at 09 51 55](https://user-images.githubusercontent.com/130371/163129464-45282fb9-27b3-47c3-9193-4b79772138ef.png)
![Screenshot 2022-04-13 at 09 54 01](https://user-images.githubusercontent.com/130371/163129466-64ce4b2a-b662-4ffd-b64d-a0b784a55666.png)
![Screenshot 2022-04-13 at 10 04 37](https://user-images.githubusercontent.com/130371/163129911-39b254ea-42b9-49eb-84e0-6d74b1b3a236.png)

**Comment by jcharcalla** [comment]
@jonerer I'm going to close this and work through the ticket created via Slack. If this turns out to be a bug we will create a new github issue.
