### ISSUE TITLE
Cost for persistent disk not found

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1161]
Hi,

I see the following messages in the logs:

```
1 gcpprovider.go:906] Persistent Volume pricing not found for resizable-balanced: us-central1,pd-balanced
```

```
% k get storageclass resizable-balanced -o yaml                                                                                                                                                            
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2021-11-03T20:20:18Z"
  name: resizable-balanced
  resourceVersion: "1019803742"
  uid: 0ef93dfa-f7bc-4450-9b55-b10a7abee50b
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

This is on GCP.  Is there something I am missing?  I did setup a connection to external billing, if that matters at all. There are many of such errors, all, I believe, using the same provisioner...

App version: 1.92.0

Thank you
Dan

gz#1675<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1675'>Zendesk ticket #1675</a>)</i>

**Comment by keithhand** [comment]
Hi @DanTulovsky, I believe this is because there isn't a custom pricing option for this specific StorageClass, and it is mainly a notification to let you know that object will use a default pricing model. However, I'm not 100% certain of that. Let me tag @nealormsbee to see if he is more familiar with this.

**Comment by DanTulovsky** [comment]
Ok, I just wanted to make sure this doesn't mean that these PDs are being ignored...

**Comment by nealormsbee** [comment]
@DanTulovsky @keithhand you're right on. The GCP cloud billing API didn't return custom pricing data for that storage. It won't be ignored; it will be priced using default storage pricing.

**Comment by keithhand** [comment]
Perfect; thank you for the clarification, Neal! I will close this out as it seems we have figured out the root issue.

**Comment by DanTulovsky** [comment]
And that pricing is presumably based on the type?

parameters:
  type: pd-balanced

**Comment by keithhand** [comment]
It gets based on a concatenation of the region and that type (us-central1,pd-balanced), but that will be the main factor.

**Comment by DanTulovsky** [comment]
Ah ok. I wasn't sure if I should be concerned or not...
