### ISSUE TITLE
Failure to save report

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1162]
Hi,

I am getting a 400 error trying to save a report:

```
{"window":"7d","aggregateBy":"label:app","chartDisplay":"treemap","rate":"cumulative","idle":"shareByCluster","filters":[],"sharedOverhead":null,"sharedNamespaces":null,"sharedLabels":null,"title":"Cumulative cost for last 7 days by App"}
```

The response is a 400 error with: `invalid report: %!s(<nil>)`

The report itself displays just fine.

App version: 1.92.0

thank you
Dan

gz#1676

**Comment by DanTulovsky** [comment]
It seems like the problem is just with `treemap`. The others save just fine.

**Comment by kaelanspatel** [comment]
Hi Dan,

Thanks for the bug report! I think I see the problem. 

We'll get this fixed in the next release.

**Comment by dwbrown2** [comment]
Thanks for the report, Dan! cc @AdamStack18 to add to 1.93 release.
