### ISSUE TITLE
Error: "have relation but no coeff"

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1163]
Hi,

I am seeing the following error in the logs:

```
"[Warning] CostModel.ComputeAllocation: allocation cluster-one/mynamespace/mystatefulset/myapp and PVC mypvc have relation but no coeff"
```

Is this a concern?  myapp does use mypvc.

Thank you
Dan

gz#1678

**Comment by kbrwn** [comment]
@DanTulovsky It is just a warning. It is not critical error. You will find there are many logs and warnings that are present in the kubecost logs that are not completely comprehensible or useful.

**Comment by DanTulovsky** [comment]
Ok thank you.

**Comment by kirbsauce** [comment]
@DanTulovsky , thanks for the question!  Apologies for the inconvenience.  If there are any other logs which you have a concern with please let us know.  Slack and/or support@kubecost.com are also great ways to pose these questions.  Slack is especially useful as it gives more exposure to our large community there.  Thanks for using kubecost!
