### ISSUE TITLE
Pre-cache Cluster Sizing Recommendations?

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1164]
Hi,

Is it possible to somehow pre-cache the Cluster Sizing Recommendations (and other) pages?  Sometimes they are very slow to come up. I assume it's rebuilding the information.  This isn't the sort of data that needs to be up to the minute fresh (for us at least), so if it just updated itself in the background and showed whatever the last result was, that would be fine and improve the user experience substantially.

Thank you
Dan

gz#1679

**Comment by DanTulovsky** [comment]
Related: https://github.com/kubecost/cost-model/issues/1165

**Comment by jcharcalla** [comment]
@DanTulovsky Thank you for the suggestion. We have several performance and caching improvements in the works which should improve the UI performance.

Jason

**Comment by AjayTripathy** [comment]
@kaelanspatel is working on exactly that! We'll be computing this data from our ETL cache of prometheus metrics starting in v1.93

**Comment by dwbrown2** [comment]
However, when recording rules are available this should be reasonably fast on most clusters... something else may be going on here.

**Comment by AjayTripathy** [comment]
Yeah, if recording rules are available I tend to agree-- couple more notes on slowness here: https://github.com/kubecost/cost-model/issues/1165#issuecomment-1102830786

**Comment by DanTulovsky** [comment]
How fast is reasonably fast? It seems to take 2 min right now..

**Comment by dwbrown2** [comment]
I would call < 15 seconds reasonably performant. Sounds like we have a major improvement here.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
