### ISSUE TITLE
Cluster Sizing Recommendations: Error and Very Slow

### ISSUE THREAD

**Issue by DanTulovsky** [opencost/opencost#1165]
Hi,

When I click through to the "Cluster Sizing Recommendations" view, the javascript console starts to spit out 404 errors:

```
Request URL: https://kubecost.public.lightstep.io/cluster/status
Request Method: GET
Status Code: 404 
Remote Address: 34.117.136.203:443
Referrer Policy: strict-origin-when-cross-origin
```

And otherwise it's just spinning... I am not sure how long this should take. This is a cluster of about 350 nodes.

Thank you
Dan

gz#1680

**Comment by DanTulovsky** [comment]
fwiw, on the staging install (much smaller cluster) I also get the 404 errors in the logs, so those seem to be a red herring.  And this one comes up very quickly (about 20 nodes).

**Comment by DanTulovsky** [comment]
It's not been many minutes, and there is still no data.. I don't see anything obvious in the logs.
<img width="1761" alt="Screen Shot 2022-04-19 at 10 06 33 AM" src="https://user-images.githubusercontent.com/509887/164022733-c26a50fc-034a-4284-96b4-1746b7b17f34.png">

**Comment by DanTulovsky** [comment]
It's not our of cpu or memory...

<img width="993" alt="Screen Shot 2022-04-19 at 10 07 43 AM" src="https://user-images.githubusercontent.com/509887/164022957-da8284c6-cf1a-412f-a4a3-38381b7ecdc1.png">

**Comment by DanTulovsky** [comment]
I wonder if this is related...

The prometheus server seems to also have plenty of cpu/memory... 

<img width="1315" alt="Screen Shot 2022-04-19 at 10 20 17 AM" src="https://user-images.githubusercontent.com/509887/164025557-9034aaa4-0968-4d00-af55-fff805b2d5c2.png">

**Comment by DanTulovsky** [comment]
It looks like they timeout after 1 min...

**Comment by DanTulovsky** [comment]
After a couple of restarts of both server and prometheus, diagnostics is now coming back ok... but the recommendation page still isn't working.  Some console error messages.  Those 502s must be coming from prometheus again?


<img width="1743" alt="Screen Shot 2022-04-19 at 11 09 17 AM" src="https://user-images.githubusercontent.com/509887/164035981-d00c6e70-3ee6-4667-b54b-8a1d85b32990.png">

**Comment by kbrwn** [comment]
@DanTulovsky It doesn't seem like prometheus or kubecost is stable. This would be expected behavior if this is the case. You should look into the resource usage of both prometheus and kubecost-cost-analyzer pods and ensure these pods are not getting OOM'd or CPU throttled or frequently restarting.

**Comment by DanTulovsky** [comment]
They are not.. they both seem to have enough resources.  For example, right now on the "Reserved Instances" savings page it's also timing out. The console shows a bunch of failures like this:

```
https://kubecost.public.lightstep.io/model/prometheusQueryRange?query=sum(kube_pod_container_resource_requests%7Bresource%3D%22cpu%22%2C%20unit%3D%22core%22%7D)&start=2022-03-20T04%3A00%3A00.000Z&end=2022-04-19T15%3A11%3A16.194Z&duration=1h&window=1h
```

All with a 502.  I can run that query just fine on the prometheus server itself though.  And now, I just refreshed the page, and it loaded almost instantly. (Is this data cached?)

**Comment by DanTulovsky** [comment]
Here's the prometheus server:

<img width="993" alt="Screen Shot 2022-04-19 at 11 20 08 AM" src="https://user-images.githubusercontent.com/509887/164038319-5814a31f-9e37-422c-9359-2c09bf657197.png">

Here's kubecost:

<img width="998" alt="Screen Shot 2022-04-19 at 11 20 35 AM" src="https://user-images.githubusercontent.com/509887/164038400-102ae95d-c430-42e7-8ae0-4cddd7b7622d.png">

**Comment by DanTulovsky** [comment]
But the "Cluster Sizing Recommendations" page is still not working.  I am not sure what else to look for. Is there some fundamental mistake I am making here for the size of the cluster we have? It's 384  nodes.

**Comment by kbrwn** [comment]
@DanTulovsky If you can fetch a [heap/profile](https://guide.kubecost.com/hc/en-us/articles/4407595921431) while attempting to load the cluster-sizing page that may provide more info.

**Comment by DanTulovsky** [comment]
I get a 502 when trying to get a profile.

<img width="884" alt="Screen Shot 2022-04-19 at 11 51 15 AM" src="https://user-images.githubusercontent.com/509887/164044471-7f6eb58f-be2b-4f7f-aa58-0c7e197c16e2.png">

I did get the heap file.

**Comment by AjayTripathy** [comment]
Hi @DanTulovsky , thanks for this report. I have a couple different theories:
1. What's the timeout between your ingress and kubecost? a 30s profile failing seems like it might be timing out.
2. If that's > 30s were there any restarts of the cost-analyzer-server pod?
3. Is this a standard installation of kubecost with the helm chart or are you using a byo-prometheus setup? If the latter, this page may require recording rules still to return.
4. We're re-doing the cluster-sizing API to be more performant and not depend on the results of live prometheus queries. But meanwhile, based on your notes about prometheus targets errors and the lack of prometheus restarts, is it possible there's some sort of networking error between kubecost and prometheus?

**Comment by DanTulovsky** [comment]
1.  I was just realizing this might be an issue :)  It was 30 seconds, I updated it to 120s and now I can get a profile.
2. No, no restarts of the cost anayzer or prometheus pods.
3. This is the standard helm chart install with the prometheus brought up by the chart.

**Comment by DanTulovsky** [comment]
I just posted the profile to slack: https://kubecost.slack.com/archives/CLFV60Y90/p1650389363028399

thank you!

**Comment by michaelmdresser** [comment]
I'm fairly certain the repeated 404 on `/cluster/status` isn't an indicator of the core of Kubecost failing -- I think the cluster sizing page checks that endpoint to see if the cluster controller is enabled for 1-click cluster sizing.

@kaelanspatel is the one who showed this behavior to me. Kaelan, does this description match what you were experiencing?

**Comment by DanTulovsky** [comment]
With the change to the ingress timeout to 120s (instead of 120) the page now loads, although it's not very fast.  It takes 2 min.. although maybe that's not slow :)

Caching this would be great.

Thank you all for your help!  Please feel free to close this, unless there is anything else I can provide here...

**Comment by michaelmdresser** [comment]
The cluster sizing recommendation should load much faster in the next release of Kubecost. We've made substantial improvements to the backing API. Give it a try when it comes out, and let us know if its still unreasonably slow!

**Comment by kaelanspatel** [comment]
@michaelmdresser Yes that's the behavior I was talking about. I've increased the interval to a minute to reduce some of the spam, but the 404 doesn't effect functionality in any way.
