### ISSUE TITLE
Replace klog with a new logging library

### ISSUE THREAD

**Issue by dramich** [opencost/opencost#1170]
This issue is to gather feedback on a replacements for klog

Currently klog presents us with some challenges:

1. The way it parses args [see here](https://github.com/kubecost/cost-model/issues/1122#issuecomment-1072622457)
2. It's slow (this is known and part of the reason k8s is moving to structured logging backed by zap)

Proposed solution:
1. Update our log package to use this new library and where a logger struct is referenced move to https://github.com/go-logr/logr
2. Replace klog inside the log package with https://github.com/rs/zerolog. 
3. Move all direct calls to klog over to the log library

**Comment by michaelmdresser** [comment]
I'm on board! A couple of questions:

1. Do we need `logr`? I'm not familiar with the library or where we would apply it.

2. Since zerolog supports structured logging, do you have any recommendations for what fields to log and when?

**Comment by dwbrown2** [comment]
Not sure what the lift is here, but would this be a good potential addition for 1.94?

**Comment by pierluigilenoci** [comment]
Klog also has another major problem: https://github.com/kubernetes/klog/issues/212

**Comment by michaelmdresser** [comment]
I believe this has been addressed in https://github.com/kubecost/cost-model/pull/1178. I'm going to close this issue -- feel free to reopen if needed.
