### ISSUE TITLE
Azure LB pricing is inaccurate

### ISSUE THREAD

**Issue by Sean-Holcomb** [opencost/opencost#1220]
Azure Load Balancer pricing is determined on a per SVC basis with pricing from this [page](https://azure.microsoft.com/en-us/pricing/details/load-balancer/). This is implemented [here](https://github.com/kubecost/cost-model/blob/3582bc7238d434254a972704cb17ec649c91fa01/pkg/cloud/azureprovider.go#L1066). However Load Balancer services in Kubernetes actually correspond to "Microsoft.Network/publicIPAddresses" which are priced using this [scheme](https://azure.microsoft.com/en-us/pricing/details/ip-addresses/). Particularly they seem to correspond to static ip addresses with standard pricing. To complicate matters further it appears that each Azure cluster has a "load balancer" that follows the first pricing model, and each additional k8s loadbalancer SVC counts as an additional "rule" in that pricing model, which means after 5 rules have been added, each additional rule increases the price $0.01/hr. 

To solve this problem there needs to be a per cluster load balancer cost which follows the original pricing model taking into account the number of k8s loadbalancer SVCs on the cluster. Additionally if other rules can be identified from the k8s api this should also be done. Finally there should be additional line items for each of the k8s loadbalancer SVCs using the second pricing model. This should accurately capture the in cluster costs of load balancing.

**Comment by zorrobyte** [comment]
Relevant case for tracking: https://kubecost.zendesk.com/agent/tickets/1659

**Comment by ErnestG4** [comment]
Due to the way load balancers are represented on AKS (a single LB with multiple public IPs), would it make sense to either consolidate LB objects per-cluster on Azure or take the line item for the Cluster's LB and divide it out by the number of LBs represented on the cluster itself?
