### ISSUE TITLE
Make namespace annotations/labels available when aggregating by namespace

### ISSUE THREAD

**Issue by rcallphin** [opencost/opencost#1223]
When using the allocations API you should be able to aggregate by namespace and specify explicitly the annotations/labels you want to be included in the properties field. Today, you can pull in annotations only if you specifically ask to aggregate by the annotation. The reason for this is the possibility for these values to conflict with more granular level objects like pods.  The feature request would be to enable the ability to specify specific annotations set at the namespace level to be authoritatively pulled in to the dataset when aggregating by namespace, regardless of conflicts with the lower level attributes. 

Use Case: As a K8S operator the ability is needed to tag namespaces with specific business related metadata that will be used in other admin processes. We need the ability to pull in that metadata through kubecost and not have it affected by other objects set within the namespace. 

gz#1868<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1868'>Zendesk ticket #1868</a>)</i>

**Comment by AjayTripathy** [comment]
Thanks for filing this @rcallphin . Historically our precedence model for labeling has been that conflicts are resolved from most specific (pod) to least specific (namespace). But the usecase makes sense here. We may want to make precedence configurable, and additionally add the labels to the aggregation.

**Comment by ameijer** [comment]
@rcallphin we can probably just roll up all namespace labels/annotations. What do you think about the following implementation? 

```
curl http://kubecost.xyz/model/allocation?window=7d&aggregate=namespace

"alex": {
        "name": "alex",
        "properties": {
          "cluster": "cluster-localrun-default",
          "namespace": "alex",
          "namespaceLabels": {
            "kubernetes_io_metadata_name": "alex",
            "name": "alex"
          },
          "namespaceAnnotations": {
            "com_kubecost_annotation": "myannotation"
          }
        },
...
```
