### ISSUE TITLE
Announcement: repo included in CNCF Submission!

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1224]
Kubecost has submitted this project to the Cloud Native Computing Foundation (CNCF) for onboarding under the new “OpenCost” effort. We are currently in the queue for review, and we’re excited to share updates on this mission as they develop.

From the start, our goal has been to enable teams using Kubernetes to operate with a single model for measuring and managing cost across all of their environments. We consistently hear from users and our partners that standardization across cloud platforms, Kubernetes distributions, and teams is strongly needed. To most effectively drive a standard, we feel it is important that OpenCost is not driven by any single entity—and that the project continues to evolve and thrive within the broader Kubernetes community. We believe the CNCF is the best organization to help with this goal.

The community of cloud industry leaders supporting OpenCost intend to develop industry documentation that standardize methodologies and best practices for tracking Kubernetes costs. Founding companies of the OpenCost community are all heavy adopters of Kubernetes and have experienced firsthand the gap around Kubernetes cost standards. If you are interested in joining the OpenCost community or interested in learning more, please join the [CNCF Slack community](https://cloud-native.slack.com/?redir=/archives/C03D56FPD4G) — we’d love to speak with you!

**Comment by dwbrown2** [comment]
Proud to report that the OpenCost project has been approved by the CNCF TOC and we are now going through onboarding!

**Comment by mattray** [comment]
Let's close this once https://github.com/cncf/cncf.io/issues/610 has been closed

**Comment by mattray** [comment]
Upstream updated.
