### ISSUE TITLE
SYNTAX_ERROR: line 4:25: Column 'line_item_usage_start_date' cannot be resolved

### ISSUE THREAD

**Issue by gkaskonas** [opencost/opencost#1227]
I am trying to set up CUR integration with kubecost but keep getting this error in athena.

Has anyone encountered this before?

`SYNTAX_ERROR: line 4:25: Column 'line_item_usage_start_date' cannot be resolved`
gz#1895<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1895'>Zendesk ticket #1895</a>)</i>

**Comment by gkaskonas** [comment]
This was simply bad configuration

**Comment by weiwuprojects** [comment]
@gkaskonas Do you remember what part of your conifguration was bad?

**Comment by Adam-Stack-PM** [comment]
@weiwuprojects, Are you experiencing the same error or have any additional info you can share?  

@jcharcalla, Could you keep eyes  on this issue and help support this ticket?
