### ISSUE TITLE
Update the main install page to remove links to guide.kubecost.com

### ISSUE THREAD

**Issue by alexkubecost** [opencost/opencost#1247]
From here, https://github.com/kubecost/opencost

The "Getting Started" section takes users to: https://guide.kubecost.com/hc/en-us/articles/4407601821207

Proposal is to instead of install documentation live within the opencost.io domain, instead of guides.kubecost.com.

gz#1943<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1943'>Zendesk ticket #1943</a>)</i>

**Comment by jcharcalla** [comment]
There is a docs page at https://www.opencost.io/docs/ we could change the link to, although it just points to github which ultimately sends you back to guide.kubecost.com

@kbrwn is it possible to add a second (guide.opencost.io) domain to the guide page?

**Comment by kbrwn** [comment]
@jcharcalla I am not involved in opencost.io/docs. I can set up a similar redirect server to guide like docs.kubecost.com (or a reverse proxy if the url being opencost.io is important.) Although I think that keeping kubecost/opencost docs separated is a good idea.

**Comment by stacy-tumarkin** [comment]
I think that even just having complete open source install instructions live within the opencost.io/docs page, with any links back to kubecost documentation (1) explicitly referenced as guides for using Kubecost as a recommended path, and (2) included after we discuss installing the open source tool as a standalone, would be a great first step.

**Comment by dwbrown2** [comment]
Yeah, I agree. I definitely think we need to have fully standalone opencost docs. We made the decision to pull them out piece by piece given there will be a lot to move over. The content should be very similar though.

**Comment by dwbrown2** [comment]
PR now open: https://github.com/kubecost/opencost-website/pull/10

**Comment by mattray** [comment]
This was fixed in a previous merge.
