### ISSUE TITLE
Assets : You are requesting more than 15 days

### ISSUE THREAD

**Issue by klemen-df** [opencost/opencost#1265]
I'm using the free tier with a limitation of 15 days of metrics.

In 'Assets' and 'Cost Allocation' I can only select 7days.

If I select 30 days, I get the warning about the limitation.

In some cases, like 'Right sizing your requests' I can select 30 (and I presume it only displays 15 days of data).

Is this a bug or a feature?

gz#2007<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2007'>Zendesk ticket #2007</a>)</i>

**Comment by jcharcalla** [comment]
@KlemenDanfoss Thank you for bringing this to our attention. 

I was able to reproduce the 'Right sizing your requests' page allowing a 30 day selection window when using the 15 day free tier. This appears to be a bug to me.

**Comment by jcharcalla** [comment]
Screenshot showing the 15 day warning on the assets.html page with a 30 day window..

<img width="1228" alt="Screen Shot 2022-06-17 at 10 47 31 AM" src="https://user-images.githubusercontent.com/17748044/174322721-d3c3cab5-9b84-407f-954c-4cf573f997c6.png">

Warning missing from the request-sizing.html page with a 30 day window.
<img width="1228" alt="Screen Shot 2022-06-17 at 10 48 34 AM" src="https://user-images.githubusercontent.com/17748044/174322760-2f948dec-77c3-4a11-a4f3-aec12a986189.png">

**Comment by jcharcalla** [comment]
@KlemenDanfoss In regards to the assets page... While there is not a "Last 15 days" selection available in the drop down menu, with the free version you can still select a custom date range of up to 15 days. Additionally in the address bar you can modify the window to `window=15d` to view the last 15 days.

**Comment by klemen-df** [comment]
Of course.  It would just be easier if '30 days' would work or if there would be a '15 days' selector.

**Comment by AjayTripathy** [comment]
Routing to @teevans -- sounds like we could quickly add a 15d dropdown on the frontend?

**Comment by teevans** [comment]
Absolutely, we'll get that added this release! Thanks for pointing this out @KlemenDanfoss!

**Comment by teevans** [comment]
@jjarrett21 - Let's get this knocked out this release!
