### ISSUE TITLE
Run kubecost locally

### ISSUE THREAD

**Issue by ShibraAmin18** [opencost/opencost#1268]
Can we run this tool on our local machine?

I want to set up this as when we need, we would be able to quickly run it by providing **GCP service account key** as an authentication method and check the cost for different clusters.

I see **helm** and **kubectl** method for installation but how can we run this on local linux machine not inside any k8s cluster ?

Also please confirm what is the role of **prometheus** in this setup?

**Comment by kbrwn** [comment]
Hello @ShibraAmin18 kubecost is designed to run on kubernetes.  If you are looking to run locally you can do so by deploying kubecost using a local k8s provider such a minikube, k3s, or docker-kubernetes.

**Comment by nealormsbee** [comment]
Closing.
