### ISSUE TITLE
Potential cAdvisor metrics label inconsistency

### ISSUE THREAD

**Issue by tdinucci** [opencost/opencost#1271]
I am running v1.94.3 and the diagnostics page shows the following warning:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/35197667/175042769-daf4f82e-1614-4325-9cbe-2819f96ecbb2.png">

I am a bit confused by this for the following reasons:
1. My cluster is running k8s v1.12 and cAdvisor labels are `pod_name` and `container_name`, rather than `pod` and `container`.
2. [Your Helm chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.94.3/cost-analyzer/charts/prometheus/values.yaml#L1206) seems to contain relabeling rules to rename `pod` and `container` labels so that they become `pod_name` and `container_name`
3. I've searched through your codebase and there appears to be a mixture of these labels referred to.  For example, [this query](https://github.com/kubecost/opencost/blob/e5dc00d4fb594f1f4b6dfc098414e09f6eec599f/pkg/costmodel/allocation.go#L29) filters on both `container` and `container_name`.  Due to the `container!=""` condition this will fail if there is no `container` label.

I'm hoping someone can help me understand if I've misconfigured something or if this is an issue.

Also, can you confirm that if I manage to resolve this problem it will help with my figures related to current usage and recommendations?  At the moment I'm just seeing zero values:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/35197667/175046669-c0d401e4-8b73-45cb-ab88-ba975ad0b1af.png">

gz#2025<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2025'>Zendesk ticket #2025</a>)</i>

**Comment by tdinucci** [comment]
FWIW I've updated my `metric_relabel_configs` so that cAdvisor series are now recorded with 4 labels (`pod`, `pod_name`, `container` and `container_name`) and this has resolved the warning and also the problem where I wasn't getting recommendations, etc.

**Comment by kirbsauce** [comment]
thanks for the update @tdinucci , and sorry for the delay!

**Comment by Adam-Stack-PM** [comment]
@tdinucci Is there anything else we can help with?

**Comment by AjayTripathy** [comment]
Let's add this mapping back to our documentation, with a note to support the new metrics relabel configs for versions up to I believe 1.13 @kirbsauce can you assign someone on support?

**Comment by Adam-Stack-PM** [comment]
@kirbsauce Friendly nudge. See the Above documentation request.  Possibly a good task for Brett?

**Comment by kirbsauce** [comment]
@keithhand and I are investigating the history.  Well, @keithhand is and I'm just trying to keep up.  Doc update forthcoming.

**Comment by keithhand** [comment]
@AjayTripathy I opened a PR [here](https://github.com/kubecost/docs/pull/300) with what I believe is the relevant information. Does that look right to you?

**Comment by AjayTripathy** [comment]
Left a few notes thanks!

**Comment by tdinucci** [comment]
Thanks for picking this up - the doc update is helpful :)

**Comment by AjayTripathy** [comment]
Thanks for the feedback! @keithhand anything stopping us from picking this up and merging?
