### ISSUE TITLE
Update OpenCost website slack link

### ISSUE THREAD

**Issue by alexkubecost** [opencost/opencost#1281]
All mentions of "Slack" on opencost.io need to redirect to this channel: https://cloud-native.slack.com/archives/C03D56FPD4G  

We are currently linking to the Kubecost organization which is now incorrect. 

These are the following areas that I see need updating.

**1) "Join Slack" on the Opencost.io header**

![Screen Shot 2022-06-27 at 11 17 29 AM](https://user-images.githubusercontent.com/89622567/176008875-030f6b60-c0b8-4d54-a672-afa7e1ef5331.png)

**2) Opencost.io  >  blog  >  bottom of page, "Try it yourself!" section**

![Screen Shot 2022-06-27 at 11 18 01 AM](https://user-images.githubusercontent.com/89622567/176008940-e0ca88da-7ba6-4b12-9e59-5a513dd22883.png)

**3) Website footer**

![Screen Shot 2022-06-27 at 11 19 12 AM](https://user-images.githubusercontent.com/89622567/176009135-b0930696-9928-48f6-8abb-45892bc68864.png)

**4) Opencost.io  >  Documentation  >  Advanced Configuration** 

![Screen Shot 2022-06-27 at 11 20 28 AM](https://user-images.githubusercontent.com/89622567/176009331-9dba5a96-3edc-4392-a15a-6d97f13245e8.png)

**5) Opencost.io  >  Documentation  >  Staying in the loop**

![Screen Shot 2022-06-27 at 11 20 46 AM](https://user-images.githubusercontent.com/89622567/176009396-1ef8390c-e70c-4daf-afa6-d1da29e4db39.png)

gz#2053<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2053'>Zendesk ticket #2053</a>)</i>

**Comment by dwbrown2** [comment]
@alexkubecost do you plan to take this one or need help?

**Comment by alexkubecost** [comment]
> @alexkubecost do you plan to take this one or need help?

@dwbrown2 Help would be great (and much much faster). @trentbroderick mentioned potentially taking this. Otherwise if we can triage as usual that works too.

**Comment by dwbrown2** [comment]
@srpomeroy is all over it!

**Comment by alexkubecost** [comment]
> 

Amazing let me know how I can help @srpomeroy

**Comment by srpomeroy** [comment]
See conversation in https://github.com/kubecost/opencost-website/pull/26

**Comment by Adam-Stack-PM** [comment]
@srpomeroy Great work!

**Comment by srpomeroy** [comment]
Closed with https://github.com/kubecost/opencost-website/pull/26

**Comment by dwbrown2** [comment]
Maybe out of scope on this issue but I believe there are 1-2 references in this repo too.

**Comment by srpomeroy** [comment]
> Maybe out of scope on this issue but I believe there are 1-2 references in this repo too.

Excellent catch @dwbrown2! See the above-mentioned PR.

**Comment by Adam-Stack-PM** [comment]
@srpomeroy and @alexkubecost Is the above PR still needed and if so is it ready to be reviewed and merged?

**Comment by alexkubecost** [comment]
@Adam-Stack-PM I defer to @srpomeroy , but these all look updated from my side.

**Comment by srpomeroy** [comment]
@Adam-Stack-PM Yes, still required. Should be a very simple review.

**Comment by srpomeroy** [comment]
It appears that I do not have the ability to assign a reviewer or labels since moving to the new opencost GH org.

**Comment by srpomeroy** [comment]
@Adam-Stack-PM You are free to close this issue as #1290 has been merged.

**Comment by mattray** [comment]
Verified and closed
