### ISSUE TITLE
Migrate exporter page to reference OpenCost

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1282]
As part of CNCF on-boarding, we'll want to change this file to reference OpenCost instead of Kubecost: https://github.com/kubecost/opencost/blob/develop/kubecost-exporter.md

**Comment by Adam-Stack-PM** [comment]
@avrodrigues5 Would you be game to take this issue?

**Comment by Adam-Stack-PM** [comment]
@dwbrown2 is jumping on this item.  For clarity we should update all references to Kubecost **EXCEPT** items that would cause the application to not work?   

Example: kubecost_cluster_management_cost

For clarity should we add a note to the document about the name change from Kubecost to Opencost? 

CC @avrodrigues5

**Comment by dwbrown2** [comment]
Yeah, it will be a broader discussion around breaking variable chances. 

@avrodrigues5 while this one should be quick, I'd vote we tackle the other CNCF onboarding tasks first! Can discuss more today.

**Comment by jessegoodier** [comment]
Should we move this to opencost-website/docs?

**Comment by dwbrown2** [comment]
Good call, I do think that would likely be better.

**Comment by jessegoodier** [comment]
I have "big" PR that is almost ready. when send for feedback. 

Just trying to wrap up what I had put together for the summit.

**Comment by mattray** [comment]
This was removed in https://github.com/opencost/opencost/pull/1280/files#diff-06a6a0129d193b9e9ea8ac26544568cc79168aefff3b8d18cc5e3ad3bdf50333
