### ISSUE TITLE
Add OpenCost to CNCF Sandbox page

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1285]
Submit a Pull request to add your project as a sandbox project to https://landscape.cncf.io/

**Comment by dwbrown2** [comment]
@AdamStack18 have you been able to find exactly where we submit this PR or have a couple example PRs for us to reference?

**Comment by dwbrown2** [comment]
Steps: https://github.com/cncf/landscape#new-entries

Example PR: https://github.com/cncf/landscape/pull/2611/files

I would propose we add to `Observability and Analysis - Continuous Optimization` category.

@AdamStack18 do we have SVG file we can share?

**Comment by AdamStack18** [comment]
https://docs.google.com/document/d/14anae77yAPlBMXJLUQ8eIx4Bu-WiSlNsvXEdxU_TBcg/edit

**Comment by Adam-Stack-PM** [comment]
Here is the file https://drive.google.com/file/d/1cRKV_WjbSw8ewWY3WazlBYE2iXufTwFf/view?usp=sharing

@avrodrigues5 If you need changes @Annalillie is your go to person.

**Comment by Annalillie** [comment]
Thanks for the tag @AdamStack18, feel free to reach out to me here or on Slack if you need anything @avrodrigues5

**Comment by avrodrigues5** [comment]
@dwbrown2 ,there's a kubecost entry under continuous optimization already, is it something that was previous done? PR for the same is : https://github.com/cncf/landscape/pull/2563

**Comment by dwbrown2** [comment]
Good catch, @avrodrigues5! Given OpenCost is a new project, we'll want to add a new entry. It will likely be similar, but I believe should reference we're a sandbox project like this entry: https://github.com/cncf/landscape/blob/5752aad46ec45793ed1a304a3c2f6038433d100d/landscape.yml#L88-L97

**Comment by avrodrigues5** [comment]
Hello @dwbrown2 , Please review the commit on forked branch of landscape repo 

https://github.com/cncf/landscape/compare/master...avrodrigues5:add_opencost_to_landscape:master

before raising PR against the original branch.

**Comment by dwbrown2** [comment]
I think for crunchbase we would want to put, or at least that's what other cncf projects do. 

```
crunchbase: https://www.crunchbase.com/organization/cloud-native-computing-foundation
```

also, i see other cncf projects have the following. should we include?

```
project: sandbox
```

otherwise, looks good!

**Comment by avrodrigues5** [comment]
Closing this Issue since the PR https://github.com/cncf/landscape/pull/2644 got merged. Will Reopen it if anything is pending related to this.
