### ISSUE TITLE
Add OpenCost project to https://github.com/cncf/contribute

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1286]
Example PR: https://github.com/cncf/contribute/pull/112/files

**Comment by avrodrigues5** [comment]
Hello @dwbrown2 , Please review the commit on forked branch of cncf/contribute repo 

https://github.com/cncf/contribute/compare/main...avrodrigues5:add_opencost_to_cncf:main

before raising PR against the original branch.

**Comment by dwbrown2** [comment]
For `Focus`, is there a set of predefined fields we have to fit into? If not, I may propose `Cost Monitoring`

**Comment by avrodrigues5** [comment]
looks like the https://github.com/cncf/landscape#new-entries says "We are unlikely to create a new category for products/projects as we'd rather find the best home with the current options." Doesn't state anything about procedure to create new entry.

**Comment by dwbrown2** [comment]
Definitely agree with that on the landscape page, but does that apply to this `Focus` column? 

One way to estimate... do other values align with landscape entries?

**Comment by avrodrigues5** [comment]
Looks like few entry like IoT, Edge, Tooling(landscape.yml has Tools), Load balancer and lot of other names are not available on landscape.yml. I think we can change focus area to `Cost Monitoring`.

**Comment by avrodrigues5** [comment]
Successfully Merged to cncf/contribute repo
