### ISSUE TITLE
Artwork: Submit a pull request tok with your artwork

### ISSUE THREAD

**Issue by Adam-Stack-PM** [opencost/opencost#1287]
Submit PR here: https://github.com/cncf/artwork
Files Needed:  https://drive.google.com/file/d/1cRKV_WjbSw8ewWY3WazlBYE2iXufTwFf/view?usp=sharing

Also need to research if we need to open a PR to add Opencost to the README doc or if CNCF will add it to the list for us.

**Comment by avrodrigues5** [comment]
Hello @dwbrown2 , Please review the commit on forked branch of artwork repo 

https://github.com/cncf/artwork/compare/master...avrodrigues5:add_opencost_to_artwork:master

before raising PR against the original branch.

**Comment by dwbrown2** [comment]
Don't know all the requirements here, but generally LGTM!

**Comment by avrodrigues5** [comment]
Successfully merged to cncf/artwork repo
