### ISSUE TITLE
Put you project in its own separate neutral github organization

### ISSUE THREAD

**Issue by Adam-Stack-PM** [opencost/opencost#1288]
As part of CNCF onboarding we need to migrate the Opencost repo to its own organization.

**Comment by Adam-Stack-PM** [comment]
@dwbrown2  @AjayTripathy Trying to get a sense of the work that will need to be completed to make this happen and identify any possible breaking variable changes.   Setting up this issue to start the discussion.  

Please disregard if this task is simpler than I'm thinking. 

CC @alexkubecost

**Comment by dwbrown2** [comment]
@AjayTripathy and @teevans already did this to create the OpenCost repo. This will be similar but just moving to github.com/opencost org. Plan is to do this after 1.95 release.

**Comment by Adam-Stack-PM** [comment]
Note adding v1.96 to track all work that we hope to complete over that period.  Can adjust as needed.

**Comment by mattray** [comment]
The project has been moved to https://github.com/opencost/opencost
