### ISSUE TITLE
opencost.io is unavailable

### ISSUE THREAD

**Issue by kamilsk** [opencost/opencost#1295]
Hi! Something went wrong with the domain

```bash
$ dig +noall +answer opencost.io
# nothing...
```

gz#2091<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2091'>Zendesk ticket #2091</a>)</i>

**Comment by jcharcalla** [comment]
Thank you for reporting this! We are investigating the cause of the outage.

**Comment by kamilsk** [comment]
maybe https://github.com/upptime/upptime will be useful

**Comment by dwbrown2** [comment]
Status available here: https://github.com/cncf/sandbox/issues/215

This was accidentally broken during transfer to Linux Foundation.

**Comment by Adam-Stack-PM** [comment]
Note to @Adam-Stack-PM check Opencost in the morning and close out issue when it is up.

**Comment by dwbrown2** [comment]
Now addressed, more detail here for those interested: https://github.com/cncf/sandbox/issues/215
