### ISSUE TITLE
Define a cost model for Serverless applications

### ISSUE THREAD

**Issue by skonto** [opencost/opencost#1298]
One common scenario requested by customers for on-premise setups is utilizing a Serverless solution and then try to separate costs based on some multi-tenancy story eg. distribute costs among teams, departments etc. Another topic is the cost model for the Serverless solution itself eg. bill per request or per K8s utilization or both etc. Or billing could happen even per time the container was active.
This issue should cover different scenarios such as Function as a Service (FaaS) eg. AWS Lambda, [serverless containers](https://knative.dev/docs/) etc. Any spec should also be in alignment with other efforts such [OpenTelemetry FaaS terminology](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/faas-metrics.md).

gz#2108<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2108'>Zendesk ticket #2108</a>)</i>

**Comment by dwbrown2** [comment]
@skonto thanks for filing! I view available serverless solutions (and we've had several community discussions) in two potential buckets:

1) solutions where the k8s api is exposed, e.g. knative 
2) solutions that are external to a cluster from an API standpoint, e.g. AWS Lambda

The former feels like a very natural and easy extension of the current OpenCost model, whereas the latter may fall into the  external cloud cost bucket given some of the core k8s concepts won't exist. 

If others agree with this framework, my proposal would be that we look at supporting solutions under group 1 very soon but that group 2 may require some more input.

**Comment by skonto** [comment]
Yes let's start with the first option. The second one probably requires cloud vendors participation.
How should we proceed with this?

**Comment by dwbrown2** [comment]
Talked with @maximilien at last OpenCost community meeting. Would you want to join that in the next couple weeks and we can discuss the best next steps then? Either that or we can start a doc soon for collaboration.
