### ISSUE TITLE
Network Traffic Cost Allocation is failing to measure ingress traffic 

### ISSUE THREAD

**Issue by fcomte** [opencost/opencost#1299]
I am facing an issue with my kubecost network traffic. 

When a kubernetes pod download data from Internet (let's say wget something) , I think kubecost does not see this network traffic ( maybe  the traffic is affected to the node IP and not to the pod IP. 
I have no problem to see : 
- internal traffic between pods
- egress traffic to Internet.

gz#2114<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2114'>Zendesk ticket #2114</a>)</i>

**Comment by mbolt35** [comment]
Hey @fcomte Thanks for filing the issue. We are currently only tracking `egress` traffic in the the application currently, but I believe there are plans to eventually support ingress costs. We are outputting `ingress` metrics which you could use to materialize your own view: `kubecost_pod_network_ingress_bytes_total`

This metric has the following labels:
* namespace: Namespace of the pod receiving the traffic. 
* pod_name: Pod receiving the traffic. 
* sameRegion: true if the traffic is coming from the same region
* sameZone: true if traffic is coming from the same zone. 
* service: Whether or not the data is coming from a specific service. ie: `gcp-artifactregistry`, `aws-s3`

**Comment by fcomte** [comment]
Yes but this counter is false in my case
 It does not count the ingress traffic coming from Internet

**Comment by Adam-Stack-PM** [comment]
@kaelanspatel Can you help triage this issue?

**Comment by kaelanspatel** [comment]
Hi @fcomte, can you clarify for me, are you seeing that the `kubecost_pod_network_ingress_bytes_total` metric is not emitting properly i.e. it doesn't show up, or is it that the numbers you're seeing aren't correct?

**Comment by aakanshaverma1310** [comment]
@fcomte  - How to set network cost in opencost? Can you please guide?

**Comment by mattray** [comment]
@aakanshaverma1310 right now OpenCost does not support network traffic costs. This is a feature of Kubecost, which is why I've tagged this issue with "kubecost" and hopefully we'll get it closed/migrated out of this repository.
