### ISSUE TITLE
Requested rows of Asset data which exceeds the limit of 75000

### ISSUE THREAD

**Issue by dschunack** [opencost/opencost#1301]
Hi,

we noticed some problems to visualize the Assets with v1.94 and all is related to Storage Assets.
The problem is the high amount of PVCs and Storage (60TB+) in the K8S. 
PVCs are created for a very short time to store artifacts and released after the job. 
kubecost lists more than 24000 Disks for the last 13 hours.  

All Time ranges are not working from 1d or longer for the Storage or global view. 

Is it possible to change the limit of 75000?

```
Requested 133877 rows of Asset data which exceeds the limit of 75000.
```

![Xnip2022-07-07_13-30-22](https://user-images.githubusercontent.com/19306599/177763566-ebb21b79-72ad-4804-a924-46d26ecd9c92.jpg)
![Xnip2022-07-07_13-30-39](https://user-images.githubusercontent.com/19306599/177763575-e1689b93-156b-40e2-af22-b0e090bdace0.jpg)

gz#2126<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2126'>Zendesk ticket #2126</a>)</i>

**Comment by Adam-Stack-PM** [comment]
@dschunack, thanks for this issue. 

@teevans @nealormsbee Getting this on your radar, any thoughts?

**Comment by nealormsbee** [comment]
This limit happens at the API level, it was put into place (I believe) to as a quick solution to prevent the Assets UI from locking up when too many values are returned.

The API does supply an option to bypass this limitation by adding `?noLimit=true` to the query. Maybe a decent UX is to let users control this `noLimit` parameter via some control in the UI?
I.e. "If you flip this switch, it is possible that you will query too much data and tank your software or lock up your browser, but if you want to try it then go ahead".

**Comment by teevans** [comment]
That's a good idea @nealormsbee - But, until we support that size of a data set I'm going to say we shouldn't enable that. We know the breaking point is right around there, and the experience of trying to view that data isn't going to be good anyhow, so I'd say let's punt on it until we get into the web workers.

**Comment by nealormsbee** [comment]
That works for me. Once we have the web workers that ceiling goes way up :+1:

**Comment by Adam-Stack-PM** [comment]
@sundeepghuman, I wanted to get this on your radar for upcoming work related to pagination and scale.

**Comment by AjayTripathy** [comment]
iirc this was more of a "the frontend is crashing" limitation than something on the backend necessarily. We should actually simulate a number of assets in the 500k range, bump the cap, and see what happens.

**Comment by teevans** [comment]
^^ This. I suspect we'll be able to tackle this sometime this month given the work being done on scale testing.

**Comment by Adam-Stack-PM** [comment]
@dschunack, Our engineering leads are working on a solution to remove this data cap.  I can not guarantee a timeframe, but it will likely be included in v1.97 or v1.98.

**Comment by Adam-Stack-PM** [comment]
@dschunack, This is still on our radar but not scheduled for a release at this time.

**Comment by dwbrown2** [comment]
I'd like to review with 1.99 now that we've scale tested new UI! @Adam-Stack-PM can we track?

**Comment by dschunack** [comment]
Thanks for the Update.

**Comment by Adam-Stack-PM** [comment]
@dschunack, This is not going to make v1.99. However, we are tracking it and will keep you updated as we get into v1.100.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
