### ISSUE TITLE
please add IBM cloud support

### ISSUE THREAD

**Issue by rpashko-lohika-tix** [opencost/opencost#1312]
please add IBM cloud support

gz#2159<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2159'>Zendesk ticket #2159</a>)</i>

**Comment by zorrobyte** [comment]
Howdy @rpashko-lohika-tix 

You'll be pleased to know that OpenCost has been accepted into the CNCF, of which IBM is a member and has shown interest in support!

You can learn more about OpenCost here:
https://www.opencost.io

Thank you for the enhancement request. We look forward to expanding our product into the future.

Ross Fisher
Senior Support Engineer
KubeCost

**Comment by dwbrown2** [comment]
Would love to see first party support here! 

@skonto any suggested contacts on the IBM team? 

cc @alexkubecost @trentbroderick

**Comment by maximilien** [comment]
Hi, all, happy to help with this request. Any elaborations and timeframe? I will use this to follow-up with my colleagues in IBM Cloud

@rpashko-lohika-tix ^^^

**Comment by AjayTripathy** [comment]
I've seen a number of users interested in running Kubecost on IBM k8s or OpenShift on IBM cloud. So I'd be fully supportive of helping here. Here's the new provider guide and it's generally pretty fast to add a new provider: https://docs.google.com/document/d/1JVPCeQmvGU88aw0bJJjtTzdl5RhhOqT7FPs2szuHBkc/edit
