### ISSUE TITLE
Azure nodes naming mismatch

### ISSUE THREAD

**Issue by biancaburtoiu** [opencost/opencost#1339]
Names of some Azure instance types don't match our current Azure `NodeType` naming schema.

For example: 
- Name in Azure: "Standard_DS2_v2" vs. name in Kubecost: "DS2 V2"
- Name in Azure: "Standard_B2ms" vs. name in Kubecost: "B2MS"

This leads to the following issues on the Cluster Sizing Recommendations page for Azure users:
- (important) Not being able to display current cluster information (showing a warning instead), as our algorithm isn't able to match the user's nodes with our known dataset of resource properties (CPU/RAM) (also flagged by this user [here](https://github.com/opencost/opencost/issues/596#issuecomment-1198798279))
- The names of the nodes we're recommending don't exactly match the node naming found on the Azure website. However, these can be inferred - eg. from "F72s v2" - the user's recommendation in the issue to "Standard_F72s_v2" on [Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machines/fsv2-series)

TODO: Revisit the homogenised node name generation algorithm and account for the presence of the "Standard" string in the original Azure node names.

**Comment by andrijaperovic** [comment]
Thanks @biancaburtoiu .
Can you also clarify on where the Azure VM SKU's are retrieved for Cluster Sizing Recommendations?
Was curious if this incorporates the new ARM-based VM series offered by Azure (like `standardDPLSv5Family`):
https://github.com/kubernetes/autoscaler/blob/6c16531d12e36515ff51903813c16d0568eff81e/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go#L476

**Comment by Adam-Stack-PM** [comment]
@biancaburtoiu, @biancaburtoiu, See above. Quick follow-up question above when you have time.

**Comment by biancaburtoiu** [comment]
Hi @andrijaperovic, thanks for your question! The new ARM-based Azure VMs are on our radar, we plan to introduce support in a future release.

**Comment by williamscs** [comment]
Was speaking with Ross in Slack about cluster node right-sizing and we're seeing the same issue with our AKS setup. Only a warning when viewing the "current" setup. 

He believes this issue may also be leading to some label mapping issues.

**Comment by rossfisherkc** [comment]
@AjayTripathy pinging you as this issue has stalled, I have an open case from Sep 13th, and another customer, above, waiting on this fix

**Comment by AjayTripathy** [comment]
Hey @rossfisherkc sounds like we have a good description of the issue. This seems like something I can knock out for v1.98.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Pushing to v1.99.
