### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [opencost/opencost#1351]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade OpenCost to the newer version (hopefully with no downtime)
- How to downgrade OpenCost to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

gz#2323<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2323'>Zendesk ticket #2323</a>)</i>

**Comment by jcharcalla** [comment]
@zamazan4ik 

Thank you for the feedback and great suggestion!

**Comment by jcharcalla** [comment]
@zamazan4ik until documentation is created here is the basic process.

To upgrade with Helm first update the repo `helm repo update` and then use `helm upgrade ...` with the same values as used during the install. 

You can downgrade or specify a version by adding the `--version x.xx.x` to the helm command.

Any specific upgrade or compatibility issues between versions should be documented in the release notes. https://github.com/opencost/opencost/releases

**Comment by dwbrown2** [comment]
@zamazan4ik was that helpful for you? We'll get this added to more docs if so.

**Comment by zamazan4ik** [comment]
Yeah, it is helpful. So please add this information into the documentation. Thank you!

**Comment by Adam-Stack-PM** [comment]
@zamazan4ik, Have this marketed P1, which means we should get the docs updated in the next few weeks. 

@bstuder99, If you have enough context here would be great if you could run with this update.

**Comment by brstuder** [comment]
This looks like a simple addition to the documentation. Can I assume you can upgrade/downgrade Kubecost in the same way described above for OpenCost?

**Comment by jcharcalla** [comment]
@bstuder99 Yes this would be the same for Kubecost.
