### ISSUE TITLE
[Local Development] How to get my PROMETHEUS_SERVER_ENDPOINT?

### ISSUE THREAD

**Issue by francis-jjk** [opencost/opencost#1360]
Hi folks,
    I followed this [wiki](https://github.com/francis-jjk/opencost/blob/develop/CONTRIBUTING.md) but stuck in the step of getting PROMETHEUS_SERVER_ENDPOINT. Here's more details:
    1. K8s Env: AKS
    2. Prometheus: Installed via helm
  
<img width="828" alt="image" src="https://user-images.githubusercontent.com/110971964/185574859-88a8b7eb-00b6-4063-85be-4530f8cc6f9c.png">

gz#2438<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2438'>Zendesk ticket #2438</a>)</i>

**Comment by kaelanspatel** [comment]
Hi @francis-jjk

PROMETHEUS_SERVER_ENDPOINT should just be whatever address you can access Prometheus on. If you're using a non-kubecost included Prometheus you'd need to do something like `kubectl port-forward service/<prometheus service name> --namespace=<prometheus namespace> <service port>`, and then set it to localhost:port.

You should be able to get this by running `kubectl get svc -n <prometheus namespace>` and finding the Prometheus one.

**Comment by francis-jjk** [comment]
Hi @kaelanspatel ,
     This is the prometheus server I got according to your guide
`prometheus-kube-prometheus-prometheus     ClusterIP   10.0.150.118   <none>        9090/TCP                     4d17h`
and namespace is `prometheus`,
So the PROMETHEUS_SERVER_ENDPOINT=`http://prometheus-kube-prometheus-prometheus.prometheus.svc` ?

**Comment by kaelanspatel** [comment]
Hi @francis-jjk 

No, sorry I wasn't too clear. If you're developing locally your PROMETHEUS_SERVER_ENDPOINT should be `PROMETHEUS_SERVER_ENDPOINT="http://127.0.0.1:9090"` (or `PROMETHEUS_SERVER_ENDPOINT="http://localhost:9090"`, I believe either will work).

The key is just that you need to port-forward. You can do so by running `kubectl port-forward service/prometheus-kube-prometheus-prometheus --namespace=prometheus 9090`.

**Comment by AjayTripathy** [comment]
To clarify, if you want to set kubecost up on a kubernetes node in your cluster, the endpoint is http://prometheus-kube-prometheus-prometheus.prometheus.svc . If you're trying to develop locally, it's wherever you port-forward into that prometheus.

**Comment by dwbrown2** [comment]
@kaelanspatel @bstuder99 worth a quick doc updates to add this guidance you think?

**Comment by brstuder** [comment]
Sure. Do we think the addition should be made in this article? https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus

**Comment by Adam-Stack-PM** [comment]
@kaelanspatel, See above when you have time.

**Comment by kaelanspatel** [comment]
@dwbrown2 @bstuder99 I will note that the docs do [reference port forwarding](https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md#running-locally), but I think the main thing is that the port-forward command is a kubecost-bundled prometheus specific one rather than a general one.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
