### ISSUE TITLE
Create OpenAPI / Swagger docs

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1377]
Goal is to help end users as well as those implementing the OpenCost spect better understand API definition. 

More detailed proposal: https://docs.google.com/document/d/1BbuJgh9ToQNa_4mnjxG--enAO2_vmIsrkfWxJR-JGIA/edit

**Comment by jpelletier1** [comment]
What API should we start with? I see you have an aggregation-related one defined. Start there?

The API response that Fairwinds uses is different from what you've defined in the above doc, but should have similar data points. I will try and get a copy of that.

**Comment by dwbrown2** [comment]
I'd vote we start with the Allocation API! Can discuss more in community meeting tomorrow if that sounds good.
