### ISSUE TITLE
Make AWS regions configurable

### ISSUE THREAD

**Issue by larhauga** [opencost/opencost#1382]
In our environment, opencost is not allowed IAM permissions to access resources in all AWS regions. 
This causes a lot of IAM errors with PermissionDenied due to the following hardcoded list of regions (https://github.com/opencost/opencost/blob/cda202ddedb57d02bc307ea63052b29f1a504c97/pkg/cloud/awsprovider.go#L111-L138)

This is used in the GetDisks https://github.com/opencost/opencost/blob/cda202ddedb57d02bc307ea63052b29f1a504c97/pkg/cloud/awsprovider.go#L1528 and GetAddresses functions https://github.com/opencost/opencost/blob/cda202ddedb57d02bc307ea63052b29f1a504c97/pkg/cloud/awsprovider.go#L1445

Is there any way that this could be made configurable, so that we could specify only the regions we are interested in?

**Comment by AjayTripathy** [comment]
Hi @larhauga sorry for the late response. Some of this functionality is likely going to be moving out of opencost to slim down the scope. We'll be sure when it's migrated to Community Edition Kubecost to allow configuration of regions. In the meantime, would silencing the errors be helpful?

**Comment by mmurph3** [comment]
I have a customer experiencing this issue in kubecost enterprise. Generates a lot of noise in cloudtrail logs.

**Comment by rossfisherkc** [comment]
> I have a customer experiencing this issue in kubecost enterprise. Generates a lot of noise in cloudtrail logs.

cc @AjayTripathy is there a way for the customer to disable these log errors?

**Comment by AjayTripathy** [comment]
I think setting the log level is the only way currently: https://github.com/kubecost/cost-analyzer-helm-chart#adjusting-log-output

**Comment by mmurph3** [comment]
Here’s a sample log entry that we’re seeing:

```
{

  "eventVersion": "1.08",

  "userIdentity": {

    "type": "IAMUser",

    "principalId": "REDACTED",

    "arn": "arn:aws:iam::<REDACTED>:user/REDACTED",

    "accountId": "<REDACTED>",

    "accessKeyId": "REDACTED",

    "userName": "REDACTED"

  },

  "eventTime": "2022-11-15T18:18:32Z",

  "eventSource": "ec2.amazonaws.com",

  "eventName": "DescribeVolumes",

  "awsRegion": "sa-east-1",

  "sourceIPAddress": "<REDACTED>",

  "userAgent": "aws-sdk-go-v2/1.16.2 os/linux lang/go/1.19.3 md/GOOS/linux md/GOARCH/amd64 api/ec2/1.29.0",

  "errorCode": "Client.UnauthorizedOperation",

  "errorMessage": "You are not authorized to perform this operation.",

  "requestParameters": {

    "maxResults": 1000,

    "volumeSet": {},

    "filterSet": {}

  },

  "responseElements": null,

  "requestID": "d6f20ef7-e59f-439c-8236-574cc7364691",

  "eventID": "57225f4a-0018-4ca7-bf25-bcf577d1527d",

  "readOnly": true,

  "eventType": "AwsApiCall",

  "managementEvent": true,

  "recipientAccountId": "REDACTED",

  "eventCategory": "Management",

  "tlsDetails": {

    "tlsVersion": "TLSv1.2",

    "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",

    "clientProvidedHostHeader": "ec2.sa-east-1.amazonaws.com"

  }

}
```

 Note that we’ve seen a lot fewer since we successfully upgraded to kubecost v1.98 and configured it properly, but they are still happening at around 100/day.

**Comment by mmurph3** [comment]
Further info:

What it appears to do is every 3 hours, it does both ec2:DescribeVolumes and ec2:DescribeAddresses in all 16 "other" regions, all in the same second. So, 32 calls within the same second, every 3 hours.
