### ISSUE TITLE
Example missing: out-of-cluster resources

### ISSUE THREAD

**Issue by eumel8** [opencost/opencost#1387]
In the Readme the possibility of measurement of out-of-cluster resources like RDS is mentioned. This would be very interesting, especially to implement this in Opencost or is it already possible? An example/use case would be nice.

**Comment by nikovacevic** [comment]
Hi @eumel8 thank you for the suggestion! For an example, this is implemented in Kubecost's Allocation API. (See documentation for that here: https://guide.kubecost.com/hc/en-us/articles/4407595916823-Allocation-API#querying)

**Comment by eumel8** [comment]
@nikovacevic thx for the link. I've tried something with `filterControllerKinds` to count and invoice resources for the customer, like `filterControllerKinds=certificate` or `filterControllerKinds=rds`or `filterControllerKinds=ingress`, but couldn't get results. So I used this wrong, or it's not implemented? And if not, how to start working on it?

**Comment by AjayTripathy** [comment]
Hey @eumel8 -- quick question, are you using Opencost or the free community edition Kubecost (https://github.com/kubecost/cost-analyzer-helm-chart)? out-of-cluster resources are available in community edition kubecost. It was a mistake during the migration to Opencost to leave it in the readme here. Apologies for any confusion-- I'll remove that from the README https://github.com/opencost/opencost/pull/1399.

**Comment by eumel8** [comment]
@AjayTripathy Indeed, we are using Kubecost Community Edition. I wasn't aware about the Opencost project. Good to know you haven't this feature here, but also in Kubecost project I don't see the option to fetch other API resources. But I will ask there.
