### ISSUE TITLE
Inquiry: how cost is computed

### ISSUE THREAD

**Issue by omartheironman** [opencost/opencost#1389]
I installed opencost on our clusters. Does it get the default values from gcp.json? and assumed 30% discount? or does it connect to GCP billing and gets the info from there?

**Comment by nikovacevic** [comment]
Hi @omartheironman. Thank you for the question.

It sounds like you're on GCP, and asking about how we determine node pricing. We try to connect to GCP Billing APIs, but if that fails we fall back on a local default configuration.

Please checkout the code to learn more, here:

[func (cm *CostModel) GetNodeCost(cp costAnalyzerCloud.Provider)](https://github.com/opencost/opencost/blob/develop/pkg/costmodel/costmodel.go#L933)

[func (gcp *GCP) NodePricing(key Key)](https://github.com/opencost/opencost/blob/develop/pkg/cloud/gcpprovider.go#L1342-L1362)

**Comment by omartheironman** [comment]
@nikovacevic  
Looking at the discount config, i see 30% is that automatically assigned then? so the cost i see at the moment is coming from the billing api and also includes 30%?

**Comment by nikovacevic** [comment]
If you haven't changed the settings, and you're using nodes that have a 30% sustained use discount, then yes, that is correct.

**Comment by mattray** [comment]
This appears to be answered.
