### ISSUE TITLE
Consolidate and/or Update Spec Docs 

### ISSUE THREAD

**Issue by Adam-Stack-PM** [opencost/opencost#1390]
Currently, Opencost.io Spec docs link users to Google Drive. Within google drive, different versions of the spec link users to multiple places to find the latest version. Additionally Im not 100% sure, but the spec docs in GitHub may be outdated. 

We should make sure that Github always has the latest version published and act as the source of truth. 

**Links**

Drive: https://drive.google.com/drive/folders/196Dq_GHOGeva5ojwF2jd3L21ab-Y7wp5

Opencost.io Spec:https://www.opencost.io/docs/#specification

Spec: https://github.com/opencost/opencost/tree/develop/spec

**Images**

<img width="1426" alt="Screen Shot 2022-09-16 at 8 37 57 AM" src="https://user-images.githubusercontent.com/102822297/190665018-234280dd-49a3-446d-af0d-22e50cb9cea4.png">

<img width="1289" alt="Screen Shot 2022-09-16 at 8 40 45 AM" src="https://user-images.githubusercontent.com/102822297/190665484-98fae9a4-c298-4862-bfd9-253f862b5d98.png">

<img width="1356" alt="Screen Shot 2022-09-16 at 8 39 04 AM" src="https://user-images.githubusercontent.com/102822297/190665279-f263c2fa-16b8-4a3f-a752-8f0a5f80c16f.png">

CC: @dwbrown2

**Comment by dwbrown2** [comment]
This issue belongs here: https://github.com/kubecost/opencost-website

And there's already an open PR!
