### ISSUE TITLE
provision to add custom costs based on node labels

### ISSUE THREAD

**Issue by Karthik-Chowdary** [opencost/opencost#1398]
In settings we currently only see one setting for all custom costs for GPU, cpu, ram etc., costs
This does not support the following use cases for on-prem and may be for others as well
1. Different GPU types cost different (Ex: Nvidia Ampere costs different than Turing generation and in between generations there are multiple SKU's and boards)
2. Different servers cost vary (HDD servers, NVME servers, Dual PSU servers, Rack space in Data Center etc.,)

If we have a provision to add costs based on node labels(These can be maintained by individuals) It provides a more accurate representation of costs that are in line with actual cost spent.

Example:
label ->  node_type: perf    cpu_hourly_cost: 0.13
label -> node_type: regular     cpu_hourly_cost: 0.11
label -> node_type: perf; board_type: RTX_3090    cpu_hourly_cost: 0.12; gpu_hourly_cost: 0.33

Label based cost customization is something that accurately measures custom costs. Can we please have this feature?

**Comment by biancaburtoiu** [comment]
Thank you for raising this @Karthik-Chowdary! We will consider this enhancement as part of our product roadmap.

**Comment by etamong** [comment]
> In settings we currently only see one setting for all custom costs for GPU, cpu, ram etc., costs This does not support the following use cases for on-prem and may be for others as well
> 
> 1. Different GPU types cost different (Ex: Nvidia Ampere costs different than Turing generation and in between generations there are multiple SKU's and boards)
> 2. Different servers cost vary (HDD servers, NVME servers, Dual PSU servers, Rack space in Data Center etc.,)
> 
> If we have a provision to add costs based on node labels(These can be maintained by individuals) It provides a more accurate representation of costs that are in line with actual cost spent.
> 
> Example: label -> node_type: perf cpu_hourly_cost: 0.13 label -> node_type: regular cpu_hourly_cost: 0.11 label -> node_type: perf; board_type: RTX_3090 cpu_hourly_cost: 0.12; gpu_hourly_cost: 0.33
> 
> Label based cost customization is something that accurately measures custom costs. Can we please have this feature?

I'm really looking forward it to be included in the product roadmap.🙂

Our K8S clusters have various GPUs such as: 
- Geforce RTX2080
- Quadro RTX5000
- Tesla V100 (16g)
- Tesla V100 (32g)
- Tesla A100 (40g)
- Tesla A100 (80g)
...

And we found that they are same price at this time.
However Tesla A100 and Geforce GPUs' price are so different.

**Comment by AjayTripathy** [comment]
https://github.com/opencost/opencost/pull/1471 should begin to help address some of this for GPUs, at least when the CSV pricing sheet is provided.

**Comment by mattray** [comment]
This appears to be fixed in https://github.com/opencost/opencost/pull/1480
