### ISSUE TITLE
Kubernetes deployment file is creating opencost namespace but not using it

### ISSUE THREAD

**Issue by amar-chand** [opencost/opencost#1402]
In [Kubernetes deployment file](https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml), Following resources/objects are being created:
1. `opencost` Namesapce
2. `opencost` SA
3. `opencost` ClusterRole
4. `opencost` ClusterRoleBinding
5. `opencost` Deployment
6. `opencost` Service

All the resources/objects do not contain the namespace definition. It is pretty much confusing as we are creating namespace from inside the file, yet we are providing -`-namespace opencost ` parameter in the kubectl command, rather than defining the namespace for various resources/objects inside their definition YAMLs respectively.

Let's say user needs to change a few things, he/she will be bound to set `--namespace` argument all the time, and it is a bit of rework.

What can be done to fix it?
We can set the namespace of all the resources/objects inside the file.

**Comment by biancaburtoiu** [comment]
Hello @amar-chand, thank you for raising this! We will consider this improvement when revisiting our Kubernetes resource definitions.

**Comment by mattray** [comment]
Everything's in `opencost` now.
