### ISSUE TITLE
Fix OpenCost UI Documentation

### ISSUE THREAD

**Issue by anders-elastisys** [opencost/opencost#1405]
The documentation on running the open-source UI, found [here](https://github.com/opencost/opencost/tree/develop/ui#installation--running), does not seem to be correct as it seems to be written for Kubecost and not Opencost. The last command for port-forwarding does not work as there is no deployment called `kubecost-cost-analyzer` created with the open-source project. The correct kubectl command for port-forwarding the Opencost container that works with the UI is:

```
kubectl port-forward -n opencost deploy/opencost 9090:9003
```

**Comment by Adam-Stack-PM** [comment]
@bstuder99, Could you run with updating this doc when you have time?

**Comment by brstuder** [comment]
Issue created that corrects this: https://github.com/opencost/opencost/pull/1410

**Comment by AjayTripathy** [comment]
Fixed in #1410
