### ISSUE TITLE
Asset Price Not Right

### ISSUE THREAD

**Issue by chenbiao7** [opencost/opencost#1408]
Hi Guys, I install kubecost on AWS EKS in us-east-1 region. When I open the Web UI , I found the price is not the same as AWS, you can look the following screenshot.
1\ Node price:
**In AWS us-east-1 region ,the on demand price with t3.meduim 0.0416$/Hour**
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/21186145/193183046-391cc27e-c710-4586-a1fb-ef47d9237c5a.png">
2\AWS LoadBanlacer
**In AWS ue-east-1 region ,the network loadbalancer is 每 Network Load Balancer 小时（或不足一小时）0.0225 USD**
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/21186145/193183235-8fd8867f-1e3b-4e9e-90b2-a42e073c7f51.png">

So it  is not the same with AWS offical price , Is there anyone can help to take a look . Thanks in advance ~

My kubecost detail information are as bellows:
Kubecost Info
Version
1.97.0
API Version
1.97.0 (98ec1091304e45dc3109b4b59f4cb7d66b5e2d30)
License Version
FREE

**Comment by AjayTripathy** [comment]
1. Looks like the node price is roughly correct (0.042 ~ 0.0416 to 3 significant figures). For the UI we round to 2 decimals, I believe if you look in the API you will see the price.
2. Loadbalancer prices are estimates, you can get more accurate billing data by integrating with kubecost + the cost and usage report. https://github.com/kubecost/docs/blob/main/aws-out-of-cluster.md

**Comment by AjayTripathy** [comment]
@chenbiao7 closing this for now. Let me know if you have any other questions.

**Comment by chenbiao7** [comment]
Hi @AjayTripathy， 
Thanks for your reply， I made a test in the past tow days. on 09/30, I intergrated the kubecost and the cost and usage report what you can see the following pictures:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/21186145/193467521-7d5e08f8-dda5-42ec-a0b5-6dafca80fad6.png">
Unfortunately, my LoadBalancer price is still not right and the hourly rate is 0.025 , however the offical price in us-east-1 is 0.0225/hour, you can refer the following:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/21186145/193467606-a22f1bce-a1cf-4c86-9861-f40240628644.png">
Is there any other wrong with my test and can you give me more advice ?

**Comment by AjayTripathy** [comment]
Accurate data from the AWS CUR is available only > 48 h after integration, and only for data > 48 h. Can you confirm you're looking at loadbalancer cost for days > 48 old?
