### ISSUE TITLE
Opencost discrepency with GKE usage metering even with reconciliation enabled

### ISSUE THREAD

**Issue by pcperera** [opencost/opencost#1409]
### Issue

We have observed significant cost variance (between opencost and GKE usage metering) for several namespaces of our GKE cluster. The below comparison was done for 11 day range for **argocd**, **victoria-metrics** and **kube-system** namespaces.

![image](https://user-images.githubusercontent.com/15628990/193188268-22c27d2f-a652-4494-af1c-2323572b466f.png)

![image](https://user-images.githubusercontent.com/15628990/193188441-210b13ce-0d1b-4307-a352-dfcf952e41d6.png)

![image](https://user-images.githubusercontent.com/15628990/193188365-fd440ad7-b417-4d7a-86e6-84c0b4668551.png)

What exactly is represented by the **Shared** cost in opencost ? Note that we use the "Share by Cluster" option for idle costs.

![image](https://user-images.githubusercontent.com/15628990/193187544-f868e6cd-3752-4a42-b0b8-97df46faa08d.png)

Why there is a significant discrepancy for **Network**, **Storage** and **Memory** for some of the namespaces even when reconciliation is enabled ?

### Expectation

Opencost to produce roughly approximate numbers with GKE usage metering when reconciliation is enabled. 

### Actual

Opencost produces significantly different numbers for the same kubernetes namespaces with reconciliation enabled.

### Version

1.96.0

**Comment by AjayTripathy** [comment]
Hi @pcperera -- can you:
1. Ensure that reconciliation is enabled with a detailed billing report from GCP? https://github.com/kubecost/docs/blob/80847ba25a4978bbb939223a94d6334fcdcee5d8/gcp-out-of-cluster.md#step-1-enable-billing-data-export
2. The invariant on the kubecost / opencost side is that sum(CPU + GPU + RAM) on the allocations side, with idle allocated == price of the node on the kubecost assets page == price of the node in GCP for data which has been reconciled (data > 48 h old). Are any of these invariants broken? If so could you tell us which ones and for which classes?

Also, worth noting that Kubecost is based on [OpenCost](https://opencost.io/) calculations. You can see the spec here: https://github.com/opencost/opencost/tree/develop/spec

**Comment by pcperera** [comment]
Hi @AjayTripathy 

1. Correct. Detailed billing exports have already been enabled. 

![image](https://user-images.githubusercontent.com/15628990/193285701-9b62ff58-8f42-4142-bbd6-b2b1db800a7e.png)
![image](https://user-images.githubusercontent.com/15628990/193285787-f11b5cad-f092-41b2-a1dd-3043fad53b72.png)

2. Do you mean the total (CPU + GPU + RAM) cost of the cluster or for the namespace ?

**Comment by pcperera** [comment]
@AjayTripathy 

We generally receive the below error when loading asset data. Is this due to timing out opencost to billing export connection ? If so how this timeout can be increased ? If not what is the cause ?

![image](https://user-images.githubusercontent.com/15628990/193289281-7a8d2591-6b8c-4b73-b958-c4a036a4cc69.png)

**Comment by AjayTripathy** [comment]
It seems likely that the backing pod is unavailable. You probably want to look for the reason for the restart (kubectl describe pod) to figure out why. Common reasons might include an OOM.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
