### ISSUE TITLE
Asset CSV downloads are missing details useful for sorting

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1413]
When looking at Assets there are details such as instance-type, # of CPUs and total memory. These additional details are not provided in the downloaded CSV and would provide valuable data for sorting.

<img width="2264" alt="Screen Shot 2022-10-05 at 7 28 51 PM" src="https://user-images.githubusercontent.com/330023/194016214-5465ad8f-557a-4244-bd75-8b860e59abfe.png">

**Comment by AjayTripathy** [comment]
Let's revisit the CSV for v1.99 cc @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
Related issue https://github.com/opencost/opencost/issues/1416

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
