### ISSUE TITLE
Inconsistent cost efficiency numbers

### ISSUE THREAD

**Issue by pcperera** [opencost/opencost#1414]
### Issue

Cost efficiency of the last 7 days is 32.8% according to the overview page.

![image](https://user-images.githubusercontent.com/15628990/194215528-baaa6c49-52c7-4022-bbdd-79cb257c3da0.png)

But if I go to the cost efficiency link indicated above it shows a different efficiency number.

![image](https://user-images.githubusercontent.com/15628990/194215947-7144d336-cf77-4c5e-85d0-f18e3fa0a5ab.png)

### Expectation

A single stat for cost efficiency for last 7 days.

### Actual

Different numbers of cost efficiency at different locations.

**Comment by AjayTripathy** [comment]
Hi @pcperera, looks like the Overview card is showing "hardware" (used resources on a node) efficiency, while Cost Allocation is showing "workload" (usage/request) efficiency. We'll make this clearer in v1.98

**Comment by Adam-Stack-PM** [comment]
@nealormsbee, Could you let me know if this is fixed in v1.98 or should we push it to v1.99?

**Comment by nealormsbee** [comment]
I did not open a PR for this 🤦 

v1.99 it is

**Comment by AjayTripathy** [comment]
I'd like to get this in v1.98 if this is as quick as we thought it was @nealormsbee

**Comment by nealormsbee** [comment]
Sure! Only question I have is:

Do we want to make it clearer that this number includes idle costs, or change the number to use workload efficiency (like cost allocation)? I'd probably favor the 2nd approach, but no strong preference.

**Comment by AjayTripathy** [comment]
I thnk I agree with favoring the 2nd approach, let's just make these match so we aren't introducing another concept here.

**Comment by dwbrown2** [comment]
Proposals out of this discussion: 

1. tooltips in allocation (1.99)
2. link cluster efficiency to new page with efficiency details / over time (1.100)

**Comment by dwbrown2** [comment]
Part 1 of this is complete in 1.99.
