### ISSUE TITLE
Unable to set clusterName

### ISSUE THREAD

**Issue by thomasvn** [opencost/opencost#1429]
In OpenCost, you are able to set the `cluster_id` by setting the Deployment's environment variable. As shown [here](https://github.com/opencost/opencost/blob/92519f1885fc728abf0419c573cf4cbb0f4f09e6/kubernetes/opencost.yaml#L158).

While you can similarly set a [`cluster_id` in Kubecost](https://github.com/kubecost/cost-analyzer-helm-chart/blob/5c43d0fa6bdd0870a258641825db6eda4af325f7/cost-analyzer/values.yaml#L484), there is no equivalent for Kubecost's `.Values.kubecostProductConfigs.clusterName`.

As a result, there is no way to change the cluster name in the OpenCost UI:
<img width="1470" alt="Opencost-ui 1" src="https://user-images.githubusercontent.com/11251627/196291921-ed2a8a05-f800-4e67-a080-04dbf302dd7c.png">

Here, OpenCost's Prometheus is showing I set the `cluster_id=thomas-cluster-one`:
<img width="1470" alt="Opencost-ui 2" src="https://user-images.githubusercontent.com/11251627/196292017-9ba8b8ec-4f69-461b-b599-6529a54560af.png">

**Comment by thomasvn** [comment]
For reference, I was able to access the OpenCost UI by:

```bash
# Terminal 1: Make OpenCost metrics available to localhost:9090
$ kubectl port-forward --namespace opencost service/opencost 9090:9003

# Terminal 2: Build and run the UI
$ cd opencost/ui
$ npm install
$ npx parcel src/index.html

# Visit http://localhost:1234 in your browser
```

And I was able to access the Prometheus UI by:

```bash
kubectl port-forward --namespace prometheus service/my-prometheus-server 8080:80
```

**Comment by AjayTripathy** [comment]
Thanks for the issue. Definitely think we can support this, but think this might be tricky since Opencost doesn't really have storage outside of the PromQL instance it puts timeseries in. Adding another label to each vector with clusterName is probably overkill. Any indication why just using ClusterID is insufficient?

**Comment by thomasvn** [comment]
> *Definitely think we can support this, but think this might be tricky since Opencost doesn't really have storage outside of the PromQL instance it puts timeseries in.*

For this concern, I think that OpenCost can emit both the `id` and `name` from its /metrics endpoint as shown below:

```
kubecost_cluster_info{account="",clusterprofile="development",errorreporting="true",id="thomas-cluster-one",logcollection="true",name="AWS Cluster #1",productanalytics="true",provider="AWS",provisioner="",region="us-west-1",remotereadenabled="false",thanosenabled="false",valuesreporting="true",version="1.22+"} 1
```

> *Any indication why just using ClusterID is insufficient?*

Using `cluster_id` is mostly sufficient! However for the UI, changing `cluster_id` does not actually change the name of the cluster as shown in the screenshot above.

**Comment by AjayTripathy** [comment]
> For this concern, I think that OpenCost can emit both the id and name from its /metrics endpoint as shown below:

Every additional byte is meaningful since this is appended to all metrics. Not opposed to this solution, just wanted to call that out.

**Comment by mattray** [comment]
Not sure when the fix went in, but this works with the OpenCost Helm chart by passing `opencost.exporter.defaultClusterId='gke-opencost-3'`

<img width="824" alt="Screenshot 2023-10-19 at 1 49 57 PM" src="https://github.com/opencost/opencost/assets/330023/39ae8611-fab6-4239-98b4-819b390e8744">
