### ISSUE TITLE
Add ability to filter prometheus queries by current cluster ID

### ISSUE THREAD

**Issue by AndrewChubatiuk** [opencost/opencost#1431]
Now OpenCost queries do not have current cluster id filter as they expected to be performed against per-cluster Prometheus which has only current cluster metrics. In a setup with Victoria Metrics it requires to have agent per each cluster for metrics aggregations and this agent has no /metrics endpoint, it pushes metrics to monitoring cluster. It's inconvenient to have a separate Prometheus in each cluster just for OpenCost.
With current cluster selector it's possible to start using a shared monitoring cluster instead of a per-cluster Prometheus

**Comment by AjayTripathy** [comment]
Hey @AndrewChubatiuk I'm supportive here, just a few notes on testing and we can look to add this to v1.99

**Comment by Pokom** [comment]
Curious to see where we're at for the PR. We currently run `prom-label-proxy` to add the cluster label to each PromQL query but would love to remove this dependency for our deployments.
