### ISSUE TITLE
1.97 and -rc releases are missing from Releases

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1434]
I assume this is automated? If not, everything after 1.96 is missing.

**Comment by dwbrown2** [comment]
@AjayTripathy can you comment? Can we document this as part of the release process if it's not automated?

**Comment by AjayTripathy** [comment]
@kaelanspatel I think you discussed possibly tagging this one manually but decided against it? could you provide context as buildmaster this time?

**Comment by kaelanspatel** [comment]
This part is certainly automated, but is currently expected to be run by each buildmaster locally using their own gh cli auth.

As I am not an opencost maintainer, the script that does this fails to add the release (and maybe did for Neal in v1.97).

**Comment by AjayTripathy** [comment]
I think let's give the buildmaster temporary write/maintainer access to opencost. I can do that now.

**Comment by AjayTripathy** [comment]
https://github.com/opencost/opencost/releases/tag/v1.98.0 has been properly tagged, so closing.
