### ISSUE TITLE
No opencost API for predicting future cost

### ISSUE THREAD

**Issue by atamnitkkr** [opencost/opencost#1441]
Could not find Opencost API for predicting future cost of Kubernetes cluster https://www.opencost.io/docs/api. But I could see corresponding cli command 
![image](https://user-images.githubusercontent.com/116127135/197081405-3aa28ac5-fbab-4598-b99f-5b6adf887618.png)

**Comment by AjayTripathy** [comment]
Hi @atamnitkkr , kubectl cost runs against the community edition kubecost-- there's currently no support for projections in the open-core APIs. However, you could derive one quickly by taking the window and multiplying it over the window you want to project costs over.

**Comment by atamnitkkr** [comment]
@AjayTripathy 
Do we have an API that can give the total cost of the cluster i.e. Resource allocation cost? (which include idle resource cost).
I see API is for resource usage cost.

**Comment by AjayTripathy** [comment]
In opencost you can use "/clusterCosts" for that computation.

**Comment by atamnitkkr** [comment]
@AjayTripathy thanks

**Comment by atamnitkkr** [comment]
@AjayTripathy I tried using the suggested API /clusterCosts. Unfortunately there is no documentation of it  https://www.opencost.io/docs/api 

API - curl http://localhost:9003/clusterCosts -d window=120m   -d resolution=1m   -d aggregate=cluster   -d accumulate=true   -G
Result -
![image](https://user-images.githubusercontent.com/116127135/199842702-081e2f5f-371e-44e6-bb0a-28359870349d.png)

Few questions - 
- In CPU breakdown it shows a total of one CPU (But the cluster has a lot more CPU cores). Is it a percentage? or an actual CPU core count?
- Also, is it expected that the storage cost breakdown will be zero for all users?
- This API does not report the cost of the used Loadbalancer, PVs, and Network cost.

**Comment by AjayTripathy** [comment]
Yes, CPU breakdown is a percentage.

It sounds like we've got https://github.com/opencost/opencost/issues/1468 open for network costs and PVs. The storage breakdown would be expected to be 0 for all users if we aren't getting any PV statistics.
