### ISSUE TITLE
Inaccurate PV costs (off by 7-9% of actual disk costs shown on Assets view)

### ISSUE THREAD

**Issue by tohjustin** [opencost/opencost#1446]
Currently observing some discrepancy in PV costs on Kubecost v1.97.0.

There's consistently a 7-9% difference between the PV costs shown in the Cost Allocation view compared to the costs of the underlying FSx Filesystems & EBS Volumes shown in the Assets View (which matches our AWS bills).

## Example A: EBS-based PVs, mounted by one pod at a time (over 7 days)

- Assets View: Total costs for all EBS Volumes backing the PV volumes dynamically provisioned for `kubecost` = **$2.28**
- Cost Allocations View: Total PV costs allocated to `kubecost` namespace = **$2.09** (~8.333% lower than actual)

![Example A (EBS w: mounted by single pod)](https://user-images.githubusercontent.com/8844886/197748150-d39626ae-2172-4ca4-9cc0-baa1c930d4f3.png)

## Example B: EBS-based PVs, mounted by more than pod at a time (over 7 days)

- Assets View: Total costs for all EBS Volumes backing the PV volumes dynamically provisioned for `kubecost-govkube-1768-ebs` = **$0.27**
- Cost Allocations View: Total PV costs allocated to `kubecost-govkube-1768-ebs` namespace = **$0.25** (~7.407% lower than actual)

![Example B (EBS w: mounted by multiple pods)](https://user-images.githubusercontent.com/8844886/197748274-e2b07a76-059c-4c0b-a875-4299fb633743.png)

## Example C: FSx-based PVs, mounted by more than pod at a time (over 7 days)

- Assets View: Total costs for all FSx File Systems backing the PV volumes dynamically provisioned for `kubecost-govkube-1768-fsx` = **$44.98**
- Cost Allocations View: Total PV costs allocated to `kubecost-govkube-1768-fsx` namespace = **$41.32** (~8.137% lower than actual)

![Example C (FSx w: mounted by multiple pods)](https://user-images.githubusercontent.com/8844886/197748169-4235e6ba-c232-4699-bc26-7aef49106c59.png)

**Comment by AjayTripathy** [comment]
Hi @tohjustin , thanks for this report. Would it be possible for us to get a dump of your data via tarball so we can investigate this closely? https://github.com/kubecost/etl-backup . You can send it to me via email me at ajay@kubecost.com

**Comment by tohjustin** [comment]
Hi @AjayTripathy, apologies for the late follow up. I’ve just sent you an email ([ajay@kubecost.com](mailto:ajay@kubecost.com)) with the requested files 🙏

**Comment by kaelanspatel** [comment]
Sorry, closed this accidentally with the PR.

**Comment by kelvinwijaya** [comment]
Hi @kaelanspatel 

As per our check after upgrading kubecost to v1.100.2, we still seeing the same discrepancy rate of around 7% as what @tohjustin highlighted earlier




EBS-based PVs (as per 14th Apr 2023) with Kubecost v1.100.2




Differences: |0.25-0.27| / 0.27 * 100% = 7.4%

Cost Allocation View: Total PV costs allocated to `kubecost-govkube-1768-ebs` namespace = $0.25
![image](https://user-images.githubusercontent.com/11241076/231938800-1738bfdb-6601-4eed-8753-13bc8338b811.png)

Asset View[Actual]: Total costs for all EBS Volumes backing the PV volumes dynamically provisioned for `kubecost-govkube-1768-ebs` namespace = $0.27

![image](https://user-images.githubusercontent.com/11241076/231946477-604e6ea6-c733-4502-a711-7f016fc3a307.png)

**Comment by kwombach12** [comment]
@AjayTripathy were we able to diagnose this issue previously? Do we need anther data dump?

**Comment by junaid-ali** [comment]
It also seems that the cost model doesn't take volume parameters (e.g throughput or IOPS) into account when calculating the EBS costs. Just started looking at Kubecost but `Features(...)` doesn't seem to have any configs related to that (please correct me if I'm looking at the wrong place): 

https://github.com/opencost/opencost/blob/develop/pkg/cloud/aws/provider.go#L703C25-L707

With the AWS estimator: https://calculator.aws/#/estimate?id=d74c3f8e019de76cf2979d9bfc6b4889558f6df0, I get `$18.7` per month while kubecost estimates the cost to be `~$9.5`, around `51%` less than the actual cost.

![kubecost-ebs-gp3-350](https://github.com/opencost/opencost/assets/20142968/859a20a9-f6fb-4282-b5bb-bc524ae8557b)

P.S: the cost in kubecost is in Euros, and `$9.5` provided above is the converted one.

**Comment by kwombach12** [comment]
@AjayTripathy @teevans Can you take a look at this? Is there a bug we can add to our burndown here?

**Comment by teevans** [comment]
@kwombach12 - Let's get this on the burndown list, I suspect we'll have some bandwidth to look at this during 104.

**Comment by kwombach12** [comment]
Thanks @teevans. Added

**Comment by avrodrigues5** [comment]
Hello @tohjustin @kelvinwijaya , 

If this issue is still persistent , could you provide fresh ETL dumps that i can investigate on.

You could send them over at alanrodrigues@kubecost.com

CC: @cliffcolvin 

-regards
Alan

**Comment by mattray** [comment]
Closing this as a stale Kubecost issue.
