### ISSUE TITLE
External Prometheus Authentication

### ISSUE THREAD

**Issue by Ulrar** [opencost/opencost#1462]
**Describe the bug**
I'm trying to deploy OpenCost to run using our existing Prometheus deployment, which is in another cluster.
It's protected using Basic Auth, and I can't find how to define that for the kubecost-cost-model container.

Looking at [this](https://aws.amazon.com/blogs/mt/integrating-kubecost-with-amazon-managed-service-for-prometheus/) it sounds like there might be more env variables than just PROMETHEUS_SERVER_ENDPOINT, but I'm not sure which.

Am I also correct in assuming that this is because of this (the pod can't get the prometheus config on startup because it's not authenticated) that the port 9003 never opens ?
Out of curiosity why is that required ? I was hoping to use this as an exporter only, but it looks like that's not possible.

It may also be missing permission on the GCP Billing API key, I haven't found any instructions on how that should be setup either.

**To Reproduce**
1. Point `PROMETHEUS_SERVER_ENDPOINT` to an external address requiring basic auth
2. Start the pod

Am I missing any documentation on this ?
Thank you !

**Comment by AjayTripathy** [comment]
Check out https://github.com/opencost/opencost/blob/e89a0df34131d4695b5500de629864e248d06f4c/pkg/env/costmodelenv.go#L52

@mattray seems like another great opportunity to add to the opencost docs as well. 

@Ulrar you may find this easier to deploy our community edition helm chart: https://github.com/kubecost/cost-analyzer-helm-chart

**Comment by Ulrar** [comment]
Hi,

Thanks, those variables do work.
I've had a look at that chart but I didn't see any reference to prometheus authentication, sorry if I missed it.

Still having an issue with the GCP API Key, but that's a separate problem.
Thanks !

**Comment by AjayTripathy** [comment]
@kirbsauce can you please assign to the support eng team to make sure this gets documented? Then I think this issue is ok to close.

**Comment by kirbsauce** [comment]
documentation task being tracked here -> https://github.com/kubecost/support/issues/40

**Comment by mattray** [comment]
This looks to be supported in the Helm chart: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L145
