### ISSUE TITLE
Reports zero Network cost, Loadbalancer cost and PVs cost

### ISSUE THREAD

**Issue by atamnitkkr** [opencost/opencost#1468]
**Describe the bug**
Zero cost reported for Network, Loadbalancer, PVs.
Note that PVs exist in the cluster which are used by Prometheus and grafana.

**To Reproduce**
Prometheus is setup as follows -
helm install prometheus prometheus-community/kube-prometheus-stack \
--namespace prometheus \
--set alertmanager.persistentVolume.storageClass="standard" \
--set server.persistentVolume.storageClass="standard" \
-f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml

Opencost is setup using 
https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml 
where the prometheus endpoint is modified 

Query ran -
curl http://localhost:9003/allocation/compute \
  -d window=60m \
  -d resolution=1m \
  -d aggregate=cluster \
  -d accumulate=true \
  -G

Results -
{"code":200,"status":"success","data":[{"cluster-one":{"name":"cluster-one","properties":{"cluster":"cluster-one"},"window":{"start":"2022-11-03T17:36:08Z","end":"2022-11-03T18:36:08Z"},"start":"2022-11-03T17:59:00Z","end":"2022-11-03T18:36:00Z","minutes":37.000000,"cpuCores":2.736216,"cpuCoreRequestAverage":2.736216,"cpuCoreUsageAverage":0.148538,"cpuCoreHours":1.687333,"cpuCost":0.053338,"cpuCostAdjustment":0.000000,"cpuEfficiency":0.054286,"gpuCount":0.000000,"gpuHours":0.000000,"gpuCost":0.000000,"gpuCostAdjustment":0.000000,"networkTransferBytes":11263905654.434429,"networkReceiveBytes":9756468872.426695,"networkCost":0.000000,"networkCostAdjustment":0.000000,"loadBalancerCost":0.000000,"loadBalancerCostAdjustment":0.000000,"pvBytes":0.000000,"pvByteHours":0.000000,"pvCost":0.000000,"pvs":null,"pvCostAdjustment":0.000000,"ramBytes":4177566875.675675,"ramByteRequestAverage":4177566875.675676,"ramByteUsageAverage":2387956587.658378,"ramByteHours":2576166240.000000,"ramCost":0.010166,"ramCostAdjustment":0.000000,"ramEfficiency":0.571614,"sharedCost":0.000000,"externalCost":0.000000,"totalCost":0.063504,"totalEfficiency":0.137099,"rawAllocationOnly":null}}]}

**Expected behavior**
Should report cost of Network, Loadbalancer, Pvs.

**Screenshots**
![image](https://user-images.githubusercontent.com/116127135/199810439-761c5509-18a0-4ac6-b878-782254aad966.png)

**Which version of OpenCost are you using?**
 - image: quay.io/kubecost1/kubecost-cost-model:latest
 - https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml 

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by thomasvn** [comment]
@atamnitkkr. For network costs I believe you'll need to enable the [networkcosts daemonset](https://guide.kubecost.com/hc/en-us/articles/4407595973527-Network-Traffic-Cost-Allocation). And for load balancer costs I believe you'll need to enable cloud integrations.

I was unable to reproduce your issue for the `PersistentVolume` metrics. I see data for `pvBytes` and `pvCost` in my Opencost deployment.

Perhaps one thing to check, is whether your Prometheus instance has the [`kube_persistentvolume_capacity_bytes` metric derived from KSM](https://guide.kubecost.com/hc/en-us/articles/4425134686743-User-Metrics#kube-state-metrics).

```bash
kubectl port-forward svc/my-prometheus-server 8080:80 -n prometheus

# Visit http://localhost:8080/ in the browser
# Try querying for kube_persistentvolume_capacity_bytes 
# Check the graph view to see if the data exists at all or if it was missing during a specific time period
```

**Comment by atamnitkkr** [comment]
@thomasvn 

- Opencost is being deployed via the YAML file. I do not see a way via helm chart. Also, I do not see opencost YAML have networkcosts daemonset. Is it also part of the Apache license?

https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml 

- How can I enable cloud integration?
- Yes looks like kube-prometheus donot have kube_persistentvolume_capacity_bytes metric. So Opencost donot officially support this flavor of prometheus i.e.  kube-prometheus ??

**Comment by AjayTripathy** [comment]
Hi @atamnitkkr , the network costs daemonset and the cloud integration with network costs is not currently part of our open source offering. We'll look to either expanding the offering or remove it from the API spec.

https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolume-metrics.md is a KSM metric, so not sure why that wouldn't exist unless no PVs were mounted in your cluster. Is it being blacklisted/whitelisted out?

**Comment by atamnitkkr** [comment]
@AjayTripathy Ok thanks. Yes, we can make documentation and API spec consistent in that case because as of now opencost is claiming to give cost for Loadbalancer and Network.
https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md 
I will investigate why I am not getting PV metrics.

**Comment by AjayTripathy** [comment]
@mattray can you find and update the relevant documentation?

**Comment by AjayTripathy** [comment]
@atamnitkkr load balancer costs should be available. I think that there may be another metric missing from Prometheus

**Comment by atamnitkkr** [comment]
@AjayTripathy possible, even opencost metric opencost_load_balancer_cost/kubecost_load_balancer_cost is missing. Can you please help me with the metric name?
Or if possible can you please help with opencost development setup steps, where I can debug opencost by attaching a debugger?
Sorry for asking for too much help on this.

**Comment by AjayTripathy** [comment]
No problem. Are you whitelisting anything on prometheus? Can you find either of those metrics by port-forwarding to the pod and visiting  localhost:9003/metrics ? That would help us understand if its metric emission or something else in prometheus preventing us from seeing that.

**Comment by atamnitkkr** [comment]
@AjayTripathy I have vanilla Prometheus. (not whitelisting or blacklisting). I am able to compute load balancer cost if it is created for any Kubernetes service. 
In my case, we are creating a Load balancer as a part of k8s deployment, and it is used for the k8s API server. and its cost should be related to accessing the k8s API server. but looks like opencost doesn't compute the cost of the mentioned Load balancer or I am missing any metrics here?

**Comment by AjayTripathy** [comment]
Could you paste the output of localhost:9003/metrics ? That would give us a sense of whether its failing to detech or something else. 

Loadbalancer metrics should be read/emitted here:
https://github.com/opencost/opencost/blob/cda202ddedb57d02bc307ea63052b29f1a504c97/pkg/costmodel/metrics.go#L569

**Comment by atamnitkkr** [comment]
Hi @AjayTripathy ,
Please find attached metrics from opencost and prometheus. Note that It happens only for the load balancer we deploy for the k8s API server.  
[prometheus.txt](https://github.com/opencost/opencost/files/10060710/prometheus.txt)
[opencost.txt](https://github.com/opencost/opencost/files/10060712/opencost.txt)

I checked the referred code, it looks for a load balancer with a service list only. Not for the k8s API server.

https://github.com/opencost/opencost/blob/58a3c39607adc8b5195ba031d6bdd6d3be3b25de/pkg/costmodel/costmodel.go#L1228
servicesList := cm.Cache.GetAllServices()
	loadBalancerMap := make(map[serviceKey]*costAnalyzerCloud.LoadBalancer)


	for _, service := range servicesList {

**Comment by AjayTripathy** [comment]
Hi @atamnitkkr I would love to collaborate on a way to discover and emit metrics for that loadbalancer. Where in the k8s api is that loadbalancer enumerated?

**Comment by atamnitkkr** [comment]
Hi @AjayTripathy,
I could see this load balancer using Kubernetes config view and also in kubeconfig.yaml.

![image](https://user-images.githubusercontent.com/116127135/203417222-c3b8ecb3-abba-4d93-a8e3-7f72427ac99b.png)

**Comment by AjayTripathy** [comment]
Hey @atamnitkkr as noted on the call that is not a LB enumerated in the kubernetes API, ie 
```kubectl get service --all-namespaces``` 
so is beyond the scope of tracking in the API.
