### ISSUE TITLE
Cost aggregation for pod label is not working

### ISSUE THREAD

**Issue by atamnitkkr** [opencost/opencost#1470]
**Describe the bug**
I am trying to get cost of all pods with particular labels eg.
![image](https://user-images.githubusercontent.com/116127135/199818999-3eabf5a5-aa91-40ba-95d7-3853d4f37bd4.png)

But aggregation is not working ... It always reports the cost with 
![image](https://user-images.githubusercontent.com/116127135/199819213-ed526190-e00f-44ad-be38-4c794a793853.png)

**To Reproduce**
Prometheus is setup as follows -
helm install prometheus prometheus-community/kube-prometheus-stack
--namespace prometheus
--set alertmanager.persistentVolume.storageClass="standard"
--set server.persistentVolume.storageClass="standard"
-f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml

Opencost is setup using
https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml
where the prometheus endpoint is modified

Query ran -
curl http://localhost:9003/allocation/compute \
  -d window=60m \
  -d resolution=1m \
  -d aggregate=label:spark-app-selector \
  -d accumulate=true \
  -G

or 

curl http://localhost:9003/allocation/compute \
  -d window=60m \
  -d resolution=1m \
  -d aggregate=label:spark-app-selector=spark-5726c4578f014379a1df342d835bd206 \
  -d accumulate=true \
  -G

Result -
{"code":200,"status":"success","data":[{"__unallocated__":{"name":"__unallocated__","properties":{"cluster":"cluster-one"},"window":{"start":"2022-11-03T17:25:49Z","end":"2022-11-03T19:25:49Z"},"start":"2022-11-03T17:59:00Z","end":"2022-11-03T19:25:00Z","minutes":86.000000,"cpuCores":2.556163,"cpuCoreRequestAverage":2.556163,"cpuCoreUsageAverage":0.162676,"cpuCoreHours":3.663833,"cpuCost":0.115817,"cpuCostAdjustment":0.000000,"cpuEfficiency":0.063641,"gpuCount":0.000000,"gpuHours":0.000000,"gpuCost":0.000000,"gpuCostAdjustment":0.000000,"networkTransferBytes":12641134734.421846,"networkReceiveBytes":10411426641.107183,"networkCost":0.000000,"networkCostAdjustment":0.000000,"loadBalancerCost":0.000000,"loadBalancerCostAdjustment":0.000000,"pvBytes":0.000000,"pvByteHours":0.000000,"pvCost":0.000000,"pvs":null,"pvCostAdjustment":0.000000,"ramBytes":2802608866.976744,"ramByteRequestAverage":2802608866.976744,"ramByteUsageAverage":2213297255.308443,"ramByteHours":4017072709.333333,"ramCost":0.015851,"ramCostAdjustment":0.000000,"ramEfficiency":0.789727,"sharedCost":0.000000,"externalCost":0.000000,"totalCost":0.131669,"totalEfficiency":0.151053,"rawAllocationOnly":null}}]}

**Expected behavior**
Should provide the cost of all pods with particular label i.e. spark-app-selector=spark-5726c4578f014379a1df342d835bd206

**Screenshots**
 

**Which version of OpenCost are you using?**
image: quay.io/kubecost1/kubecost-cost-model:latest
https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by AjayTripathy** [comment]
Based on other tickets it seems like another metric may be missing from Prometheus. Does 'kube_pod_labels' exist in Prometheus?

**Comment by atamnitkkr** [comment]
@AjayTripathy Yes, this metric is available. Pods with this label have been terminated after completion. But Seems like I was giving the wrong window. **My error.**

**Just to confirm my use-case** 
Usecase - let's say I submitted one spark job with a particular label. This particular spark job creates multiple executors pods. Some executor pods live for a short time. Some executor pods live for a longer time. After spark job completion, I want to compute its Resource allocation cost (i.e. include idle resources) by aggregating it on a particular label (via opencost). 
Its can be done as follows -
eg.
CPU Resource allocation can be computed (including idle resource cost)= cpuCost/cpuEfficiency. 
where assuming cpuCost is actually a cpuUsuages cost.
Total Resource allocation cost = totalCost/totalEfficiency.

**Comment by AjayTripathy** [comment]
I believe in that case you just need to issue a query that covers the range of time those pods were running. Are the pods not being picked up over that window? If not how long were those pods running? If the runtime is very small, the Prometheus scrape interval needs to be shrunk; we are not guaranteed to pick up all pods with duration less than the scrape interval.

**Comment by bribroder** [comment]
I found this issue as well with all labels with the exception of `app` and `component`:

```
$ curl -X GET "http://localhost:9003/allocation/compute?window=today&aggregate=label:app" | jq '.data[0] | keys'
[
  "__unallocated__",
  "cainjector",
  "cert-manager",
  "prometheus",
  "webhook"
]

$ curl -X GET "http://localhost:9003/allocation/compute?window=today&aggregate=label:name" | jq '.data[0] | keys'
[
  "__unallocated__"
]

$ curl -X GET "http://localhost:9003/allocation/compute?window=today&aggregate=label:component" | jq '.data[0] | keys'
[
  "__unallocated__",
  "alertmanager",
  "proxy",
  "pushgateway",
  "redis",
  "scheduler",
  "server",
  "singleuser-server",
  "statsd",
  "triggerer",
  "user-scheduler",
  "webserver",
  "worker"
]
```

This does not seem to be an issue with punctuation in labels--I tested all of these labels:

- name
- release
- heritage
- chart
- app.kubernetes.io/name (also as app_kubernetes_io_name)
- k8s-app (also as k8s_app)

None of which return results except `__unallocated__`

Pods matching these labels are running continuously over the window and I do get results for the `app` label which should then appear for other label queries, such as:

```$ kubectl describe pods -l app=cert-manager
Name:             cert-manager-68fd58f5c8-lms5r
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager
Labels:           app=cert-manager
                  app.kubernetes.io/component=controller
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=cert-manage
```
