### ISSUE TITLE
Downstream performance impacts on Metrics store

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1472]
**Overview**

At Grafana, we've rolled out `opencost` to our fleet of clusters and are seeing a downstream impact on our Mimir databases read performance.
Our read performance SLO had ~10% drop once we rolled out `opencost` to all of our clusters(`2022-10-21`):

![Image](https://user-images.githubusercontent.com/1080566/200383286-49dd8a57-7542-440f-8b53-9d420c1e4de5.png)

We've been able to trace some of the slowest running queries to a number of `query_range` calls originating from `opencost`.
The main thing we noticed was the queries did not have their start/end times alinged with the step being called, which reduces the effectiveness of caching. 
We've been able to mitigate the impact of the queries coming from `opencost` by forcing Mimir to [align queries](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/query-frontend/#caching) to ensure our query frontends are using as much cached data as possible.
The SLO graph above doesn't provide much evidence of an improvement, however an adhoc query to track the time spent processing `opencost` queries is more drastic(we enforced step-aligned queries on `2022-10-28`):

![Image](https://user-images.githubusercontent.com/1080566/200383855-d81d1448-1a79-4f79-8526-7d511b097b81.png)

**Expected behavior**
I would expect range queries to have the start/end times aligned with the step to enable underlying metric systems to better utilize caching mechanisms.

**Which version of OpenCost are you using?**
`quay.io/kubecost1/kubecost-cost-model:prod-1.97.0`

**Additional Context**
While I can't go into too much details about our production systems, we've deployed `opencost` to all of our production clusters that are running in GKE, EKS, and AKS. 
The `opencost` instances query our Mimir cluster that's responsible for storing metrics for all of our clusters. 
We did not notice a major decrease in performance when running ~4 instances of `kubecost` and `opencost`.

After some personal investigation, I've been about to identify two areas where the start/end times could be aligned with the step:
- [costmodel.go](https://github.com/opencost/opencost/blob/c7706a4fb2920869500f46ead1a7c5304080187f/pkg/costmodel/costmodel.go#L1564-L1572)
- [query.go](https://github.com/opencost/opencost/blob/cb96d62cf394c41dea507c8e72e781ab84c900ab/pkg/prom/query.go#L319-L323)

Here's the code that Mimir uses to enforce the start/end times are aligned: [step_align.go](https://github.com/grafana/mimir/blob/83bca0c0aa9d4ddb5b282f97aa8f46e554fb5b90/pkg/frontend/querymiddleware/step_align.go).

My ask for the opencost folks is see if there are any potential problems with aligning the start/end times with the step for range queries. I'd be more then happy to submit a PR to review and see if we can collaborate on generating an image we can run across our fleet to test out the change.

**Comment by AjayTripathy** [comment]
Hi @Pokom thank you so much for this report! We're always excited by performance improvements on the promQL side. Here are my thoughts. 

1. I don't see any potential problems with aligning the start/end times; we can try this out and run integration tests on our end to gain confidence.
2. Any indication what queries are being run as range queries out of alignment? We've taken a pass to try and cut down on those, so curious what you're seeing on your end.

**Comment by Pokom** [comment]
@AjayTripathy I think all the queries that are fired off in parallel here(https://github.com/opencost/opencost/blob/c7706a4fb2920869500f46ead1a7c5304080187f/pkg/costmodel/costmodel.go#L1613-L1635) are potential queries that are out of alignment. I can work with Mimir engineers to see if we can validate these are the main culprits, but it's a bit of a needle in a haystack search. 

I'd love some help on running integration tests! If you end up having a public image, I can roll this out to our fleet as well and have Mimir team disable forcing the queries to be step-aligned and track our SLO. 

**edit**

One of the queries that clued us in to the problem originating from `opencost` were:
- `"/api/prom/api/v1/query_range?end=2022-11-01T10:48:33.754793185Z&query=avg_over_time(kube_pod_labels{cluster="OUR_CLUSTER_HERE"}[1h])&start=2022-10-31T10:48:33.754793185Z&step=3600.000"`

This query too ~7 seconds to run.

**Comment by Logiraptor** [comment]
Hi :wave: I'm on the Mimir team at Grafana. 

> I can work with Mimir engineers to see if we can validate these are the main culprits, but it's a bit of a needle in a haystack search.

I agree with @Pokom those are probably the bulk if not all. I'm not super familiar with the opencost codebase but those do look like a lot of the queries I see in our logs. 

One other thing that would help improve performance for us is to have the option of running queries with a delay of 24h. For Mimir, this would mean queries can avoid hitting the ingesters for recent data and also make use of the more efficient compacted blocks. I'm not sure if that would harm the usefulness of opencost to have data delayed by 24h, but figured I'd suggest it since it would help us.

**Comment by AjayTripathy** [comment]
@Pokom thanks for the tip. We shouldn't be running those sorts of queries in any automated loop-- could I get a sense of what queries are being made / what APIs are being called on your end? Also, to clarify, you've installed just the opencost containers, not the full suite of kubecost tooling (https://github.com/kubecost/cost-analyzer-helm-chart), right?

**Comment by Pokom** [comment]
@AjayTripathy 
> you've installed just the opencost containers, not the full suite of kubecost tooling (https://github.com/kubecost/cost-analyzer-helm-chart), right?

Just the `opencost` container with no additional UI/kubecost tooling. 

>We shouldn't be running those sorts of queries in any automated loop-- could I get a sense of what queries are being made / what APIs are being called on your end

That's interesting. The only thing we're doing is scraping the `/metrics` endpoint to gather the metrics. Can you point towards the entrypoint in the codebase for kicks off running processes in the background to collect metrics? We're getting the following metrics exported:

- `container_cpu_allocation`
- `container_memory_allocation_bytes`
- `kubecost_load_balancer_cost`
- `kubecost_network_internet_egress_cost`
- `kubecost_network_internet_region_cost`
- `kubecost_network_internet_zone_cost`
- `node_cpu_hourly_cost`
- `node_ram_hourly_cost`
- `node_total_hourly_cost`
- `pv_hourly_cost`

Looking through our logs for `opencost`, I see lots of instances similar to this this line: `[90m2022-11-09T20:35:47.842863046Z[0m [32mINF[0m ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found true, disableCache true, noCache false)`

![image](https://user-images.githubusercontent.com/1080566/200936985-9fa52ce3-1aff-45a4-9890-db9634ed33a6.png)

The graph above is an aggregate of all of our `opencost` containers. So for some reason, the `ComputeAggregateCostModel` method is being called by each container every few minutes. Just looking at the log, it looks like disableCache is true which is why this is getting tripped up. Let me see if I can enable cache...

**Comment by AjayTripathy** [comment]
Thanks @Pokom ...let me also do some investigation on our side. Maybe our container usage derivation loop (queries prometheus for usage data not in the k8s api) is needlessly doing this or perhaps needlessly hitting all clusters instead of scoping down to per-cluster.

**Comment by Pokom** [comment]
So just an update from my investigations into enabling `disableCache`:

The missed cache log statement is coming from [aggregation.go#1411](https://github.com/opencost/opencost/blob/3a4efb06f179d4b1cfa9b9e0e4d884529d091c9e/pkg/costmodel/aggregation.go#L1411), and it's pretty clear from the logs that `disableCache` is always set to `true` when it gets to this point of the code. I looked back at the past 30 days worth of logs and could not find an instance where it was set to false. I also see that `found` is always true, so the data *is* cached, but we short circuit using the cache here https://github.com/opencost/opencost/blob/3a4efb06f179d4b1cfa9b9e0e4d884529d091c9e/pkg/costmodel/aggregation.go#L1403-L1409

Tracing back, `disableCache` is derived from [ops.DisabledCache](https://github.com/opencost/opencost/blob/3a4efb06f179d4b1cfa9b9e0e4d884529d091c9e/pkg/costmodel/aggregation.go#L1098) which is either the value passed into the method(Could use some help tracing this a bit better), or comes from [DefaultAggregateQueryOpts](https://github.com/opencost/opencost/blob/3a4efb06f179d4b1cfa9b9e0e4d884529d091c9e/pkg/costmodel/aggregation.go#L1031). The default value for `disableCache` is false, and it doesn't look like there's any way of defining that via an environment variable. 

There is one code path though that sets `disableCache = ` https://github.com/opencost/opencost/blob/831c65c364156dc048da50bbb4814a9da9583dfb/pkg/costmodel/aggregation.go#L1390-L1397
So for some reason this check always ends up disabled the cache. 

@AjayTripathy ~I can submit a PR that adds that environment variable so that it can be defined at runtime :smile:~ I submitted a PR to allow the operator override the `disableCache` value: https://github.com/opencost/opencost/pull/1478

**Comment by AjayTripathy** [comment]
@Pokom have you tried to rebuild/redeploy and see if this has made an impact? All clear on our end to at least deploy this is a beta. If you want us to provide a release/image for you we can do that as well.

**Comment by Pokom** [comment]
@AjayTripathy I haven't had a chance, last week we had an offsite and this week I'm on vacation :turkey: 

If you provide us an image, I'd be more then happy to release this out to our clusters and remove the flag on Mimir that enforces step-alignment on queries.  

I'll be back next Monday(2022-11-28) and will have the bandwidth to roll this out fairly quickly.

**Comment by Pokom** [comment]
@AjayTripathy I'm back today, let me know if there's an image available I can use to rollout to our fleet, otherwise I can try and build an internal one for us to evaluate.

**Comment by AjayTripathy** [comment]
@Pokom take a look at this image I cut: 
```gcr.io/kubecost1/opencost:test-prom-opt```
 and let me know!

**Comment by Pokom** [comment]
@AjayTripathy rolled out to our development clusters and things are looking good! Here's a sample log to demonstrate the queries step aligned:

```sh
level=info ts=2022-11-29T16:49:05.134639341Z caller=handler.go:240 user=9960 msg="query stats" component=query-frontend method=POST path=/prometheus/api/v1/query_range response_time=1.589155ms query_wall_time_seconds=0 fetched_series_count=0 fetched_chunk_bytes=0 fetched_chunks_count=0 fetched_index_bytes=0 sharded_queries=0 split_queries=0 param_end=2022-11-29T16:00:00Z param_query="max(count_over_time(kube_pod_container_resource_requests{cluster=\"dev-eu-west-3\",resource=\"memory\",unit=\"byte\"}[1h]))" param_start=2022-11-28T16:00:00Z param_step=3600.000 status=success
```

**Comment by Pokom** [comment]
Released the image across our fleet and turned off the feature flag in `mimir` to force queries to be step aligned. So far there's been no regressions and am pretty confident all of the queries sent via opencost are now step aligned.

**Comment by AjayTripathy** [comment]
Awesome, thank you so much for testing that and the PR!

**Comment by Pokom** [comment]
My pleasure Ajay! Thanks for helping see this through and providing support when needed :smile: I'm looking forward to contributing more.
