### ISSUE TITLE
deployments.apps "opencost-cost-analyzer" not found

### ISSUE THREAD

**Issue by yourmoonlight** [opencost/opencost#1474]
**Describe the bug**
when i try to follow the ui doc，run this cmd and then the error comes.
https://github.com/opencost/opencost/tree/develop/ui

**Screenshots**
<img width="732" alt="image" src="https://user-images.githubusercontent.com/6244271/200578936-922d9eb7-77a8-4e6d-9ad0-6f7cb8d96d03.png">

**Comment by AjayTripathy** [comment]
The name's been changed in opencost-- @mattray can you help update the documentation here? Probably should read 

kubectl port-forward deployment/opencost 9090

**Comment by dwbrown2** [comment]
@mattray how do you want to handle this one?

**Comment by zeed-w-beez** [comment]
@yourmoonlight try this:
```
kubectl port-forward deployment/opencost 9090:9003
```

**Comment by AjayTripathy** [comment]
Closed based on merged UI doc! Thanks zeed!
