### ISSUE TITLE
node_cpu_hourly_cost and node_ram_hourly_cost contain unnormal spikes

### ISSUE THREAD

**Issue by AndrewChubatiuk** [opencost/opencost#1481]
**Describe the bug**
When visualizing opencost metrics in grafana node_cpu_hourly_cost and node_ram_hourly_cost metrics contain spikes, which are not expected as they appear for instance, which has constant pricing model.

**To Reproduce**
Visualize opencost metrics in grafana

**Expected behavior**
All node_cpu_hourly_cost and node_ram_hourly_cost metrics should be constant for instance type

**Screenshots**
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/3162380/201349009-13d26a21-0145-429f-885d-5ae0ece9728c.png">

**Which version of OpenCost are you using?**
Latest

**Comment by AjayTripathy** [comment]
Hi @AndrewChubatiuk , I don't see this on our end. Can you share:
1. a graph of node_total_hourly_cost ?
2. what instance this is and your cloud provider/how this pricing is being determined?
