### ISSUE TITLE
opencost open ui error

### ISSUE THREAD

**Issue by luojieio** [opencost/opencost#1501]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25678606/202668612-e3f2ad9b-f9d4-4189-ad5b-28ca4204ca24.png)

**To Reproduce**
reference this step to deploy https://github.com/opencost/opencost/tree/develop/ui

**Which version of OpenCost are you using?**
opencost latest version
open ui is latest version

**Additional context**
I test opencost is can get right output，but ui is not work right, port is ok

**Comment by AjayTripathy** [comment]
Hi @luojieio the most likely case is that we can't connect to the backend. Is your port-forward running? What's the output there?

```kubectl port-forward deployment/opencost 9090:9003```

**Comment by luojieio** [comment]
![image](https://user-images.githubusercontent.com/25678606/205593808-9c248faa-39cb-4e17-a4e9-98951dc517b2.png)
![image](https://user-images.githubusercontent.com/25678606/205593919-f0e1767b-09ae-44c2-9347-2f609acd73c8.png)
![image](https://user-images.githubusercontent.com/25678606/205594006-8f1959d4-4bae-4264-bb2c-a8a44052c58a.png)

**Comment by luojieio** [comment]
fix，because eci machine CORS
