### ISSUE TITLE
Why not use existing Prometheus?

### ISSUE THREAD

**Issue by dudicoco** [opencost/opencost#1504]
Hi,

This is not a bug but there wasn't an option to open a general question about the docs.

It is stated in the docs that it's recommended to install the Prometheus deployment which is bundled with opencost/kubecost rather than using an existing Prometheus installation: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus#bring-your-own-prometheus

The docs are vague about why specifically this is recommended, for example:
> The Kubecost Prometheus deployment is optimized to not interfere with other observability instrumentation and by default only contains metrics that are useful to the Kubecost product. This results in 70-90% fewer metrics than a Prometheus deployment using default settings.

If I already have an existing Prometheus installation, what metrics exactly would opencost add other than the metrics which it exposes on port 9003 in `/metrics`?

Why is the additional overhead of maintaining an additional Prometheus installation is recommended here?

**Comment by AjayTripathy** [comment]
Hi @dudicoco you can definitely bring your own prometheus-- it's just more straightforward to not modify configs, whitelists, etc. in an existing setup, so that's the recommended path for most users.

**Comment by dwbrown2** [comment]
I agree docs should give more guidance/rationale. Here's some of my view from seeing teams integrate:

1. getting the right metrics can require some setup, e.g. ksm + kubecost endpoint
2. harder to troubleshoot, e.g. network issues or others issues that kubecost diagnostics would have less visibility into
3. teams can have other consumers of Prom that could impact uptime or others

Let me know if this is helpful and we can look at adding to docs. cc @kirbsauce

**Comment by kirbsauce** [comment]
Thanks @dwbrown2.  I'll create a separate issue to make note of the (likely) pending update.  

@dudicoco, If you do decide to use your own prometheus, one thing we do recommend is to start with the bundled prometheus and integrate with your cloud provider(s).  When you're confident with the numbers, you have a baseline before using advanced features, such as using your own prometheus.  We've found that having this baseline can help reduce the pain with item 2 from @dwbrown2, namely troubleshooting.

**Comment by mattray** [comment]
https://www.opencost.io/docs/install#providing-your-own-prometheus

**Comment by ahmedbs94** [comment]
Is there any updates for this setup?
