### ISSUE TITLE
Remove kube-state-metrics related metrics

### ISSUE THREAD

**Issue by dudicoco** [opencost/opencost#1509]
**Is your feature request related to a problem? Please describe.**
Opencost currently exports duplicated KSM metrics while also depending on metrics exported by KSM, see https://docs.kubecost.com/architecture/ksm-metrics

Per that page, the current long term plan is to remove the dependency on KSM, this has a few downsides:
1. Maintaining code for all of the duplicated metrics 
2. Exporting many more metrics in addition to the cost metrics
3. Requires additional RBAC permissions

**Describe the solution you'd like**
Rather than removing the dependency on KSM I believe the better solution would be to only depend on KSM metrics and remove all of the duplicated metrics, while aligning with the metrics from the latest version of KSM.

Opencost already has a hard dependency on Prometheus (and possibly node-exporter and cadvisor?), so it could also have a hard dependency on KSM.

**Comment by AjayTripathy** [comment]
Hi @dudicoco thanks for the observation here. Our philosophy is to use KSM if it exists, but not take a hard dependency on it. To that end, if you're running KSM v1, you can set EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to false. If you're running KSM v2, you can set EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true. 

I agree we should update to support interoperability with KSM V2 better so you can have a simple flag to where Opencost emits no KSM metrics at all when KSMv2 is enabled. To that end, I propose we rename this issue to be something like "create flag to support ksm v2 with no metrics duplication". What do you think of that?

**Comment by dudicoco** [comment]
Thanks @AjayTripathy.
Yes i'm aware of the different flags, though some of the KSM V1 metrics generated by opencost do exist in KSM V2, they only differ by a label or two.
For example the metric `kube_pod_owner` emits a lot of sample and it's a waste to duplicate it.

Can you please elaborate why should opencost be responsible for emitting KSM metrics but not node-exporter/cadvisor metrics which it also needs to operate?

**Comment by AjayTripathy** [comment]
@dudicoco if there are specific metrics that seem to be duplicated, I'm very open to adding flags to remove them from opencost.

We chose to not take a hard dependency on KSM for two main reasons:
1. KSM metrics are 100% mandatory to display useful costing information. Cadvisor and node exporter hydrate different data fields, like usage etc. If we don't have usage data we fall back to billing on request data available in KSM. node-exporter likewise adds just a few supplementary pieces of data not mandatory for an accurate and fair costing model.
2. Feasibility. It's much harder to run a query against every agent than a single point like the k8s api.

**Comment by simonpasquier** [comment]
I'm more familiar with kube-state-metrics than kubecost so take my comment with a grain of salt. IMHO having a soft dependency on kube-state-metrics is desired because KSM is already 1) available in many environments and 2) time-tested. For instance, it implements its own Prometheus instrumentation library because prometheus/client_golang triggered performance and resource issues on large clusters.

**Comment by dudicoco** [comment]
> KSM metrics are 100% mandatory to display useful costing information. Cadvisor and node exporter hydrate different data fields, like usage etc. If we don't have usage data we fall back to billing on request data available in KSM. node-exporter likewise adds just a few supplementary pieces of data not mandatory for an accurate and fair costing model.

@AjayTripathy prometheus is also %100 mandatory for kubecost to work at all, yet it's included as a hard dependency rather than implementing an internal metrics storage.

Can you please also elaborate what you mean by this statement:
> It's much harder to run a query against every agent than a single point like the k8s api.

**Comment by dudicoco** [comment]
> I'm more familiar with kube-state-metrics than kubecost so take my comment with a grain of salt. IMHO having a soft dependency on kube-state-metrics is desired because KSM is already 1) available in many environments and 2) time-tested. For instance, it implements its own Prometheus instrumentation library because prometheus/client_golang triggered performance and resource issues on large clusters.

@simonpasquier isn't what you describe is a reason to have it as a hard dependency?

**Comment by simonpasquier** [comment]
@dudicoco I understand why the kubecost maintainers want to avoid a hard dependency on KSM (e.g. easier to deploy kubecost and play with it) but I suspect that for production usage, kubecost would benefit from leveraging kube-state-metrics. Again just my 2c, I don't have much context about this project :)

**Comment by dudicoco** [comment]
@AjayTripathy we've now run into some problems due to the metrics duplication.

We're getting errors from Prometheus related to the `kube_pod_owner` metric that is duplicated by kubecost: `many-to-many matching not allowed: matching labels must be unique on one side`.

Why is this metric needed alongside the metric generated by KSM V2? The labels are identical between the two.
Could I just drop this metric from kubecost?

**Comment by AjayTripathy** [comment]
Yes, you can. I will also file an issue to remove that metric if you have set EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true.

**Comment by dudicoco** [comment]
Thanks @AjayTripathy.
I went through all of the metrics listed [here](https://docs.kubecost.com/architecture/ksm-metrics#dealing-with-duplicate-metrics-when-a-non-kubecost-ksm-is-present-in-the-cluster) and found that only the following ones are not emitted by KSM v2:
kube_node_status_capacity_memory_bytes
kube_node_status_capacity_cpu_cores
kube_node_status_allocatable_memory_bytes
kube_node_status_allocatable_cpu_cores

Are these metrics still used by opencost? If so perhaps it's time to modify the code to use `kube_node_status_capacity` and `kube_node_status_allocatable` instead which would remove the dependency on KSM v1 metrics.

The rest of the metrics can be removed when you set EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true, can you please add them to #1571?

**Comment by kaelanspatel** [comment]
Hi all,

While this doesn't preclude any changes to the flags to make them more user-friendly, I note we do support a metrics blacklist. Metrics can be disabled in a fine-grained way by configuration in the helm chart:
```
kubecostProductConfigs:
  ...
  metricsConfigs:
    disabledMetrics:
      - <metric-to-be-disabled>
      - <metric-to-be-disabled>
      etc.
```
https://github.com/kubecost/cost-analyzer-helm-chart/blob/f9a8f3326a540e1b0ece714c52f100fa085bf0b8/cost-analyzer/values.yaml#L928-L929

This does require more manual configuration, but it should solve this (and any related duplication) issue(s) without a need to upgrade and/or change flag behavior.

**Comment by lilywolfrum** [comment]
Hey @dudicoco so we actually do support turning metrics off at a more granular level within the app. Does this meet your needs in order to move forward? Thanks - Lily Wolfrum

**Comment by dudicoco** [comment]
Hi @AjayTripathy @kaelanspatel @lilywolfrum,

Adding this config indeed removed the problematic metrics, thanks!
However this fix is just a workaround so i'm not sure why https://github.com/opencost/opencost/pull/1635 was closed?

The user experience when integrating kubecost is currently lacking due to these duplicate metrics and the not so approachable way of disabling them (different flags via environment variables + disabled metrics config).

Also there is a lot of documentation missing in the official docs for some configuration options which only exist within the kubecost helm chart (what about users who are not using this chart?), for example the metrics configmap which you need to add in order to disable the metrics is not documented in the official docs.

As a side note, the way kubecost loads configmap currently is by watching the configmaps via the kube api, this totally disregards the native mechanism of mounting configmaps into files on the container.

**Comment by AjayTripathy** [comment]
Hey @dudicoco thanks for your feedback. We'll make sure to add the configs to documentation and consider global toggles for disabling batches of metrics in an upcoming release. Let's see where we stand on usability after clearly documenting the disabling and which metrics should be disabled on a BYO-kube-state-metrics install.

**Comment by dudicoco** [comment]
Hi @AjayTripathy,

Can the all of the rbac permissions (except for node permissions which I think are still needed) be removed from kubecost after disabling the metrics, or would kubecost not work properly without those?
