### ISSUE TITLE
Move OpenCost out of Kubecost container registry

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1518]
OpenCost is currently deployed via the manifest https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml

and the image pulled is 
```
        - image: quay.io/kubecost1/kubecost-cost-model:latest
```

Ideally the image should be renamed to opencost and potentially hosted at a CNCF-provided location. Once the opencost-ui image is available it should be there too.

**Comment by chipzoller** [comment]
This can be closed. The OpenCost image is now a [package in this repository](https://github.com/opencost/opencost/pkgs/container/opencost).
