### ISSUE TITLE
Customised pricing for on-prem cluster in opencost

### ISSUE THREAD

**Issue by dipchavan** [opencost/opencost#1564]
Kindly provide the customised pricing option for on-prem clusters in opencost.

I am seeing it is documented in opencost faq page: https://www.opencost.io/docs/FAQ but looks like it is not currently supported.

**Comment by AjayTripathy** [comment]
https://github.com/opencost/opencost/blob/develop/configs/default.json

Hi @dipchavan for now, you can set your prices in default.json and build the image to change custom pricing. I think that we can look to improve this with env variables in the future-- @mattray can you document the current process and also file an issue to improve?

**Comment by dipchavan** [comment]
Thank you Ajay. Let me try this and will let you know if need any help.Regards,Dipak Sent from my iPhoneOn 15-Dec-2022, at 2:33 AM, Ajay Tripathy ***@***.***> wrote:﻿
https://github.com/opencost/opencost/blob/develop/configs/default.json
Hi @dipchavan for now, you can set your prices in default.json and build the image to change custom pricing. I think that we can look to improve this with env variables in the future-- @mattray can you document the current process and also file an issue to improve?

**Comment by AjayTripathy** [comment]
@mattray ping? Can we please document this process as how to set custom pricing in opencost?

https://github.com/opencost/opencost/issues/1564#issuecomment-1352173995

You will need to edit the "default.json" file and send it to whatever container is running the image at this location: https://github.com/opencost/opencost/blob/develop/Dockerfile#L36

**Comment by mattray** [comment]
@AjayTripathy it's on my todo list for this week.

**Comment by brstuder** [comment]
@mattray Let me know if you need any help on this doc, or another pair of eyes at least

**Comment by dipchavan** [comment]
Sure Matt Thanks Sent from my iPhoneOn 31-Jan-2023, at 8:35 PM, bstuder99 ***@***.***> wrote:﻿
@mattray Let me know if you need any help on this doc, or another pair of eyes at least

**Comment by mattray** [comment]
https://github.com/opencost/opencost-website/pull/80 documents the `default.json` approach.

**Comment by mattray** [comment]
https://www.opencost.io/docs/on-prem#custom-pricing-using-the-opencost-helm-chart shows using a ConfigMap with the Helm Chart to apply custom prices. I'm closing this issue accordingly.
