### ISSUE TITLE
Run opencost without prometheus

### ISSUE THREAD

**Issue by day1118** [opencost/opencost#1565]
**Is your feature request related to a problem? Please describe.**
I want to use opencost to import the cloud infra costs into any metrics tool (via prometheus scraping). In this case, there would be no prometheus for opencost to read from.

**Describe the solution you'd like**
Opencost scrapes kube-state-metrics directly to get the custer/node info and generates the scrape data.

**Describe alternatives you've considered**
Running a dedicated prometheus for opencost to query, even though that prometheus will not scrape opencost

**Additional context**
I want to use a managed prometheus which scapes opencost, but I don't want opencost to have access to the managed prometheus to query. I accept that some metrics will not exist as node exporter would not be running/accessible in this case. I just want to report the cloud compute costs to my metrics tool.

**Comment by dwbrown2** [comment]
@day1118 if you don't pass a Prometheus endpoint, you should get all OpenCost metrics but without usage statistics --https://github.com/opencost/opencost/blob/55ebcfd746133dae14adc4723333435705ee6cf1/kubernetes/opencost.yaml

Have you tried that?

My understanding is the main part left to have all metics be equivalent would be to directly scrape cadvisor. @Sean-Holcomb was potentially interested in exploring. 

@mattray can you share any relevant Prometheus documentation?

@AjayTripathy is there any else you want to add?

**Comment by day1118** [comment]
> If you don't pass a Prometheus endpoint, you should get all OpenCost metrics but without usage statistics

That was my hope, but instead I get: 
```No address for prometheus set in $PROMETHEUS_SERVER_ENDPOINT. Aborting.```
https://github.com/opencost/opencost/blob/cda202ddedb57d02bc307ea63052b29f1a504c97/pkg/cmd/agent/agent.go#L70

**Comment by mattray** [comment]
I'll defer to @AjayTripathy or @Sean-Holcomb on how to implement this.

**Comment by AjayTripathy** [comment]
This behavior is unintentional, so I'd call this a bug. Our goal should be to emit request statistics in the absence of prometheus, to let's get this fixed!

**Comment by dwbrown2** [comment]
Would love to get this knocked out soon and would call P0/1 for 1.100. 

@michaelmdresser I believe you and I worked on originally enabling this functionality... remember where we documented?

**Comment by michaelmdresser** [comment]
There was this PR from a while ago, which may be what you're asking about @dwbrown2. Not sure where this documentation is these days, many changes have happened since then.
- https://github.com/opencost/opencost/pull/697

**Comment by dwbrown2** [comment]
Thanks, @michaelmdresser! 

@mattray are we able to see why [kubecost-exporter.md](https://github.com/opencost/opencost/blob/da55364e680851c8c6315073c6413aa0aac8caec/kubecost-exporter.md) was deleted and then restore that documentation for OpenCost?

**Comment by mattray** [comment]
@dwbrown2 it looks like it came out of https://github.com/opencost/opencost/pull/1369
We can cherry-pick it back, do we want to open a new issue and rename it opencost-exporter.md?

**Comment by dwbrown2** [comment]
@mattray that sounds good to me! just created https://github.com/opencost/opencost/issues/1575

@jessegoodier remember if there was a specific reason why we dropped?

**Comment by jessegoodier** [comment]
> @mattray that sounds good to me! just created #1575
> 
> @jessegoodier remember if there was a specific reason why we dropped?

oh no. That's completely my fault. 

@mattray, happy to fix this, or let me know if you have already started.

**Comment by mattray** [comment]
@jessegoodier I'll let you bring it back

**Comment by mattray** [comment]
@jessegoodier did https://github.com/opencost/opencost/pull/1578 fix this issue sufficiently?

**Comment by jessegoodier** [comment]
Yes, this should be closed, unless we have reports that sometihng is not working?

**Comment by jawadqur** [comment]
I just want to bump this up, I want to run opencost model and just get an estimate of the pod pricing without prometheus, based on cpu/memory requests and this is still showing the error: 

```
2024-09-11T14:43:27.539731727Z FTL No address for prometheus set in $PROMETHEUS_SERVER_ENDPOINT. Aborting.
```

**Comment by jessegoodier** [comment]
> I just want to bump this up, I want to run opencost model and just get an estimate of the pod pricing without prometheus, based on cpu/memory requests and this is still showing the error:
> 
> ```
> 2024-09-11T14:43:27.539731727Z FTL No address for prometheus set in $PROMETHEUS_SERVER_ENDPOINT. Aborting.
> ```

I believe you can set that to any fake address:
```
            env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: http://fake-prometheus
```
