### ISSUE TITLE
Container image opencost-ui is  not public so we can't install it

### ISSUE THREAD

**Issue by sogos** [opencost/opencost#1567]
**Describe the bug**
Following the documentation on installing opencost, the manifest file in documentation try to deploy the image:
`quay.io/kubecost1/opencost-ui:latest` but actually access to this image is forbiden

**To Reproduce**
1. `kubectl apply --namespace opencost -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml`
2. Observe the logs
3. Get the message `Failed to pull image "quay.io/kubecost1/opencost-ui:latest": rpc error: code = Unknown desc = Error response from daemon: unauthorized: access to the requested resource is not authorized  `

**Expected behavior**
The container and pod is up and running

**Which version of OpenCost are you using?**
I use develop branch version

**Comment by sogos** [comment]
@mattray Thanks 🙏

**Comment by donmstewart** [comment]
I have the same issue at present as well following the installation guide.

**Comment by sklarsa** [comment]
+1

**Comment by Tommyf** [comment]
I just went to follow the install docs on the main docs site [here](https://www.opencost.io/docs/install) and have the same problem.

**Comment by AjayTripathy** [comment]
@mattray was this image being moved somewhere?

**Comment by dwbrown2** [comment]
Assigning this to @mattray as a P0

**Comment by AjayTripathy** [comment]
Hey folks, apologize for the delay. I've just set the repository to public. Please let me know if the issue persists.
![Screen Shot 2022-12-13 at 9 39 59 AM](https://user-images.githubusercontent.com/453512/207405788-55a1f76c-c49a-407c-a574-6dc97229f12b.png)

**Comment by Tommyf** [comment]
Working for me now. Thanks!

**Comment by IDerr** [comment]
Will the code be open sourced also ?

**Comment by mattray** [comment]
@IDerr which code? The UI is all here: https://github.com/opencost/opencost/tree/develop/ui

**Comment by IDerr** [comment]
oops, my bad... Thanks for the link

**Comment by sogos** [comment]
Thanks, it's working now @mattray  :)
