### ISSUE TITLE
Audit application and configuration of Account across cloud providers

### ISSUE THREAD

**Issue by nikovacevic** [opencost/opencost#1570]
## Description
The "Account" field on Assets seems to be rather difficult to pin down. Sometimes it is absent, and seemingly for different reasons on different cloud providers.

## Goals
1. Full explain how Account gets set for each combination of (Kubernetes Assets, Cloud Assets) and (AWS, Azure, GCP)
2. Fix any bugs associated with any of those 6+ implementations
3. Improve configuration, and ideally consolidate across providers

## Related
* https://github.com/kubecost/cost-analyzer-frontend/issues/709

**Comment by nikovacevic** [comment]
## AWS

### Kubernetes Assets
https://github.com/opencost/opencost/blob/v1.99/pkg/cloud/awsprovider.go#L1328
```go
func (awsProvider *AWS) ClusterInfo() (map[string]string, error) {
	// ...

	makeStructure := func(clusterName string) (map[string]string, error) {
		m := make(map[string]string)
		m["name"] = clusterName
		m["provider"] = kubecost.AWSProvider
		m["account"] = c.AthenaProjectID // this value requires configuration but is unavailable else where
		m["region"] = awsProvider.clusterRegion
		m["id"] = env.GetClusterID()
		m["remoteReadEnabled"] = strconv.FormatBool(remoteEnabled)
		m["provisioner"] = awsProvider.clusterProvisioner
		return m, nil
	}
```

`config.AthenaProjectID` gets set in helm `kubecostProductConfigs.athenaProjectID`

Then, each Kubernetes Asset will have `Account` set by `src.propertiesFromCluster(node.Properties)` (closed source)

### Cloud Assets

TO DO

**Comment by mmurph3** [comment]
please see latest screenshots (12/20/22) https://kubecost.zendesk.com/agent/tickets/3176 looks like we're missing account in the clusterinfomap output.

**Comment by mmurph3** [comment]
@nikovacevic @Sean-Holcomb - customer set kubecostProductConfigs.ProjectID. After running etl repair and reconcile we're still seeing "No account". https://kubecost.zendesk.com/agent/tickets/3176

```
"at<obfuscated>": {
"id": "at<obfuscated>",
"name": "at<obfuscated>",
"profile": "production",
"provider": "AWS",
"account": "",
"project": "",
"region": "us-east-1",
"provisioner": "EKS"
}

```

**Comment by Sean-Holcomb** [comment]
@mmurph3 the correct value that needs to be set is `kubecostProductConfigs.athenaProjectID`, sorry for the confusion

**Comment by mmurph3** [comment]
Thanks @Sean-Holcomb We’re able to see the `account` on `/clusterInfoMap` endpoint now for all associated clusters. Just fyi, I don’t think running `/repair` or even `/reconcile` endpoints fixed the issue after adding `kubecostProductConfigs.athenaProjectID`. We're also seeing this in azure environments (no account line item in assets page). Any additional data points needed that aren't present in the recent comments on issue https://github.com/kubecost/cost-analyzer-frontend/issues/709 ?

**Comment by Sean-Holcomb** [comment]
Rebuild will not change the historic data, because the setting that value only adds the field to prometheus data moving forward. Since the value is not present in historic prometheus data rebuilds will not make it show up.
