### ISSUE TITLE
Add opencost_build_info prometheus metric

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1576]
**Is your feature request related to a problem? Please describe.**
Currently there is no way of determining what version of `opencost` via PromQL. This is important for two reasons:
1. Internally we rely upon querying `${SERVICE}_build_info` to determine if a new version is available for us to upgrade to
2. When having _many_ `opencost` deployments, it's helpful to understand which cluster has which version of `opencost` running

**Describe the solution you'd like**
We should export an addition metric `opencost_build_info` that has at least a `version` label that is inferred at build time of the container. 

**Describe alternatives you've considered**
We could manually release upgrades, but that's tedious and goes against our internal goal of staying relatively up to do. 
We could also write custom scripts to determine the versions per cluster, but again would prefer for this to align with our existing dashboards.

**Comment by Pokom** [comment]
I've got a pr (#1577) available where I'd love to get some early feedback. The technique that I followed makes use of `ldflags` to pass in the relevant values during build time, and are exposed via a prometheus metric `opencost_build_info`. 

I think I need buy in from the team to use this approach because it will modify how we build `costmodel`. I've included a Makefile that will set each of the flags and pass them in to the go build command. I don't necessarily think we _need_ the Makefile long term, just wanted to include it for easy reference. 

Here's what the metric looks like when running locally:

```
[
  {
    "name": "opencost_build_info",
    "help": "opencost_build_info Build information",
    "type": "GAUGE",
    "metrics": [
      {
        "labels": {
          "branch": "feat/build-info-metric",
          "builddate": "2022-12-16T15:26:40-05:00",
          "goversion": "go1.19",
          "revision": "732c6e01",
          "version": "feat-build-info-metric-732c6e01"
        },
        "value": "1"
      }
    ]
  }
]
```

**Comment by Adam-Stack-PM** [comment]
@Pokom, Thanks for the linked PR. I will get eyes on this for a review early next week.

**Comment by dwbrown2** [comment]
A big +1 here on doing this! Thanks for the contribution.

**Comment by Pokom** [comment]
Awesome, thanks for getting some :+1: on the idea at least. @dwbrown2 I think the main area I'm going to need some guidance on is how we want the `version` to be populated. I'm leaning on how some of the OSS Grafana Projects are exporting this information today, but am completely open a new direction as well.

**Comment by AjayTripathy** [comment]
Hi @Pokom I peeked at #1577 . I think that the updates there are good-- we haven't been attaching build sha numbers so far, though I think that would be an improvement. What we do is just tag the version in each release branch as an env variable https://github.com/opencost/opencost/blob/v1.99/pkg/env/costmodelenv.go#L170 . Is that helpful context?

**Comment by Pokom** [comment]
Thanks @AjayTripathy!! Totally overlooked that and saw we're exposing the version and commit info in the [dockerfile](https://github.com/opencost/opencost/blob/93d4997ff165283b6edd95010a85918a5dea88b3/Dockerfile#L14-L15) and then passing them along as `-ldflags` in the [build step](https://github.com/opencost/opencost/blob/93d4997ff165283b6edd95010a85918a5dea88b3/Dockerfile#L28-L30).

Let me update my PR just a bit to take advantage of what exists already.

**Comment by Pokom** [comment]
Alright I've updated my PR now that I know we already have a mechanism in place to pass in the version and revision number when building the image. @AjayTripathy would you want me to remove the Makefile I created in favor of any existing scripts you use internally? Otherwise I can expand upon it to write up the commands to generate the image.
