### ISSUE TITLE
container_cpu_allocation documentation unclear

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1582]
I've been trying to make better sense of what exactly `container_cpu_allocation` measures and exports and think there's some inconsistency in the documentation. While I'm focusing on CPU, it's the same level of confusion for memory and GPU as well. Here are  the places I've checked:

- [spec](https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md#workload-costs), as: `The greater of requested and used CPU resources measured in cores or millicores.`
- [prometheus exporter help](https://github.com/opencost/opencost/blob/develop/pkg/costmodel/metrics.go#L214): `container_cpu_allocation Percent of a single CPU used in a minute`
- [kubecost docs](https://github.com/kubecost/docs/blob/main/user-metrics.md#kubecost-cost-model): `Average number of CPUs requested/used over last 1m`

What I'm trying to do is get an estimate for the cost of running a workload based upon _actual_ usage. My understanding according to the spec is that this metric should be the `max(request, usage)`, but I have my reservations given other documentation on queries to run(https://github.com/opencost/opencost-website/pull/69/files#diff-ea7709a8edb327c8f6d08717e39532671865997b719fbc80a46a0cf9556ecbceR88-R92) that seem to imply that `container_cpu_allocation` only measures the cost of requests.

So here's my question:
- What exactly does `container_cpu_allocation` measure and can someone point me to where in the source code this gets updated?
- If `container_*_allocation` metrics do not take into account actual usage, is there any plan to getting `opencost` compliant with the specification for measuring the workloads cost?

If nothing else, I think it would be beneficial if we can review some of the existing documentation and make sure there's alignment on what the exported metrics measure.

**Comment by Pokom** [comment]
Something worthwhile to share: Without `opencost`, we're able to gather data on requests for workloads from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md#pod-metrics) using the `kube_pod_container_resource_requests` metric. There's labels for memory and cpu, but not gpu.

**Comment by AjayTripathy** [comment]
Hey @Pokom your understanding about the allocation being max of requests and usage is correct. Are you seeing something where that's not the case? Happy to add clarity to documentation.

**Comment by Pokom** [comment]
@AjayTripathy Thanks for confirming my assumptions! Nothing with the data seems off, I was just looking for clarification. I was starting to second guess myself when reviewing a recording rule and couldn't track down exactly what `container_*_allocation` was measuring. 

Aligning the documentation would be excellent. Let me know if you'd prefer to keep this issue open to track the work, or if you want to create a new issue.

**Comment by AjayTripathy** [comment]
I think it's great to keep the issue open. @mattray can you look at adding clarity to the docs here when you return?

**Comment by djmcgreal-cc** [comment]
I can't seem to get these metrics to appear for containers that are scheduled (i.e. GPU node spun up, allocated), but unable to start, due to e.g. ImagePullBackoff. My understanding of the spec is such that these containers should be considered `allocated` and therefore chargeable.

Is it a bug that OpenCost is only recording metrics for these containers once they're Running or something?

**Comment by dwbrown2** [comment]
@mattray can you please share an update? Do you need input?

**Comment by mattray** [comment]
This is on my documentation backlog, it's currently a lower priority than some of the API work.

**Comment by lordofire** [comment]
@mattray happy to help here, since I’m recently evaluating opencost and I’m interested in adding more doc here based on what I read in code. Let me know!

**Comment by mattray** [comment]
@lordofire certainly. If you would like to make a PR for it I'm happy to review.
