### ISSUE TITLE
opencost ui fails on startup - kube-dns dependency

### ISSUE THREAD

**Issue by a7i** [opencost/opencost#1587]
**Describe the bug**
opencost UI has a dependency on kube-dns which was replaced as the default in k8s 1.11
for clusters without kube-dns, startup fails

**To Reproduce**
1. Deploy the application to a cluster without kube-dns
2. Observe startup failure leading to crash loop backoff

**Expected behavior**
No hard-coded dependency on dns resolvers (let kubernetes discovery handle it)

**Screenshots**
```
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/12/22 04:46:28 [emerg] 1#1: host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/conf.d/default.nginx.conf:54
nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/conf.d/default.nginx.conf:54
```

**Which version of OpenCost are you using?**
1.99

**Additional context**
Seems like this was added in #1422 ([link](https://github.com/opencost/opencost/pull/1422/files#diff-2901fce5839c064e631533a3b6a4a230a0625c5d740faa2bf1d92da053ef0e1aR54))

**Comment by AjayTripathy** [comment]
Hi @a7i thank you for this feedback! Let's walk that back and allow any resolver. Is the PR here as simple as deleting that line?

**Comment by a7i** [comment]
> Hi @a7i thank you for this feedback! Let's walk that back and allow any resolver. Is the PR here as simple as deleting that line?

Unfortunately that doesn't work. I tried creating a PR but it seems that the release tag and the main branch have drifted, where the change is not on `develop` nor `master`.

This is the change that worked for me.
```
-    resolver kube-dns.kube-system.svc.cluster.local valid=5s;
+    resolver 127.0.0.1 valid=5s;
```

**Comment by stobias123** [comment]
bump - can't even start from docs.

**Comment by AjayTripathy** [comment]
https://github.com/opencost/opencost/pull/1601 should fix this. We'll get this built in our v1.100 general release, or you can build the opencost ui image from the PR there/develop when it is merged.

**Comment by gterrazas** [comment]
bump, can't boot due to this issue. thank you for looking into this :)
