### ISSUE TITLE
Resource allocations are not tracked when scheduled, but only during Pod Running state

### ISSUE THREAD

**Issue by djmcgreal-cc** [opencost/opencost#1590]
**Describe the bug**

My immediate problem is specific to GPUs, but I think this may apply to resources more generally.

OpenCost only considers a resource to be allocated whilst its Pod is in a `Running` state. However, the resources on a node are already allocated to the Pod as soon as its scheduled (no other Pods can use it, at least for GPUs). In our case we're unable to assign costs to namespaces for Pods with containers in an `ImagePullBackoff` state.

**To Reproduce**

1. Run a Pod with a non-existent image
2. See that there are no `container_gpu_allocated` metrics for this Pod
3. Edit the Pod to point to an existent image
4. See that there will now be metrics for the Pod

**Expected behavior**

That allocation metrics are recorded as soon as the Pod is allocated to a node, e.g. that `spec.nodeName != null`

**Screenshots**

**Which version of OpenCost are you using?**

v1.97.0

**Additional context**

EKS 1.21, Nvidia GPUs (g4dn.xlarge)

**Comment by Adam-Stack-PM** [comment]
@djmcgreal-cc,  Thanks for opening this issue and the additional context.  I will get eyes on this tomorrow.

**Comment by AjayTripathy** [comment]
Hey @djmcgreal-cc I think this is an interesting point. I don't think pending pods block the scheduler but scheduled failed pods with imagepullbackoff do, and we don't currently account for them in our cost model. 

@nikovacevic thoughts on modifying our cost-model here to support imagepullbackoff? I think there is some technical complexity in implementing this quickly. We should at least document this for now.

**Comment by dwbrown2** [comment]
Should we diagram all [pod states](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) and add to spec?

**Comment by AjayTripathy** [comment]
That makes sense. Maybe all states and note what charge model is used for them? @bstuder99 can we add this note to documentation and get this knocked out? Basically a table like this:

State                      |  Cost Allocation         | Status
Running                 | max(usage, request) | Implemented
ImagePullBackoff | request                       | TODO, currently no charge

**Comment by brstuder** [comment]
@AjayTripathy Yeah this idea sounds pretty easy to knock out, just need some clarifying details. We'll be implementing this in the OpenCost spec[ here](https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md), right? For the example table you list, do we want to include other pod states in the article Webb linked?

**Comment by nikovacevic** [comment]
Yeah, this one's a bit tricky, as we do use `kube_pod_container_status_running` to determine (start, end) today. If we want to explore listening for pod created, pending, running, and terminated events from the Kubernetes API, that would give us the flexibility to do this of course -- but that's a very heavy lift.

The other obvious option is to find a different metrics to use instead (or more likely in addition) but that would require some serious performance testing, as this is a touchy one. e.g. there's `kube_pod_status_phase` which has a `phase` label we could set to `Pending` for the one kind of allocation (request only) and `Running` for the normal state (`max(request, usage)`) but this is all hypothetical and there are many unknowns.

**Comment by nikovacevic** [comment]
Self-assigned, and will put it on my team's backlog. Happy to put together a more robust proposal at any point.

**Comment by djmcgreal-cc** [comment]
Thanks for giving this your attention.

I've been trialing using `kube_pod_container_resource_requests{job="kube-state-metrics", resource="nvidia_com_gpu", node!=""}` but I think that this will also include Pods that are Completed, etc, by which point they're presumably not blocking scheduling. I imagine I can account for it, and Failed, etc, but it all starts to feel like maybe there's an easier approach.

**Comment by djmcgreal-cc** [comment]
Oh and in other, anecdotal, experience I think it's probably not just ImagePullBackoff. I've seen containers struggle with assigning networking and storage at this stage and could imagine their resources would be considered allocated.

The Pod lifecycle `Pending` seems to cover all of these but some are considered allocated and some aren't.

I notice that `describe node` has a list of _Non-terminated Pods_ somehow, with (some) detail as to resources ,but only CPU, memory, at least in `describe`.

Not sure any of this is any help, sorry!

**Comment by djmcgreal-cc** [comment]
Oh again! Reading https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states sounds like a more direct way of tracking allocation?

**Comment by djmcgreal-cc** [comment]
Seemingly `get pod -o json` has no `status.containerStatus` field if the Pod is Pending but unallocated, when allocated `status.containerStatus[].state.waiting` is present until it's passed through image retrieval, etc, then `status.containerStatus[].status.running`.

**Comment by mattray** [comment]
I'll re-raise this with Kubecost Engineering to see if they want to address it.
