### ISSUE TITLE
AWS Costs not ingested due to column error

### ISSUE THREAD

**Issue by stobias123** [opencost/opencost#1596]
**Describe the bug**
I'm seeing no successful completed queries due to `line_item_resource_id` being a missing column. It seems that the only query completing is describing the schema, and after that queries fail due to this column missing.

**To Reproduce**
Add athena CUR integration. 

Check diagnostics page. 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/590677/210659091-acf6c631-76d6-4675-b4f8-cafedef6a5c7.png">

Associated query results page.
![image](https://user-images.githubusercontent.com/590677/210659304-59a6491d-3766-4d77-b01b-53fece55b2d4.png)

**Expected behavior**
I expect this integration to work as described, whether or not I have reservations in my account.

**Which version of OpenCost are you using?**
This may be the Kubecost release. 1.99

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by AjayTripathy** [comment]
Hm, I don't think that has anything to do with reservations. Resource ID uniquely identifies nodes so is required for doing price matching. Can you update your CUR to support resource ids?

**Comment by stobias123** [comment]
yup that's it! totally missed this step thank you!

**Comment by AjayTripathy** [comment]
@Sean-Holcomb  is there a quick diagnostic we could write here to make this more clear?

**Comment by Sean-Holcomb** [comment]
Yes I will look into adding that into CloudCost
