### ISSUE TITLE
EKS: No spot instances detected

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1600]
**Describe the bug**

`kubecost_node_is_spot` is returning no results for any spot nodes in EKS clusters. `kubecost_node_is_spot` _does_ return the correct *total* number of nodes in an EKS cluster. My hunch is that the code to check if a node is a spot is flaky and is causing the value to always return as false. GKE and AKS clusters are reporting the correct amount of "premptible" nodes.

**Expected behavior**

I would expect `kubecost_node_is_spot` to return the correct number of nodes that are spot. 

**Screenshots**

In source code, the following value is hard coded to check if a machine is a spot node or not: https://github.com/opencost/opencost/blob/7320861234ce317c99fff8f17b0fb7b0987aad4b/pkg/cloud/awsprovider.go#L49

However, looking at two clusters nodes, I see the label with the following value: 
![image](https://user-images.githubusercontent.com/1080566/211408018-544b88a7-626f-4980-9cb5-e5a2915f0c52.png)
![image](https://user-images.githubusercontent.com/1080566/211408043-ec42a551-37a0-4bd0-a677-216bd056757d.png)

From CLI, I can also confirm that the value looks like so: 

```
aws --region us-east-2 --profile workloads-prod eks describe-nodegroup --cluster-name XXXX --nodegroup-name XXXX |egrep capaci
        "capacityType": "SPOT",
```

**Which version of OpenCost are you using?**
Latest

**Comment by AjayTripathy** [comment]
Looks like we haven't implemented the IsSpot() function for AWS and the generic IsSpot() function is passing through: 

https://github.com/opencost/opencost/blob/13f6525c09fd9427d18afea5efb26b3e27c7866d/pkg/cloud/provider.go#L79

All we need to do is implement this to check for that label, I believe. IsSpot() is called in the metrics emission to generate that metric. Happy to look over a PR that implements IsSpot() in awsprovider.go: https://github.com/opencost/opencost/blob/13f6525c09fd9427d18afea5efb26b3e27c7866d/pkg/cloud/awsprovider.go

if you feel so inclined; if not we can get this reviewed during our fix-it week for v1.100

**Comment by Pokom** [comment]
Awesome, thanks Ajay!! If you wanted, I can take this on and issue a PR in
the next few days. Just assign the issue to me so I know.

**Comment by AjayTripathy** [comment]
Go for it! Assigned.

**Comment by Pokom** [comment]
@AjayTripathy when you have a chance, the PR linked to the issue will now mark nodes as being spot or not in EKS. 

One thing I'm struggling with, and may be worth moving to a separate issue, is the calculations for cost comes from default data that is pre populated. Here's the code that prevents getting spot data: https://github.com/opencost/opencost/blob/6c8dad20f42e079a67789e93621dd678089dc96e/pkg/cloud/awsprovider.go#L806-L809



Edit:

Just to clarify, the issue above was when working locally. However I'm looking at logs for our existing deployments and see the following log in all or our opencost instances running on EKS:

```
operation error S3: ListObjects, https response error StatusCode: 403, RequestID: TQAGX4H8PS85JK6Z, HostID: ZHzxyDJik4HaoiV8rQyoJV8ki+YRY7FqjplIwvYIIELd9zwY3YMYWPIPffVosfgwBf+BUSM+xuBGKGY/Yq0CLw==, api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

So to clarify my question: Is there any existing documentation on how to set the AWS Access Key so these requests don't fail? This step prevents further computation for Spot pricing of EKS nodes.

**Comment by AjayTripathy** [comment]
Hey @Pokom there is some documentation about attaching that available for the kubecost community edtion: https://github.com/kubecost/docs/blob/main/aws-spot-instances.md#spot-data-feed-integration

Opencost works very similarly but with env variables instead of helm chart values.

Please bear with us while we migrate over the relevant docs to opencost -- cc @mattray maybe open an issue to document this setup with a focus on Opencost.

**Comment by Pokom** [comment]
Sounds good Ajay, not a problem. I'll take a look tomorrow and potentially
open up a second ticket.
