### ISSUE TITLE
Relocate OpenCost spec doc from its own folder to opencost-website/docs

### ISSUE THREAD

**Issue by brstuder** [opencost/opencost#1607]
**Is your feature request related to a problem? Please describe.**
The OpenCost spec doc exists in it's own folder with a readme which only links to the same spec doc. An important doc like this should have greater visibility (a hyperlink to this page exists in our docs).

**Describe the solution you'd like**
By moving the doc from its own folder into opencost-website/docs, it can both be continuously updated through GitHub while still appearing in the frontend left navigation for easy reference.

**Additional context**
One thing to keep in mind would be potentially breaking any other hyperlinks to this spec doc across our other properties such as tech docs, blogs, etc. GitHub has some flexibility with redirects but I would have to consult someone on this further.

**Comment by mattray** [comment]
@dwbrown2 @AjayTripathy is there a historical reason not to move this to /docs?

**Comment by AjayTripathy** [comment]
I'm supportive!

**Comment by dwbrown2** [comment]
The proposal to move the spec into a website repo? What exact benefits are you picturing? Not necessarily opposed, but just trying to learn more about impact.

**Comment by brstuder** [comment]
The website repo is just where all OpenCost docs live. It would make sense we should add the spec doc there, the only benefit being we can have it appear in our OpenCost docs left navigation and provide greater visibility to it.

**Comment by mattray** [comment]
Should we bring it up in the OpenCost Working Group? I don't know if folks have historically looked for the Spec in the opencost/opencost repository and if we move it they might not know where to look.

**Comment by dwbrown2** [comment]
I tend to agree with Mat. I worry people won't be able to find. Would its
own repo be a better way to expose?

Webb
Kubecost, Co-founder

**Comment by mattray** [comment]
After talking with @bstuder99 I think we should plan on creating an opencost-docs repository to hold the docs from opencost and opencost-website as well as the spec and swagger.json. We'll need to update how docs are rendered on the website, but I think that'll be a better longterm repository and solution. I'll bring it up in the Working Group Meeting.
