### ISSUE TITLE
Rate Card Azure MSI auth fails if multiple identities present

### ISSUE THREAD

**Issue by pl4nty** [opencost/opencost#1610]
**Describe the bug**
The Rate Card API fails to authenticate to Azure with a Managed Service Identity (MSI) if multiple identities are present, with the following error response from Azure:
> Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request

**To Reproduce**
1. Configure multiple managed identities (eg built-in and AKS cluster extensions)
2. Provide azureClientID to OpenCost (or any combination of subscription/tenant IDs)
3. Reload OpenCost
4. Check error logs

**Expected behavior**
Azure MSI authentication succeeds with the provided client ID

**Which version of OpenCost are you using?**
kubecost prod-1.99.0

**Comment by pl4nty** [comment]
Possibly related to https://github.com/opencost/opencost/blob/6cb52d08d24adfefa62bbb4316220ff83cb3019b/pkg/cloud/azureprovider.go#L546-L551

**Comment by thomasvn** [comment]
@pl4nty Thanks for reporting! Could you clarify which configs you are providing? Is it all of the ones listed below?

```yaml
  azureSubscriptionID: <Azure Subscription ID>
  azureClientID: <Azure AD App ID>
  azureTenantID: <Azure AD Tenant ID>
  azureClientPassword: <Azure AD Client Secret>
```

**Comment by pl4nty** [comment]
@thomasvn I tried just client ID, then added tenant ID and subscription ID. Tenant ID and sub ID should be automatically detected by the MSI though

**Comment by thomasvn** [comment]
@pl4nty I agree, based on the code snippet you shared above. One more thing to clarify, you still received an error response even when specifying `azureClientID`, `azureTenantID`, and `azureSubscriptionID`?

**Comment by pl4nty** [comment]
@thomasvn yes, the error message didn't change. I also received the same error when no azure parameters were provided

**Comment by dwbrown2** [comment]
@teevans @thomasvn know if work would be needed for 1.100 here?

cc @Adam-Stack-PM

**Comment by thomasvn** [comment]
@dwbrown2 There should be no issue authenticating with Azure Rate Card Integration if the user provides an `azureClientPassword`!

The feature request here would be to perform authentication with a Managed Service Identity (MSI) as opposed to an `azureClientPassword`. It’s unclear to me whether this feature was ever fully functional? @Sean-Holcomb commented [here](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1899#issuecomment-1405671528) that MSI is not currently supported with Azure Cost Export Integration. Sean, has MSI worked for Azure Rate Card Integration before? We see some references to it in the code (shown above).

**Comment by Sean-Holcomb** [comment]
I don't have any insight on that as I have not tried to configure it that way and I am unsure who the original author is.

**Comment by andriktr** [comment]
I have faced something very similar and was able to fix it by setting up Azure Pod Identity for opencost deployment. 
For this u need to have addon enabled on cluster level, create a separate user assigned managed identity and assign it to cluster VMSS, then give a reader permission on subscription level. After this create AzurePodIdentity and AzurePodIdentityBinding. The last step is to add a label to the deployment template
```yaml
  template:
    metadata:
      labels:
        app: opencost
        aadpodidbinding: {{ .Values.azurePodIdentity.azureIdentityBinding.selector }}
```

**Comment by pl4nty** [comment]
@andriktr Thanks! Do you know whether this works with AAD Workload Identities, which [replaced AAD Pod Identity](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/)? I don't think my cluster implements either of them, but it does have a cluster-level identity as well as two extension identities

**Comment by andriktr** [comment]
@pl4nty I have not tested AAD Workload Identities in terms of OpenCost, but I have plans to do it in upcoming days. Will let u know about result.

**Comment by andriktr** [comment]
@pl4nty Just tested OpenCost with Azure Workload Identity unfortunately it's not working using this approach. 
Most probably [https://github.com/AzureAD/microsoft-authentication-library-for-go](https://github.com/AzureAD/microsoft-authentication-library-for-go) should be integrated into OpenCost.

**Comment by AjayTripathy** [comment]
Thanks for the feedback. I think we should incorporate the above helm chart changes as well as look to integrate the authentication library in an upcoming release. I've tagged this as a proposal for 1.102.

**Comment by t1murl** [comment]
Hi @all, First of all thanks for the great work with OpenCost. I'd love to introduce OpenCost for our AKS clusters. 
I'm also interested in using AAD workload identities with OpenCost 👍 We are currently migrating from AAD pod identity to workload identities.
I can see this currently tagged as a v1.102-proposal with the current release being  v1.105. @AjayTripathy , can you possibly share some information on the status of this? Thanks!

**Comment by Davidsoff** [comment]
I have made a start for workload identities here: #2117 
Will need some help to get it production ready though
