### ISSUE TITLE
Report metric if savings plan retrieval was successful or not

### ISSUE THREAD

**Issue by davidwin93** [opencost/opencost#1614]
**Is your feature request related to a problem? Please describe.**
I would like to know if there's an issue fetching AWS Savings Plan data from my CUR. If a retrieval fails it can skew data making historical analysis more difficult. 

**Describe the solution you'd like**
I would like a metric to be reported indicating if my savings plan information could be retrieved or if an error was encountered 

**Describe alternatives you've considered**
Using a bulky log based alerting system. This won't scale as well as a single metric.

**Comment by thomasvn** [comment]
@davidwin93 Great idea, and thanks for the PR!

@teevans Thoughts? One small comment, but I believe most metric instantiation & emission currently happens in `/pkg/metrics` or [`/pkg/costmodel/metrics.go`](https://github.com/opencost/opencost/blob/develop/pkg/costmodel/metrics.go). Would this PR need to be reworked?

**Comment by teevans** [comment]
@nikovacevic - Want to weigh in on the lift?

**Comment by nikovacevic** [comment]
Well, in this case the lift is zero because @davidwin93 already has a PR open! Many thanks to him! More of a product call w/r/t behavior and metric naming.

cc @AjayTripathy @dwbrown2 Kai

**Comment by davidwin93** [comment]
Thanks for taking a look all. I can move the metric instantiation into `pkg/metrics`. I'll also try and match up the naming a little closer. I was using the buildInfo gauge as a template for this.  I figure it's worth adding additional metrics around Reserved Instances and Spot Pricing as well, so I'll add those in.

**Comment by mattray** [comment]
> Kai

@kwombach12
