### ISSUE TITLE
Potential bug with provider specific default configuration

### ISSUE THREAD

**Issue by keithhand** [opencost/opencost#1617]
**Describe the bug**
When deploying a fresh install, the default configuration file doesn't mirror the values from the [provider-specific configurations](https://github.com/opencost/opencost/tree/develop/configs). Instead, it looks like the values always come from [this default configuration](https://github.com/opencost/opencost/blob/e83493e4e832a256aadd1579f4cb7b06b2c315cd/pkg/cloud/providerconfig.go#L214-L231). The `internetNetworkEgress` value has different values for each provider but appears the same in the final configuration. The `description` also seems to match the default config.

```
❯ kubectl --context aws:cluster/khand-dev-2 exec deploy/kubecost-cost-analyzer -c cost-model -- cat /var/configs/aws.json | jq | head -n 13
{
  "provider": "base",
  "description": "Default prices based on GCP us-central1",
  "CPU": "0.031611",
  "spotCPU": "0.006655",
  "RAM": "0.004237",
  "spotRAM": "0.000892",
  "GPU": "0.95",
  "spotGPU": "0.308",
  "storage": "0.00005479452",
  "zoneNetworkEgress": "0.01",
  "regionNetworkEgress": "0.01",
  "internetNetworkEgress": "0.12",
❯ kubectl --context azure:dev-1 exec deploy/kubecost-cost-analyzer -c cost-model -- cat /var/configs/azure.json | jq | head -n 13
{
  "provider": "base",
  "description": "Default prices based on GCP us-central1",
  "CPU": "0.031611",
  "spotCPU": "0.0066549999999999995",
  "RAM": "0.004237",
  "spotRAM": "0.000892",
  "GPU": "0.95",
  "spotGPU": "0.308",
  "storage": "0.00005479452",
  "zoneNetworkEgress": "0.01",
  "regionNetworkEgress": "0.01",
  "internetNetworkEgress": "0.12",
❯ kubectl --context gke_us-central1-a_standard-cluster-1 exec deploy/kubecost-cost-analyzer -c cost-model -- cat /var/configs/gcp.json | jq | head -n 13
W0118 13:57:29.237885   71779 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
{
  "provider": "base",
  "description": "Default prices based on GCP us-central1",
  "CPU": "0.031611",
  "spotCPU": "0.006655",
  "RAM": "0.004237",
  "spotRAM": "0.000892",
  "GPU": "0.95",
  "spotGPU": "0.308",
  "storage": "0.00005479452",
  "zoneNetworkEgress": "0.01",
  "regionNetworkEgress": "0.01",
  "internetNetworkEgress": "0.12",
```

**To Reproduce**
1. Deploy fresh instance of Opencost (using the Kubecost helm chart for deployment) and check for the `/var/configs/{provider}.json`
    1. Example: `kubectl exec deploy/kubecost-cost-analyzer -c cost-model -- cat /var/configs/gcp.json`
3. See that the description and internetNetworkEgress values don't match for each provider
    1. Generated Files: 0.12
    2. [AWS config](https://github.com/opencost/opencost/blob/develop/configs/aws.json): 0.143
    4. [Azure config](https://github.com/opencost/opencost/blob/develop/configs/azure.json): 0.0725
    5. [GCP config](https://github.com/opencost/opencost/blob/develop/configs/gcp.json): 0.12

**Expected behavior**
Configuration that gets generated for providers should be based on those provider-specific configs.

**Which version of OpenCost are you using?**
Kubecost v1.99

**Comment by thomasvn** [comment]
Seems like it's potentially related to this commit https://github.com/opencost/opencost/commit/e8bd549d569843e0129a584c76eda18ca053d93c, and these lines:

https://github.com/opencost/opencost/blob/2440a76e2df6df692d2127a3633836850d0e3b0b/pkg/cloud/provider.go#L537-L570

@Sean-Holcomb Any ideas why we are always using the `default.json`, even when deployed to specific cloud providers?

**Comment by Sean-Holcomb** [comment]
@thomassvn I have see the issue a little down stream of this, config files are being placed at `/models/XXXX.json` by the docker file, but the `CONFIG_PATH` env variable is being set to `/var/configs/`. So it is looking in the wrong place. I will ask around to see what the best course of action here is.

**Comment by Sean-Holcomb** [comment]
@AjayTripathy this looks like it is related to some complexity around making this value configurable, and having it default to `/models/` in an OpenCost context but `/var/configs/` in KCM. Do you have some insight into why this value is configurable?

**Comment by AjayTripathy** [comment]
No good reason other than I probably didn't think it through 4 years ago. Just go ahead and move it to /var/configs imo
