### ISSUE TITLE
The hardcoded label "eks.amazonaws.com/capacityType" doesn't work with Karpenter

### ISSUE THREAD

**Issue by gillg** [opencost/opencost#1621]
**Describe the bug**
When you use Karpenter to manage nodes instead of EKS node groups the label `eks.amazonaws.com/capacityType=SPOT` is absent and there is a label `karpenter.sh/capacity-type=spot` instead. Same thing for on demand with the type in lowercase.
This var should else be smarter with fallbacks else overridable.

**To Reproduce**
Use Karpenter to scale nodes and start a node.

**Expected behavior**
Opencost should be able to detect spot or on demand nodes created by Karpenter.

**Screenshots**
![image](https://user-images.githubusercontent.com/5639241/213890492-1bf61213-65aa-4229-97e0-79796ccd86ec.png)

**Which version of OpenCost are you using?**
`public.ecr.aws/kubecost/cost-model:prod-1.99.0`

**Comment by thomasvn** [comment]
@gillg Just to clarify my understanding. Because OpenCost classifies a node as being `SPOT` or `ON_DEMAND` based on the node's labels (example below), you would like for OpenCost to be able to detect the node labels created by Karpenter as well?

```bash
# Abridged example of a node's labels
$ kubectl describe node ip-192-168-18-130.us-west-1.compute.internal
Name:               ip-192-168-18-130.us-west-1.compute.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t3.medium
                    beta.kubernetes.io/os=linux
                    eks.amazonaws.com/capacityType=ON_DEMAND
                    topology.ebs.csi.aws.com/zone=us-west-1a
                    topology.kubernetes.io/region=us-west-1
                    topology.kubernetes.io/zone=us-west-1a
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.18.130
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by gillg** [comment]
Exactly :)
Most of them are "well known" and related to kubernetes itself, but ebs and eks labels are specific and related to the way you launch a node in EKS. The capacityType as an example is related to "node groups".
Karpenter uses the officials EKS amis but doesn't rely on a "node group" in background.
I also guess, if you use "EKS anywhere" you will have other labels. But I never tested.

I let you choose if it makes more sense to hardcode labels and fallbacks or if some configuration could override them.

**Comment by teevans** [comment]
@nikovacevic - Can we throw this on your investigate list with a hope that it gets put into bug fix week next week?

**Comment by dwbrown2** [comment]
Would love to get this resolved for 1.100 as more teams are using Karpenter & Opencost together!

@Adam-Stack-PM can you help track?

**Comment by nikovacevic** [comment]
Looks quick

**Comment by nikovacevic** [comment]
For EKS, at least, seems like we just need to make a change here: https://github.com/opencost/opencost/blob/develop/pkg/cloud/awsprovider.go#L670
