### ISSUE TITLE
OpenCost community calendar is hard to find

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1636]
Have had a couple people state that the OpenCost community calendar is hard to find. There's not obvious reference in the README or opencost.io. I propose we make it more visible!

**Comment by mattray** [comment]
The [OpenCost README](https://github.com/opencost/opencost#community) and the [OpenCost website](https://www.opencost.io/docs/#stay-in-the-loop) both list the calendar URL (https://bit.ly/opencost-calendar).

**Comment by mattray** [comment]
The community fortnightly meeting needs to be listed in the format outlined here:
https://clomonitor.io/docs/topics/checks/#community-meeting
