### ISSUE TITLE
Finding Swagger docs is hard

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1654]
Opencost recently created a set of Swagger docs I believe. I'm unable to find them as a user. Can we make this more accessible?

**Comment by AjayTripathy** [comment]
@mattray any thoughts?

**Comment by mattray** [comment]
The swagger.json is currently here: https://github.com/opencost/opencost/blob/develop/docs/swagger.json

The plan is to render them into the website, similar to what Kubernetes does with theirs: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
