### ISSUE TITLE
some bugs caused by logic and grammar

### ISSUE THREAD

**Issue by wujunwei** [opencost/opencost#1664]
**Is your feature request related to a problem? Please describe.**
I am very interested in this project, when I look into this project , I found some bugs caused by logic or grammar .show as belows:

---
https://github.com/opencost/opencost/blob/eabe8bbfe4cad99a08b2523a117955b3df69418a/pkg/kubecost/window.go#L587-L590
> receiver `w` is not a pointer ,any operetion on it make no effect.

---
https://github.com/opencost/opencost/blob/232f9f6abbc4771ac617f6ce898112b99b0630fe/pkg/clustercache/clusterexporter.go#L29-L33
json tag **omitEmpty** can not be recognize by json option, **omitempty** can

---
https://github.com/opencost/opencost/blob/c7706a4fb2920869500f46ead1a7c5304080187f/pkg/costmodel/sql.go#L97-L101
when error occured, `db` could be null, call `db.Close() `  will lead to panic! `defer db.Close() ` shound move under err nil judge.

---
and so on ...

**Describe the solution you'd like**
All bugs methioned above can be foreseen and avoid by  adding some frequently-used linters in`.golangci.yml` and run it before merge PR in CI.

**Additional context**
None

**Comment by thomasvn** [comment]
@wujunwei Thanks for pointing this out!

@mattray @teevans Thoughts on enabling `.golangci.yml` linter in Github Actions?

**Comment by mattray** [comment]
@thomasvn @teevans I think that's a great idea, the more pedantic the better

**Comment by AjayTripathy** [comment]
PR is merged, we can leave this open until some linting is introduced.
