### ISSUE TITLE
v1.100 breaks OpenCost UI

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1669]
As first reported in https://github.com/opencost/opencost/issues/1643 the OpenCost UI does not connect to the API backend. 

The log messages don't reveal much, but by looking at the changes made from 1.99 to 1.100 this PR stands out:
https://github.com/opencost/opencost/pull/1574

Reverting those changes restores the connection and the UI works again. I'll submit a PR for the work-around and hopefully a v1.100.1 for OpenCost can be released while a proper fix is implemented.

**Comment by dwbrown2** [comment]
@AjayTripathy @teevans this looks critical

**Comment by teevans** [comment]
@mattray - Do you have a PR here?

**Comment by teevans** [comment]
Just kidding @nealormsbee  and @nikovacevic already have a fix for this. Push coming soon.

**Comment by nikovacevic** [comment]
Here's the fix https://github.com/opencost/opencost/pull/1674 and cherry-pick https://github.com/opencost/opencost/pull/1675

h/t @nealormsbee -- we fixed it together
