### ISSUE TITLE
OpenCost UI should use a favicon

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1672]
The OpenCost UI doesn't have a favicon, there's already one available on the OpenCost website.
https://github.com/opencost/opencost-website/blob/main/static/img/favicon.ico

**Comment by saif-xgrid** [comment]
Hi @mattray , is this issue still open, I want to work on this issue if its open ?

**Comment by mattray** [comment]
@saif-xgrid It was fixed already, I'm closing the issue. Thanks for looking to help, feel free to contact me directly and I can recommend some low-hanging fruit if you're looking to get involved. (mattray@kubecost.com)
