### ISSUE TITLE
Make BASE_URL in the opencost UI dynamic

### ISSUE THREAD

**Issue by logyball** [opencost/opencost#1677]
**Is your feature request related to a problem? Please describe.**

When deploying the opencost UI, it works great when the host of the UI and the API are both `localhost`.  Communication between the UI -> `localhost:9003` works well.  However, when deployed behind something like an ingress controller, path resolution can be a problem.  For example, when deploying behind an `nginx` ingress, path mapping may look like this:

```
                 -> /path1 -> service 1
traffic -> nginx -> /path2 -> service 2
                 -> /path3 -> service 3
```

So a full path to `service1` might look like this: `http://www.domain.com/path1`.

In our case, deploying the UI and `opencost` API might have the following map:

```
                 -> /opencost (port 9003) -> opencost api
traffic -> nginx -> /opencost (port 9090) -> opencost UI
```

However, once within the UI, the URL that is always used is either `localhost:9003/model` or the env var BASE_URL.  [This appears to be defined here.](https://github.com/opencost/opencost/blob/develop/ui/src/services/allocation.js#L4)

The docker image that is built for the UI hardcodes this URL to `/model` [here](https://github.com/opencost/opencost/blob/develop/ui/Dockerfile#L6).  When running behind `nginx` ingress, this means that all API calls are sent to `http://www.domain.com/model` rather than `http://www.domain.com/opencost/model`, which prevents API calls from functioning.

**Describe the solution you'd like**

It would be great if we could set the `BASE_URL` environment variable at boot time.  This can be handled via adding a special value as the BASE_URL in react code, then running a shell script as a docker `ENTRYPOINT` that uses `sed` to replace the value of `BASE_URL` with either an environment var or a default value.

**Describe alternatives you've considered**

We considered forking the repo and building our own docker container with a hardcoded val, or restructuring our `nginx` ingress controller.  It may also be simpler to package the UI into the same container as the API.

**Comment by thomasvn** [comment]
@logyball The `BASE_URL` is an [environment variable set in the Dockerfile](https://github.com/opencost/opencost/blob/v1.100/ui/Dockerfile#L6). I believe this can be overwritten by passing `-e BASE_URL='/opencost/model'` when running `docker run`. I also believe it can be passed [here in the helm chart](https://github.com/opencost/opencost-helm-chart/blob/5d1078be55e37f71e6ae90219132c3fb0c4ba051/templates/deployment.yaml#L65-L69).

Let me know if I'm misunderstanding!

**Comment by Pokom** [comment]
@thomasvn we're not deploying via the helm chart so that's not an option for us. I believe the `BASE_URL` is set at *compile* time in the builder image and the generated assets have the `BASE_URL` baked into the runtime image, so it's not possible to override at run time.

**Comment by logyball** [comment]
hey @thomasvn - another reason why users of the helm chart (and those who don't) won't be able to simply set the environment variable to change the behavior is what @Pokom alluded to. `BASE_URL` is set during compile time and the generated assets have the value that is baked into the docker image.  When the asset is served to the user's browser, it cannot dynamically read the value of the environment variable in the container.

If we wanted to leverage the actual environment variable in the Dockerfile, we would have to do that by building and maintaining our own version of the docker image.  I argue instead that we could do something like this:

```Docker
FROM node:18.3.0 as builder
ADD package*.json /opt/ui/
WORKDIR /opt/ui
RUN npm install
ADD src /opt/ui/src
ENV BASE_URL=/model
RUN npx parcel build src/index.html

FROM nginx:alpine
COPY --from=builder /opt/ui/dist /var/www
COPY default.nginx.conf /etc/nginx/conf.d/
COPY nginx.conf /etc/nginx/

ENTRYPOINT ['/bin/entry.sh`]
```

Where our `entry.sh` script does something like:

```shell
#!/bin/sh

sed -i '' "s/PLACHOLDER/$BASE_URL/g" /var/www/*.js
```

Or whatever.  This will allow the built asset to be search/replaced at boot time, which lets the developer who deploys the UI supply an environment variable that can be a prefix for the base url while still using the image that is built and maintained by opencost.

**Comment by logyball** [comment]
I have a functional example here:

https://github.com/opencost/opencost/pull/1700

If this is something that the maintainers are interested in, I can fully document the PR and raise it officially.

**Comment by thomasvn** [comment]
@Pokom @logyball  Ah thanks for clarifying, that makes sense. Took a look at the PR, and that also helped to clarify my questions. Let’s move ahead with the PR!
