### ISSUE TITLE
Is it possible to change opencost endpoint which  opencost-ui use to connect ?

### ISSUE THREAD

**Issue by Devops-Techstack** [opencost/opencost#1679]
Query:

Hi Team,
By default opencost-ui connect opencost with this endpoint http://opencost.opencost.svc.cluster.local:9003. Is this endpoint configurable because for my case cluster name is different ?
I thought we can configure it here https://github.com/opencost/opencost/blob/e120baa88c2b1283b8271a15d9a0907f938d99dc/ui/default.nginx.conf#L62 but didn't worked .

**Which version of OpenCost are you using?**
Using the Image : prod-1.99.0

**Comment by thomasvn** [comment]
@Kritika-git The `$server` var in nginx.conf should be configurable. Could you validate whether the [`resolver`](https://github.com/opencost/opencost/blob/v1.99/ui/default.nginx.conf#L54) var is able to resolve the DNS name of your configured server?

Note that when upgrading to [v1.100](https://github.com/opencost/opencost/blob/v1.100/ui/default.nginx.conf), there are changes to the `location`, `server`, and `resolver` in nginx.conf.

**Comment by Devops-Techstack** [comment]
@thomasvn , I had to change resolver var to 127.0.0.1 valid=5s; for core dns.
Also since with latest image UI was not loading i had to use prod-1.99.0 tag , I tried to change the $server var in nginx.conf  over here :
location /allocation {
          proxy_connect_timeout       180;
          proxy_send_timeout          180;
          proxy_read_timeout          180;
          set $server http://opencost.opencost.svc.cluster.local:9003;
 Please do confirm if this change is correct ?

**Comment by Devops-Techstack** [comment]
@thomasvn , Also curl request  from opencost-ui works fine for me with the same DNS which i am changing in nginx.conf
curl http://opencost.opencost.svc.cluster.local:9003/allocation/compute?window=today&aggregate=namespace&step=1d&accumulate=false

**Comment by Devops-Techstack** [comment]
@thomasvn The issue is now resolved .Thank you.
It was related to resolver only.

**Comment by thomasvn** [comment]
@Kritika-git Great to hear! So you set it to the following? `set $server http://opencost.opencost.svc.cluster.local:9003;`

**Comment by Devops-Techstack** [comment]
@thomasvn yes right , set $server http://opencost.opencost.svc.my-cluster-name.local:9003;
Also had to change in resolver with my kube-dns service name.Thank you!!
