### ISSUE TITLE
nginx upstream server config in 1.00.1 won't work on any cluster with more than one node

### ISSUE THREAD

**Issue by calebcall** [opencost/opencost#1680]
**Describe the bug**
In the nginx.default.conf config, the upstream server is set to [0.0.0.0:9003](https://github.com/opencost/opencost/blob/e8e18879f3033674204f5666c5898a57f6bc565a/ui/default.nginx.conf#L38) and this will only work when deployed to a single node cluster (i.e. like Minikube). 

**To Reproduce**
1. deploy version 1.00.1 on cluster with more than one node
2. confirm opencost backend and opencost-ui live on different nodes `kubectl get pods -n opencost -o wide`
3. browse to UI and will get a 502

**Expected behavior**
To have a sane default value (i.e. opencost.opencost.svc.cluster.local:9003, if following the provided install documentation, this is where the backend service should live) and allow value to be configurable as there is no guarantee for the service to be deployed to an opencost namespace or even use the opencost name for the backend deployment.

**Screenshots**
N/A

**Which version of OpenCost are you using?**
1.00.1

**Additional context**
N/A

**Comment by jessegoodier** [comment]
I think they are typically deployed as a single pod. Like this: https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml

Or you could create a configMap for the nginx.conf which could be customized to your service.namespace accordingly.

Would that work for you?

**Comment by calebcall** [comment]
Yes, I've already deployed the nginx config as a configmap as a work around.

**Comment by AjayTripathy** [comment]
@calebcall feel free to make a contribution back to the project if you have this working for you!

**Comment by mattray** [comment]
To clarify, this happens when the opencost and opencost-ui containers within the pod are deployed to different nodes? I haven't observed this on my 3 multi-node node clusters (2, 3 and 4 nodes), they always get deployed on the same node together.
