### ISSUE TITLE
Pricing Sources: Missing columns in Athena CUR should not cause a kubecost diagnostic error

### ISSUE THREAD

**Issue by matt-land** [opencost/opencost#1683]
**Describe the bug**
The lack of the columns 'reservation_reservation_a_r_n' or 'reservation_effective_cost' in an AWS cost usage report causes the diagnostics check for "Savings Plans" (AWS) to fail, but this is a valid condition.

AWS docs state that the Cost Reporting schema is semi-dynamic based on what the user does in the account, so if the AWS account doesn't have any reservations, the columns may not be present in the report.

> All other columns are included only if your monthly AWS usage generates data to populate those columns. For example, your report includes savingsPlan/ columns only if you used Savings Plans during that month.
https://docs.aws.amazon.com/cur/latest/userguide/troubleshooting.html

It seems reservations are being deprecated for savings plans, as per the messages in EC2 reservation's page of the AWS console:

> We recommend Savings Plans over Reserved Instances. Savings Plans are the easiest and most flexible way to save money on your AWS compute costs and offer lower prices (up to 72% off) just like Reserved Instances. To learn more and get started with Savings Plans click [here](https://aws.amazon.com/savingsplans/)

**To Reproduce**
Open a new AWS account or an account with no reservation history
Launch a cluster and install kubecost
Set up an was bucket for the CUR to be delivered, per the kubecost docs
Set up the CUR
Apply the cloudformation template delivered in the bucket to create the Athena database/tables, etc
Configure Cubecost for the Athena delivery of the AWS CUR.

**Expected behavior**
- The kubecost diagnostics page does not show a warning and error if the reservation data columns are not present in the report

**Screenshots**
<img width="672" alt="Screen Shot 2023-02-10 at 3 27 15 PM" src="https://user-images.githubusercontent.com/4174972/218200840-0328fc0e-4b3d-4a5c-b4b0-4b2964412aca.png">

**Which version of OpenCost are you using?**
version 1.100.0

**Additional context**
Any AWS account that has ever purchased a reservation will likely have the 'missing' columns present in the CUR.

Potentially I can "buy" a single reservation in each account to make the column appear, then delete the cloudformation stack and re-apply after the column is added (to fix Athena), but at the scale of many AWS accounts this isn't a workable solution.

Code:
https://github.com/opencost/opencost/blob/6847bc082ba28cc94c6b3ab7cffec205250abcfd/pkg/cloud/awsprovider.go#L1990

**Comment by thomasvn** [comment]
@matt-land Thanks for reporting!

@AjayTripathy @Sean-Holcomb thoughts on how the error logging/handling from [`GetReservationDataFromAthena()`](https://github.com/opencost/opencost/blob/v1.100/pkg/cloud/awsprovider.go#L1974) can be improved here? Note, similar issue reported [here](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1901).

**Comment by kwombach12** [comment]
I propose that we update the UI so that we show a warning (maybe a yellow triangle) instead of an error when no reservation data is available from Athena.

cc @Adam-Stack-PM should be a quick fix for 1.101

**Comment by matt-land** [comment]
Is there some way to convey that Athena is still working for retrieval of data, even if there are no reservations? In our case, we do savings plans. There is no way to confirm if that is working or not, even after the proposed change.

**Comment by kwombach12** [comment]
@matt-land I see your point. As a quick fix, what if we put a green check next to the top line "Savings Plan, Reserved Instance, and Out-Of-Cluster" to indicate that savings plans are still working as expected, and then have a warning next to 'no reservation data available in Athena' to show there is no reservation data returned?

**Comment by matt-land** [comment]
Sounds good to me.

**Comment by nealormsbee** [comment]
@nikovacevic @teevans is it possible to fix this API-side? Dug into the underlying calls and we can fix this client-side, but it would be cleaner to do it server-side.

**Comment by nikovacevic** [comment]
@Adam-Stack-PM @teevans fair to say this is P2? P1?

**Comment by AjayTripathy** [comment]
P1 sounds right, should be pretty quick though.

**Comment by matt-land** [comment]
This issue also manifests as an error in the logs at startup:
```
2023-03-06T18:36:17.019561802Z ERR Failed to lookup reserved instance data: no reservation data available in Athena
```

**Comment by Adam-Stack-PM** [comment]
@nikovacevic, When you have time could you post an update on the status of this issue? Will it make v1.101?

**Comment by nikovacevic** [comment]
Unlikely to make v1.101, especially if not P0. I'll add it to Jira for v1.102.

**Comment by Adam-Stack-PM** [comment]
Tracking for v1.102. However being a short release  it is not garenteed to make it.

**Comment by dwbrown2** [comment]
This feels like an issue we want to fix sooner rather than latter... is this not really easy, i.e. just make it a warning vs error in frontend?

**Comment by Adam-Stack-PM** [comment]
Based on the linked PR closing issue. @nealormsbee and @dwbrown2, please re open if needed.
