### ISSUE TITLE
Generic extended resource support

### ISSUE THREAD

**Issue by boniek83** [opencost/opencost#1701]
**Is your feature request related to a problem? Please describe.**
Currently only nvidia gpus are supported as far as extended resources are considered. Landscape of devices that have their own kubernetes device plugins is expanding constantly.

**Describe the solution you'd like**
 It would be great to have an architecture that supports not only all current but all future devices as well.

**Additional context**
See link below for sample of what kind of devices kubernetes supports currently:
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#examples

**Comment by mattray** [comment]
We're starting a conversation around external asset costs in the OpenCost Working Group, where we'll map things not directly managed by Kubernetes into the cluster for tracking (ie. S3, RDS, monitoring). Do you think this fits in that use case?

https://docs.google.com/document/d/1ZCMdRfP0DUCU5Ygk6Epy3tLJhscv46HvnU3Uez4HtQQ/edit#heading=h.vqg5bou11415

**Comment by boniek83** [comment]
While this is really great stuff I'm not sure this solves the same problem. What I'm talking about are internal cluster devices like gpus, fpgas etc that are exposed using device plugins and can be assigned to pods just like cpu or memory. So far you practically hardcode support for nvidia as the only gpu (or device in general) in existence, but as a link provided in OP states there are much more devices available.

**Comment by AjayTripathy** [comment]
Agree we can do more here and we can add to roadmap. Would welcome any PRs to add the devices! @Adam-Stack-PM maybe we can add to the backlog?
