### ISSUE TITLE
OpenCost Prometheus Metric Exporter Only Deployment Inaccurate Azure pricing 

### ISSUE THREAD

**Issue by Mouszie** [opencost/opencost#1708]
**Describe the bug**
Opencost metric exporter only deployment has inaccurate price information. When looking at the logs we see this error. 
[90m2023-02-22T21:42:20.519638623Z←[0m ←[31mWRN←[0m no pricing data found for eastus,Standard_DS2_v2,ondemand
Additional logs can be provided

**To Reproduce**
Used the provided  opencost github link from this doc https://www.opencost.io/docs/opencost-exporter 

**Which version of OpenCost are you using?**
Latest/prod-1.100.2

**Additional context**
AKS v1.24.9

**Comment by AjayTripathy** [comment]
Hey Mouszie, looks like your ratecard API hasn't been attached based on that log. 

Here's some details on how to do this via kubecost: https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config

@mattray can you note that we'll need to turn this into documentation on how to do this on opencost?

**Comment by mattray** [comment]
I've updated the issue and marked it as a "good first issue" since I assume someone with Azure access can probably just walk through the Kubecost doc, follow those steps, and get OpenCost working.
