### ISSUE TITLE
Dynamically get the pricing of resources from different cloud providers

### ISSUE THREAD

**Issue by karthiravich** [opencost/opencost#1711]
Hello, we are running our workloads on Openshift with on-prem servers. We are able to deploy opencost and get the results. We would like to know the approx cost if the same workload is run on an aws or Azure or any other cloud environment , without actually deploying them. 

Is that feature possible or available  with current opencost setup? Kindly assist.

**Comment by Pokom** [comment]
Hi @karthiravich that's a really interesting idea! Off hand I don't believe there's a way of doing this, as OpenCost is assuming that you're running in a cluster of the provider. I would be curious to see what kind of lift it would take to make OpenCost a bit more neutral in this, but I have a hunch it's not a simple lift.

**Comment by karthiravich** [comment]
Hi @Pokom - Thanks for the update! I agree it may not be a easy one. Maybe you could think of considering the common parameters across environments like CPU cost/hr, RAM cost/hr, GPU cost/hr etc, calculate the cost based on standard machine sizing .and maybe allow user to switch the provider using a flag (like _--provider_)for _kubectl-cost_ client command for a rough cost visualization across kubernetes environments - onprem or cloud.

I could be wrong here but just sharing my thoughts.

**Comment by AjayTripathy** [comment]
If you had a barebones GCP,AWS,and Azure cluster setup, you could quickly run kubectl predict across all of them: https://blog.kubecost.com/blog/resource-cost-prediction/. Maybe in the future we could run a small service on behalf of users that allows them to call kubectl predict against some reference clusters we run?
