### ISSUE TITLE
Aggragate by label doens't work 

### ISSUE THREAD

**Issue by delamainer** [opencost/opencost#1727]
**Describe the bug**
Aggregation by label doesn't work.  My request looks like this: `.../allocation/compute?window=1d&aggregate=namespace,label:app&step=1d&accumulate=false` and the response I got is (the same for the rest of namespaces):

```
{
  "code": 200,
  "status": "success",
  "data": [
    {
      "kube-system/__unallocated__": {
        ...
      }
    }
  ]
}
```

**To Reproduce**
Execute: `curl --location 'https://.../allocation/compute?window=1d&aggregate=namespace%2Clabel%3Aapp&step=1d&accumulate=false'`

**Expected behavior**
Request must return correct data, aggregated by namespace and `app` label.

**Which version of OpenCost are you using?**
- `quay.io/kubecost1/opencost-ui:prod-1.99.0`
- `quay.io/kubecost1/kubecost-cost-model:prod-1.99.0`

**Additional context**
AWS EKS, k8s 1.22

**Comment by AjayTripathy** [comment]
The most common reason for this is that the opencost pod isn't being scraped, or KSM is not emitting all pod labels. Can you check to make sure opencost is being scraped into the target prometheus?

**Comment by delamainer** [comment]
I added following annotations to opencost pod:
```
prometheus.io/path: /metrics
prometheus.io/port: 9003
prometheus.io/scrape: true
```
It still doesn't seem to work.

**Comment by delamainer** [comment]
I was able to fix the issue. Thank you.

**Comment by pranav-shankar-swi** [comment]
Hi @ThePos1tive, Can you please share how you fixed it

**Comment by delamainer** [comment]
> Hi @ThePos1tive, Can you please share how you fixed it

I added labels above.

**Comment by AjayTripathy** [comment]
@pranav-shankar-swi have you been able to make this work?
