### ISSUE TITLE
Proportional Use Data

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#1731]
**Is your feature request related to a problem? Please describe.**
1. Retrieve proportional use data per node with an API call.
2. Potentially aggregate this proportional use data per node, so a rollup of namespace with multiple nodes would have each cluster/node that pod ran on, plus its fractional usage on that node.

**Describe the solution you'd like**
We should return the proportion of node resources a pod is using, in addition to costs. This makes custom splits of cost data calculable easily.

**Describe alternatives you've considered**
Manually compute proportional use by querying the full cluster costs API in a second API call. This is somewhat difficult due to scale and because data becomes cost weighted instead of resource weighted, prevents some aggregations.

**Comment by AjayTripathy** [comment]
Here's an example API.

```
GET /model/allocation?window=7d...&includeProportionalAssetCost=node

{
	"cluster/node/namespace/pod/container": {
		...all existing fields,
		"proportionalCost": {
			"node1": {
				"cpuCost": 2.07,
				"cpuPercentage": 0.004321,
				"ramCost": 0.22,
				"ramPercentage": 0.083745
                         },
	                "node2": {
				"cpuCost": 2.07,
				"cpuPercentage": 0.004321,
				"ramCost": 0.22,
				"ramPercentage": 0.083745
                        },
	           ...
                  }
            }
}
```

**Comment by wamak9** [comment]
bump, need UI.

**Comment by AjayTripathy** [comment]
@wamak9 we'll look into adding this into the UI-- I was just wondering if a visual display of the data we're showing here is more or less what you're looking for here.

**Comment by wamak9** [comment]
bump
