### ISSUE TITLE
Opencost is generating useless metrics with high cardinality 

### ISSUE THREAD

**Issue by dudicoco** [opencost/opencost#1736]
Opencost exposes a few `*_allocation` [metrics](https://www.opencost.io/docs/prometheus#available-metrics), these metrics seem to provide an identical data to that of KSM's `kube_pod_container_resource_requests` metric, except with less labels.

A couple of examples:

CPU
![Screen Shot 2023-03-08 at 10 48 47](https://user-images.githubusercontent.com/51051860/223666347-5ab5afda-48c5-4df4-98b8-0bf06fd06511.png)
![Screen Shot 2023-03-08 at 10 49 02](https://user-images.githubusercontent.com/51051860/223666414-5caab5e3-5699-4bd0-a245-9df4636ec2e0.png)

Memory
![Screen Shot 2023-03-08 at 10 49 40](https://user-images.githubusercontent.com/51051860/223666580-02554da7-cf9e-4eaa-90d7-c1967b365404.png)
![Screen Shot 2023-03-08 at 10 49 27](https://user-images.githubusercontent.com/51051860/223666536-a70cd195-0ca9-4154-868c-a7d1cf1b24aa.png)

Why are these metrics needed?

**Comment by AjayTripathy** [comment]
Maybe our docs need clarification. https://www.opencost.io/docs/prometheus says 

`Average number of CPUs requested/used over last 1m`

Whereas it should say something like 
`Max of the (CPU Request,CPU Usage) over the last 1m`

Same for container_memory_allocation_bytes.

@mattray can you pick up this as a documentation task?

**Comment by dudicoco** [comment]
Thanks @AjayTripathy.

Why are new dedicated metrics needed here? Can't we just use a `max()` query instead? Creating new metrics adds unnecessary cardinality in prometheus.

In addition, I believe that using only request is a more accurate representation of the cost, any extra usage above the request is not guaranteed and the k8s scheduler only takes request into consideration with scheduling pods.

**Comment by AjayTripathy** [comment]
Thanks for that feedback. The decision was made to use a single metric that could be multiplied by price to get total costs for ease of use.  
You can price out on simply requests by instead taking the request amounts and multiplying by node_cpu_hourly cost etc.

**Comment by dudicoco** [comment]
@AjayTripathy would the kubecost API work properly if I [disable these metrics](https://github.com/kubecost/cost-analyzer-helm-chart/blob/f9a8f3326a540e1b0ece714c52f100fa085bf0b8/cost-analyzer/values.yaml#L928-L929)?

Also does opencost support disabling metrics as well?

**Comment by AjayTripathy** [comment]
No, we rely on these metrics in kubecost/opencost to compute allocation cost.

And no, opencost does not, though of course you can whitelist what you want on the prometheus side.

**Comment by dudicoco** [comment]
Thanks @AjayTripathy.

What are your thoughts about changing the code to make opencost/kubecost rely on `kube_pod_container_resource_requests` instead? Thus removing some duplicate metrics.

**Comment by AjayTripathy** [comment]
Hey @dudicoco , that's a pretty sizable refactor and not currently on the roadmap, but thanks for the feedback.

**Comment by dudicoco** [comment]
@AjayTripathy where can we see the roadmap for OpenCost?

**Comment by mattray** [comment]
@dudicoco https://github.com/opencost/opencost/blob/develop/ROADMAP.md is quite stale. I'll work on getting something refreshed more frequently.
