### ISSUE TITLE
Prometheus exporter docs are misleading

### ISSUE THREAD

**Issue by dudicoco** [opencost/opencost#1737]
https://www.opencost.io/docs/opencost-exporter instructs on how to deploy opencost as a prometheus exporter, however, looking at the installation yaml file shows that the only difference between this and the normal installation is the lack of the UI container.

So this installation still provides all of the normal opencost features (api).
This was confusing to me and could be for other users as well.

I believe this documentation should be merged into the other sections:
1. Installation with/without UI in https://www.opencost.io/docs/install
2. Rest of prometheus specific information in https://www.opencost.io/docs/prometheus

**Comment by AjayTripathy** [comment]
Thanks @dudicoco . @mattray something for you to document?

**Comment by mattray** [comment]
@dudicoco I think this was carried over from the Kubecost docs, so there were a few more things besides the UI to disable. I'll leave it as a doc issue, installation and Prometheus both need a cleanup

**Comment by dudicoco** [comment]
@mattray can you please elaborate on that? I don't see anything similar in the kubecost docs.

**Comment by mattray** [comment]
@dudicoco the exporter-only was originally documented to trim down Kubecost, but you're right. It's just the API and server, no UI, so we should roll the documentation into the Installation instructions.

**Comment by AjayTripathy** [comment]
It's the API, server, and metrics emissions loop to be clear.

**Comment by jbg** [comment]
Is there any way to just emit cost metrics based on what is found in the cluster, or is configuring a Prometheus client always necessary?

**Comment by mattray** [comment]
https://www.opencost.io/docs/prometheus has been updated
