### ISSUE TITLE
Support single persistentvolumeclaim associated with two storageclasses

### ISSUE THREAD

**Issue by jacklozano** [opencost/opencost#1741]
**Describe the bug**
Our opencost deployment is giving the following error:
```
CostDataRange: Request Error: Prometheus communication error: 422 (Unprocessable Entity) Headers: { Content-Type: [ applica
tion/json ], Date: [ Wed, 08 Mar 2023 17:54:44 GMT ] }, 

Body: {"status":"error","errorType":"execution","error":"found duplicate series for the match group {n
amespace=\"opencost\", persistentvolumeclaim=\"data-wordpress-mariadb-0\"} on the left hand-side of the operation: [{namespace=\"opencost\", persistentvolumec
laim=\"data-wordpress-mariadb-0\", storageclass=\"cinder-release\", volumename=\"pvc-64b52910-334e-4919-974d-93300b9c0f6b\"}, {namespace=\"opencost\", persist
entvolumeclaim=\"data-wordpress-mariadb-0\", storageclass=\"block\", volumename=\"pvc-fa2429b6-25b1-446f-bee6-f6073711bb12\"}];many-to-many matching not allow
ed: matching labels must be unique on one side"} 

Query: 
avg(avg(kube_persistentvolumeclaim_info{volumename != ""}) by (persistentvolumeclaim, storageclass, na
mespace, volumename, cluster_id, kubernetes_node)
    *
    on (persistentvolumeclaim, namespace, cluster_id, kubernetes_node) group_right(storageclass, volumename)
    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{}) by (persistentvolumeclaim, namespace, cluster_id, kubernetes_node, kubernetes_name)) by
(persistentvolumeclaim, storageclass, namespace, cluster_id, volumename, kubernetes_node)

```
**Screenshots**
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/45109701/223855538-1069caa2-da08-46a7-a229-824c4f31bf83.png">

**Which version of OpenCost are you using?**
v1.100.0 (latest at the time)

**Comment by AjayTripathy** [comment]
@thomasvn any ideas on this one?

**Comment by thomasvn** [comment]
@jacklozano Taking a look now! Is this a recurring error in the log? Or is it only happening upon start up.

**Comment by jacklozano** [comment]
This reoccurs very 5 mins or so

Send using Outlook for iOS
________________________________
From: Thomas Nguyen ***@***.***>
Sent: Thursday, March 9, 2023 5:14:56 PM
To: opencost/opencost ***@***.***>
Cc: Lozano, Jack ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [opencost/opencost] CostDataRange: Request Error: Prometheus communication error: 422 (Unprocessable Entity) - many-to-many matching not allowed: matching labels must be unique on one side (Issue #1741)

@jacklozano Taking a look now! Is this a recurring error in the log? Or is it only happening upon start up. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 


@jacklozano<https://urldefense.com/v3/__https://github.com/jacklozano__;!!NiYMbFKv!Pl6iLrdYwdR0SyXhX9NtbNUsRxAlM0rsnMnExgxh5-DaHqK594_fkSZ1T2t_JbPGW9KjrbRkaDEaYBcdyy26CR3vT5o$> Taking a look now! Is this a recurring error in the log? Or is it only happening upon start up.

**Comment by thomasvn** [comment]
@jacklozano I believe the issue here is that you have a single persistentvolumeclaim associated with two storageclasses, which the Prometheus query isn’t expecting.

Specifically, the LHS and RHS of this operation found multiple series when matching on `{namespace=\"opencost\", persistentvolumeclaim=\"data-wordpress-mariadb-0\"}`. This prevented Prometheus from doing the `*` operation.

Is there a reason that this PVC is associated with two `storageclasses`? From my understanding, this would be atypical?

**Comment by jacklozano** [comment]
We thought the same thing, so we deleted the extraneous PVCs.  However, the cost model engine continued to alert on the PVCs mismatch a few days after deletion.  

After inspecting the logs this morning, the container is no longer complaining about that query.  I suspect the timeseries has fallen off as we only have a 10 day retention on prometheus data.

At this point, I think this issue can be closed since it was related to artifacts in prometheus and not with opencost.  Thank you so much for your input.

**Comment by AjayTripathy** [comment]
Thanks for investigating @thomasvn . We should be more resilient to this-- lets leave this issue open and look to file a fix?
