### ISSUE TITLE
Download CSV via api 

### ISSUE THREAD

**Issue by ndallavalentina** [opencost/opencost#1745]
**Is your feature request related to a problem? Please describe.**
I would like to download a daily CSV via API(there is already this function in the Opencost UI) with the ability to specify the same parameters like 1d etc. I cannot see it in the API documentation at the moment this function. By checking I can see just **GET /allocation/compute**. I would like to save this report in external storange as cost reference

there was a separate discussion to convert the JSON to CSV by using a script but this functionality would be great to be native

**Comment by ndallavalentina** [comment]
I can confirm that `-d format=csv` taken from Kubecost does not work. 
https://docs.kubecost.com/apis/apis-overview/allocation

I tried `-d format=csv` and `-d format=json` and I obtained the same output

**Comment by AjayTripathy** [comment]
Hey @nicolodallavalentinaclearscore , I think this is something we'd take a PR for if interested.

**Comment by ndallavalentina** [comment]
if this function is already present on Kubecost is it possible to backport on Opencost?

**Comment by mattray** [comment]
@nicolodallavalentinaclearscore I'd be happy to help you develop this, I don't believe Kubecost Engineering is working on this right now.

**Comment by AjayTripathy** [comment]
We actually just got a contribution that potentially might help! https://github.com/opencost/opencost/pull/1792/files
