### ISSUE TITLE
JSON-serialization NaN is still occuring 

### ISSUE THREAD

**Issue by rossfisherkc** [opencost/opencost#1746]
Looks like we had a PR cc @nealormsbee for this https://github.com/opencost/opencost/pull/1137

Have a customer where it's still occurring in the Cost Allocation report
![image](https://user-images.githubusercontent.com/113053906/224062358-99c7584a-083b-47e0-b7ec-bc99f509ec58.png)

Asked them for a localhost:9090/model/allocation/summary?window=3d&aggregate=cluster&external=true&accumulate=true&shareIdle=true&idleByNode=false&format=csv

Name,CPU,GPU,RAM,PV,Network,LoadBalancer,External,Shared,Efficiency,Total
REDACTED,881.065,NaN,1525.347,205.265,0.000,0.000,0.000,0.000,0.000,NaN

Version: 1.97.0

**Comment by rossfisherkc** [comment]
Updated to the latest version, still occurring

**Comment by AjayTripathy** [comment]
cc @nealormsbee , can you take a look? What other info do you need?

**Comment by nealormsbee** [comment]
Spoke to @rossfisherkc this morning. I am not going to be the best person to get in and diagnose this. We weren't able to reliably reproduce the issue before, and I'm not well-equipped to plumb those data pipelines. My last contribution was a best-guess at where division by 0 might occur (per Sean's comment [here](https://github.com/opencost/opencost/pull/1137#pullrequestreview-929331085)).

Recommendation is to get somebody from the Cloud or Core groups the reproduction info they need and find the problem.
Longer term, it may be wise to have a general strategy for handling NaNs -- maybe convert to `null` and return a warning?

**Comment by rossfisherkc** [comment]
This issue has been migrated to Jira - EV-35

**Comment by abdennour** [comment]
Great guys ! We are the customer here . If it's a regression bug , what's the latest stable version so we can rollback . We already started by 1.197.x , and we kept upgrading , and this bug appeared at 1.200.2

**Comment by abdennour** [comment]
Please check my software react-csv . I remember the challenges to render empty values and it might help even if it's not sane prof. Lang

**Comment by abdennour** [comment]
Hi guys, please share news. We tried to run  the ETL repair API.. but it responds with 403 requiring token. Note that we are using OIDC for authentication. how can we run this API with authentication

**Comment by thomasvn** [comment]
Hi @abdennour! While we were on a call together, I believe we solved the original NaN issue. Specifically, we resolved this by replacing all `NaN` with `0` in your `/var/configs/default.json`. Then we restarted the pod.

@abdennour Is it safe to close this issue?
