### ISSUE TITLE
custom costs

### ISSUE THREAD

**Issue by mohang6770** [opencost/opencost#1747]
is there a way of uploading the custom costs, could you please help.

**Comment by mattray** [comment]
On-prem pricing is documented here: https://www.opencost.io/docs/on-prem 

Are you trying to override individual node prices on a cloud? I think that works but I don't currently have documentation.

**Comment by mohang6770** [comment]
i am trying to change the custom costs for the on-premises, do you have any documentation on how the costs is calculated. Any examples to time and cost applies.

**Comment by mohang6770** [comment]
> On-prem pricing is documented here: https://www.opencost.io/docs/on-prem
> 
> Are you trying to override individual node prices on a cloud? I think that works but I don't currently have documentation.

i am trying to change the custom costs for the on-premises, do you have any documentation on how the costs is calculated. Any examples to time and cost applies.

**Comment by mattray** [comment]
The technique here is what needs to be documented: https://github.com/calebcall/opencost/blob/main/deploys/deployment.yaml 
and
https://github.com/calebcall/opencost/blob/main/deploys/configmap.yaml

I'm traveling right now, so I won't have my homelab for testing until next week.

**Comment by mohang6770** [comment]
> The technique here is what needs to be documented: https://github.com/calebcall/opencost/blob/main/deploys/deployment.yaml and https://github.com/calebcall/opencost/blob/main/deploys/configmap.yaml
> 
> I'm traveling right now, so I won't have my homelab for testing until next week.

Thanks..
I did the config map earlier, but what I am trying to do is the calculation of the cost...is the cost we see in default.json is per hour or per minute

**Comment by mattray** [comment]
@mohang6770 looking at https://github.com/opencost/opencost/blob/develop/pkg/cloud/providerconfig.go#L212 we see that pricing is per hour.

**Comment by mattray** [comment]
https://www.opencost.io/docs/on-prem#custom-pricing-using-the-opencost-helm-chart shows how to apply custom costs. You can override `defaults.json`, `aws.json` or whatever you need.


FYI calling curl -s -X GET 'http://localhost:9003/allNodePricing' | jq will give you a dump of current pricing.

I'm closing this for now, if there are specific updates you'd like in the documentation please open a new PR.
