### ISSUE TITLE
Allocation API to return both Namespace and Pod Labels on Allocation requests

### ISSUE THREAD

**Issue by David-Elizondo** [opencost/opencost#1748]
**Is your feature request related to a problem? Please describe.**
As defined in the source code here: https://github.com/opencost/opencost/blob/v1.100.2/pkg/costmodel/allocation_helpers.go#L929-L931 when returning labels. Quoted below: 

```
- // Apply node labels first, then namespace labels, then pod labels
- // so that pod labels overwrite namespace labels, which overwrite
- // node labels.
```
We need to see namespace labels even though they may be the same label name as a pod label.

**Describe the solution you'd like**
It would be better to return the Namespace labels as well as the combined label content generated at the code specified.
 
**Describe alternatives you've considered**
No Alternative is possible when labels have the same name across Namespace and Pod.

**Additional context**
This is an Enterprise Issue.

**Comment by AjayTripathy** [comment]
Hi @David-Elizondo thanks for this feature request and wow, a corresponding PR! Let's continue discussion on the PR.

**Comment by mattray** [comment]
Related: https://github.com/opencost/opencost/pull/1789
