### ISSUE TITLE
WRN Skipping AWS spot data download: operation error S3: ListObjects, https response error StatusCode: 403

### ISSUE THREAD

**Issue by ndallavalentina** [opencost/opencost#1751]
**Describe the bug**
I can see from the logs that is trying to download some spot instance's data price from some Aws bucket.

WRN Skipping AWS spot data download: operation error S3: ListObjects, https response error StatusCode: 403, RequestID: xxxxxxxxxxx, HostID:Xxxxxxxxxxxxxxxxxxxxxx api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
2023-03-10T08:14:41.408149878Z INF Spot Pricing Refresh scheduled in 15.00 minutes.

every 15 minutes will display in the logs.

by reading the code it seems like it is aspected that some AWS credentials are required to be set as it will download this data and map as struc: 
https://github.com/opencost/opencost/blob/3507d95d08803ef541ce3f147b40db500d10c1b6/pkg/cloud/awsprovider.go#L189

but actually, when I install it is not requested to be set. 
https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml

**To Reproduce**
Install Opencost v1.100.0 on the k8s cluster with spot instance 

**Expected behavior**
Probably, as a suggestion, enable this feature (to download some sort of spot instance price metrics) by setting AWS permission as an env variable for the container also it needs to update the documentation with an example of which bucket is trying to retrieve data, and what permissions are requested. etc..

**Screenshots**
N/A

**Which version of OpenCost are you using?**
v1.100.0

**Additional context**
I was not able to find any documentation about this feature to understand what it was trying to do. This feature could be really useful if documented well and maybe instead using AWS credentials ( as we store after on git) using an IAM role

**Comment by AjayTripathy** [comment]
@mattray we should have kubecost docs here that should be migrated to opencost-- can you handle?

**Comment by mattray** [comment]
@AjayTripathy I didn't think OpenCost could do spot instances, don't they require accessing the CUR since prices aren't fixed?

Docs are here: https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances

**Comment by AjayTripathy** [comment]
I think that opencost still has a way to estimate spot instance prices, though they will not be 100% accurate since data is delayed and not reconciled to the CUR.

**Comment by bryanasdev000** [comment]
Related: https://github.com/opencost/opencost/issues/1809

**Comment by mattray** [comment]
I'm closing this because Spot pricing is documented: https://www.opencost.io/docs/configuration/aws#aws-spot-instance-data-feed-configuration
