### ISSUE TITLE
Cost Model Environments: Multi Cloud provider secret key should be set an IAM role ( example for Aws)

### ISSUE THREAD

**Issue by ndallavalentina** [opencost/opencost#1752]
**Describe the bug**
I can see from the code there is a possibility to set environment variables when I launch a container:
example
- AWS_SECRET_ACCESS_KEY
- ALIBABA_ACCESS_KEY_ID

I guess this will be used to download prices for spot instances and probably communicate with other Cloud services: 
https://github.com/opencost/opencost/blob/3507d95d08803ef541ce3f147b40db500d10c1b6/pkg/env/costmodelenv.go#L16

I was not able to find any documentation that explains what these environmental variables are used for. Which permission needs to be attached to it 

**To Reproduce**
Just by reading the code 

**Expected behavior**
Ability to set an IAM role and attach it to the pod instead hardcoded secret into the code. 
Also document what these Cost Model Environments are used for 

**Screenshots**
N/A

**Which version of OpenCost are you using?**
v.1.100

**Additional context**
N/A

**Comment by AjayTripathy** [comment]
@mattray we have Kubecost docs here, right thing to do should be to migrate to opencost. Can you handle?

**Comment by mattray** [comment]
https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#attach-via-servicekey-and-kubernetes-secret 

shows setting the AWS_SECRET_ACCESS_KEY into your `values.yaml` or as a secret within K8s for use by Kubecost.

For the IAM permissions, https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances refers to https://github.com/kubecost/cloudformation/blob/master/kubecost-single-account-permissions.yaml which has the IAM permissions required for the `KubecostUser` to access the spot pricing feed.

Similarly https://docs.kubecost.com/install-and-configure/install/provider-installations/alibaba-install has usage for the ALIBABA_ACCESS_KEY_ID

**Comment by mattray** [comment]
I've put this in my documentation backlog.

**Comment by Qixuanw** [comment]
@mattray Can we use IAM role with proper permissions instead of hardcode the AWS_SECRET_ACCESS_KEY ?

**Comment by mattray** [comment]
@Qixuanw does this cover what you're looking for? https://www.opencost.io/docs/AWS

**Comment by thehackercat** [comment]
> [@mattray](https://github.com/mattray) Can we use IAM role with proper permissions instead of hardcode the AWS_SECRET_ACCESS_KEY ?

I have the same question on Alibaba cloud
