### ISSUE TITLE
Document Azure support for OpenCost

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1757]
OpenCost needs to document how to properly configure Azure, based on 
https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config

**Comment by CsBigDataHub** [comment]
@mattray Thanks for working in this. Looking forward to this feature.
Rate card seems to be from 2019 - https://github.com/opencost/opencost/blob/develop/configs/azure.json

**Comment by AjayTripathy** [comment]
Would love to bump priority on this one, we will have more cool Azure integrations to support as well!
