### ISSUE TITLE
search cost via annotations - labels

### ISSUE THREAD

**Issue by ndallavalentina** [opencost/opencost#1761]
**Is your feature request related to a problem? Please describe.**
Would be great to be able to search from the UI and via API by labels and annotations. In this way, we can check which team or application under the same cluster cost more or the variation during the time.

**Describe the solution you'd like**
be able to search via labels or annotations

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AjayTripathy** [comment]
Thanks for this feature request. It's currently supported in the API but not the UI. See more details on the API here. https://www.opencost.io/docs/api
