### ISSUE TITLE
How to convert dollars into CNY(China Yuan)

### ISSUE THREAD

**Issue by gunner-me** [opencost/opencost#1800]
The OpenCost is really useful to us, but the trouble is that the page can only display the dollar sign, can not be converted into our familiar CNY, is there a way to modify it at present, if not, the later version will consider support？thank you

**Comment by mattray** [comment]
I believe the currency is a function of either locale or it's hard-coded, I don't believe it's stored with the data. 
https://github.com/opencost/opencost/blob/develop/ui/src/Reports.js#L122 appears to be where it's set via the util.js `toCurrency` in https://github.com/opencost/opencost/blob/develop/ui/src/util.js#L261

Probably the container is getting the locale as `en_US`, but I'm not sure how/where to override it.

**Comment by gunner-me** [comment]
> I believe the currency is a function of either locale or it's hard-coded, I don't believe it's stored with the data. https://github.com/opencost/opencost/blob/develop/ui/src/Reports.js#L122 appears to be where it's set via the util.js `toCurrency` in https://github.com/opencost/opencost/blob/develop/ui/src/util.js#L261
> 
> Probably the container is getting the locale as `en_US`, but I'm not sure how/where to override it.

thank you any way

**Comment by mattray** [comment]
I want to leave this ticket open, I'd like to see this documented.

**Comment by mattray** [comment]
Fixed in https://github.com/opencost/opencost/pull/1940
Will be in 1.104
