### ISSUE TITLE
namespaced resources in opencost/opencost/develop/kubernetes/opencost.yaml should specify namespace

### ISSUE THREAD

**Issue by trondhindenes** [opencost/opencost#1807]
**Describe the bug**
The opencost manifest in the quickstart documentation misses namespace attribute for several of the resources. It would be good if the manifest was made more robust by always specifying the `opencost` namespace

**Expected behavior**
All namespaced resources should specify namespace, so that they don't rely on the user being in a certain namespace when applying

**Screenshots**

**Which version of OpenCost are you using?**

**Additional context**

**Comment by mattray** [comment]
This will be addressed by https://github.com/opencost/opencost/pull/1511
