### ISSUE TITLE
Costs for CRDs

### ISSUE THREAD

**Issue by raballew** [opencost/opencost#1818]
**Is your feature request related to a problem? Please describe.**
Kubernetes can be used to managed resources that are external to the cluster itself. A popular framework being used is [Crossplane](https://github.com/crossplane) that can manage any infrastructure or application no matter where they run. Similarly this could be done through a custom operator with its own set of CRDs. There are costs associated with managing these resources as well and I would like to track them in them same way.

**Describe the solution you'd like**
Extend opencost so that costs for any CR can be described in a custom pricing sheet.

**Comment by mattray** [comment]
@raballew this sounds like it would fit in what we are currently working on in the External Asset Costs working group. We are hashing out a specification, reference example and documentation for incorporating resources not directly part of the Kubernetes cluster into OpenCost. We're meeting weekly and I encourage you to join us and discuss your use cases.
[Meeting Notes](https://docs.google.com/document/d/1-d-Vvy1VGHW0sXKiTjTplIUEnrElIlnfMU8sUpEehlA/edit#heading=h.vmcygvd1xmbm)
[OpenCost Community Calendar](https://bit.ly/opencost-calendar)

**Comment by raballew** [comment]
@mattray I will join next weeks call and try to give some insights into the use case I am thinking of.

**Comment by mattray** [comment]
See you Tuesday!

**Comment by mattray** [comment]
This was brought up in today's meeting, no one was against adding it to the specification, you'll just need to be very thoughtful about the potential for high cardinality in the metrics

https://docs.google.com/document/d/1-d-Vvy1VGHW0sXKiTjTplIUEnrElIlnfMU8sUpEehlA/edit#heading=h.yelnpogu94oe

**Comment by raballew** [comment]
@mattray I am not sure where to track this discussion. I have added a comment to the doc https://docs.google.com/document/d/1-d-Vvy1VGHW0sXKiTjTplIUEnrElIlnfMU8sUpEehlA/edit?disco=AAAAu0mC2fw

**Comment by mattray** [comment]
Why don't you email me at ***@***.*** or hit me up in Slack and
we'll have an offline conversation as I give you a current status and see
how to help you get involved?

**Comment by AllenZMC** [comment]
@mattray @raballew Is there any new progress?
