### ISSUE TITLE
Backend CI (Action) is taking ~= 1 hour to complete

### ISSUE THREAD

**Issue by michaelmdresser** [opencost/opencost#1820]
**Describe the bug**

https://github.com/opencost/opencost/actions/workflows/pr.yaml

<img width="758" alt="image" src="https://user-images.githubusercontent.com/17585786/228626306-b3563e66-77a3-4af0-8ee3-3386fe5b974c.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/17585786/228626961-de02b641-d53b-4cae-aa94-ac310f0e363e.png">

**Expected behavior**

CI should be < 15 min.

**Comment by michaelmdresser** [comment]
@mattray I'm not sure, but this could be burning a lot of cash on Actions.

**Comment by michaelmdresser** [comment]
Offending lines with timestamps from one run:

https://github.com/opencost/opencost/actions/runs/4555449422/jobs/8034508835#step:4:379

<img width="993" alt="image" src="https://user-images.githubusercontent.com/17585786/228627954-0da8c41c-5880-4fb4-989a-6ed22aee86f0.png">

The build seems to be taking a while, but I'm not sure why the tests are taking so long; no package's tests seem to exceed 30s in duration.

**Comment by michaelmdresser** [comment]
I think I know why: ARM64 builds, which are probably being QEMU-emulated on a presumably AMD64 Actions runner. That'll do it.

https://github.com/opencost/opencost/blob/e2a30e36b814d5196cff8af54608b9611dc1b8d7/.github/workflows/pr.yaml#L32

**Comment by keithhand** [comment]
Dropping this here: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs. Running parallel builds would likely speed things up a lot

**Comment by mattray** [comment]
This PR last week from @wilsonwu introduced Arm64 support. https://github.com/opencost/opencost/pull/1799

The `go test` step on amd64 and arm64  take 690.5s and 3511.7s respectively and appear to already be parallelized in the log output.

Do we think we're going to catch additional issues with arm64 enabled? We're already building and releasing on this platform, this is strictly running our tests for inbound PRs, maybe we should disable it?

**Comment by michaelmdresser** [comment]
@mattray I agree with the suggestion to disable the ARM64 build. I don't believe we're going to discover new issues as a result and it's an enormous drag on the development feedback loop right now. I opened a PR: https://github.com/opencost/opencost/pull/1827

**Comment by mattray** [comment]
arm64 removed from PR reviews: https://github.com/opencost/opencost/pull/1827
