### ISSUE TITLE
Opencost-ui container uses root user.

### ISSUE THREAD

**Issue by r2k1** [opencost/opencost#1824]
**Is your feature request related to a problem? Please describe.**

Opencost-ui container is using root user. It poses some potential vectors for attack and best practices is to launch a container as a non-root user.

Some kubernetes clusters may be configured with a policy preventing such containers from starting. Opencost API container is using non-root user.

https://github.com/opencost/opencost/blob/develop/Dockerfile
https://github.com/opencost/opencost/blob/develop/ui/Dockerfile

**Comment by AjayTripathy** [comment]
Thanks for the feedback @r2k1 ... this should be quick. https://github.com/opencost/opencost/blob/develop/Dockerfile#L41

All we need to do is add the USER directive to the UI docker container like we do for the API container. Anyone in the community want to take @mattray ? If not I can do it quickly but great first issue to get the workflow down!
