### ISSUE TITLE
Please list organizations using OpenCost in an ADOPTERS.md

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1831]
Part of the methodology for establishing production usage of a project is allowing organizations to publicly announce their usage of OpenCost. 

If your organization would like to be listed as using OpenCost in production or at stages of testing, please comment on this issue or make a PR to the <https://github.com/opencost/opencost/blob/develop/ADOPTERS.MD> file.

**Comment by dsterz** [comment]
The mindcurv group helps design, implement and run scalable, cost effective and secure digital commerce platforms on top of kubernetes and enables DevOps teams to build and run run any workload on tailormade platforms. Mindcurv was involved in drafting the initial OpenCost specification and continue to recommend OpenCost-based solutions for our clients and technology partners.

**Comment by mattray** [comment]
Updating to use the [definitions provided by the CNCF](https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-adopter).
