### ISSUE TITLE
Publish docker images with semver compliant tags

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1910]
The two images that get generated for OpenCost do not appear to follow semver tags. The GitHub releases do follow semver. The current format is `prod-vX.X.X-${ARCH}`

The two images are:
- quay.io/repository/kubecost1/opencost-ui 
- quay.io/repository/kubecost1/kubecost-cost-model

We should also generate tags that are strictly in `vX.X.X` so that automation tools that parse the semver tag are able to parse both image tags without problems.

**Comment by mattray** [comment]
Waiting on permissions to submit a PR to the internal Kubecost release repository.

**Comment by Pokom** [comment]
@michaelmdresser Are semver compliant tags going to be uploaded going forward? I looked at the [registry](https://quay.io/repository/kubecost1/kubecost-cost-model?tab=tags) and don't see anything without the `prod-*` prefix.

**Comment by michaelmdresser** [comment]
@Pokom compliant tags should start showing up for releases starting tomorrow. If you don't see them, let me know.
