### ISSUE TITLE
ERR Error updating CSV: querying oldest sample: no results

### ISSUE THREAD

**Issue by ndallavalentina** [opencost/opencost#1915]
What I'm expected: 
After I setup the environment variable  "EXPORT_CSV_FILE" I expected a daily csv report into AWS s3 bucket but Actually has not created or uploaded anything on the s3 bucket.

What error I can see when I reload the pod:
`2023-05-15T07:09:31.198540281Z ERR Error updating CSV: querying oldest sample: no results

When it happened:

It's the first time that I'm trying to set up CSV exported to Aws the moment happened overnight at 00:10 and every time I reloaded a pod. 

Specs:
- Opencost version in use: 1.103.1
- Prometheus data retention has been set 1 day from the OpenCost UI I can download the csv from Yesterday

Note: 
The S3 bucket exited on the correct location and I gave permissions to the role and attached it to the pod as annotation:

`iam.amazonaws.com/role: opencost-report-development`

role permissions
```
"s3:PutObject",
"s3:GetObject",
"s3:ListObject",
"s3:HeadObject",
"s3:PutBucketAcl"
"s3:ListBucket"
```

I'm not sure where the issue is, but would be great to improve this part with some checks: 
https://github.com/opencost/opencost/blob/ce4d2eb52dc09705df371f8cdd9ba13c6065ed8a/pkg/cmd/costmodel/costmodel.go#L61
or at least report the logs error from here in the logs: https://github.com/opencost/opencost/blob/ce4d2eb52dc09705df371f8cdd9ba13c6065ed8a/pkg/costmodel/csv_export.go#L45

**Comment by mattray** [comment]
@r2k1 any suggestions for troubleshooting this?

**Comment by r2k1** [comment]
It appears that the node_cpu_hourly_cost Prometheus metric is not returning any data. This metric is crucial for determining the date range of stored data in Prometheus to avoid incomplete data. To populate this metric, the opencost pod needs to be scraped.

CSV export requires such metric contains data at least for a day in UTC (from 00:00 to 23:59). Which may take between 24 and 48 hours after the opencost installation.

Here is an extra prometheus config needs to be applied. From [documentation](https://www.opencost.io/docs/install)
```
helm install my-prometheus --repo https://prometheus-community.github.io/helm-charts prometheus \
  --namespace prometheus --create-namespace \
  --set pushgateway.enabled=false \
  --set alertmanager.enabled=false \
  -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
```

Does prometheus scrapes opencost?

If you check the opencost UI / CLI do you see any available data there?

If opencost is successfully scraped by Prometheus, please verify the following two queries in Prometheus:

Query to check the problematic metric:
```
node_cpu_hourly_cost
```

Query to retrieve all metrics produced by opencost:
```
count({job="opencost"}) by (__name__)
```

**Comment by r2k1** [comment]
With the default prometheus installation you should be able to use something close to the next command to access the prometheus UI.

```bash
kubectl -n kube-system port-forward svc/my-prometheus-server 9090:9090
```

**Comment by mattray** [comment]
@ndallavalentina were you ever able to test this?

**Comment by morawat** [comment]
@r2k1 / @mattray   we are getting same error while using export_csv feature.

using image tag: "1.111.0"
chart version: 1.41.0


**Error messages:**
```
ERR Error updating CSV: querying oldest sample: no results
WRN not caching 1d cluster costs: no data or less than 5.000000 minutes data

```

I don't know if this is relevant. i cannot change the value of "ComputeAggregateCostModel" to "true" even after updating this.

```
    env:
      - name: DISABLE_AGGREGATE_COST_MODEL_CACHE
        value: "false"
```

` ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found false, disableAggregateCostModelCache true, noCache false) `


When I query in Prometheus for output for node_cpu_hourly_cost, i do get output.

**Comment by AjayTripathy** [comment]
What is the output you're seeing on node_cpu_hourly_cost @morawat ?

**Comment by morawat** [comment]
Thank you for your response, @AjayTripathy. I am no longer experiencing the issue. It seems to have resolved itself without any further intervention.
