### ISSUE TITLE
Add label archType to the node_* metrics

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1916]
**Is your feature request related to a problem? Please describe.**
As teams adopt ARM workloads, it would be nice to get a detailed view of costs by the architecture type workloads are running upon. These is especially important when making total cost of ownership(TCO) decisions on workloads. 

**Describe the solution you'd like**
- `node_*_cost` metrics have a label `archtype` added to it

**Describe alternatives you've considered**
OpenCost already exports this label on `kube_node_labels`, and would also be available using the [kube_node_annotations](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/node-metrics.md) metric from `kube-state-metrics`. However this then requires all queries and dashboards to join the two metrics, making the queries more expensive. It would be great to be able to do a query like: `sum by (archtype) (node_cpu_hourly_cost)`

**Comment by mattray** [comment]
Do we need a separate metric for this or can you just query for the Label `kubernetes.io/arch=arm64`?

(edit) Nevermind, I fully read the issue 🤦

**Comment by Pokom** [comment]
Pretty much I'm looking for someone to convince me _not_ to do this. The PR is simple enough to add, but wanted to get some feedback from kubecost folks.

For me it comes down to ergonomics:

```
sum by (arch) (node_cpu_hourly_cost)
```

vs

```
sum
(
    node_cpu_hourly_cost
    * on (node)
    kube_node_labels{label_kubernetes_io_arch="arm64"}
)
```

I'd need to do some `label_replace` manipulation to preserve the arch for nodes, but you get the gist. For simple queries, I think the later would work fine. For complex queries, having the arch on the node_*_cost metrics would greatly simplify queries.

**Comment by thomasvn** [comment]
@Pokom I'd agree that this would be ergonomically nice for queries!

My first reaction to adding a label here, is the increase in [cardinality](https://prometheus.io/docs/practices/naming/#labels) for all `node_*_cost` metrics. And what compute/memory impact this could have for large-scale users/queries.

Considering that the label is just the arch of the node and the same node won't ever have two arches, I think this is ok?

@michaelmdresser @AjayTripathy ?

**Comment by Pokom** [comment]
> My first reaction to adding a label here, is the increase in [cardinality](https://prometheus.io/docs/practices/naming/#labels) for all node_*_cost metrics. And what compute/memory impact this could have for large-scale users/queries.

I thought about this a bit more and I don't think there actually will be an increase in cardinality. Each node will only have a single arch type(I'd seriously hope so at least). There will be extra memory consumption in having another label, but that's about it.

On the opposite end, the cost of having to query `kube_node_labels{label_kubernetes_io_arch="arm64"}` will be far greater than the cost of storing an additional label.

**Comment by thomasvn** [comment]
@Pokom Yep after thinking on it some more, I agree! I'm good with the change you made in the PR!
