### ISSUE TITLE
OpenCost not matching node type in Azure, causing costs including GPU to be ignored

### ISSUE THREAD

**Issue by lostcities** [opencost/opencost#1938]
**Describe the bug**
A clear and concise description of what the OpenCost bug is. Please ensure this is an issue related to the OpenCost cost model, API, UI or specification. Public Kubecost bugs may be opened at https://github.com/kubecost/cost-analyzer-helm-chart/ 

We are using NC8as T4 v3 nodes in AKS, specifically for their GPU capabilities.  Because they appear in the Azure pricing data as  "Standard_NC8as T4 v3" rather than "Standard_NC8as_T4_v3" they are ignored, and OpenCost does not report any of their costs.  We noticed because GPU costs were coming up as zero which was clearly not correct.  It is a significant issue for us as we try to allocate costs to the appropriate teams in a shared cluster.

**To Reproduce**

1. Deploy Standard_NC8as_T4_v3 nodepool in aks cluster/
2. Watch OpenCost logs, note warning for no pricing data
![image](https://github.com/opencost/opencost/assets/12943342/1da843ab-fa8f-48d4-905c-c34fae8a6c3b)
3. Also note that no GPU costs are found despite active nodes of this type.

The fix is a one-character addition to change the 1 to a -1 to replace whitespace maximally with underscores:

https://github.com/opencost/opencost/blob/f137ea2eba4dae37b06783a926d896737a5bcde4/pkg/cloud/azure/provider.go#L992

(as in this PR submitted last month pre-refactoring of the Azure provider -- but the issue remains.  https://github.com/opencost/opencost/pull/1868)

**Expected behavior**

Node type Standard_NC8as_T4_v3 is correctly identified and costs assessed for it.

**Screenshots**

**Which version of OpenCost are you using?**
This may be the Kubecost release.

 We're currently using OpenCost 1.103.1

**Additional context**

Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

Azure-AKS, deployed in West Europe region (but we track costs in USD).
Kubernetes version 1.24 (at the time I was debugging this, now we've moved on to 1.25)

**Comment by mattray** [comment]
I'll inquire with Kubecost Support, this feels like a bug that would be relevant to both OpenCost and Kubecost.

**Comment by angelos34** [comment]
Hello,

We also facing the same issue:
 no pricing data found for westeurope,Standard_F16s_v2,ondemand: &{map[agentpool:systempool beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_F16s_v2 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:westeurope failure-domain.beta.kubernetes.io/zone:westeurope-1 kubernetes.azure.com/agentp

Do we have the fix for  this plz?

Thanx in advance

**Comment by srpomeroy** [comment]
This PR I was working on may be related.
https://github.com/opencost/opencost/pull/2009
