### ISSUE TITLE
OpenCost missing Azure PV ZRS types due to name matching issues

### ISSUE THREAD

**Issue by lostcities** [opencost/opencost#1939]
**Describe the bug**
A clear and concise description of what the OpenCost bug is. Please ensure this is an issue related to the OpenCost cost model, API, UI or specification. Public Kubecost bugs may be opened at https://github.com/kubecost/cost-analyzer-helm-chart/ 

Opencost does not match on the naming found in the Azure pricing data for PVs, in particular for ZRS types.

**To Reproduce**

1. Deploy AKS cluster utilizing StandardSSD_ZRS type.
2. Turn on debugging in OpenCost
3. Observe that pricing is not found for this node type.

(I am not sure what correlates to the "default" PV type ... maybe some future debugging to do there ...)

[90m2023-05-22T18:18:00.938145881Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938269982Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938292482Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938346483Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938367483Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938387883Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938411084Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938428384Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938449384Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938475084Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938493284Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938515585Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938535185Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938557885Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938572185Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938594985Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938621886Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938636886Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938662586Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938678286Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938703787Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938729287Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938745087Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938775087Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938792187Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938813788Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938829888Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938853088Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938870688Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938885388Z[0m [33mDBG[0m Persistent Volume pricing not found for default: westeurope,
[90m2023-05-22T18:18:00.938908589Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS
[90m2023-05-22T18:18:00.938924289Z[0m [33mDBG[0m Persistent Volume pricing not found for managed-zrs: westeurope,StandardSSD_ZRS

**Expected behavior**

We'd like to see the pricing data be matched to the PV types.  We are specifically affected by the StandardSSD_ZRS type but digging into the problem, I think other types are getting missed also.  See:  https://github.com/opencost/opencost/pull/1868/files
for the collection of changes that I believe fix a number of PV matching issues.

**Screenshots**

**Which version of OpenCost are you using?**
This may be the Kubecost release.

1.103.1. (originally tested on an earlier version but the issue is still present)

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

Azure-AKS, West Europe region.
Originally validated using Kubernetes 1.24 but we moved to 1.25 recently -- shouldn't matter since this is tied to the Azure pricing data.

**Comment by mattray** [comment]
You commented "This may be the Kubecost release." If you are using Kubecost, feel free to open an issue with Kubecost Support. Either way, this feels like a bug that would be relevant to both OpenCost and Kubecost.

**Comment by lostcities** [comment]
We are using OpenCost.  Since there is clearly overlap, I think in the moment I wasn't sure how to interpret that question.  Because yes, I think this affects both (we started with Kubecost).

**Comment by mblaschke** [comment]
can confirm this issue

**Comment by mattray** [comment]
Thanks, I'm raising this with Kubecost Engineering.
