### ISSUE TITLE
Default values in `configs/aws.json` breaks IRSA with kubecost helm deployment

### ISSUE THREAD

**Issue by patrickli-foxtel** [opencost/opencost#1955]
**Describe the bug**

This bug is related to https://github.com/kubecost/cost-analyzer-helm-chart/issues/2238. Please refer to that ticket for detailed description.

In a nutshell, we don't want `awsServiceKeyName` or `awsServiceKeySecret` to have values when using IRSA (this is also the best practice when using EKS, rather than using long-term access keys). It will only do so then both key name and secret are empty. But the default value for `awsServiceKeyName` will cause `cost-model` to try to authenticate with the default access key instead of trying to use IRSA

Kubecost helm chart only use the key name and secret values to create a [secret](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/aws-service-key-secret.yaml). It does not set the values in `aws.json`. So I believe the best solution is to set `awsServiceKeyName` to empty in `configs/aws.json`. This way if they are not explicitly set, IRSA will be used. Currently there is no way to use IRSA unless we login to the pod and manually remove the `awsServiceKeyName` from `configs/aws.json`.

I believe we should do the same for the following keys as well.

* `awsSpotDataRegion`
* `awsSpotDataBucket`
* `awsSpotDataPrefix`
* `athenaBucketName`
* `athenaRegion`
* `projectID`

Other cloud config files does not suffer from this problem as they access key values are empty by default.

**Which version of OpenCost are you using?**
`v1.104.0-rc.2`

**Comment by mentos1386** [comment]
Workarround as the issue author mentions is  `cost-analyzer-helm-chart` is to run:

```bash
kubectl exec -it -n kubecost deployment/cost-analyzer -c cost-model -- sed -i 's/AKIXXX//' /var/configs/aws.json
```

**Comment by mattray** [comment]
I believe this is being tracked over here: https://github.com/kubecost/cost-analyzer-helm-chart/issues/2238

**Comment by patrickli-foxtel** [comment]
I think here is more appropriate as it requires a change to a file in this repo.

**Comment by thomasvn** [comment]
I just reproduced this and agree with the proposed workaround! I will put together a PR now.
