### ISSUE TITLE
Azure Cost Reporting Issues

### ISSUE THREAD

**Issue by kstedman9** [opencost/opencost#1960]
So I am trying to figure out why my pricing for workloads does not seem to match reality.  We know the price we are being charged and based on the usage metrics we get from kubernetes we know how much a workload should be approximately costing us.   The issue I am seeing is that workloads that tend to have a higher memory footprints with low CPU usage do not create the correct cost.  Their costs as shown in opencost are significantly lower than they should be.  

This is because when I run the numbers in the metrics the total cost of the node is being divided between the CPU at approx. 84% and the memory approx. 16%.  But in reality the memory should be weighted more than the cpu.  In kubernetes clusters the CPU is more easily shared across workloads where the memory will have affects of causing new nodes to be spun up or keeping workloads from being scheduled on a node. Memory is not shared.  So if the owner of the workload has poor memory usage or poor memory resource requests it will cost them more in the cluster.  

I have an example:  I have a workload that is a daemonset that runs on every node of the cluster.  Because it is a 3rd party installed software we have no control on how they use memory and what they recommend for memory requests and limits.  So I took the metrics from kubernetes on memory usage and they are using approx. 40% of the total cluster memory for their product.  I would expect them to cost in opencost around that amount.  The CPU usage is very little.  Thus because CPU is weighted so much higher than memory the cost in opencost for that workload is approx 6% of the cost of the cluster.  

Is there any way to change how the CPU/Memory per hour costs are being divided up from the node total cost per hour.  If not can this be something added to the backlog to allow for the operators to control how the costs are weighted when creating that?

For a work around I will probably for now ignore the node cpu and node memory  metrics being produced by opencost since they do not reflect reality and create my own metrics to accomplish this.  But it would be nice to have some control over this.

**Comment by mattray** [comment]
Pricing for workloads is based on the maximum of the requested and used CPU and RAM as a ratio for the cost of the container. The pricing for CPU and RAM varies depending on what's returned in the pricing API, but the [example azure.json](https://github.com/opencost/opencost/blob/develop/configs/azure.json) shows higher costs for CPU than RAM (per milicore vs. gigabyte) which possibly follows your result. 

https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md#appendix-a

The CPU to RAM ratio is fixed: https://github.com/opencost/opencost/blob/develop/pkg/costmodel/costmodel.go#LL1100C44-L1100C44
but you could override pricing if you want to tilt the ratio or go to the raw data to make your own queries.

**Comment by kstedman9** [comment]
Since we have had OpenCost up and running for a month now we are comparing the total cost for each cluster with actuals from our Subscription and it looks like OpenCost is running about 23% to 24%  cheaper than what we are actually being charged.  We are comparing the OpenCost CPU and Memory with the VMSS from the AKS install.  We would expect these costs to be a whole lot closer since that is just compute costs.  

I see in the logs OpenCost has successfully pulled RateCard from Microsoft.

**Comment by mattray** [comment]
I've got a PR to add https://www.youtube.com/watch?v=P46g6go2KEk to the docs for walking through workload costs.

Are you still seeing inconsistencies?
