### ISSUE TITLE
Diagnostics broken by addition of cluster_id

### ISSUE THREAD

**Issue by nikovacevic** [opencost/opencost#1980]
**Describe the bug**
A previous PR (https://github.com/opencost/opencost/pull/1430) added support for cluster_id in Prometheus query diagnostics. Unfortunately, some of the queries were not templated properly to accept the new parameter, but are sent through the same query templating function, so we're seeing errors.

**To Reproduce**
1. Visit Diagnostics page, or hit the API, and notice errors

**Expected behavior**
No errors, correct diagnostics.

**Screenshots**
![image](https://github.com/opencost/opencost/assets/8070055/cd2e2cfb-f206-4453-8356-fbd016270136)

**Which version of OpenCost are you using?**
`develop` branch, `v1.104`

**Comment by nik-kc** [comment]
This PR addresses this issue:
#1981
