### ISSUE TITLE
Use workload identity with CSV Export with Azure 

### ISSUE THREAD

**Issue by mpicard** [opencost/opencost#1986]
**Is your feature request related to a problem? Please describe.**

To ensure better security practices, using AZURE_CLIENT_SECRET is not recommended and using workload identities / federated token exchange is preferred because it is password-less, the client secret is vulnerable to attacks.

**Describe the solution you'd like**

I would like for workload identities to be supported so that when CSV exports are uploaded to Azure Storage Accounts that I would NOT need to configure an AZURE_CLIENT_SECRET but instead use workload identities to authenticate.

**Describe alternatives you've considered**

The only alternative is client secrets, which is less secure.

**Additional context**

It's pretty easy to implement with azure-identity package

**Comment by mattray** [comment]
Perhaps @r2k1 or @babbageclunk could weigh in?

**Comment by r2k1** [comment]
For CSV export opencost uses default credential provider.

Setting `AZURE_` ENV variables is one of the ways. But you also should be able to use workload identity.

Did you try to create a workload identity with the permissions to read/write from the storage account and attach it to the opencost pod?

**Comment by mpicard** [comment]
Awesome thanks for the info, the docs make it sound like it needs to be with AZURE_CLIENT_SECRET, therefore I did not try it. I will try it out and close the issue.
