### ISSUE TITLE
opencost-exporter without prometheus

### ISSUE THREAD

**Issue by gmarcot** [opencost/opencost#1996]
Hello,

i'm in trouble with opencost-exporter: i don't want install prometheus and i want collect the metrics in datadog.
Without the promethues url in spec env the pod doesn't start, with promethues fake url i see a lot of error in the pod's log like:

```
Request Error: query error: 'Post "http://my-prometheus-server.prometheus.svc/api/v1/query?query=max%28count_over_time%28kube_pod_container_resource_requests%7Bresource%3D%22memory%22%2C+unit%3D%22byte%22%2C+%7D%5B2m%5D+%29%29&time=1687440202": dial tcp: lookup my-prometheus-server.prometheus.svc on 172.20.0.10:53: no such host' fetching query 'max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] ))'
  Parse Error: Prometheus communication error: max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] ))
for Query: max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] ))
```

there are some option to exclude  promethues or it's mandatory to have prometheus?

Thanks

**Comment by danielmilanov** [comment]
Same issue here. 
Is it mentioned anywhere in the documentation for what purpose does opencost call prometheus?
I can only see mentioned that prometheus api endpoint is required to be passed as environment variable, but why?
TIA

**Comment by mattray** [comment]
My understanding is that it's currently required to have Prometheus, but we could probably add support to run without it. I'm going to change this to an Enhancement and bring it up with @AjayTripathy, but if someone wants to sort out removing the dependency we'd appreciate the PR.

**Comment by mattray** [comment]
Take a look at https://www.opencost.io/docs/integrations/opencost-exporter and https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-opencost-exporter
