### ISSUE TITLE
Currency dropdown missing in 1.104.0 release

### ISSUE THREAD

**Issue by majooneez** [opencost/opencost#2007]
**Describe the bug**
There is no way to change currency in opencost-ui using Azure provider. I thought this feature was going to be provided in 1.104.0 release (https://github.com/opencost/opencost/pull/1940) but it is not (or I don't understand how to enable it).

**Expected behavior**
Dropdown menu with Currency list at homepage

**Which version of OpenCost are you using?**
prod-1.104.0

**Comment by mattray** [comment]
This appears to be a regression, I'll track it down.

**Comment by mattray** [comment]
The [commit with multi-currency support](https://github.com/opencost/opencost/commit/6f10f5072c9893bca73fbd4df84215d50a789165) wasn't in the 1.104 branch, but it is in the upcoming 1.105 branch. I'm looking to see if we can cherry-pick it into 1.104 if we do another release before 1.105.
