### ISSUE TITLE
question: Terraform support for azure EnrollmentReader billing role

### ISSUE THREAD

**Issue by csimplestring** [opencost/opencost#2015]
Hi

based on this link: https://www.opencost.io/docs/azure-prices#grant-billing-access-to-your-service-principal 
a bash script is provided. Is it possible to do this in a terraform native way?
Thanks!

**Comment by mattray** [comment]
My suggestion would be to open a PR to add a Terraform wrapper to the [OpenCost Helm chart](https://github.com/opencost/opencost-helm-chart). If that works for you, we can move this issue over there. We'll update the documentation once there's a PR with the support afterward so folks can find the Terraform wrapper.

**Comment by csimplestring** [comment]
the problem we are facing now is: we want to manage the role assignment via terraform, not by this bash script. But we tried some days still not working in tf. If someone can inspire us, that will be great.

**Comment by mattray** [comment]
Closing since https://github.com/opencost/opencost-helm-chart/issues/91 exists
