### ISSUE TITLE
Volume Snapshot Support

### ISSUE THREAD

**Issue by ashish1099** [opencost/opencost#2022]
**Is your feature request related to a problem? Please describe.**
I'm looking to predict the cost and see the utilization of current volume snapshot  

**Describe the solution you'd like**
An endpoint where we can see how much money is spend over volume snapshot 

**Describe alternatives you've considered**
Nothing as of now

**Comment by mattray** [comment]
This feels like something that would need to be supported by parsing the CUR or bill, which OpenCost doesn't currently support. If so we can turn this into a feature request for once we add CUR processing to OpenCost, but it may already be supported in Kubecost (brought up because this came in through Kubecost via email).

@AjayTripathy could you confirm?

**Comment by mattray** [comment]
It looks like Kubecost doesn't have this feature either, @Adam-Stack-PM you want to put this in their backlog?

**Comment by KlavsKlavsen** [comment]
knowing what your backup costs would f.ex. be quite useful.. so you could adjust "retention" f.ex... and sometimes we've found a bug - so old backups (PV snapshots) was not being removed..  thats expensive :)

**Comment by marcoboffi** [comment]
No ETA for this features?  
I think it's very important add this cost type to PVC cost because various backup solutions (velero Azure Backup for AKS,...) create snapshot resource for each PVC/PV.

**Comment by AjayTripathy** [comment]
The volume snapshot pricing should be available in Cloud Costs. Have you tried to set Cloud Costs up for Opencost and looked there?

**Comment by marcoboffi** [comment]
> The volume snapshot pricing should be available in Cloud Costs. Have you tried to set Cloud Costs up for Opencost and looked there?

Sure, price can be get with Cloud Clost feature but then you need a custom implementation to trace it back to the pvc/pv that generated it (and finally to namespace/service/application)

**Comment by AjayTripathy** [comment]
You can use an AWS cost allocation tag to associate them. You can already do so in commercial products like Kubecost or the EKS-optimized Kubecost bundle; doing so in opencost is likely beyond the scope of the open source project.
