### ISSUE TITLE
[Question] Thanos Connection to OpenCost

### ISSUE THREAD

**Issue by sherifkayad** [opencost/opencost#2027]
**Is your feature request related to a problem? Please describe.**
Disclaimer: this is a question.

Thanks a lot for this awesome project. We just have a couple of questions regarding connecting OpenCost with Thanos:
- What are the configs required to have OpenCost correctly connected to a Thanos Querier / Query Frontend instance?
- Assuming we have a Thanos cluster (with a querier / query frontend) that exposes the metrics of multiple clusters, how can one tell OpenCost to target the metrics with a certain cluster selector / label e.g. `cluster="my-cluster"`

Please note that we intend to use the Helm Chart (https://github.com/opencost/opencost-helm-chart/tree/main/charts/opencost) to install OpenCost.

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by mattray** [comment]
I know there are a couple of folks rolling their data up to a centralized database like Thanos (Mimir and Victoria Metrics). If they could provide documentation for how they configured it, we could add it to github.com/opencost/opencost-website and github.com/opencost/opencost-helm-chart

**Comment by Reasonably** [comment]
https://github.com/opencost/opencost-helm-chart/pull/98  
I've made PR for supporting thanos. It already can use thanos using additional env.
