### ISSUE TITLE
Incorrect cpu ram and gpu hourly cost on GPU nodes

### ISSUE THREAD

**Issue by ian-lmcb** [opencost/opencost#2029]
**Describe the bug**
CPU RAM and GPU hourly cost metrics are much lower than they should be when a node has a GPU present. Found this issue in kubecost but also tested with opencost and we are seeing the same result.
See https://github.com/kubecost/cost-analyzer-helm-chart/issues/2418

This is in a Suse Rancher cluster where each node has the same `instance_type` of `rke2` which from the kubecost/opencost logs is not known and so pricing falls back to defaults. Specifying custom default prices exhibits the same unexpected behavior. Hourly costs reflect the expect cost values based on the custom pricing only when there is no gpu on the node. When the gpu is present the values are divided by a significant factor that seems related to the sum of the three prices.

Our guess is kubecost/opencost is doing something like summing the resource costs into a single machine cost but then unnecessarily dividing each cost by that total.

**To Reproduce**
See the kubecost issue https://github.com/kubecost/cost-analyzer-helm-chart/issues/2418 but install opencost instead of kubecost.

**Expected behavior**
GPU nodes should have hourly costs that match the specified prices.

**Screenshots**
E.g. from grafana, three nodes without gpu and one node with gpu, all using fallback default prices
<img width="1311" alt="image" src="https://github.com/opencost/opencost/assets/95671557/5fbcf442-3adc-4aa8-9658-db86d85a890a">

**Which version of OpenCost are you using?**
1.105.0-rc.6 (b7736a7)

**Additional context**
Cluster is a Suse Rancher RKE2 cluster running on AWS EC2. GPU node in this instance is a `g4dn.xlarge` with one Nvidia Tesla T4 GPU.

**Comment by rossfisherkc** [comment]
Relevant support case
#4545

**Comment by mattray** [comment]
It looks like Kubecost Support is tracking this.

**Comment by dwbrown2** [comment]
@rossfisherkc @mattray any updates on this issue?

**Comment by jcharcalla** [comment]
Looks like this may have been overlooked, @kwombach12 has added jira BURNDOWN-222 to track.

**Comment by pawel-lmcb** [comment]
@dwbrown2 thanks for the bump, I'm just curious if any ETA can be provided on this? 🙏

**Comment by cliffcolvin** [comment]
@pawel-lmcb for follow up we are currently working on this. I'll let you know asap with targeted release.

**Comment by pawel-lmcb** [comment]
Hi @cliffcolvin just wanted to know if you can share any ETA on the target release for this?

Thank you!
Pawel

**Comment by kwombach12** [comment]
@pawel-lmcb We are actively working on a fix right now! You should expect to see this resolved in the next published version of Kubecost. cc: @cliffcolvin

**Comment by pawel-lmcb** [comment]
Hello, I saw that there was a release recently but didn't see this fixed. Just wanted to bump this for more info!

**Comment by kwombach12** [comment]
@pawel-lmcb sorry I should have been more clear. The fix here is still in progress and will be published in our next minor release - 1.107. We expect 1.107 to be published on Nov 1st.

**Comment by pawel-lmcb** [comment]
@kwombach12 thanks for the update appreciate it!

**Comment by pawel-lmcb** [comment]
Hi @kwombach12 congrats on the v1.107 release, I wanted to follow up whether this issue was resolved and merged into that release or not since I didn't see it referenced. Thank you!

**Comment by kwombach12** [comment]
Hey @pawel-lmcb we tried hard to implement this in 1.107, but found this to be a heavier than expected lift. @cliffcolvin can share more details on the challenges

**Comment by pawel-lmcb** [comment]
@kwombach12 thanks for the quick response @cliffcolvin please let us know what you've discovered, and what we could help with in order to bring this over to the finish line.
