### ISSUE TITLE
Allow Thanos `auto` Downsampling

### ISSUE THREAD

**Issue by sherifkayad** [opencost/opencost#2041]
**Is your feature request related to a problem? Please describe.**
As per https://github.com/opencost/opencost/blob/develop/pkg/env/costmodelenv.go#L400 the following resolutions seem to be supported and given to Thanos:
- `0s`
- `5m`
- `1h`
- `raw` => corresponding to `0s`

I believe a value `auto` should be supported as well and given to Thanos like that .. This is very convenient in cases where people maintain custom resolutions for certain retentions .. e.g.:
```
- --retention.resolution-raw=14d
- --retention.resolution-5m=30d
- --retention.resolution-1h=3y
```

**Describe the solution you'd like**
Allowing `auto` to be passed through as a possible value further down the line to Thanos.

**Describe alternatives you've considered**
N.A.

**Additional context**
Refer to https://thanos.io/tip/components/query.md/#auto-downsampling

**Comment by mattray** [comment]
I'm not sure OpenCost is utilizing this feature, given Thanos is supported by Kubecost and not currently supported by OpenCost. We'd welcome fleshing out the Thanos support in OpenCost for sure.

**Comment by sherifkayad** [comment]
That would be great! .. Just out of curiosity: so far seems like OpenCost is using the KubeCost backend (Cost Model) .. would there be a plan to have an own image at some point of time soon and drift away from the KubeCost backend image? .. Also is there a link to the roadmap or so of OpenCost that one can see?
