### ISSUE TITLE
[OpenCost UI] Using the /model/allocation/view API instead of the /model/allocation/compute

### ISSUE THREAD

**Issue by sherifkayad** [opencost/opencost#2042]
**Is your feature request related to a problem? Please describe.**
Currently the performance of the OpenCost UI is sub-optimal. Every time a query is calculated from scratch without using the feature of the model / backend to use the cached results in the filesystem DB. These cached results are available under `/view` instead of `/compute`.

Would be really great if the UI is using the cached results instead of calculating every time.

**Describe the solution you'd like**
Would be really great if the UI is using the cached results instead of calculating every time. That will return immediate results in the UI.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by AjayTripathy** [comment]
Caching is a bit beyond the scope of the opencost project; instead we suggest you use kubecost community edition which has caching layers or export the data and serve it yourself-- we provide the ability to export in many different formats.
