### ISSUE TITLE
Support Reserved Instance pricing for Azure

### ISSUE THREAD

**Issue by graemechristie** [opencost/opencost#2043]
Can reserved instance pricing be implemented for Azure ?

Almost all of our AKS clusters run on reserved instances in Azure. Currently the pricing returned from Opencost is about %60 higher than the real cost we are paying and does not reflect reality in any meaningful way.

@AjayTripathy indicated this was done an in beta in [this issue](https://github.com/opencost/opencost/issues/500)

However it appears not be the case looking at [this code](https://github.com/opencost/opencost/blob/eadd55d5fcee528547492df4baf29497dc019470/pkg/cloud/azure/provider.go#L1561)

Any information on when or if this is likely to be implemented would be greatly appreciated.

**Comment by AjayTripathy** [comment]
Hi @graemechristie currently only kubecost supports RI pricing and cloud integrations in general; we suggest the community edition of kubecost available at https://github.com/kubecost/cost-analyzer-helm-chart. We expect to have more details on how to support RIs on azure with opencost in the coming months.

**Comment by kaitimmer** [comment]
@AjayTripathy Are there any updates on this? I would still be interested in RIs on Azure with Opencost.

**Comment by mattray** [comment]
@kaitimmer have you configured customer-specific pricing? https://www.opencost.io/docs/configuration/azure#customer-specific-pricing

If that's not sufficient we'd need to do reconciliation of the CUR with the recorded results in Prometheus, which isn't currently available.

**Comment by AjayTripathy** [comment]
That being said, we'd take a PR on supporting RI estimates on Opencost, if the customer specific pricing isn't sufficient.

**Comment by rajibhossen** [comment]
Is there any update on supporting RI price on OpenCost?
