### ISSUE TITLE
Cluster label could be overriden

### ISSUE THREAD

**Issue by hakuno** [opencost/opencost#2052]
**Is your feature request related to a problem? Please describe.**
It can be a problem. For instance, I've already set `cluster` label. But, the OpenCost uses `cluster_id`. It's not a standard.

**Describe the solution you'd like**
It shall support custom label name. Look,

```
helm...
--set opencost.exporter.overrideClusterIdLabel=cluster
--set opencost.exporter.defaultClusterId=my_cluster
```

:-1: So `cluster_id` label doesn't need to be a **hardcoded** thing.
:+1: We can override `cluster_id` label if desired. Be sure many people will deploy OpenCost easier with it.

Maybe it's too hardcoded on there..? Let me know.

**Describe alternatives you've considered**
I could add one more label to my metrics on Prometheus' `external_labels`.

**Additional context**
OpenCost will be deployed on running environments. So we cannot repeat or add a metric label to satisfy it.

**Comment by hakuno** [comment]
I saw the KubeCost has something related to it
> In order to distinguish between multiple clusters, Kubecost needs to know the label used in prometheus to identify the name. Use the `.Values.kubecostModel.promClusterIDLabel`. The default cluster label is `cluster_id`, though many environments use the key of `cluster`.

[ref](https://github.com/kubecost/docs/blob/main/custom-prom.md#distinguishing-clusters)

**Comment by mattray** [comment]
@Pokom you deploy a number of clusters and use cluster_id extensively right? Could you weigh in on if this is an issue we need to fix in code or documentation?

**Comment by Pokom** [comment]
@mattray I haven't had an opportunity to migrate away from using `prom_label_proxy` just yet. Once I do that I can weigh in on this issue and let you know if there's any problems

**Comment by hakuno** [comment]
@Pokom I've seen the `prom_label_proxy` just enforces an existing label at query. Or does that support to add a label in query result without enforcement?

Ps. I guess this `prom_label_proxy` purpose is just for multitenancy support as explained [at here](https://grafana.com/blog/2023/02/02/how-grafana-labs-uses-and-contributes-to-opencost-the-open-source-project-for-real-time-cost-monitoring-in-kubernetes/).

**Comment by Pokom** [comment]
> @Pokom I've seen the `prom_label_proxy` just enforces an existing label at query. Or does that support to add a label in query result without enforcement?

We use `prom_label_proxy` specifically to add the `cluster_id` to all outbound queries. Not sure I'm following the enforcement bit, that's not how I understand `prom_label_proxy` but this is the only use case I've had for it :)

The blog post you linked is pretty clear on why we use `prom-label-proxy`:

```
We deployed [prom-label-proxy](https://github.com/prometheus-community/prom-label-proxy) for filtering and subsetting, showing each OpenCost instance only the data it expects to see
```

I'd like to try and upgrade our dev opencost instances to drop using `prom-label-proxy` in favor of using the built in mechanism now that's available. I don't know when I'll have the time to. 

For now though, here's a sample configuration of our deployment for prom-label-proxy:

```
prom-label-proxy:
    Image:      quay.io/prometheuscommunity/prom-label-proxy:master@sha256:3d055b873827f95230d5babb9de48ad32b9a77e5e1a017eebe7eb898128194a9
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      -insecure-listen-address=0.0.0.0:8080
      -label=cluster
      -label-value=dev-us-east-0
      -upstream=https://${UPSTREAM_PROMETHEUS_URL}/api/prom
```

The `-label-value` flag will ensure `cluster=dev-us-east-0` is added to all queries.

**Comment by hakuno** [comment]
@Pokom Thank you for that. Now I see it can help a lot!

But I don't know which mechanism you're talking about:
> in favor of using the built in mechanism now that's available

What's built in feature is there?

**Comment by hakuno** [comment]
https://victoriametrics.com/blog/monitoring-kubernetes-costs-with-opencost-and-victoriametrics/
