### ISSUE TITLE
Track bigquery jobs for billing purpose

### ISSUE THREAD

**Issue by octavd** [opencost/opencost#2057]
Hello,

Could you please tell me that if sing opencost, can i track for billing purposes bigquery jobs in a gke cluster where i have jupyter notebooks where users can submit those jobs from a pod?

**Comment by mattray** [comment]
OpenCost does not currently have that functionality. We have an initiative called External Asset Costs to bring out-of-cluster resources into OpenCost and associate them with your Kubernetes deployments, but it is under development and will not cover every integration initially.

**Comment by mattray** [comment]
I've closed this as a `question`, but if you want to work on it in the future we can reopen it as an Issue.

**Comment by octavd** [comment]
Hey @mattray,
Thank you for your response.
Hmm, do you have any more information about that initiative? i've searched on the branches or doc and couldn't find anything.

**Comment by mattray** [comment]
We've been discussing it in the [Community Meetings](https://bit.ly/opencost-calendar), @Pokom is working on it and we hope to have an initial release for object storage (S3, Blob Storage, etc.) as a reference example soon. We'll be sure to publicize it once we have something available.

**Comment by octavd** [comment]
Thank you!
