### ISSUE TITLE
ALB support

### ISSUE THREAD

**Issue by runningman84** [opencost/opencost#2065]
**Is your feature request related to a problem? Please describe.**
It would be great if ALB loadbalancer costs would also be calculated.

**Describe the solution you'd like**
Gather the information in the ingresses and look for class alb. Divide the costs through the number of services a given alb is used. E.g. most of the time there would be a single alb serving dozens of ingresses (up to 100).

**Describe alternatives you've considered**
There are no alternatives right now

**Additional context**
Add any other context, documentation links, or screenshots about the feature request here.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/

**Comment by mattray** [comment]
There should be a patchset landing soon that introduces External Asset Costs with object storage (S3, Blog Storage, etc.), which should provide an example of incorporating other cloud services into OpenCost (ie. ALB).
