### ISSUE TITLE
AWS spot instances with custom label are not detected

### ISSUE THREAD

**Issue by diegmonti** [opencost/opencost#2066]
**Describe the bug**
In OpenCost logs, I have encountered several errors similar to this one: `Error getting node pricing. Error: Invalid Pricing Key "eu-west-1,m6i.2xlarge,linux,"`. The missing key is related to a spot instance, and I believe it should be `eu-west-1,m6i.2xlarge,linux,preemptible`. The issue arises because our spot instances are identified by a custom label instead of `eks.amazonaws.com/capacityType`. The problem could be here: https://github.com/opencost/opencost/blob/c5fb20711662581e4dc8a5e46d5d69563d048088/pkg/cloud/aws/provider.go#L645

**To Reproduce**
1. Install OpenCost in an EKS cluster with spot instances identified by a custom label.
2. Check the logs for the mentioned error.

**Expected behavior**
The `SpotLabel` and `SpotLabelValue` configuration parameters should be honored.

**Screenshots**
None.

**Which version of OpenCost are you using?**
OpenCost 1.105.0

**Additional context**
OpenCost is installed on an EKS cluster (AWS) using Helm.

**Comment by mattray** [comment]
This looks like a potential bug, I'll raise it internally.

**Comment by lmello** [comment]
This was fixed in https://github.com/opencost/opencost/pull/2177

@mattray you can close this issue.
