### ISSUE TITLE
pod pvBytes is different from pv capacity

### ISSUE THREAD

**Issue by little-guy-lxr** [opencost/opencost#2079]
<img width="1200" alt="image" src="https://github.com/opencost/opencost/assets/26966109/e27505e6-4b34-47d1-9b4d-3a4c98305aa0">

pv info:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: pv1
  namespace: test-ns1
  resourceVersion: "313757"
  uid: 09914b4d-0fca-40be-b0f5-bb9b9fd87dfa
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sc-topolvm
  volumeMode: Filesystem
  volumeName: pvc-09914b4d-0fca-40be-b0f5-bb9b9fd87dfa
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
```

why  pv capacity is 5Gi but pvBytes is 4.617GiB

**Comment by mattray** [comment]
I don't really see a good reason for this discrepancy, I'll raise it for Kubecost reproduction.

**Comment by AjayTripathy** [comment]
Hi @little-guy-lxr we haven't been able to reproduce this. Can you share what view of the application you're seeing this on? Is it possible we're reporting the addressable space on the disk here? Some provisioners don't guarantee the total space you get is what is requested.
