### ISSUE TITLE
Method to determine if costs have been reconciled

### ISSUE THREAD

**Issue by ribeiroh** [opencost/opencost#2092]
**Is your feature request related to a problem? Please describe.**
When consuming allocation data via the API, there isn't a reliable method to determine if data points have already been reconciled with the CSP or not. As a comparison, there is a feature in the Kubecost UI that highlights whether or not costs have been already reconciled (although it isn't clear how reliable that functionality is either).

**Describe the solution you'd like**
A simple property in each data element in the return response like `reconciled: True` would be enough. Optionally, it would also be useful to be able to submit this as a query parameter. For example, to only fetch costs that have been reconciled.

**Describe alternatives you've considered**
- Fetch data with at least 48 hours of lag: although this should work for the happy path, it's not safe in situations when problems occurred to reconcile the data.
- Test for `*CostAdjustment` properties being different than 0: although true for most cases, there's likely a variety of scenarios where the adjustment for a reconciled cost might still be 0.

**Comment by mattray** [comment]
Currently OpenCost has no reconciliation, it only accesses the on-demand APIs available and does not process your actual bill. There have been discussions about Kubecost eventually open-sourcing reconciliation, they recently open-sourced billing access, but today there is no support.

**Comment by ribeiroh** [comment]
Hey @mattray, thanks for coming back to me. This was actually supposed to be a feature request for Kubecost, which I created here as per instructions from Kubecost folks on their [slack](https://kubecost.slack.com/archives/CE76NJE6S/p1691777845389869?thread_ts=1691731958.918689&cid=CE76NJE6S). I realise now that I didn't make myself clear anywhere on the ticket, my apologies.

Is this also the correct place for Kubecost feature requests? :) Thanks!

**Comment by mattray** [comment]
@ribeiroh Their public-facing GitHub for issues is here: https://github.com/kubecost/cost-analyzer-helm-chart/
