### ISSUE TITLE
Support headers in Prometheus connection

### ISSUE THREAD

**Issue by hbjydev** [opencost/opencost#2094]
https://github.com/opencost/opencost/blob/3186c1eee8de0826e44f0b13d00bf06f86db787e/pkg/prom/prom.go#L41

It would be useful to be able to set generic headers (like Mimir's `X-Scope-OrgID`) for Prom-compatible systems that have authentication without bearer tokens or basic auth. Makes it a non-starter for our internal uses currently.

**Comment by kwombach12** [comment]
Thanks @hbjydev. @cliffcolvin Can someone on the team take a look at this?

**Comment by mattray** [comment]
@Pokom how does Mimir handle this?

**Comment by Pokom** [comment]
@hbjydev can you provide a bit more information on what backend you're using and the specific problem you're having? https://github.com/opencost/opencost/pull/1928 was merged in recently that provides `X-Scope-OrgID` header, so we may be able to use that for your needs. It make not be well documented.

**Comment by hbjydev** [comment]
Oh, awesome, I didn't see that actually! I'll test it and might be able to close this issue :D
