### ISSUE TITLE
Cluster controller cannot be granted tolerations

### ISSUE THREAD

**Issue by headj-origami** [opencost/opencost#2095]
**Describe the bug**
The cluster-controller Deployment in the kubecost helm chart does not make use of tolerations set in the chart's values file. 
This leaves the resulting pods with no tolerations, and unable to be scheduled.

**To Reproduce**
1. Deploy the cost-analyzer helm chart with the following values:
`-n kubecost --set clusterController.enabled=true --set tolerations[0].key=someKey`
or
```
clusterController:
  enabled: true

tolerations:
  - key: someKey
```
3. Get the tolerations for the resulting Deployment:
`kubectl get deployment kubecost-cluster-controller -n kubecost -o json | jq .spec.template.spec.tolerations`

**Expected behavior**
The Deployment contains the `key: someKey` toleration.

**Screenshots**
N/A

**Which version of OpenCost are you using?**
Kubecost 1.105.1

**Additional context**
This is occurring on Amazon EKS on kubernetes v1.22, but I do not believe this is platform-specific.

The issue appears to be within the helm chart templates, as [the deployment in question](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/kubecost-cluster-controller-template.yaml) does not make use of the global (or any other) tolerations key from the values file.

**Comment by kwombach12** [comment]
@headj-origami Thanks for logging this. @cliffcolvin Can we have someone on the team look at this?

**Comment by mattray** [comment]
This is a Kubecost issue, I can't transfer it to https://github.com/kubecost/cost-analyzer-helm-chart/ but you should reopen it there and close this one.

**Comment by headj-origami** [comment]
Raised with kubecost
