### ISSUE TITLE
Allocation API return decreased starting time from window in parameter

### ISSUE THREAD

**Issue by seeeun-cho** [opencost/opencost#2096]
**Describe the bug**
Allocation API return decreased starting time from window in parameter

**To Reproduce**

Create a request for example against: /model/allocation?window=15m&aggregate=pod&includeAggregatedMetadata=true
Get Response, Check the "minutes" and "start" value which definition as: Precise starting time of the allocation. By definition must be within the window.
```
...
"window":{
"start":"2023-08-15T10:34:57Z",
"end":"2023-08-15T10:49:57Z"
},
"start":"2023-08-15T10:35:00Z",
"end":"2023-08-15T10:45:00Z",
"minutes":10,
...
```
regardless what parameter I put in, it's only return -5minutes result. e.g. 1h->55m
I can see the correct "minute" and "start" value in "__unmounted__" pod.

**Expected behavior**
I would expect a correct starting time & minutes of the allocation.

**Which version of OpenCost are you using?**
1.105.0 - wrong
quay.io/kubecost1/kubecost-cost-model:1.105.2 works
quay.io/kubecost1/kubecost-cost-model:latest not works

**Additional context**
we're using prometheus-operator as a BYO prometheus

**Comment by mattray** [comment]
Discussed in Slack, I'll raise it with Kubecost Engineering.

**Comment by seeeun-cho** [comment]
It has only latest version.

**Comment by mattray** [comment]
I can no longer recreate this with 1.107.1, I'm closing it.
