### ISSUE TITLE
Loading error message on cluster sizing recommendations page

### ISSUE THREAD

**Issue by gietschess** [opencost/opencost#2101]
**Describe the bug**
While opening the cluster sizing recommendations page (https://kubecost.xyz/cluster-sizing) we receive a loading error.

**To Reproduce**
1. Use the aws ec2 instance type 'c6in.2xlarge' as cluster node i guess
2. Go to 'savings'
3. Click on 'Right-size your cluster nodes'

**Expected behavior**
Show cluster sizing recommendations page

**Screenshots**
![error](https://github.com/opencost/opencost/assets/49275246/71352ce6-8d2b-4d93-8787-13cbef428d57)

**Which version of OpenCost are you using?**
v1.105.1

**Additional context**
In the cost-model logs i've found the following error message:
ERR savings: cluster sizing: failed to get monthly cluster rates: failed to find cluster node type 'c6in.2xlarge' in region 'eu-central-1': failed to find node in region 'eu-central-1' matching type name 'c6in.2xlarge'
WRN got error failed to get monthly cluster rates: failed to find cluster node type 'c6in.2xlarge' in region 'eu-central-1': failed to find node in region 'eu-central-1' matching type name 'c6in.2xlarge' for metric clusterSizing%%Production, not adding to cache

**Comment by kwombach12** [comment]
Hey @gietschess. We are aware of this issue and have a fix ready to go in our 1.106 release which should be published next week!

**Comment by gietschess** [comment]
Hi @kwombach12 , great to hear that. In this case feel free to close the issue.

**Comment by mattray** [comment]
This is a Kubecost issue that should be reopened in https://github.com/kubecost/cost-analyzer-helm-chart/. I'll close this issue shortly, or you can close it after reopening it over there.
