### ISSUE TITLE
Cost derived from Prometheus doesn't match UI Data

### ISSUE THREAD

**Issue by r2k1** [opencost/opencost#2110]
**Describe the bug**

I am unable to match the numbers displayed in the Opencost UI with those derived from Prometheus using the metrics provided by Opencost. I have a more complex query for other metrics producing mismatching results. But for simplicity I'll focus only CPU.  

**To Reproduce**

Open Opencost UI. Select "Yesterday" Date range. It sends next request:
http://localhost:9091/model/allocation/compute?window=yesterday&aggregate=namespace&step=1d&accumulate=false

Result: 
```
Total CPU: $15.29
```

Simple query (approximation):
```
sum(
      avg by (container, instance, namespace, pod) (container_cpu_allocation)
    * on (instance) group_left ()
      avg by (instance) (node_cpu_hourly_cost)
) * 24
```
Explanation: The given query returns the container's hourly cost based on the current second's consumption. Multiplying by 24 provides an extrapolation for a 24-hour timeframe. `avg by` purpose is to remove duplicates (sometimes happens when the opencost pod is recreated or scheduled on a different node) 

Result: 
```
9.886375925747867
```

Using a more accurate query with a 1-minute step:
```
sum(
      sum_over_time(
        (
            avg by (container, instance, namespace, pod) (container_cpu_allocation)
          * on (instance) group_left ()
            avg by (instance) (node_cpu_hourly_cost)
        )[1d:1m]
      )
    /
      scalar(count_over_time(vector(1)[1d:1m]))
)  * 24
```

Result:
```
9.689604374361824
```

Explanation: The term `sum_over_time((query)[1d:1m]) / scalar(count_over_time(vector(1)[1d:1m]))` is akin to `avg_over_time((query)[1d:1m])`, but it counts missing data points as zeros. Thus, it accounts for periods when a container is inactive. This can alternatively be expressed as `sum_over_time((query)[1d:1m]) / 24 / 60`.

**Expected behavior**

Total cost of all workloads using opencost UI and prometheus should roughly match.

**Screenshots**
![image](https://github.com/opencost/opencost/assets/2599261/22c51098-af52-4d7f-915f-f785f34855dd)

**Which version of OpenCost are you using?**
v1.105.0

**Additional context**
I have a test cluster with static workload. Pods are not changing and fluctuations in the CPU/RAM consumption are minimal. Most of the workload is just requesting resources without actually utilizing them.

**Comment by mattray** [comment]
I'll raise this with Kubecost Engineering for assistance.

**Comment by nikovacevic** [comment]
Hi @r2k1 thanks for your inquiry.

These are the queries we use to determine CPU cost for a container:
```
# CPU allocation per container
avg(avg_over_time(container_cpu_allocation{container!="", container!="POD", node!=""}[24h])) by (container, pod, namespace, node, %s)

# CPU pricing per node
avg(avg_over_time(node_cpu_hourly_cost{}[24h])) by (node, cluster_id, instance_type, provider_id)

# Pod running time
avg(kube_pod_container_status_running{}) by (pod, namespace, cluster_id)[24h:1m]
```
You should be able to reproduce the Kubecost figures by running these (perhaps for an individual container), matching the pod to the node, and then multiplying the results. (The last query is used to determine the amount of time the pod ran, so it is the timestamps you're interested in, not the values.) The units involved, respectively, are [CPU] * [$ / CPU-Hr] * [Hr] = [$].

**Comment by r2k1** [comment]
@nikovacevic thanks for the queries.

I looked into the numbers and found a problem with the kube-state-metric service. It couldn’t connect to the kube-api but still gave out old data from its cache.

Opencost uses data from both its own system and KSM. Because these data sources served different data (especially the `kube_pod_container_resource_requests`), it led to incorrect numbers in the Opencost UI.

The issue came from the Prometheus setup. But maybe Opencost could just use data from a single source to avoid similar issues.

**Comment by nikovacevic** [comment]
I see. That's unfortunate, but it's a good insight for others who might encounter something similar in the future. Glad you were able to sort it out.

For that particular measurement (i.e. pod time running) OpenCost should also consider directly measuring start and end times by listening for Kubernetes API events. That would be more accurate (not subject to Promethes scrape intervals or query resolutions) and would also protect against that particular issue, though it comes with its own risks and tradeoffs.
