### ISSUE TITLE
Include integration option for Cloud Carbon Footprint (CCF) estimates

### ISSUE THREAD

**Issue by 4upz** [opencost/opencost#2121]
### Is your feature request related to a problem? Please describe.
Currently, OpenCost provides valuable insights into Kubernetes usage data. It would be great to add support for showing the environmental impact of resources shown within OpenCost as well. Many organizations are increasingly concerned about their carbon footprint, and integrating this information directly into the OpenCost UI would provide a more comprehensive overview of their impact and energy usage. 

---

### Describe the solution you'd like
I propose adding the [Cloud Carbon Footprint](cloudcarbonfootprint.org) Tool (CCF) into the OpenCost project as an integration option. Users would have the option to link their CCF instance or API to their OpenCost instance. By leveraging the Kubernetes usage data already available in OpenCost, we could display additional columns in the OpenCost UI that show "Total Energy (kWh)" and "Estimated Co2e (t)" for each listed container/cluster. This would allow users to better understand both their cost and environmental impact in one interface.

---

### Describe alternatives you've considered
I noticed there was a related issue in opencost/opencost#3554 for integrating cloud provider carbon data using their native tools. This could be a nice multi-cloud option that utilizes a consistent methodology for estimating each cloud provider resource. We also support some of the same metrics that the cloud providers support such as Google's regional carbon intensity and CFE%.

---

### Additional context
@mattray Feel free to add additional context or ask any lingering questions from our previous conversations. Our team is willing to implement this if you're still willing to provide high-level support and point us in the right direction 🚀

**Comment by mattray** [comment]
We should be finding out if we have a CO2 talk accepted into KubeCon this week, I'll follow up with you :)

**Comment by 4upz** [comment]
@mattray Awesome, thanks! Feel free to keep me posted

Adding @camcash17 for visibility as well

**Comment by spalvarez** [comment]
I'm wondering what aggregation granularity would work best for an OpenCost integration, as different levels are supported in different APIs (though it can be changed)

/footprint gives the carbon cost estimates. It aggregates by:
- Cloud Provider
- Account
- Region
- Resource Type (i.e. EC2 vs RDS)
- Tags

/emissions gives the carbon emissions data.  It aggregates by:
- Cloud Provider
- Region

/recommendations are given by individual resource ID (i.e. ARN or similar)

Mostly thinking of /footprint, can we work with resource type granularity or should we also be able to return cost estimates by individual resource ID (i.e. ARN or similar)?

**Comment by mattray** [comment]
In today's call we realized that with the new Cloud Costs shipping in 1.108 we don't need to restrict ourselves to Kubernetes carbon costs, we have access to the complete CUR and billing data for the cloud providers. This means we could start integrating CCF's carbon billing data next to financial costs without delay. I'm researching what this looks like and what we'll need, but it's promising.

**Comment by mattray** [comment]
This was shipped in OpenCost 1.110.0 https://www.opencost.io/blog/carbon-costs
