### ISSUE TITLE
Incorrect Pod PVC cost computing

### ISSUE THREAD

**Issue by tshfc** [opencost/opencost#2129]
**Describe the bug**
When the PVC is used by multiple pods at different times, its cost calculation is incorrect.

**To Reproduce**
1. Time 1:00 create the pvc P and pod A, pod A bound the pvc P
2. Time 2:00 create pod B and bound the pvc P
3. Time 3:00 compute the cost at window 1:00-3:00 and aggregated by pod
4. See cost result

**Expected behavior**
The pvCost of pod A should be three times pod B. For example, if the cost of pvc P is $2 per hour: 
* The pvCost of pod A should be: 2 + 2/2 = 3
* The pvCost of pod B should be: 2/2 = 1

But in fact, the pvCost of pod B is 0.5.

**Additional context**
It seems that the `hrs` should be the duration of pvc rather than pod, because the `coef`  is already the coefficient of the pod over the entire pvc duration. 

```
			for _, alloc := range pod.Allocations {
				s, e := pod.Start, pod.End

				minutes := e.Sub(s).Minutes()
				hrs := minutes / 60.0

				gib := pvc.Bytes / 1024 / 1024 / 1024
				cost := pvc.Volume.CostPerGiBHour * gib * hrs
				byteHours := pvc.Bytes * hrs
				coef := getCoefficientFromComponents(coeffComponents)

				// Apply the size and cost of the pv to the allocation, each
				// weighted by count (i.e. the number of containers in the pod)
				// record the amount of total PVBytes Hours attributable to a given pv
				if alloc.PVs == nil {
					alloc.PVs = kubecost.PVAllocations{}
				}
				pvKey := kubecost.PVKey{
					Cluster: pvc.Volume.Cluster,
					Name:    pvc.Volume.Name,
				}

				// Both Cost and byteHours should be multiplied by the coef and divided by count
				// so that if all allocations with a given pv key are summed the result of those
				// would be equal to the values of the original pv
				count := float64(len(pod.Allocations))
				alloc.PVs[pvKey] = &kubecost.PVAllocation{
					ByteHours: byteHours * coef / count,
					Cost:      cost * coef / count,
				}
			}
```

Reference: [applyPVCsToPods](https://github.com/opencost/opencost/blob/v1.106.0-rc.13/pkg/costmodel/allocation_helpers.go#L2033-L2063)

**Comment by mattray** [comment]
I feel like this was an issue reported by a Kubecost customer, I'll bring it up with Support.

**Comment by tshfc** [comment]
@mattray Is there any progress?

**Comment by AjayTripathy** [comment]
Hi @tshfc we haven't been able to prioritize at the moment, but would welcome any community support on this.
