### ISSUE TITLE
Include OCI annotations in container images

### ISSUE THREAD

**Issue by MindTooth** [opencost/opencost#2132]
**Is your feature request related to a problem? Please describe.**
A follow up to https://github.com/opencost/opencost/issues/1910.

Please make sure that containers being built have the proper [OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) added:

This can be added by the [docker-metadata](https://github.com/docker/metadata-action) action if you guys are using that.

**Describe the solution you'd like**
Making sure that tags like these are added to the image:
```
  org.opencontainers.image.created=2023-07-08T19:52:41.761Z
  org.opencontainers.image.description=reveal.js on steroids! Get beautiful reveal.js presentations from any Markdown file
  org.opencontainers.image.licenses=MIT
  org.opencontainers.image.revision=3fed7dbe6a05715a22edc3a03869b869b49b824a
  org.opencontainers.image.source=https://github.com/webpro/reveal-md
  org.opencontainers.image.title=reveal-md
  org.opencontainers.image.url=https://github.com/webpro/reveal-md
  org.opencontainers.image.version=5.5.1
```

**Describe alternatives you've considered**
N/A.

**Additional context**
The reason for why I want for you to add these, is that e.g. [Renovate Bot ](https://github.com/apps/renovate) is able to lookup `org.opencontainers.image.source` for where to look for the changelog to be included in a pull request.

I've replicated the behavior I like to see using some custom rules for Renovate Bot:

- Without changelog: https://github.com/MindTooth/renovate-opencost-test/pull/1
- With changelog: https://github.com/MindTooth/renovate-opencost-test/pull/2

**Comment by mattray** [comment]
Thanks for bringing this up, I'll refer it to Kubecost Engineering unless a PR is provided.

**Comment by MindTooth** [comment]
I can of course submit a PR, but where do you want the changes?  Hard coded values in the `Dockerfile` or do you have a pipeline somewhere?

**Comment by mattray** [comment]
If you want to open it against the Dockerfile that'll work. I'll make sure it gets propagated accordingly.
