### ISSUE TITLE
Athena Catalog Configuration

### ISSUE THREAD

**Issue by a7i** [opencost/opencost#2140]
**Is your feature request related to a problem? Please describe.**
Athena configuration does not allow using a custom Catalog (only allows the default aws data catalog)

**Describe the solution you'd like**
We want to be able to specify our own custom catalog.

**Describe alternatives you've considered**
Dump the tables in the default catalog

**Additional context**
Add any other context, documentation links, or screenshots about the feature request here.

**Comment by mattray** [comment]
Thanks for the Issue (and PR)! I'll raise it with Kubecost Engineering because it looks like it's not an OpenCost issue directly.
