### ISSUE TITLE
Missing properties on some pods (labels, services, container)

### ISSUE THREAD

**Issue by nabadger** [opencost/opencost#2142]
**Describe the bug**

I am looking to export data using the allocations API.

In my case, I'm testing a query like so:
```
kubectl port-forward --namespace opencost service/opencost 9090
curl "localhost:9090/model/allocation?window=1d&aggregate=pod"
```

For most pods, i get back the correct info such as:

```
    "promtail-964s7": {
        "name": "promtail-964s7",
        "properties": {
          "cluster": "us-prod1",
          "node": "redacted",
          "container": "promtail",
          "controller": "promtail",
          "controllerKind": "daemonset",
          "namespace": "monitoring",
          "pod": "promtail-964s7",
          "services": [
            "promtail-metrics"
          ],
          "providerID": "i-02e82d6ae1be1f109",
          "labels": {
            "app_kubernetes_io_instance": "promtail",
            "app_kubernetes_io_managed_by": "jsonnet",
            "app_kubernetes_io_name": "promtail",
            "app_kubernetes_io_part_of": "promtail",
            "app_kubernetes_io_version": "2.7.0",
            ...

          },
```

For some workloads, the `labels`, `services` and `container` values are missing.

I end up with something like:
```
      "myapp-589c97887f-cnwgc": {
        "name": "myapp-589c97887f-cnwgc",
        "properties": {
          "cluster": "us-prod1",
          "node": "redacted",
          "controller": "myapp",
          "controllerKind": "deployment",
          "namespace": "myapp",
          "pod": "myapp-589c97887f-cnwgc",
          "providerID": "i-0976f0fe1e0222b57",
          "namespaceLabels": {
            "app_kubernetes_io_managed_by": "jsonnet",
            "argocd_argoproj_io_instance": "namespace-myapp",
            "elbv2_k8s_aws_pod_readiness_gate_inject": "enabled",
            "kubernetes_io_metadata_name": "myapp"
          }
        },
```

Also
1. This seems like it's specific to certain workloads, i.e. the labels for a workload (Deployment) are either there or they are not. But the odd thing is that we use a shared template to render most of our workloads (so they will be consistent in how they are configured in terms of labels/selectors/exported metrics etc).
2. I see entries in `kube_pod_labels` for the workloads with missing values (labels in this case). The pods generally have good uptime. One pod in particular with missing values was up for 7hrs~ . Other `kube_` metrics look good too.

**Expected behaviour**

I would expect to see the `labels`, `services` and `container` fields populated in the response.

If it's related to sidecars, then perhaps `container` would be a list of values?

**Screenshots**

**Which version of OpenCost are you using?**
v1.105.0

**Comment by nabadger** [comment]
I think I've spotted a commen theme, which is the `labels`, `services` and `container` properties are missing for all those workloads which have multiple containers (sidecars) running.

I can imagine this might make sense for `services` and `container` (although they could be lists?), but not sure why the labels would be missing too?

**Comment by nabadger** [comment]
Ah, it seems if i I aggregate by `pod,container`, I do get the labels and services.

Given that labels are at the pod level, should they not be available when aggregating only by pod?

**Comment by mattray** [comment]
I'm not sure what the right answer is, I'll see if I can get a response to see what causes this.

**Comment by mattray** [comment]
Here's the response I got:

"I think the reason when aggregating by pod, but not seeing labels/services/container properties is that there are conflicting values for each of those properties. This is most obvious if a pod has multiple containers. Then when you aggregate by pod it can't have a single "container" property ... and therefore drops the property altogether."

So we can leave it as a bug, but it may be "works as intended"
