### ISSUE TITLE
Opencost quick setup does not work

### ISSUE THREAD

**Issue by tamalsaha** [opencost/opencost#2144]
**Describe the bug**
I am using the quick setup instructions:
https://www.opencost.io/docs/installation/install

It was working last week. It is not working today. The opencost-ui pod is in crashloop.

```
running with BASE_URL=/model
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/09/01 14:19:18 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml

Needs a > 1024 port for opencost-ui.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which version of OpenCost are you using?**
This may be the Kubecost release.

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by dwbrown2** [comment]
@mattray @teevans @cliffcolvin aware of any recent changes here?

**Comment by dwbrown2** [comment]
@tamalsaha just to confirm are you using the following two commands?

```
helm install my-prometheus --repo https://prometheus-community.github.io/helm-charts prometheus \
  --namespace prometheus --create-namespace \
  --set prometheus-pushgateway.enabled=false \
  --set alertmanager.enabled=false \
  -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
```

```
kubectl apply --namespace opencost -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml
```

Can you all share how you are pulling that pod log?

**Comment by tamalsaha** [comment]
<img width="1104" alt="Screenshot 2023-09-01 at 9 10 35 AM" src="https://github.com/opencost/opencost/assets/94814/c2be4609-f00b-4603-982d-290b2758e265">

I am running it in a freshly created KIND 1.27.3 cluster.

**Comment by dwbrown2** [comment]
cc @thomasvn potentially related to recent root permission changes?

**Comment by thomasvn** [comment]
Thanks for the screenshots & logs @tamalsaha! Yes this error likely has to do with root permission changes in a recent PR https://github.com/opencost/opencost/pull/2130.

Without root permission, we're unable to bind to port 80. OpenCost's Nginx _should_ be [configured to bind to port 9090](https://github.com/opencost/opencost/blob/74e9101d24e365611a4c5d3057d2f35a5a79b6a0/ui/default.nginx.conf#L59-L60) though. According to your Nginx logs, we're loading confs from `/etc/nginx/conf.d/default.conf` when we should be loading the conf `/etc/nginx/conf.d/default.nginx.conf`

I believe it's due to the slight differences between these two Dockerfiles. One removes the `default.conf` while the other does not.
- https://github.com/opencost/opencost/blob/74e9101d24e365611a4c5d3057d2f35a5a79b6a0/ui/Dockerfile#L8-L12
- https://github.com/opencost/opencost/blob/74e9101d24e365611a4c5d3057d2f35a5a79b6a0/ui/Dockerfile.cross#L1-L6

**Comment by tkatrichenko** [comment]
I faced the same issue using `latest` tag for `opencost-ui` container. The container runs under uid 1001

If I use `quay.io/kubecost1/opencost-ui:1.106.0-rc.14` (tag from 30th of Aug) the container runs under root and it works.

@tamalsaha you can use `quay.io/kubecost1/opencost-ui:1.106.0-rc.14` image as a workaround till this fixed

**Comment by mattray** [comment]
I'm not seeing this with `1.106.0-rc.16`(`latest` when I tried to recreate) on amd64 on K3s v1.27.4. @tamalsaha is that kind amd64 or arm64? I'm trying to recreate.

**Comment by tamalsaha** [comment]
I am on Mac M1 (arm64) with latest Docker Desktop. I am using KIND to create 1.27.3 cluster (the default version).

**Comment by mattray** [comment]
Didn't recreate with `1.106.0-rc.16-arm64` following up in Slack

**Comment by tamalsaha** [comment]
I just tried. Still seeing this error.

<img width="1097" alt="Screenshot 2023-09-03 at 11 35 35 PM" src="https://github.com/opencost/opencost/assets/94814/dd14dfd2-2687-4d9f-99ef-c8c26386defb">

**Comment by AjayTripathy** [comment]
Hey Tamal! Maybe 1.106.0-rc.16-arm64 is different from what's in latest? can you explicitly try 1.106.0-rc.16-arm64 as mattray suggested?

**Comment by mattray** [comment]
I'm able to recreate this with kind and eks, but not k3s (which is what my home labs use). I'll escalate this to a P0 and we'll get a fix and an updated build for OpenCost made.

**Comment by tamalsaha** [comment]
Thanks @mattray ! I request that you also make it part of the GH CI checks to ensure the installer is not broken going forward.

**Comment by mattray** [comment]
@tamalsaha opened https://github.com/opencost/opencost/issues/2149

**Comment by dwbrown2** [comment]
@tamalsaha @tkatrichenko everything working ok for you at this point? Let us know if we can do more.

**Comment by tamalsaha** [comment]
I am waiting for the `quay.io/kubecost1/opencost-ui:1.106.1` to be released, so we know the problem is actually fixed.
