### ISSUE TITLE
OpenCost UI nginx should not run as root and should not run on a privileged port

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2150]
The OpenCost UI container currently runs nginx as root on port 80. As evidenced by the OpenCost UI failure https://github.com/opencost/opencost/issues/2144 (caused by https://github.com/opencost/opencost/pull/2130 with the revert https://github.com/opencost/opencost/pull/2148), we need a proper fix.

I would suggest that nginx listen on a non-privileged port (ie. 9090) and restore the user 1001 configuration removed in https://github.com/opencost/opencost/pull/2148. This probably means updating the [Dockerfile](https://github.com/opencost/opencost/blob/develop/ui/Dockerfile), [Dockerfile.cross](https://github.com/opencost/opencost/blob/develop/ui/Dockerfile.cross), [opencost.yaml](https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml), and the [Helm chart](github.com/opencost/opencost-helm-chart/).

**Comment by AjayTripathy** [comment]
I'm supportive of changing the port. Is that all we need to do?

**Comment by mattray** [comment]
I think so. Change the port and update all the places that refer to it (docs, Helm chart, opencost.yaml).

**Comment by roopesh83** [comment]
Unfortunately the opencost.yaml containing the deployment object for Opencost UI wasn't updated. It results in opencost-ui container going into crashloopbackoff

**Comment by mattray** [comment]
@roopesh83 https://github.com/opencost/opencost/pull/2163 will temporarily fix this
