### ISSUE TITLE
[Query] idle cost calculation

### ISSUE THREAD

**Issue by pallavi-khatri** [opencost/opencost#2153]
Hello,
i see a comment [here](https://github.com/opencost/opencost/blob/61bf489e01a425fcab2b5112c28c82a1c6e3e480/pkg/kubecost/allocation.go#L1922) in TODO, Just wanted to check if this is resolved already? and how accurate is idle cost calculation  for any aggregation that is used (e.g. Deployment, Label, Service, Team) ?

**Comment by mattray** [comment]
Idle costs are described in the OpenCost Specification: https://www.opencost.io/docs/specification#idle-costs

They're not explicitly broken out in the OpenCost UI or API, they're the difference between the cost of the allocated resources and the workloads consuming them. If someone wanted to update the UI to present this data or potentially add new API requests I don't think there would be any opposition.
