### ISSUE TITLE
Azure AKS inaccurate cost report

### ISSUE THREAD

**Issue by andre-adam-randoli** [opencost/opencost#2162]
**Describe the bug**
I'm reopening issue #2090, It looks like OpenCost is able to generate the correct cost as a metric but once requested by the backend, it returns a different value. On manual calculation based on the "node_total_hourly_cost" metric, the cluster I tested had a total of CAD 24.194625127 per day, Azure reports a total of CAD 24.25, but when using the OpenCost UI the value shown is CAD 13.85

**To Reproduce**
1. Go to OpenCost UI, select Yesterday as the Date range, get the total for the cluster
2. Go to Azure Cost Analysis service, select yesterday's date, and check the total
3. Compare values

**Expected behavior**
I expected the total cost shown in the UI to reflect the values in the metric endpoint.

**Which version of OpenCost are you using?**
1.105.2

**Additional context**
Running on Azure AKS, AKS managed node groups, Kubernetes version is v1.25.6.
No new nodes were added or removed in the last 20 days.

Please let me know any other information needed.

**Comment by mattray** [comment]
Is it possible you're seeing one of those as "yesterday" as in the last 24h and the other as data since yesterday? I'm just curious if you put in the same timedate range in the same timezone with absolute numbers instead of relative numbers. I'm not familiar with the Azure Cost Analysis tool, but could you look at something like 
http://localhost:9090/?window=2023-09-12T00%3A00%3A00Z%2C2023-09-13T23%3A59%3A59Z to ensure?

**Comment by andre-adam-randoli** [comment]
Is for sure about the same time period, tried with the absolute filter, same day start and end, in OpenCost and Azure, and still different values.

Prices reported with the filter for day 12
OpenCost: 14.03
Azure: 24.42

**Comment by mattray** [comment]
Thanks, I'll escalate for investigation.

**Comment by mattray** [comment]
What's the efficiency being reported in OpenCost? Is it 62%? Are we missing idle from the total so you're seeing the cost of allocated workloads but not the total cost of the nodes?

**Comment by andre-adam-randoli** [comment]
Apologies for the delay in responding, I checked the values for yesterday(2023-09-25), and here are the details:

http://localhost:9090/?window=2023-09-25T00%3A00%3A00Z%2C2023-09-25T23%3A59%3A59Z
Values reported by OpenCost:
CPU: $12.24
RAM: $2.03
PV: $0.13
Efficiency: 35.7%
Total Cost: $14.64

Azure reported cost: $24.25

24.25x0.357: $8.65725
24.25×0.643: $15.59275

Is there a way for me to check/add the idle column to the UI or maybe get it from the backend?

**Comment by veerendra2** [comment]
Not sure, it is related. I also find inaccurate cost calculation by Opencost, but I only looking into PVCs in a namespace for a test. 

From Azure portal, I calculated total PVCs which costs for a day(05.10.2023) €14.82
```
pvc-373b488d-3cf2-44b2-b5d2-xxxxxx-> 0.7
pvc-562a236e-9a10-4b7d-a2a4-xxxxxx -> 0.7
pvc-18a73d5f-8baa-44f1-a564-xxxxxx -> 0.7
pvc-a27b5abb-36f9-4ef3-bab2-xxxxxx -> 4.24
pvc-076c1421-bff1-4a8f-ba3d-xxxxxx -> 4.24
pvc-43a274cf-7d61-4475-90e7-xxxxxx -> 4.24
```

In the opencost, the PV cost for the namespace is reporting for a day(05.10.2023) €21.30

**Comment by AjayTripathy** [comment]
@veerendra2 that's unrelated but can you share regions and the storage classes of the persistent volumes?

**Comment by veerendra2** [comment]
@AjayTripathy The region is `Germany West Central` and the storage class used those PVs is
```
$ k describe storageclass managed-premium
Name:                  managed-premium
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           disk.csi.azure.com
Parameters:            cachingmode=ReadOnly,kind=Managed,storageaccounttype=Premium_LRS
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```

**Comment by AjayTripathy** [comment]
thanks @veerendra2 can you share the results of your "/model/metrics" metrics endpoint in kubecost?

**Comment by veerendra2** [comment]
@AjayTripathy Sorry for the delay, didn't see the comment. [here](https://drive.google.com/file/d/1cvKJOQyuha8iegi3B3e_fhaaYSVnsxx_/view?usp=sharing) is my opencost's "/model/metrics"

And please let know, shall I create new issue with my findings? or is this issues is enough for tracking?

**Comment by veerendra2** [comment]
In the above comments,I have only provided info for PVs.  The total cost for a day(selected custom date range) is showing inaccurately for me as well. 
In the Azure cost analysis:  €54.51
Opencost UI: €307.63

Note: I have added azure offer id by following [Configure OpenCost to use the Price Sheet API](https://www.opencost.io/docs/configuration/azure#configure-opencost-to-use-the-price-sheet-api). There is no change in total cost in Opencost UI before and after I add `AZURE_BILLING_ACCOUNT` and `AZURE_OFFER_ID`

**Comment by veerendra2** [comment]
Hello, Any updates on this issue?

**Comment by mattray** [comment]
I was working with the [kubectl cost](https://github.com/kubecost/kubectl-cost) command and it provides `__idle__` in its output for OpenCost and Kubecost returns this as well. I think it should be relatively straightforward to add this to the OpenCost UI, that would remedy at least part of the issue here. I'll take a look at adding it and if it's not in the 1.109 build I'll get a build you can test with.

**Comment by mattray** [comment]
I've added `__idle__` as a [PR to the API docs](https://github.com/opencost/opencost-website/pull/204) and I'll see about getting it into the OpenCost UI in another PR.

**Comment by mattray** [comment]
Here's the support in the OpenCost UI, pretty simple: https://github.com/opencost/opencost/pull/2557
