### ISSUE TITLE
csv export cost model: data query interval should be 1 day instead of 90 days

### ISSUE THREAD

**Issue by a7i** [opencost/opencost#2164]
**Describe the bug**
OpenCost docs mention that CSV Export includes previous day data ([ref](https://www.opencost.io/docs/integrations/csv-export)).  The query [here](https://github.com/opencost/opencost/blob/130415a82778da984581923ec108ad23f286609c/pkg/costmodel/allocation.go#L299), however, requests 90d of data which is not allowed by AWS Managed Prometheus (by default).

```
"Error updating CSV: querying oldest sample: Prometheus communication error: 422 (Unprocessable Entity) URL: 'http://127.0.0.1:8080/workspaces/<REDACTED>/api/v1/query?query=min_over_time%28timestamp%28group%28node_cpu_hourly_cost%7B%7D%29%29%5B90d%3A1h%5D%29&time=1694721310', Request Headers: 'map[]', Headers: '{ X-Amzn-Requestid: [ 3e1177f2-3706-43f0-8495-412bd0e219ac ], Content-Length: [ 152 ], Vary: [ Accept-Encoding ], Date: [ Thu, 14 Sep 2023 19:55:10 GMT, Thu, 14 Sep 2023 19:55:10 GMT ], Server: [ amazon ], Connection: [ keep-alive ], Content-Type: [ text/plain; charset=utf-8 ] }', Body: '{\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"expanding series: the query time range exceeds the limit (query length: 2160h5m0s, limit: 768h0m0s)\"}' Query: 'min_over_time(timestamp(group(node_cpu_hourly_cost{}))[90d:1h])'"}
```

**Expected behavior**
Only query 1 day of data

**Screenshots**

**Which version of OpenCost are you using?**
v105

**Additional context**
Kubernetes Version 1.26
AWS Managed Prometheus

**Comment by mattray** [comment]
Thanks for the issue and the PR! Commented on the PR with next steps.
