### ISSUE TITLE
Opencost not showing data >1 day when using Thanos as datasource - UI showing 404s

### ISSUE THREAD

**Issue by geolney** [opencost/opencost#2193]
Hello all, 
I've just deployed OpenCost to 5 of our clusters, 4 of which using Prometheus to help scrape metrics and 1 using a centralised Thanos which all Prometheus instances push to and aiming to use this latter one to view data on OpenCost UI. 

I'm getting 404 errors (screenshot below) half the time when querying for 1 day data (sometimes shows me what I want), but showing all the time when I increase this to >1 day. I have increased memory/cpu requests based on usage but the OpenCost container barely goes >60% of this at any time so I don't think it is getting OOM killed. 
Regarding the Thanos query pod that OpenCost references I have also increased resources and, again, never really exceeds 70% of these. Logs of the UI and OpenCost container do not really show anything about these 404 errors and so was wondering if there were any suggestions for this?

For reference, our Thanos S3 bucket has a 30 day retention policy on data and has ~6000 blocks and ~1.5TB data at any time. Furthermore I am seeing no restarts/OOM on any of my Thanos (compactor, storegateway and query) pods and am able to consistently query data on Grafana (same Thanos) using the scrape metric queries that are installed as part of OpenCost.

I understand this might not be 100% to do with OpenCost, but the fact that Grafana has little trouble leads me to believe that it could be on this side so just wanted to check if this definitely was the case. Happy to provide logs/screenshots/config whenever needed, thank you in advance!

<img width="1708" alt="Screenshot 2023-10-02 at 19 44 31" src="https://github.com/opencost/opencost/assets/75424289/8de2216f-d276-438f-8b7d-c7c03c87583b">

**Comment by mattray** [comment]
Thanks for opening the issue, I'm not sure what the cause is either since this isn't the standard installation. If someone with Thanos expertise could weigh in it would be appreciated.

**Comment by AjayTripathy** [comment]
These queries can get rather large, and I suspect they're just timing out. I suggest either pulling the data out of the opencost API in smaller increments or switching to the Kubecost community edition which is capable of aggregating and querying larger chunks of data.

**Comment by morawat** [comment]
@AjayTripathy  Is there a flag or configuration option available to increase the timeout for Thanos queries??

**Comment by AjayTripathy** [comment]
You'd need to look at it on the thanos side. https://github.com/thanos-io/thanos/blob/main/docs/components/query.md
