### ISSUE TITLE
Remove PROMETHEUS.md and replace with link

### ISSUE THREAD

**Issue by shelar1423** [opencost/opencost#2202]
**Describe the bug**
When clicking in the learn more hyper link in the readme.me it redirects to PROMETHEUS.md in which only the link is provided
![image](https://github.com/opencost/opencost/assets/82649533/6ad600de-4de4-40b9-9643-a6d9e39d830b)

Solution:
Removing PROMETHEUS.md and replace with the direct link :
https://www.opencost.io/docs/installation/prometheus

**Comment by shelar1423** [comment]
I would like to fix this issue,kindly assign me this.

**Comment by AjayTripathy** [comment]
Go for it @shelar1423 !
