### ISSUE TITLE
Expose OpenCost API and UI ports as configurable

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2223]
Right now the UI is hard-coded to port 9090 and the API to 9003

https://github.com/opencost/opencost/blob/develop/ui/default.nginx.conf#L38
https://github.com/opencost/opencost/blob/develop/ui/default.nginx.conf#L59

If these were configurable we could run multiple instances of OpenCost in different namespaces for testing differences.

**Comment by jessegoodier** [comment]
Edit: I see the PR, I don't see a risk there.
