### ISSUE TITLE
Building/running tests locally results in go dependency errors

### ISSUE THREAD

**Issue by anders-swanson** [opencost/opencost#2234]
**Describe the bug**
opencost build/test fails with go dependency errors; e.g.,

```bash
pkg/cloud/azure/pricesheetdownloader_test.go:11:2: missing go.sum entry for module providing package github.com/stretchr/testify/require (imported by github.com/opencost/opencost/pkg/cloud/azure); to add:
	go get -t github.com/opencost/opencost/pkg/cloud/azure
FAIL	github.com/opencost/opencost/pkg/cloud/azure [setup failed]
```

**To Reproduce**
1. Run `just build`
2. See dependency errors for missing go.sum entries. Running `go mod tidy` adds the missing go.sum entries, and `just build` works.

**Expected behavior**
`just build` works

**Screenshots**

**Which version of OpenCost are you using?**
tip of develop branch

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by mattray** [comment]
@anders-swanson Thanks for following up on our Slack conversation. I believe we're about to cut a new release for a Go vulnerability, so perhaps this is an opportunity to update this as well.

**Comment by mattray** [comment]
After testing this looks like it was corrected in https://github.com/opencost/opencost/commit/ef932c542d51474d1a4e3f98b7653954e17d4a3d or one of the other recent dependency updates.
