### ISSUE TITLE
How I can see the cost of loadbalancers and networking for AWS in Opencost UI?

### ISSUE THREAD

**Issue by asahnovskiy** [opencost/opencost#2244]
**Is your feature request related to a problem? Please describe.**
Is it possible to configure the opencost app to get costs for networking? 

**Additional context**
If yes. What needs to be done? Where I can get documentation?

**Comment by mattray** [comment]
Networking isn't supported yet and loadbalancers will be partially supported in a new feature about to launch (Cloud Costs).

**Comment by mattray** [comment]
Actually loadbalancers and networking are both in Cloud Costs, just not tied back to individual nodes yet.

**Comment by mattray** [comment]
https://www.opencost.io/blog/cloud-costs will be in the 1.108 release
