### ISSUE TITLE
no data in spot feed

### ISSUE THREAD

**Issue by gmarcot** [opencost/opencost#2253]
Good morning everyone, i use opencost in eks cluster  starting from 2 months; i have spend a lot of time to fix a problem related to spot instance cost; today i have changed the images to the latest 1.106 but the problem isn't fixed from my side.
Info:
opencost it's deployed via manifest
opencost image is: quay.io/kubecost1/kubecost-cost-model:1.106.4
prometheus doesn't  have enabled node-exporter (can i keep that disabled? )
spod datafeed is enabled and the data it's collected in the bucket
the iam role/service-account can read the data in the bucket
in the configmap there are a ref. for s3/account , i don't use the prefix and i have leave blank ( "" )
 athena is not configured, this is the cm:
{
        "provider": "aws",
        "description": "Default prices used to compute allocation between RAM and CPU. AWS pricing API data still used for total node cost.",
        "CPU": "0.031611",
        "spotCPU": "0.006655",
        "RAM": "0.004237",
        "GPU": "0.95",
        "spotRAM": "0.000892",
        "storage": "0.00005479452",
        "zoneNetworkEgress": "0.01",
        "regionNetworkEgress": "0.01",
        "internetNetworkEgress": "0.143",
        "spotLabel": "karpenter.sh/capacity-type",
        "spotLabelValue": "spot",
        "awsSpotDataRegion":"eu-west-2",
        "awsSpotDataBucket": "XXXXXXX-bucket-ew2-u-XXXXXXXXX-opencost",
        "awsSpotDataPrefix": "",
        "projectID": "XXXXXXX"
    }
The error is:
{"level":"warn","time":"2023-10-27T06:49:11.337613453Z","message":"Node i-012323ff71b9b2d96 marked preemptible but we have no data in spot feed"}
{
Can you give me some hints to fix the problem? i have checked and applied any suggestion from issue page or other consideration

**Comment by mattray** [comment]
The S3 bucket is being populated but your instance(s) aren't being looked up?

**Comment by gmarcot** [comment]
> The S3 bucket is being populated but your instance(s) aren't being looked up?

Hey Matt, yes:

the bucker it's populated; checked in one fine i can see the instance-id and the sir for the spot instance, example:

2023-10-31 06:02:19 UTC	EUW2-SpotUsage:c6i.xlarge	RunInstances:SV053	i-0fd6007cf808480ed	sir-v95ehvqn	0.2020000000 USD	0.0868000000 USD	0.0868000000 USD	1

the price calculation is the same declared in the spot request detail, but if i check in the opencost i doesn't found or the  instanceID or if i see the instanceID in the logs show "we have no data in spot feed"

**Comment by lmello** [comment]
Can you try to attach a debug kubernetes pod with AWS sdk to the opencost pod and try to list the bucket and get the spot feed files from s3 ? Might be permission related. Ensure the role being used by opencost have access to the spot bucket . Also check the spot bucket policy to confirm the access is allowed.

**Comment by mattray** [comment]
@gmarcot was it just the 1 instance or were some working and some weren't?
Maybe double-check your configuration vs. https://www.opencost.io/docs/configuration/aws#aws-spot-instance-data-feed-configuration if none are working?

**Comment by gmarcot** [comment]
Hey @mattray @lmello  ,

i have already test to create a pod with aws-cli image and use the same opencost account to list the file in the bucket, the role  attached to the SA it's ok:

k -n ns-util-XXXXXXX-opencost-exporter exec -it awscli -c awscli -- aws s3 ls XXXXXXX-bucket-ew2-u-XXXXXXX-opencost
.
.
2023-11-28 07:20:50        366 XXXXXXX.2023-11-28-03.001.588501cc.gz
2023-11-28 08:33:24        432 XXXXXXX.2023-11-28-03.002.08b20ce7.gz
2023-11-28 08:05:50        393 XXXXXXX.2023-11-28-04.001.4c70b179.gz

i have enable the debug logs  and restart the pod , now i use the new image version 1.107.1 , i waiting 1 hour before check if the spot data price it's calculated in opencost

**Comment by AjayTripathy** [comment]
It's possible that the node exists for a period of time but there isn't data in the spot data feed yet. Do you see this error for every node marked as spot always or is it transient? I would look for i-0fd6007cf808480ed in prometheus, querying for the metric node_total_hourly_cost over a few days to see if its changed.
