### ISSUE TITLE
Any Abbility to add list of the shared namespaces?

### ISSUE THREAD

**Issue by vovkanaz** [opencost/opencost#2254]
**Is your feature request related to a problem? Please describe.**
There is no ability to set shared namespaces 

**Describe the solution you'd like**
Provide an ability to set cluster shared namespaces to be able to have an ability to divide shared namespaces costs across all nonshared namespaces
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L1284

**Describe alternatives you've considered**
Kubecost https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L1284

**Additional context**
Thanks in advance

**Comment by mattray** [comment]
Thanks for opening an issue. So to clarify, you want the ability to have something that combines namespaces for reporting? Would querying over a shared tag work? I'm not sure I think I understand the usecase, just not how it would be implemented differently.

**Comment by vovkanaz** [comment]
@mattray Thanks, Well, actually main requirement is to have the ability to set a list of shared namespaces, and the total costs defined as shared namespaces should be equally redistributed among non-shared namespaces:
Shared namespaces dedicated costs  = (Total costs of  predefined shared namespaces e.g. (kube-cost, security, monitoring) / Non-shared namespaces count) 
and 
For example, Total costs for the namespace will be 

CPU + RAM + Network + PV + Shared namespaces dedicated costs = Total namespace costs

**Comment by mattray** [comment]
Looks like the yaml l got updated: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L1288
