### ISSUE TITLE
OpenCost without Kubernetes

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2268]
With the introduction of [Cloud Costs](https://www.opencost.io/docs/#integrating-cloud-costs-and-configuration) there are users who may want to use OpenCost without tracking Kubernetes usage.

Deploying to Kubernetes may still be a requirement, but working without Prometheus could be supported.

**Comment by dwbrown2** [comment]
I imagine this would be pretty easy to support now. Why not also support running OpenCost as a generic Docker container on EC2 and other places where the K8s API + Prom is not available?

**Comment by mattray** [comment]
I'm investigating this as part of Kubecost's internal hackathon.

**Comment by AjayTripathy** [comment]
@mattray let me know what you find and if you need any help modifying code to do this!

**Comment by mattray** [comment]
The configurable ports were merged in and I've updated https://github.com/opencost/opencost/pull/2317 to get this merged.
