### ISSUE TITLE
Should Microsoft Cloud Cost Service results get deduplicated?

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2275]
In the Cloud Cost Service results Microsoft results show up as both 
"Microsoft.Storage" and "microsoft.storage"
"Microsoft.Compute" and "microsoft.compute"
but apparently only "microsoft.network"?

<img width="2628" alt="Screenshot 2023-11-01 at 11 18 08 PM" src="https://github.com/opencost/opencost/assets/330023/f7e694b3-be4e-44cb-85cd-0022c40f5f38">

Other CSPs don't seem to exhibit this issue. I don't know if this is an issue for Kubecost.

**Comment by Sean-Holcomb** [comment]
That is just the value from the from the `consumedservice` column of the CSV, It is inconsistent because Azure is inconsistent with its exporting

**Comment by AjayTripathy** [comment]
Should we just ignore case on our side? Are there actually two columns in their cost explorer?

**Comment by Sean-Holcomb** [comment]
There are not too columns in the Cost Explorer.

We could normalize it. Easiest would be all lower case

**Comment by AjayTripathy** [comment]
Probably should just make it all lowercase then
