### ISSUE TITLE
Cloud Cost item details show the daily totals for all items

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2276]
Drilling down into "Items" in the Breakdown provides a list of all Items available, but clicking on an individual item has a details popup that is labeled with the individual item but has the daily totals for all items.

<img width="2672" alt="Screenshot 2023-11-01 at 11 24 39 PM" src="https://github.com/opencost/opencost/assets/330023/6e521c86-cb78-40f9-92f9-97a63c837867">

**Comment by dwbrown2** [comment]
@jjarrett21 know if this would be a quick fix? I'd call >= P1.
