### ISSUE TITLE
OpenCost UI currency selection does not persist across tabs

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2277]
If you select another currency from the drop-down (ie. "AUD") in the Cost Allocation tab and then change to Cloud Cost tab this selection is lost and it reverts back to "USD".

**Comment by rajat4984** [comment]
Is this issue still open? if yes can you give more details on which page is this issue occuring.

**Comment by mattray** [comment]
Yes, it's an issue with 1.108 and the Cloud Costs tab.
