### ISSUE TITLE
Cloud Cost UI goes blank with no cloud-integration.json as a secret

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2284]
If you click on the `Cloud Costs` tab in the UI and their is no secret with the cloud-integration.json, the page goes completely blank. No navigation, no header, just a white page. There's no error message in the logging either.

The expectation is that it should render the page with a message along the lines of "There are no Cloud Cost integrations currently configured." and hopefully there would be an error message in the opencost container logs that the request was made but there's no configuration available.

**Comment by dwbrown2** [comment]
@jjarrett21 were you planning to add a simple message here? I'd recommend we link to docs as part of this.

**Comment by jjarrett21** [comment]
@dwbrown2 yes, this as well as the drill down issue are on my radar to get resolved.
