### ISSUE TITLE
Cloud Cost UI not showing k8s utilization for EKS owned services including AmazonEC2

### ISSUE THREAD

**Issue by sossickd** [opencost/opencost#2285]
**Describe the bug**
Cloud Cost UI not showing k8s utilization for EKS owned services including AmazonEC2 for nodepools (Autosscaling groups)
Opencost on AKS shows k8s utilization for services such as Microsoft.Compute

**To Reproduce**
Open Opencost UI
Navigate to Cloud Costs / AWS
K8s Utilization only showing for AmazonEKS

**Expected behavior**
k8s utilization for EKS owned services including AmazonEC2 for nodepools (Autosscaling groups) should show in cloud cost UI

**Screenshots**
EKS
![image](https://github.com/opencost/opencost/assets/16937121/c38f226f-a0b7-49b6-b84a-cad5247ba090)

AKS
![image](https://github.com/opencost/opencost/assets/16937121/f5495cad-3bba-49be-9040-3d3dab443517)

**Which version of OpenCost are you using?**
Opencost: gcr.io/kubecost1/opencost:latest
UI: gcr.io/kubecost1/opencost-ui:latest
Helm chart version: opencost-1.26.0

**Additional context**
Public Clouds: EKS and AKS
EKS Server Version: v1.27.6-eks-f8587cb
AKS Server Version: v1.27.3

**Comment by Sean-Holcomb** [comment]
This might be an issue of particular labels not being enabled in your AWS CUR 
https://docs.kubecost.com/apis/apis-overview/cloud-cost-api/cloud-cost-metrics#aws
If these labels are not present then items from EC2 and other services cannot be identified as belonging to a Kubernetes cluster. This can be viewed in the Billing Dashboard in the AWS Console. Select "Cost allocation tags" on the side bar and search for these labels with the search bar to see if they are active or not.

**Comment by sossickd** [comment]
Thanks Sean after having a look at the link you added in your comment can you confirm exactly what the EC2 tag should look like? If i am reading it correctly should it be the below?

![image](https://github.com/opencost/opencost/assets/16937121/9151d7b3-52c6-4659-9b33-d14cc56db04e)

**Comment by sossickd** [comment]
Its ok i have you just found this AWS documentation, sorry billing is still new to me :)

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html

**Comment by sossickd** [comment]
@Sean-Holcomb  I still thing i am missing something here.

The process i took.

1. Manually added the tag below to a number of EC2 instances in the node pool for an EKS cluster.

![image](https://github.com/opencost/opencost/assets/16937121/b3598699-41fb-40c7-8672-e1e060b96016)

3. Activated this cost allocation tag in the MPA.
4. Waited 3 days and still no k8s utilisation for EC2 showing in the OpeCost UI

Am i missing something, is the tag correct?

**Comment by Sean-Holcomb** [comment]
So those are all automatic label, no need to add labels manually. What is shown in the documentation is how the labels appear in  the CUR as columns. The actual label is `eks:cluster-name`. When labels are added as columns to the CUR special characters including ':' and '-' are converted to '_'.  They also have a prefix appended to them, either "resource_tags_aws_" or "resource_tags_user_".

**Comment by sossickd** [comment]
@Sean-Holcomb thanks for clarifying i will make the eks:cluster-name cost allocation tag active and test.

**Comment by sossickd** [comment]
Tag aws:eks:cluster-name activated and now k8s utilisation is showing up for EC2 :) Happy for issue to be closed.
