### ISSUE TITLE
Unused metrics

### ISSUE THREAD

**Issue by r2k1** [opencost/opencost#2290]
OpenCost currently emits several metrics, some of which remain unused. Notably, a subset of these unused metrics are high-cardinality ones, particularly those related to containers and pods This leads to an unnecessary increase in resource consumption.

Metrics in Question
1. kube_pod_container_resource_limits
2. kube_pod_container_resource_limits_memory_bytes
3. kube_pod_container_resource_limits_cpu_cores
4. kube_pod_container_status_restarts_total
5. kube_node_status_condition
6. kube_deployment_status_replicas_available
7. kube_deployment_spec_replicas
8. kube_persistentvolume_status_phase

**Comment by mattray** [comment]
Thanks for taking the time to identify these. I'll escalate this to Kubecost Engineering to get them to verify this and hopefully we can clear these out.

**Comment by r2k1** [comment]
I can remove the metrics. But I need a confirmation it's ok to do.

**Comment by dwbrown2** [comment]
Interested to get input from others, but I know these are used by multiple downstream projects for cost monitoring. One idea would be to allow these to be disabled with a runtime flag?

**Comment by r2k1** [comment]
Another potential metric is `kube_pod_status_phase`. Currently it emits 5 metrics per pod (1 per potential pod phase). This metrics is used in a single `queryGPURequestsStr` query. And I think it doesn't have an effect and can be removed. 

https://github.com/opencost/opencost/blob/bdb6c5df38613d845998b7f5423885cb36ae2fa1/pkg/costmodel/costmodel.go#L207

**Comment by AjayTripathy** [comment]
Hey @r2k1 I'm supportive of making these optional behind a flag but on by default. How does that sound?

**Comment by r2k1** [comment]
I managed to disable the metrics by adjusting opencost deployment:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: kube-system
spec:
  # ...
  template:
    # ...
    spec:
      # ...
      containers:
        - # ...
          name: opencost
          env:
            # ...
            - name: CONFIG_PATH
              value: "/etc/config"
          volumeMounts:
            - name: opencost-config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: opencost-config-volume
          configMap:
            name: opencost
            items:
              - key: metrics.json
                path: metrics.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost
  namespace: kube-system
data:
  metrics.json: |
    {
      "disabledMetrics": [
        "kube_pod_container_resource_limits",
        "kube_pod_container_resource_limits_memory_bytes",
        "kube_pod_container_resource_limits_cpu_cores",
        "kube_pod_container_status_restarts_total",
        "kube_node_status_condition",
        "kube_deployment_status_replicas_available",
        "kube_deployment_spec_replicas",
        "kube_persistentvolume_status_phase"
      ]
    }
```

**Comment by r2k1** [comment]
What is the goal of the feature flag?

Technically it seems possible to disable the metrics with existing configuration (though it requires digging in the source code).

If the flag is disabled by default and poorly documented no-one is going to use it. I feel like these metrics should be disabled by default.

@AjayTripathy do you want the metrics being disabled or enabled by default? (From your comment I'm unsure if you're talking about metrics or flag)

**Comment by AjayTripathy** [comment]
Hey @r2k1 think you make a good point. Let's make the metrics disabled by default but support getting them back via enabling a flag.
