### ISSUE TITLE
OpenCost is not starting on AKS.

### ISSUE THREAD

**Issue by polinchw** [opencost/opencost#2294]
**Describe the bug**
After installing the Opencost helm chart the opencost container is not starting properly.  It is connecting to Prometheus. 

**To Reproduce**
1. helm install opencost .
2. shell into the opencost container
3. This is the last thing observed in the logs before the container is restarted:
2023-11-07T14:21:17.619321883Z INF No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found                                   │
│ 2023-11-07T14:21:17.622440981Z INF No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found                                     │
│ 2023-11-07T14:21:17.62407918Z INF Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US' 

**Expected behavior**
Opencost should start up properly.

**Screenshots**

**Which version of OpenCost are you using?**
1.106.4 - container
1.26.0 - helm chart

**Additional context**
Version of Kuberentes - AKS 1.26.6

**Comment by lostcities** [comment]
Could the liveness and readiness probes be assuming failure because Rate Card API call takes a while to complete?  To diagnose try disabling them.  If that's the cause, try a longer delay time -- we were having success with 180 seconds.

**Comment by polinchw** [comment]
> Could the liveness and readiness probes be assuming failure because Rate Card API call takes a while to complete? To diagnose try disabling them. If that's the cause, try a longer delay time -- we were having success with 180 seconds.

It's working!  Turning off the liveness and readiness probe worked!
