### ISSUE TITLE
Are there any plans to port OpenCost to other container orchestrators (e.g. Nomad)?

### ISSUE THREAD

**Issue by GBT55** [opencost/opencost#2298]
**Is your feature request related to a problem? Please describe.**
We are currently using Nomad from Hashicorp as our container orchestrator, and we need a solution to estimate costs on the platform. Opencost may be the best of them, but unfortunately it is not available for Nomad.

**Describe the solution you'd like**
We need to have a cost estimation/billing platform and we believe that opencost is the most suitable. We would like to know if there is any plan of developing this in a near future.
We would also like to know how hard it would be and if we can start thinking about contributing to the project and develop this idea ourselves.

**Comment by mattray** [comment]
Thanks for taking the time to ask. There are no current plans for Nomad, OpenCost is quite tied to Kubernetes and we haven't really seen demand. With the new Cloud Costs feature there's value in OpenCost for [cost monitoring without Kubernetes](https://github.com/opencost/opencost/issues/2268), but I think Nomad would be a heavy lift.

**Comment by dwbrown2** [comment]
Now that OpenCost supports general cloud cost monitoring IMO it should support the ability to run anywhere a container can run, including Nomad. My expectation is that getting OpenCost deployed there should not be a heavy lift. That said, I'm less familiar with what underlying infrastructure + resource usage APIs would be available. @AjayTripathy @GBT55 are you familiar with what data sources would be available?

**Comment by AjayTripathy** [comment]
I think it would be great for OpenCost to support something for Nomad and any / all container runtimes. There's a decent chunk of work to interface out the k8s APIs but its certainly not imposssible. I think a great place to start would be to drop some documentation / any libraries we'd want to use to contact Nomad APIs, as well as get a test run of opencost in a generic EKS environment.

**Comment by mattray** [comment]
I'm working on getting OpenCost working without Kubernetes, it'll only provide the cloud costs initially but it could be the starting point for adding something else.
https://github.com/opencost/opencost/issues/2268

**Comment by mattray** [comment]
Docker support merged in https://github.com/opencost/opencost/issues/2268
