### ISSUE TITLE
"kubecost" packages should be refactored to "opencost"

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2309]
A substantial amount of code was recently open-sourced by Kubecost without changing the packages. Given there's nothing related to Kubecost other than they provided the code, the code should probably be refactored to map to functionality.

**Comment by AjayTripathy** [comment]
+1, would greatly appreciate community support on this one. I don't think it's too hard.

**Comment by lmello** [comment]
@mattray can you provide a list of which codes should be migrated ? I can have a look at this

**Comment by lmello** [comment]
One thing to think about is how this could impact kubecost if they source those packages. It might require some work on their side also.

**Comment by mattray** [comment]
I'll bring it up with @cliffcolvin to see how disruptive this will be and when we should time it.

**Comment by mattray** [comment]
We're hoping to tackle this on the main `develop` branch right after 1.108 is released so we have plenty of time to deal with any downstream issues.

**Comment by mattray** [comment]
Based off my quick read-through of the `pkg/kubecost` without understanding their full usage, here's a proposed first pass at where to move everything.

* `pkg/allocation` <- `allocation*, mock.go, summaryallocation*, totals.go, totals_json.go`
* `pkg/asset` <- `asset*, cloudusage.go, diff_test.go`
* `pkg/cloudcost/` <- `cloudcost*, costmetric.go`
* `pkg/util/json/` <- `json.go`
* `pkg/util/labelconfig/` <- `config.go`
* `pkg/util/pair/` <- `common.go` (rename to `pair.go`)
* `pkg/util/query/` <- `query.go`
* `pkg/util/window/` <- `window.go, coverage.go`

These I don't know, someone will need to decide if/where they belong:

* `bingen.go`
* `kubecost_codecs.go` (generated by bingen)
* `status.go` ETLStatus? Does this belong in OpenCost?

@opencost/opencost-maintainers from Kubecost please weigh in so we can move these early in this release cycle and deal with required downstream updates

**Comment by mbolt35** [comment]
For the bingen specific generation, I'm pretty sure it uses the package name you target. ie: pkg/kubecost generates 'kubecost_codecs.go'

Bingen has a pretty soft requirement of keeping the models in the same package, so if we moved allocation, assets, etc to 'pkg/models' bingen would generate the 'models_codecs.go'

The bingen.go file should just go in the same package as the models. 

Also, just planting a flag here because it's somewhat relevant. Currently, bingen is also a closed source binary (this is why we're committing the codecs file). We should probably figure out a way to publish the binary for external consumption (or open source bingen).

**Comment by cocodee** [comment]
> For the bingen specific generation, I'm pretty sure it uses the package name you target. ie: pkg/kubecost generates 'kubecost_codecs.go'
> 
> Bingen has a pretty soft requirement of keeping the models in the same package, so if we moved allocation, assets, etc to 'pkg/models' bingen would generate the 'models_codecs.go'
> 
> The bingen.go file should just go in the same package as the models.
> 
> Also, just planting a flag here because it's somewhat relevant. Currently, bingen is also a closed source binary (this is why we're committing the codecs file). We should probably figure out a way to publish the binary for external consumption (or open source bingen).

What is the progress of open sourcing bingen? Or a comment should be placed in the source code to say that the bingen is closed source. I'm spending quite a lot of time searching for the bingen implementation project.
