### ISSUE TITLE
How are the two indicators node_ram_hourly_cost and node_cpu_hourly_cost calculated?

### ISSUE THREAD

**Issue by sishuiliunian** [opencost/opencost#2314]
Hello, I am very curious about how the two indicators node_ram_hourly_cost and node_cpu_hourly_cost are calculated? There is no official unit price for vcpu and memory in AWS. Can someone explain this to me?

**Comment by AjayTripathy** [comment]
Hi @sishuiliunian you can learn more about how opencost derives prices in our specification: https://www.opencost.io/docs/specification
