### ISSUE TITLE
Opencost logs/leaks API key

### ISSUE THREAD

**Issue by DD5HT** [opencost/opencost#2327]
**Describe the bug**
Opencost leaks the GCP Api key in its logs:

eg: 
`opencost 2023-11-22T12:09:54.861217097Z INF Fetch GCP Billing Data from URL: https://cloudbilling.googleapis.com/v1/services/XXXXXX/skus?key=CENSORED`

**To Reproduce**
Run opencost with GCP api key.

**Expected behavior**
No credential leak

**Which version of OpenCost are you using?**
`quay.io/kubecost1/kubecost-cost-model:prod-1.107.0-amd64@sha256:fc4b68f7c1d5d734c26ffffeff858100617fdc1a8c07827634cbfbce484d49f3`

**Additional Info**
Either remove: or censor the URL

https://github.com/opencost/opencost/blob/836fbfeb41d7cdaddc388e6e08a3e2e9e7f75836/pkg/cloud/gcp/provider.go#L988

**Comment by AjayTripathy** [comment]
Hi @DD5HT thanks for this report. We'll get the log statement removed.

**Comment by mattray** [comment]
Assigning to @cliffcolvin to verify it makes the next release

**Comment by AjayTripathy** [comment]
Just a quick review here and we should be good: https://github.com/opencost/opencost/pull/2345
