### ISSUE TITLE
Adding additional labels

### ISSUE THREAD

**Issue by omartheironman** [opencost/opencost#2336]
Is there a way for opencost to also add additional labels? if i annotated my pods with x-label, I'd like to group based on that label for the cost

**Comment by lmello** [comment]
The api support this. It collect all labels and you can group by them. Please see https://www.opencost.io/docs/integrations/api#a_aggregate

**Comment by lmello** [comment]
@mattray you can close this issue.

**Comment by mattray** [comment]
It would be nice to add it to the UI, but yes, it's in the API
