### ISSUE TITLE
Unable to fetch Enterprise agreement prices

### ISSUE THREAD

**Issue by MateCsorsz** [opencost/opencost#2351]
**Describe the bug**
Following the [offical documentation for MS Azure](https://www.opencost.io/docs/configuration/azure) I tried to configure access for an enterprise billing account.

**To Reproduce**
1. Create SPN with Read access for subscription
2. Provide "Enrollment Reader" role on the billing account
3. Add secret for SPN in k8s
4. Add the required helm values & deploy
6. Get the following error in logs:

```
 2023-11-27T09:54:04.358803883Z ERR Error downloading Azure price sheet: getting download URL: beginning pricesheet download: GET POST https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingPeriods/{billingPeriodName}/providers/Microsoft.Consumption/pricesheets/download
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: 401
--------------------------------------------------------------------------------
{
  "error": {
    "code": "401",
    "message": "No claims present for the caller in the system"
  }
}
```

**Expected behavior**
Price sheet gets downloaded and customer specific pricing is available

**Which version of OpenCost are you using?**
1.107.1

**Additional context**
We tried with an even more privileged SPN to access this API and still get the error.

**Comment by MateCsorsz** [comment]
Managed to find out the issue is with the role assignment on the billing account

**Comment by AjayTripathy** [comment]
@MateCsorsz anything we can get into docs that would have made this easier to troubleshoot?

**Comment by zlovcevic** [comment]
@AjayTripathy I've bumped into this issue in search for explanation on how to configure this for Microsoft Customer Agreement. There isn't a EnrollmentReader role on MCA as far as I know so it would be helpful to add some explanation regarding that in the official docs. Thanks
