### ISSUE TITLE
How Opencost calculates node's cost

### ISSUE THREAD

**Issue by r-erema** [opencost/opencost#2352]
I have a cluster which has a few nodes. Taking an example of the one of the node ip-10-0-1-155 which is AWS EC2 instance with spec t4g.medium, \$0.0384/h. That node had been working more than 7 hours which means it cost should be 7h * \$ 0.0384/h  ~= 0.2688\$. Kubecost calculated a cost of that node as \$0.13 which is twice less then expected
![Screenshot from 2023-11-30 18-45-00](https://github.com/opencost/opencost/assets/6449847/b23eba92-8a6c-4148-bff6-c3cc6924d725)

![Screenshot from 2023-11-30 18-48-34](https://github.com/opencost/opencost/assets/6449847/f52f235c-fde8-4d52-9114-a30b157b113f)

**Comment by AjayTripathy** [comment]
Hi @r-erema that cost is the sum of the costs of pods running on that particular node, meaning there is likely some idle capacity on the node.

**Comment by r-erema** [comment]
> Hi @r-erema that cost is the sum of the costs of pods running on that particular node, meaning there is likely some idle capacity on the node.

@AjayTripathy Thanks. Can Opencost provide the total costs of the nodes including idle capacity?

**Comment by AjayTripathy** [comment]
You can use the node_total_hourly_cost metric in prometheus, but if you are on EKS that is also available for free in the aws-optimized kubecost bundle https://aws.amazon.com/blogs/containers/aws-and-kubecost-collaborate-to-deliver-cost-monitoring-for-eks-customers/
