### ISSUE TITLE
AggregateCostModel aggregation cache - still used/needed?

### ISSUE THREAD

**Issue by burd0047** [opencost/opencost#2361]
**Describe the bug**
I notice that on startup, opencost warms and maintains a 1 day day cache. However, looking at the code, I believe the endpoints utilizing the cache have been deprecated.  

Looking to confirm my understanding, or if I am missing how the cache is being used. 

**To Reproduce**
Install open cost with the default helm chart

**Screenshots**
I can see in the opencost logs on startup `Init: AggregateCostModel cache warming enabled` and then every 5 minutes or so: `caching 1d cluster costs for 11m0s`

**Which version of OpenCost are you using?**
`1.107.0 (dbdf7c9)`

**Additional context**
Looking at the code base, `ComputeAggregateCostModel` serves the cache (on hit) and computes and serves the cache (on miss).  Its only called from `AggregateCostModelHandler`, which listens on `/aggregatedCostModel` api end point, which if my understanding is correct is deprecated.

**Comment by AjayTripathy** [comment]
Yes, these can be removed. Good find!
