### ISSUE TITLE
Rename OpenCost image

### ISSUE THREAD

**Issue by wybe-kopersf** [opencost/opencost#2368]
**Is your feature request related to a problem? Please describe.**
I want to pull the opencost image from a repository, but I don't see a clear opencost image anywhere. 

**Describe the solution you'd like**
I would like a downloadable images right from Github per release, similar to what KEDA (another CNCF project) has done [here](https://github.com/kedacore/keda/pkgs/container/keda). 

**Describe alternatives you've considered**
I could pull the image from here: https://quay.io/repository/kubecost1/kubecost-cost-model?tab=history
But I am unsure if the kubcost-cost-model image is build from the source code in the OpenCost repository. 

**Additional context**
Being able to pull the image directly saves me time, as I don't have to build the image myself then.

**Comment by mattray** [comment]
Thanks for opening this, that is the correct image, we really need to rename it. I'll add this to the list of things we need to clean up

**Comment by AjayTripathy** [comment]
@mattray can you open an issue to rename the binary in our build scripts?
