### ISSUE TITLE
Add a repo for community scripts contributions such as opencost-parquet-exporter

### ISSUE THREAD

**Issue by sntxrr** [opencost/opencost#2369]
It would be very useful for us to have a community contributed scripts repository to hold such things as a python based opencost-parquet-exporter

It might be a great solution to have an `opencost-scripts` repo that can have subfolders such as `python` etc. for people to submit PRs against

Since the `opencost` codebase is `golang` based, it doesn't make a lot of sense to have community scripts live in that codebase, so we discussed and decided at a community meeting to setup a new repo

See the community notes from November 30th, 2023 for any additional details: https://docs.google.com/document/d/1JFB_-sjF8F9UWet1c-dWixdMZY4hri23UlQG5FX5xfY/edit

**Comment by dwbrown2** [comment]
+1, @mattray thoughts on this?

**Comment by mattray** [comment]
It was discussed in last week's community meeting. We're going to do it, I'll set it up this week.

**Comment by mattray** [comment]
https://github.com/opencost/opencost-parquet-exporter has been created and @sntxrr and @lmello have been made Maintainers.
