### ISSUE TITLE
defaultClusterId doesn't work with central Victoria Metrics

### ISSUE THREAD

**Issue by abirsigron** [opencost/opencost#2380]
**Describe the bug**
We are running opencost on each of our eks clusters, but we have one central victoria metrics which store metrics from all clusters. 
For each opencost instance on each cluster:
1. We set defaultClusterId: 'cluster_name' (which add CLUSTER_ID env var in opencost pod)
2. We set promethues -> external -> url: http://vmselect.central.example/select/0/prometheus
When we query the opencost in specific cluster, we get cost values for all clusters instead of getting only cluster specific values.

**To Reproduce**
1. use central Victoria Metrics / other metrics manager for multiple clusters
2. Set defaultClusterId for each cluster opencost
3. query opencost and find it is looking on metrics for all clusters and not only his own.

**Expected behavior**
When setting defaultClusterId we expect opencost to calculate prices only for applications which runs on the same cluster.

**Which version of OpenCost are you using?**
1.106.3

**Additional context**
On every metric in our cluster we have these 2 additional labels:
cluster="cluster_name", cluster_id="cluster_name"

**Comment by mattray** [comment]
I believe you were following up in Slack, did you get clarification on getting this to work? Would definitely love docs to support it.

**Comment by abirsigron** [comment]
Hey @mattray 
Solutions that were suggested over slack wasn't relevant for our structure.
We are currently using central victoria metrics for all clusters and querying one central opencost instance to get cost data.

But for other cases, this doc could be usefull:
https://grafana.com/blog/2023/02/02/how-grafana-labs-uses-and-contributes-to-opencost-the-open-source-project-for-real-time-cost-monitoring-in-kubernetes/
