### ISSUE TITLE
Higher efficiency than expected

### ISSUE THREAD

**Issue by andre-adam-randoli** [opencost/opencost#2430]
**Describe the bug**
I'm running an internal calculation that's based on the efficiency of each namespace, and one of the namespaces is returning about 180.00000 of efficiency, this namespace was being used for testing by a developer, it had many evicted pods and restarts in each running pod, I was wondering if this is the correct calculation or a possible bug.

**To Reproduce**
1. Create pods with a memory resource limit and request of 100Mi;
2. The pods get killed by OOM constantly;
3. Eventually pod is evicted.

**Expected behavior**
An efficiency value under 100

**Which version of OpenCost are you using?**
quay.io/kubecost1/kubecost-cost-model:1.105.2@sha256:20dc48abbfaeaa7f27652851e7fb0f17250023b2f190925df754e3be08cf7802

**Additional context**
This is the raw payload of that namespace returned by OpenCost API.

```javascript
{
    "name": "namespace-name",
    "properties": {
        "cluster": "default-cluster",
        "controllerKind": "deployment",
        "namespace": "namespace-name"
    },
    "window": {
        "start": "2024-01-01T00:00:00Z",
        "end": "2024-01-01T23:59:59Z"
    },
    "start": "2024-01-01T00:00:00Z",
    "end": "2024-01-01T23:59:00Z",
    "minutes": 1439,
    "cpuCores": 0,
    "cpuCoreRequestAverage": 0,
    "cpuCoreUsageAverage": 0.00008,
    "cpuCoreHours": 0,
    "cpuCost": 0,
    "cpuCostAdjustment": 0,
    "cpuEfficiency": 0,
    "gpuCount": 0,
    "gpuHours": 0,
    "gpuCost": 0,
    "gpuCostAdjustment": 0,
    "networkTransferBytes": 5244610.90979,
    "networkReceiveBytes": 6748742.2295,
    "networkCost": 0,
    "networkCrossZoneCost": 0,
    "networkCrossRegionCost": 0,
    "networkInternetCost": 0,
    "networkCostAdjustment": 0,
    "loadBalancerCost": 0,
    "loadBalancerCostAdjustment": 0,
    "pvBytes": 0,
    "pvByteHours": 0,
    "pvCost": 0,
    "pvs": null,
    "pvCostAdjustment": 0,
    "ramBytes": 145736.76164,
    "ramByteRequestAverage": 145736.76164,
    "ramByteUsageAverage": 26811966.19331,
    "ramByteHours": 3495253.33333,
    "ramCost": 0.00001,
    "ramCostAdjustment": 0,
    "ramEfficiency": 183.97531,
    "externalCost": 0,
    "sharedCost": 0,
    "totalCost": 0.00001,
    "totalEfficiency": 183.97531,
    "lbAllocations": null
}
```

**Comment by AjayTripathy** [comment]
Hi @andre-adam-randoli efficiency is calculated simply as usage/requests -- so if you're using more than requested you would see efficiency > 1 which tracks with pods being evicted. What would you like to see here?

**Comment by andre-adam-randoli** [comment]
Hey @AjayTripathy, that makes sense, since a workload may use resources available that are not part of the request, I think there is no way to prevent this.
Does this impact the calculation for the cost of the workload?

**Comment by AjayTripathy** [comment]
No impact to the cost. Closnig for now!
