### ISSUE TITLE
UI does not work under a domain sub-path

### ISSUE THREAD

**Issue by charalamm** [opencost/opencost#2431]
Hi, thank you for this very useful tool!

**Describe the bug**

I am having issues with exposing the opencost UI under a sub-path of a domain name, like `domain.com/opencost`.
Currently I am trying to expose the UI behind an kubernetes nginx ingress but my issue is not related to helm or Kubernetes.

When connecting to the URL that is supposed to load the UI, there is a white page and in the console there is the error `index.9d46bb91.js:1  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. index.runtime.b478a79e.js:1  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

At the same time the port forwarded UI works fine and different services with a similar setup also work.

I see this is because of the way the UI is build though. Is that correct?
https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server

**To Reproduce**
1. Deploy the UI in a non-root path of a domain name

**Expected behavior**
See the UI

**Which version of OpenCost are you using?**
Should be the v1.108.0 (I am using the image `quay.io/kubecost1/opencost-ui`)

**Comment by mattray** [comment]
This is a valid issue, we're tracking it in https://github.com/opencost/opencost-ui/issues/6

Any PRs would great be appreciated and I'd test them out, I'm just not familiar with the solution myself.
