### ISSUE TITLE
Issue with storage between OpenCost and Prometheus

### ISSUE THREAD

**Issue by led94** [opencost/opencost#2448]
Hi! 

I am trying to setup opencost to monitor an AKS cluster, but I am facing an issue, the app fails cause my /data folder in prometheus is getting full after a few days. I have tried changing the size of the PVC, up to 80 GB, and it gets full after 8 days. 

I have added the --storage.tsdb.wal-compression flag and changed the sampling to 5m. The objective is to have at least a month of information to be able to analyze the data.

Any suggestions are appreciated, let me know for any extra information needed as I am not really sure how to address this issue. 

Thanks in advance.

**Comment by mattray** [comment]
How large is your cluster? 80 GB is a lot of data and Prometheus may have trouble keeping up with reports for a month. You may want to investigate pushing the data to another time series database.

**Comment by led94** [comment]
Jmmm, I think I'll need to dig more into Prometheus then, as I do not fully understand how it stores the data. Maybe a solution would be using the export to cvs option available then. I will look and revert here if I face any issues. 

Thanks!
