### ISSUE TITLE
Binary distributions are missing copies of licenses and copyright notices for dependencies included in the build

### ISSUE THREAD

**Issue by anders-swanson** [opencost/opencost#2457]
Binary distributions are missing copies of licenses and copyright notices for dependencies included in the build, including transitive dependencies. It'd be great if we could get a copy of these included in any artifacts (images, other binaries) that are released by this project.

**Comment by AjayTripathy** [comment]
Seems reasonable. @mattray this something you can add quickly? Should be just a weak to the docker file

**Comment by mattray** [comment]
It sounds like having an SBOM would cover this requirement. The Linux Foundation has the [SPDX format](https://spdx.dev/), I can look into getting that added to OpenCost. I'll try to get on this next week.

It would also help with some other requests from the CNCF.

**Comment by anders-swanson** [comment]
If possible, I recommend reproducing the license text and copyright information for each dependency. SPDX identifiers are great, but individual license text may differ between dependencies that share the same top level license.

**Comment by mattray** [comment]
Looking at the SPDX SBOM generated by GitHub, I see we currently have 588 dependencies with 15 different licenses, but all are CNCF-approved. I'm not sure how we'd ship every copy of the license listed by the dependencies. According to the SPDX docs, [copyright is outside their scope](https://spdx.dev/learn/handling-license-info/). 

The Free Software Foundation Europe has the [reuse tool](https://reuse.software) which supports adding copyright information to the SPDX file for the individual project. In my [testing with reuse](https://github.com/opencost/opencost/commit/9540c33ce455e4e5aed8b3ca932a3fc8486db563) I was able to add this to OpenCost, but it wasn't picked up by the GitHub SPDX SBOM export. We could add a feature request to get this support added, but it looks like this [isn't under active consideration](https://wiki.debian.org/Proposals/CopyrightFormat). 

I wouldn't object to generating an SPDX for OpenCost that included its Copyright notices, but I'm not sure how to best include dependencies.

I don't see any new dependencies in the code that was added in the Oracle Cloud support, was this unrelated to that? Perhaps headers could be added to those files? I don't think that's objectionable.
https://github.com/cncf/foundation/blob/main/copyright-notices.md#what-if-i-want-my-copyright-notice-included

Feel free to follow up with me via email (mattray@kubecost.com) if it's easier and we can hash this out over a call.

**Comment by anders-swanson** [comment]
I can provide an initial distribution of the license and copyright information for this project, though do not have time to actively update this material. 

I'll plan to place the attribution of license/copyrights in the root of the container, unless another path is preferred.

**Comment by mattray** [comment]
As we discussed in Slack, if you provide an initial implementation I would expect maintaining it could be made part of the standard release process.

**Comment by anders-swanson** [comment]
Closing this issue as the initial implementation of third party attributions has been merged 🎉
