### ISSUE TITLE
Adress family not supported by protocol

### ISSUE THREAD

**Issue by pg98gh** [opencost/opencost#2465]
getting following error from the opencost-ui container: [emerg] 1#1: socket() [::]:9096 failed (97: Address family not supported by protocol)nginx: [emerg] socket() [::]:9096 failed (97: Address family not supported by protocol) as there is no ipv6 support in the cloud or rather we only use ipv4. 
support is much appreciated

**Comment by mattray** [comment]
Are you using ipv6? We haven't really tested with it yet, but we'd be happy to merge any patches needed for support.

**Comment by pg98gh** [comment]
Hi @mattray ! 
no, we're using ipv4. is there any known workaround yet?

**Comment by mattray** [comment]
I've transferred it to https://github.com/opencost/opencost because I don't believe it has anything to do with the Helm chart.

Could you provide a bit of detail about your OpenCost and Kubernetes versions and how you installed it?

**Comment by pg98gh** [comment]
OpencostVersion: 1.28.2 
K8s: Client Version: v1.18.2-0-g52c56ce and Server Version: v1.25.13+vmware.1
Installation process: pulling opencost and opencost-ui image from quay.io and pushing it to our intern artifactory, followed by modifying resources like deployments, services, networkpolicys etc and values.yaml file for intern specifications and subsequently push via company intern pipeline on argocd-cluster (version 2.7.15). which supports only ipv4. Everything except deployment-> pod (container: opencost-ui) works as it throws above error message (in this container are no changes)

**Comment by mattray** [comment]
I assume that's the Helm chart version, but that's probably OpenCost 1.108.0.

Could you attach more logging for the opencost-ui? I don't have any current theories why it's not working, but maybe there's more context in the log.

**Comment by pg98gh** [comment]
Here's all the logging of the opencost-ui container :

running with BASE_URL=/model/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d//docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh10-listen-on-ipv6-by-default.sh: info: ipv6 not available/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh/docker-entrypoint.sh: Configuration complete; ready for start up2024/01/25 10:04:57 [emerg] 1#1: socket() [::]:9096 failed (97: Address family not supported by protocol)nginx: [emerg] socket() [::]:9096 failed (97: Address family not supported by protocol)

**Comment by mattray** [comment]
Searching on the nginx message returned that this because IPv6 is disabled on your Kubernetes node. The 2 easiest fixes are enabling IPv6 or replacing https://github.com/opencost/opencost/blob/develop/ui/default.nginx.conf.template#L62 with
```
listen ${UI_PORT};
```
I'm wondering if we actually have a lot of IPv6 usage or if the template could somehow be made IPv6 aware.

**Comment by pg98gh** [comment]
Hi @mattray - sorry for my long abstinence. However, i got some new info: 
As i still struggled with the ipv6/ipv4 setup,  i wrote a configmap containing only`listen 9096 ipv4;` and mounted it in the container. Subsequently, i got the error, that the default.nginx.conf.template is missing or not existing, so i copied your default.nginx.conf.template, modified it and pasted it into my configmap and mounted it again, too. Now this solved this error. 
Now, i got this error `running with BASE_URL=/modelsed: /var/www/*.js: No such file or directory`. 
Here is my deployment.yaml and ConfigMap.yaml. 

ConfigMap.yaml:

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-nginx-conf
data:
   setup-script.sh: |-
    #!/bin/sh
    chmod +x /var/www/*.js
  default.nginx.conf.template: |-
    gzip_static  on;
    gzip on;
    gzip_min_length 50000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types
    application/atom+xml
    application/geo+json
    application/javascript
    application/x-javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rdf+xml
    application/rss+xml
    application/vnd.ms-fontobject
    application/wasm
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/eot
    font/otf
    font/ttf
    image/bmp
    image/svg+xml
    text/cache-manifest
    text/calendar
    text/css
    text/javascript
    text/markdown
    text/plain
    text/xml
    text/x-component
    text/x-cross-domain-policy;  


    server {
        server_name _;
        root /var/www;
        index index.html;
        large_client_header_buffers 4 32k;
        add_header Cache-Control "must-revalidate";

        error_page 504 /custom_504.html;
        location = /custom_504.html {
            internal;
        }

        add_header Cache-Control "max-age=300";
        location / {
            root /var/www;
            index index.html index.htm;
            try_files $uri /index.html;
        }

        add_header ETag "1.96.0";
        listen 9096;
        resolver 127.0.0.1 valid=5s;
        location /healthz {
            access_log /dev/null;
            return 200 'OK';
        }
    }`

Deployment.yaml:

`spec:
      serviceAccountName: opencost
      containers:
        - name: opencost
          image: "...../kubecost1/kubecost-cost-model:prod-1.108.0"
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - containerPort: 9003
              name: http
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 300Mi
              memory: 500Mi
            requests:
              cpu: 10m
              ephemeral-storage: 300Mi
              memory: 55Mi
          env:
            - name: API_PORT
              value: "9003"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "<my-server>"
            - name: CLUSTER_ID
              value: "default-cluster"
            # If username, password or bearer_token are defined, pull from secrets
            - name: CONFIG_PATH
              value: "/tmp/custom-config"
            - name: DATA_RETENTION_DAILY_RESOLUTION_DAYS
              value: "15"
            - name: CLOUD_COST_ENABLED
              value: "false"
            - name: CLOUD_COST_MONTH_TO_DATE_INTERVAL
              value: "6"
            - name: CLOUD_COST_REFRESH_RATE_HOURS
              value: "6"
            - name: CLOUD_COST_QUERY_WINDOW_DAYS
              value: "7"
            - name: CLOUD_COST_RUN_WINDOW_DAYS
              value: "3"
            # Add any additional provided variables
          volumeMounts:
            - mountPath: /tmp/custom-config
              name: custom-configs
              readOnly: true
        - name: opencost-ui
          image: "..../kubecost1/opencost-ui:prod-1.108.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9096
              name: http-ui
          env:
            - name: API_PORT
              value: "9003"
            - name: UI_PORT
              value: "9096"
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 300Mi
              memory: 500Mi
            requests:
              cpu: 10m
              ephemeral-storage: 300Mi
              memory: 55Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config-nginx
            - mountPath: /var/www
              name: enable-permission
            - name: setup-nginx
              mountPath: /var/www
      volumes:
        - name: enable-permission
          emptyDir: {}
        - name: config-nginx
          configMap:
            #defaultMode: 0644
            name: opencost-nginx-conf
            items:
              - key: default.nginx.conf.template
                path: default.nginx.conf.templates
        - name: custom-configs
          configMap:
            name:  opencost-conf
        - name: setup-nginx
          configMap:
            name: opencost-nginx-conf
            items:
              - key: setup-script.sh
                path: setup-script.sh
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault`

INFO: when setting the mountpath to / in `volumeMount setup-nginx` getting following error:
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/vcap/data/kubelet/pods/6fde5b47-a900-4938-8d18-4fdc93bd89cc/volumes/kubernetes.io~configmap/config-nginx" to rootfs at "/etc/nginx/": mkdir /run/containerd/state/io.containerd.runtime.v2.task/k8s.io/opencost-ui/rootfs/etc: read-only file system: unknow
`

**Comment by pg98gh** [comment]
**Update**
to solve the initial error, i added following into my configmap: 
`data:
  ip4-config.conf: |
    upstream model {
    # Update to the cost model endpoint
    # Example: host.docker.internal:9003;
    server 0.0.0.0:9003;
    }

    server {
      listen 0.0.0.0:9090;
      server_name<your-server>;
   
      add_header Cache-Control "max-age=300";
      location / {
          root /var/www;
          index index.html index.htm;
      }
      location /model/ {
        proxy_connect_timeout       180;
        proxy_send_timeout          180;
        proxy_read_timeout          180;
        proxy_pass http://model/;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location /healthz {
        access_log /dev/null;
        return 200 'OK';
      } 
      
    }
    `
and mount it in my deployment. Additionally, due to the cluster setup, i hade to take care of some firewalls/networkpolicies.

**Comment by pg98gh** [comment]
Update
to solve the initial error, i added following into my configmap:
`data:
ip4-config.conf: |
upstream model {
 #Update to the cost model endpoint
 #Example: host.docker.internal:9003;
server 0.0.0.0:9003;
}

server {
  listen 0.0.0.0:9090;
  server_name<your-server>;

  add_header Cache-Control "max-age=300";
  location / {
      root /var/www;
      index index.html index.htm;
  }
  location /model/ {
    proxy_connect_timeout       180;
    proxy_send_timeout          180;
    proxy_read_timeout          180;
    proxy_pass http://model/;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header  X-Real-IP  $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location /healthz {
    access_log /dev/null;
    return 200 'OK';
  } 
  
}`

and mount it in my deployment. Additionally, due to the cluster setup, i hade to take care of some firewalls/networkpolicies.

**Comment by AjayTripathy** [comment]
@bstuder99 can we get this documented in some sort of support FAQ?

**Comment by brstuder** [comment]
Currently looking for the best place to publish this, I'm on it

**Comment by dwbrown2** [comment]
👍
Webb
Kubecost, Co-founder

**Comment by brstuder** [comment]
PR is up here: https://github.com/opencost/opencost-website/pull/213
I'm going to try and gather more content we can populate the doc with

**Comment by jamalsms** [comment]
Hey.
We tried to install opencost from helmchart by default values.yaml file and got the same error as above.
```
2024/07/24 09:13:26 [emerg] 1#1: socket() [::]:9090 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:9090 failed (97: Address family not supported by protocol)
```

There was no configmap, generated by default from the helm chart ( varsion 1.111.0 ). Should I add it manually?

It doesn't exist :
https://github.com/opencost/opencost/blob/develop/ui/default.nginx.conf.template

**Comment by pg98gh** [comment]
Hi @jamalsms ! Yes try to add the config map manually accordingly. This fixed mine

**Comment by jamalsms** [comment]
@pg98gh  Where do you mount this configmap? I mounted it in /etc/nginx and got:
/usr/local/bin/docker-entrypoint.sh: line 21: can't open /etc/nginx/conf.d/default.nginx.conf.template: no such file


```
          volumeMounts:
          - mountPath: /etc/nginx
            name: opencost-nginx-conf
      volumes:
      - name: opencost-nginx-conf
        configMap:
          name: opencost-nginx-conf
          items:
            - key: ip4-config.conf
              path: ip4-config.conf
```

**Comment by mattray** [comment]
That looks like this: https://www.opencost.io/docs/troubleshooting#address-family-not-supported-by-protocol-error-message

**Comment by neilfarmer** [comment]
Hey all, Ive also run into this issue. My environment also does not use IPV6 so im seeing the same error. Can the opencost helm chart support adding this config map as a feature? And/or can the opencost application support either IPV6 or IPV4?

If the fix is to add the config map to the the opencost container, I might as well use a manifest to deploy that and the rest of opencost.

Btw, this documentation (https://www.opencost.io/docs/troubleshooting#address-family-not-supported-by-protocol-error-message) is not up to date. After clicking the links on that page, I get Github 404s.

**Comment by flakemonster** [comment]
@neilfarmer , i'm facing same error, after googling a bit, it looks like opencost ui code moved to a separate repo

https://github.com/opencost/opencost-ui/blob/main/default.nginx.conf.template#L62
