### ISSUE TITLE
Proposal: Move the OpenCost UI into a separate repository

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2468]
The OpenCost UI releases are currently tied to releasing OpenCost. Separating them would allow independent releases, separate maintainers, and different build and testing frameworks. The UI accesses the OpenCost API, so they're not really tightly coupled by any means. Kubecost Engineering is not usually involved with the OpenCost UI, this would potentially open it up to more external contributors and a quicker release cadence.

**Comment by dwbrown2** [comment]
I've not really seen this done with other CNCF projects that have similar components, e.g. Prometheus. Are there examples that you feel the project should aim to follow?

**Comment by mattray** [comment]
Another point for splitting, we merged a CVE dependency fix for the UI that won't ship until we do an OpenCost release. Splitting them would allow independent releases.

**Comment by mattray** [comment]
Another benefit pointed out by @cliffcolvin would be we can have separate maintainers for the UI and the OpenCost cost model. It will reduce the number of issues for `opencost/opencost` and make working on the UI more accessible. The default installation would still use both containers, but we could release them independently as necessary.

**Comment by sntxrr** [comment]
I am very much pro split. Having these decoupled would be very helpful for onboarding different skill sets from the community

**Comment by brito-rafa** [comment]
I support the split.

**Comment by asdfgugus** [comment]
I support the split as well.

**Comment by cliffcolvin** [comment]
I think this is a pretty good move @dwbrown2. There are some benefits here and no change to end-user experience. The docker containers are already split and have been as long as I've been around and helm users will still deploy a combined helm package.
