### ISSUE TITLE
Opencost :: Cloud cost console blank

### ISSUE THREAD

**Issue by vishnu-anil** [opencost/opencost#2498]
**Describe the bug**
I have installed the latest version 1.108.0 build of cloudcost, followed all the steps and configured cloudcost. But for both AWS and Azure which I have tried gives me a blank page

![image](https://github.com/opencost/opencost/assets/34236239/3fef2b5d-c003-4bac-8a70-8defa080fed3)

**To Reproduce**
1. Go to 'OpencostUI'
2. Click on 'Cloud cost'
3. See error in console

**Expected behavior**
Cloud cost tab shows some UI atleast

**Which version of OpenCost are you using?**
1.108.0

**Additional context**
Additionally some steps on how to configure the Athena is missing in the Docs, I have created the required tables and colums and made sure the pod is running fine without errors. I checked the header status when reloading the console in the network tab of the browser which earlier used to show as connection failed now shows data missing. I dont know if that has anything to do with the UI though

```
{
    "code": 200,
    "data": [
        {
            "key": "1234356789/s3://dummybucket",
            "source": "multicloud",
            "provider": "AWS",
            "active": true,
            "valid": true,
            "lastRun": "2024-02-02T08:39:49.681329981Z",
            "nextRun": "2024-02-02T14:39:49.681329981Z",
            "RefreshRate": "6h0m0s",
            "created": "2024-02-02T08:39:24.109841601Z",
            "runs": 1,
            "coverage": "[2024-01-18T00:00:00+0000, 2024-02-03T00:00:00+0000)",
            "connectionStatus": "Data Missing",
            "config": {
                "bucket": "s3://dummybucket",
                "region": "ap-south-1",
                "database": "newdatabase",
                "catalog": "",
                "table": "opencost",
                "workgroup": "primary",
                "account": "123445678",
                "authorizer": {
                    "authorizerType": "AWSAccessKey",
                    "id": "DUMMY",
                    "secret": "REDACTED"
                }
            }
        }
    ]
}
```

**Comment by mattray** [comment]
I'm looking into this, I may be recreating it.

**Comment by mattray** [comment]
I'm not reproducing this with 1.108.0, could you double-check your version isn't set to `latest`? There may be some issues with that tag.

**Comment by vishnu-anil** [comment]
Ok so I had to follow some steps from kubecost to get the athena setup done and generate the cost report, and it appears now. thanks for looking into it
