### ISSUE TITLE
__unallocated__ metrics/ resources for Deployments

### ISSUE THREAD

**Issue by Faustinekitten** [opencost/opencost#2538]
**Describe the bug**
I deployed opencost through helm chart (1.29.1) on eks 1.28. 
When I check the UI I can see metrics for namespace, pod, container with out an issue. 
However, for Deployment, Service, Controller, Controller Kind I see a fraction of __unallocated__ metrics. It ranges between 2 to 40%. 
In the pod logs I see logs as described in this issue (https://github.com/opencost/opencost/issues/2344 & https://github.com/opencost/opencost/issues/2281) 

I use an existing prometheus instance and deployed a serivcemonitor to let prometheus scrape opencost metrics. Generally it works because I have the `container_cpu_allocation`and `container_memory_allocation_bytes` metric in prometheus. 

My value file:
```bash
opencost:
  metrics:
    serviceMonitor:
      enabled: true
  exporter:
    defaultClusterId: example-cluster-id
  prometheus:
    internal:
      namespaceName: monitoring
      serviceName: prometheus-operated
      port: 9090

```

**To Reproduce**
1. Go to WebUI
2. Click on Deployment/ Service/ Controller/ Controller Kind

**Expected behavior**
No __unallocated__ resources or metrics

**Screenshots**
![opencost-unallocated](https://github.com/opencost/opencost/assets/137997996/19b0b4eb-f332-4d0b-877e-c194a28e529a)

**Which version of OpenCost are you using?**
chart version 1.29.1 (app version 1.108.0)

**Additional context**
-

**Comment by Faustinekitten** [comment]
I just found out when I display Deployments as shown in the screenshot I see the 40.4% unallocated. When I manually edit the path and change `http://localhost:9090/allocation?agg=deployment&window=24h` to `http://localhost:9090/allocation?agg=daemonset&window=24h` and `http://localhost:9090/allocation?agg=statefulset&window=24h` it sums up to the 40.4%.

Meaning that the unallocated in the Deployment are sts and ds. The questions i why is it show in the Deployment overview
and
Why I can't choose statefulset and daemonset from the drop down menu?

<img width="842" alt="image" src="https://github.com/opencost/opencost/assets/137997996/cdb79af0-ec8f-414d-98c7-bd8e96c835d9">

**Comment by mattray** [comment]
@Faustinekitten Thanks for raising this. It looks like they're missing from the available choices and not listed in the API:
https://github.com/opencost/opencost/blob/develop/ui/src/Reports.js#L48
https://www.opencost.io/docs/integrations/api#a_aggregate

If my understanding of the Allocation code is correct, we should be able to add `statefulset`, `daemonset`, and `job` since those are all Kubernetes primitives we should have indexed.
https://github.com/opencost/opencost/blob/develop/core/pkg/opencost/allocationprops.go#L75

I'll submit a patch.

**Comment by mattray** [comment]
@Faustinekitten I've created https://github.com/opencost/opencost/pull/2542

If you replace your UI container with this one: https://github.com/users/mattray/packages/container/opencost-ui/180087766?tag=2538 you can test for yourself. That's built off of the `develop` branch with the submitted patch.

**Comment by Faustinekitten** [comment]
Thanks @mattray! The new image is working nicely and I can choose sts or ds to display them over the UI. 

However, I am still facing the issue that in the deployment the sum of sts, ds and jobs are represented as `__unallocated__` and vice versa when choosing e.g. daemonsets. 

Can I hide the __unallocated__ value somehow?


By graphics I am not able to tell what percentages are taken by daemonsets
<img width="1171" alt="image" src="https://github.com/opencost/opencost/assets/137997996/a9381e4f-eedc-469a-9c20-2a43f94d268e">

I have the same issue when running the `kubectl cost` command. 

```bash
+-------------------------------+-------------------+----------------------------------------------------+--------------------+-----------------+
| CLUSTER                       | NAMESPACE         | DEPLOYMENT                                         | MONTHLY RATE (ALL) | COST EFFICIENCY |
+-------------------------------+-------------------+----------------------------------------------------+--------------------+-----------------+
| example                       | 1                 | abcd                                               |         666.241984 |        0.265776 |
|                               | 2                 | __unallocated__                                    |          53.579393 |        0.120953 |
```

**Comment by mattray** [comment]
Have you used the `Controller Kind` or `Controller` views? That would filter everything to the Controller and only show `__unallocated__` for directly deployed pods.

**Comment by Faustinekitten** [comment]
`Controller kind` and `Controller` don't show me any `__unallocated__` metrics.

So is it by design that `__unallocated__` is part of the deployment, sts, ds view? 

<img width="1078" alt="image" src="https://github.com/opencost/opencost/assets/137997996/f1fce9d6-0610-4445-86e9-18366ad44d18">

**Comment by mattray** [comment]
Good catch, I bet there's another setting in `ControllerKind` I missed. I'll investigate.

**Comment by mattray** [comment]
OK, I've dug into this, and `__unallocated__` is essentially "NOT current aggregation". Unless you have directly deployed pods, if everything maps to an existing Controller Kind you won't have `__unallocated__` show up. 

If you refresh to the latest [mattray/opencost-ui:2358](https://github.com/users/mattray/packages/container/opencost-ui/182060257?tag=2538) container you'll see the new inclusion of `__idle__` in the UI so some of the controller views will only have `__unallocated__` and `__idle__` (in my case `Jobs`).

I guess we could look at replacing `__unallocated__` with `NOT $aggregate` in the UI, but that's more involved.
