### ISSUE TITLE
Public Cloud Cost Integration - Improve Documentation

### ISSUE THREAD

**Issue by squilaSC** [opencost/opencost#2565]
**Is your feature request related to a problem? Please describe.**
Referring to this https://www.opencost.io/docs/configuration/ and especially this documentation https://www.opencost.io/docs/configuration/aws
I looked at it a few hours and try to wrap my head around. Also tried to abstract from Kubecost documentation but I have no clear idea what to do to implement cloud costs (for an AWS enviornment).
I guess I understand what should happen somehow. But which, where, what steps. I feel pretty clueless with that documentation.

**Describe the solution you'd like**
A step by step/ more detailed documentation on how to setup cloud cost integration (for AWS).

**Describe alternatives you've considered**
I looked at Kubecost documentation and tried to abstract or find any other online documentation which showed how to setup.

**Additional context**
Cluster costs are no problem and I got these running fast. However, as said for AWS for me (probably not all others) there seem to be some keypoints missing in the documentation for fast and easy understanding.

**Comment by mattray** [comment]
@squilaSC I'm working on this and hope to have some refined docs out soon

**Comment by mattray** [comment]
https://github.com/mattray/opencost-website/tree/installation_refresh is my WIP, I'm hoping to submit a PR today or tomorrow. It steps through all the installation steps for each cloud provider, so they're all fairly similar.

1) Install Prometheus
2) Gather/configure your cloud provider settings and push them into config files for installation with Helm
3) Install with Helm

There are still call-outs to alternative Prometheus settings and other customizations, but each cloud provider will follow the same template at least.

**Comment by dwbrown2** [comment]
@mattray any docs changes related to this one available?
