### ISSUE TITLE
Azure multiple subscription connection

### ISSUE THREAD

**Issue by gpnikhil** [opencost/opencost#2577]
Hi Team,

we have multiple subscriptions and each subscription has 1 Azure Kubernetes running, in one of the subscriptions we have deployed the OpenCost, I can see the cost of only that cluster where its deployed, how can i add multiple clusters to the same OpenCost server?

**Comment by mattray** [comment]
This is not currently supported in OpenCost and I don't expect us to implement it with the current architecture.

It is possible to forward your Prometheus data to a centralized database like Thanos, Victoria Metrics, Cortex, or Mimir and use Grafana to visualize it, but it's not documented in OpenCost. We'd love documentation PRs.
