### ISSUE TITLE
Multi Cluster observability

### ISSUE THREAD

**Issue by OliverChmelicky** [opencost/opencost#2638]
**Multi Cluster feature request**
Would there be a way in the future how to monitor costs in multiple GCP GKE clusters?
Theoretically would it be possible to monitor multiple clusters from multiple Cloud Providers?

**Final solution**
See in one Opencost view costs pivoted per Cluster, per Project or per Cloud provider if possible.

**Alternatives**
An alternative would be to configure Prometheus to collect metrics from different clusters in the same project or multiple projects but still using one Cloud Provider. I am not sure whether there would be an option in Opencost UI to see costs aggregated per Cluster. But per Node they should be easy to separate even in the actual implementation.

**Comment by mattray** [comment]
The most straightforward solution would be to use Prometheus forwarding sidecars to a centralized Prometheus-compatible database (Thanos, Mimir, etc.) and run Grafana against that. That's been independently implemented multiple times but it's not documented.

The OpenCost UI doesn't support that and you'd need some sort of API on top of that. But if all you want is basic observability, what I described above works.

**Comment by mhrabovcin** [comment]
> That's been independently implemented multiple times but it's not documented.

@mattray is there some example repo with Grafana dashboards for this feature?

**Comment by AjayTripathy** [comment]
@mhrabovcin you can look here for how its done in kubecost: https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer/grafana-dashboards
 As Matt Ray noted, multicluster is supported by hooking up to any promql endpoint that can aggregate data with multiple clusters.

**Comment by sadath-12** [comment]
Hi @mattray , doesn't opencost pull the metrics from prometheus and make its cost model and provide us in api ? . Is it possible via aggregation of prometheus to get cost from opencost api itself ?
