### ISSUE TITLE
Remove links to Kubecost docs

### ISSUE THREAD

**Issue by chipzoller** [opencost/opencost#2669]
**Describe the bug**
[diagnostics.go](https://github.com/opencost/opencost/blob/develop/pkg/prom/diagnostics.go) contains (several broken) links pointing to documentation files on a Kubecost repository. 

**To Reproduce**
1. Open diagnostics.go and see [L57](https://github.com/opencost/opencost/blob/develop/pkg/prom/diagnostics.go#L57).

**Expected behavior**
OpenCost should not refer to documentation in Kubecost.

**Screenshots**

**Which version of OpenCost are you using?**
Any recent.

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by jash2105** [comment]
Hey @chipzoller  , can I work on this?

**Comment by chipzoller** [comment]
I'm not a project maintainer and cannot make assignments.

**Comment by AjayTripathy** [comment]
@jash2105 sure would take a PR here!
