### ISSUE TITLE
OpenCost API and UI

### ISSUE THREAD

**Issue by kumaran99** [opencost/opencost#2681]
For the past two weeks, I've been using OpenCost without any problems. However, in the last six days, I've faced an issue where metrics are no longer visible in the UI and cannot be accessed via the API. This issue has occurred previously, and restarting the pod resolved it. However, I'm reluctant to do that again now as it may result in the loss of data from previous days.

**To Reproduce**
I've followed the opencost setup installation https://www.opencost.io/docs/installation/install guidelines.

**Expected behavior**
Metrics needed to be rendered in UI and able to get via API also.

**Screenshots**
Please refer the attachments.
<img width="1375" alt="Screenshot 2024-04-02 at 1 49 04 PM" src="https://github.com/opencost/opencost/assets/107696446/b36c35dd-7555-4530-ad8e-c1c9f94d899d">
<img width="1252" alt="Screenshot 2024-04-02 at 1 54 38 PM" src="https://github.com/opencost/opencost/assets/107696446/362cf911-b037-4795-9e39-63b1d28aed8b">
<img width="1724" alt="Screenshot 2024-04-02 at 1 55 05 PM" src="https://github.com/opencost/opencost/assets/107696446/b0f08d1e-fcc5-4600-9b10-728d49a71d28">

**Which version of OpenCost are you using?**
Latest Image

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by dwbrown2** [comment]
@kumaran99 looks like you were able to get this resolved? Any insights you can share on the solution? Just trying to see if there's a fix that might help.

**Comment by kumaran525** [comment]
Hey @dwbrown2 sorry I raised in wrong github profile.This is the issue https://github.com/opencost/opencost/issues/2682. can you please address this issue ASAP.
