### ISSUE TITLE
EXPORT_CSV_LABELS_LIST does not accept special characters

### ISSUE THREAD

**Issue by mrlnstpn** [opencost/opencost#2698]
https://www.opencost.io/docs/integrations/csv-export#export-labels

In opencost deployment, the values we had for `EXPORT_CSV_LABELS_LIST` do have `.` and `/` , csv dump shows the column created but doesn't have any data. I created dummy labels without special characters and it works, data is showing in the csv file.

**Expected behavior**
Shows data in the csv file. 

**Screenshots**
![image](https://github.com/opencost/opencost/assets/19221220/6c2c2df9-a7e4-4132-82c6-379facc1efb0)

**Which version of OpenCost are you using?**
1.109

**Comment by anitagirme** [comment]
Hey @mrlnstpn, I'm attempting to include the cluster name as a distinct column in the CSV file. I've added the `EXPORT_CSV_LABELS_LIST=cluster` environment variable, but the `Label_cluster` column is showing up as empty. How did you manage to incorporate the cluster name into the CSV file? I'd greatly appreciate any details you could provide. Thanks!
