### ISSUE TITLE
The value file settings are not being respected

### ISSUE THREAD

**Issue by lgouveia9** [opencost/opencost#2712]
I'm deploying Opencost in my company and I'm having a problem with the Prometheus endpoint defined in the deployment. Even setting the values I need to use in values.yaml, the endpoint that is in the deployment prevails. I've already tried to edit the deployment with my Prometheus and nothing happens. I have Prometheus in a different namespace than opencost, any tips for me to make this configuration work? I've also tried with the --set global.prometheus.fqdn=my-prometheus and --set global.prometheus.enabled=false parameters and nothing happens either. Any ideas on how to resolve it?

**Comment by lgouveia9** [comment]
problem solved!

I made an adjustment to the values file

**Comment by mattray** [comment]
@lgouveia9 was there anything in the Helm chart docs missing?
