### ISSUE TITLE
[API] error querying DB: error querying via querysvc query Failure on aggregate

### ISSUE THREAD

**Issue by dannyeuu** [opencost/opencost#2727]
**Describe the bug**
When aggregate costs by label return a 500

**To Reproduce**
On API model/allocation/summary
set aggregate with namespace,label:app

**Expected behavior**

**Screenshots**
![Screenshot from 2024-05-02 16-53-37](https://github.com/opencost/opencost/assets/6808348/671b4b12-09d5-481b-9d8d-27985579229e)
```json
{"code":500,"data":null,"message":"error querying DB: error querying via querysvc query Failure: Parser Error: syntax error at or near \"(\"\nLINE 1: ...NION ALL (SELECT '__idle__' AS COALESCE(\"container_1d_idle_weighted_by_cluster...\n                                                  ^"}
```

**Which version of OpenCost are you using?**
kubecost 2.2.2
API Version kcm-c630c42588_core-c3cb2218df_oc-088f891d8e (c630c425)
UI Version 2.2.2

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

**Comment by cliffcolvin** [comment]
Hello @dannyeuu this is fixed in version 2.2.3-rc.4. We should be releasing this asap.

**Comment by dannyeuu** [comment]
FYI @mlaurawanderley

**Comment by dannyeuu** [comment]
After the release of 2.2.3, the problem was solved. thanks @cliffcolvin
