### ISSUE TITLE
Failed OpenCost integration to GCP 

### ISSUE THREAD

**Issue by stefano-arre** [opencost/opencost#2742]
**Describe the bug**

Following step by step the installation guide, Opencost 1.110 fails the integration to GCP.

<img width="1674" alt="Screenshot 2024-05-09 alle 17 04 20" src="https://github.com/opencost/opencost/assets/139888610/cf82c524-71ad-4d15-932b-c0b9b6cc0db9">

These are the logs:
<img width="1676" alt="Screenshot 2024-05-09 alle 17 05 09" src="https://github.com/opencost/opencost/assets/139888610/6181968e-b860-4d31-a9af-82374f5d81d1">
<img width="1678" alt="Screenshot 2024-05-09 alle 17 05 40" src="https://github.com/opencost/opencost/assets/139888610/012665da-feab-4563-bd01-20d939c42be7">

In [this ticket](https://github.com/opencost/opencost/issues/2326) the topic was already mentioned.

**To Reproduce**
I just follow the installation guide. 

**Which version of OpenCost are you using?**
1.110

**Comment by mattray** [comment]
@stefano-arre did it clear up like in the linked ticket, or still broken?

**Comment by stefano-arre** [comment]
Unfortunately, it is still broken. 

I had a doubt here:
<img width="994" alt="image" src="https://github.com/opencost/opencost/assets/139888610/cc3dc6a2-b33e-49b0-8e83-d9caeca83c08">

I can not see the <BILLING_DATA_DATASET> attribute in the cloud-integration.json example, and I guessed I had to split the prefix "billing.data" and the name of the table "gcp_billing_export_v1..."

This is the first part of my cloud-integration.json file:
![image](https://github.com/opencost/opencost/assets/139888610/a5fab377-9532-4b89-a59e-8629c9f0ceb3)

Is it correct? Where should I add the <BILLING_DATA_DATASET>?

**Comment by dholeshu** [comment]
+1
Im seeing the same issue in 2 different gcp clusters running opencost v1.110

**Comment by iamdmitrij** [comment]
I'm using Grafana K8S monitoring with OpenCost enabled on AKS Kubernetes on Azure: https://github.com/grafana/k8s-monitoring-helm and logs show exactly same issue. I'm not using OpenCost UI, but Grafana Cloud does display pricing properly with this error present in the pods.

Version: `ghcr.io/opencost/opencost:1.110.0` running on Azure.

**Comment by mattray** [comment]
I'm getting the same issue with a previously working API key. I generated a new one slotted for `Cloud Billing API` and it still fails. I'll raise it with Kubecost Engineering.

**Comment by mattray** [comment]
Confirmed with my personal account with a fully privileged API key.

**Comment by cliffcolvin** [comment]
Created a ticket for this and will get assigned this week.

**Comment by a-sitarz** [comment]
Hi, what's the status here? I have the same problem, is there any possibility for fix release soon?

**Comment by cliffcolvin** [comment]
@a-sitarz I'll make sure we get this cherry-picked back this week and a new release cut. This shouldn't happen in develop from our testing though.

**Comment by Sean-Holcomb** [comment]
This PR is also likely relevant to your issue https://github.com/opencost/opencost/pull/2783
The fixes are in, and you can expect a new version next week

**Comment by a-sitarz** [comment]
Hi,
What about the new version? I can see this issue is closed but there was no release so far

**Comment by mattray** [comment]
@a-sitarz probably in the next few days we'll do a 1.110.1 and a 1.111.0

**Comment by akshay-sri123** [comment]
Hey, i'm still facing this issue in  1.111.0 (7afa352). Has the issue resolved for anyone else?

**Comment by AjayTripathy** [comment]
@akshay-sri123 can you share logs
