### ISSUE TITLE
/var/configs/cloud-configurations.json WRN and ERR messages filling logs

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2748]
**Describe the bug**
The logs are full of the following messages: 

```
2024-05-14T07:36:43.43448165Z WRN Controller: pullWatchers: failed to load config statuses from file: open /var/configs/cloud-configurations.json: no such file or directory. Proceeding to create the file
2024-05-14T07:36:43.43465676Z ERR Controller: pullWatchers: failed to save statuses failed to save config statuses to file: open /var/configs/cloud-configurations.json: no such file or directory
```

even if you turn off Cloud Costs in your Helm chart.
```
opencost:
  cloudCost:
    enabled: false
```

It was noticed in https://github.com/opencost/opencost-helm-chart/issues/201#issuecomment-2093117534 as well

**To Reproduce**
1. Install OpenCost 1.110.0
2. Check the logs

**Expected behavior**
This shouldn't show up if Cloud Costs are disabled.

**Which version of OpenCost are you using?**
1.110.0

**Additional context**
I haven't been able to test with a working instance of Cloud Costs, so they may be related or my accounts have been changed out from under me.

**Comment by SayakMukhopadhyay** [comment]
Looking at the diff at https://github.com/opencost/opencost/compare/v1.110...develop#diff-c9127ce2d87ae5fe988d6b5f16b63f7ba022998d617dfbafd0381bfda6ceba41L54, it seems like that this issue might not be present in the develop branch.

**Comment by cliffcolvin** [comment]
@SayakMukhopadhyay thank you for that, it was my first question. I'll find what we need here and cherry-pick to the release branch before we build a patch. Thank you for the feedback!!

**Comment by ghost** [comment]
Hello @cliffcolvin ,
I encounter the same problem with the error ` ERR Controller: pullWatchers: failed to save statuses failed to save config statuses to file: open /var/configs/cloud-configurations.json: no such file or directory`<br>

Do you know when approxamitively the new fix will be published ?

**Comment by gabrielemontano** [comment]
+1

**Comment by thomasvn** [comment]
I believe this issue will be fixed by PR https://github.com/opencost/opencost/pull/2691. I don't think this has made it into a release yet. @Sean-Holcomb to confirm?

**Comment by JoshuaFurman** [comment]
I'm seeing this issue as well... is there any traction on this getting merged into main soon?

**Comment by mattray** [comment]
I've confirmed this is fixed in the `develop` branch, I'm closing it as fixed in the next release (hopefully next week).

**Comment by mattray** [comment]
Still seeing this in the `develop` branch

**Comment by mattray** [comment]
Actually, it's gone if 
```
  cloudCost:
    enabled: false
``` 
is in your Helm chart, but it's there otherwise. Let's leave this open until it can be verified with a working Cloud Costs, mine's broken and I'm working on getting it fixed.

**Comment by Sean-Holcomb** [comment]
I have added a patch that will allow you to use
```
  cloudCost:
    enabled: false
```
in v1.110 https://github.com/opencost/opencost/pull/2776

**Comment by mattray** [comment]
@Sean-Holcomb It looks like we're going to do 1.111.0 next week instead of 1.110.1, just to confirm that the fix is in `develop`? @cliffcolvin can you confirm?

**Comment by Sean-Holcomb** [comment]
Ive got, fixes in both 1.110 and dev branches now

**Comment by andromeda306** [comment]
I've got targetRevision: 1.38.1 with 1.110 and the additional chart value however this still seems to be an issue. 
```
        opencost:
          cloudCost:
            enabled: false
```
Is there anything else that could be a culprit? Recently made an upgrade from v1.29.0 to 1.38.1

**Comment by martinsolberg** [comment]
Same thing here, I'm on the 1.38.1 and 1.110, and I'm seeing the same error messages.

**Comment by annamagdalenakosek** [comment]
Same here, I'm on the 1.38.1 with 1.110, errors persist.

**Comment by annamagdalenakosek** [comment]
@Sean-Holcomb any updates on this?

**Comment by mattray** [comment]
@annamagdalenakosek it will be in the next OpenCost release, hopefully this week

**Comment by awoimbee** [comment]
Hi, I have the same issue, but I wonder what `cloud-configurations.json` is ? How does it differ from `cloud-integration.json` ? Should I fill it with some info ?

**Comment by Sean-Holcomb** [comment]
`cloud-configurations.json` holds the configuration state of the configuration controller which can manage configurations from multiple sources. `cloud-integration.json` is a configuration input file mounted via secret. The bug is that the controller cannot create its state file.

**Comment by mattray** [comment]
1.111.0 has been released.

**Comment by andromeda306** [comment]
confirming after update to 1.40.0 the error has disappeared
