### ISSUE TITLE
Unable to aggregate by label. Getting cost of entire cluster instead

### ISSUE THREAD

**Issue by ghost** [opencost/opencost#2753]
**Describe the bug**
I tried to aggregate the cost of namespaces by label. When that didn't work, I added labels to svcs to aggregate the cost of svcs by labels. Neither worked.

**To Reproduce**
1. Add label to namespace:
<img width="482" alt="image" src="https://github.com/opencost/opencost/assets/170133328/b1c9bf51-bdfd-4fd7-8b34-e8f503a2bee6">

In this case, it's `demo-workflow`

2. Run api: http://localhost:9003/allocation?aggregate=label:demo-workflow&window=1d&step=1d&includeAggregatedMetadata=true

**Expected behavior**
I should only get $1.32
<img width="378" alt="image" src="https://github.com/opencost/opencost/assets/170133328/1ca83bd6-455c-41f0-8b98-95f8b141e120">

Instead, I get the entire cluster's total cost. Below is the output of the api run above:
```
{
	"code": 200,
	"status": "success",
	"data": [
		{
			"__unallocated__": {
				"name": "__unallocated__",
				"properties": {
					"cluster": <redacted>
				},
				"window": {
					"start": "2024-05-16T20:20:23Z",
					"end": "2024-05-17T20:20:23Z"
				},
				"start": "2024-05-16T20:20:23Z",
				"end": "2024-05-17T20:20:23Z",
				"minutes": 1440,
				...
				"pvBytes": 67410853888.00001,
				"pvByteHours": 1617860493312.0002,
				"pvCost": 0,
				"pvs": {
					"cluster=<redacted>:name=pvc-26e74c31-2c11-419f-a39b-4a63eb62aaeb": {
						"byteHours": 25680325290.666668,
						"cost": 0,
						"providerID": ""
					},
					"cluster=<redacted>:name=pvc-57a265b9-4470-4354-85a1-4739853bc42e": {
						"byteHours": 51360650581.333336,
						"cost": 0,
						"providerID": ""
					},
					"cluster=<redacted>:name=pvc-7360a481-4315-4271-a653-cd74f8495f73": {
						"byteHours": 256803252906.6667,
						"cost": 0,
						"providerID": ""
					},
					"cluster=<redacted>:name=pvc-a5918f7d-30c2-4e63-8bea-4ca898d87288": {
						"byteHours": 1284016264533.3335,
						"cost": 0,
						"providerID": ""
					}
				},
				"pvCostAdjustment": 0,
…
				"totalCost": 3.85948,
				"totalEfficiency": 0.17973,
				"lbAllocations": null
			}
		}
	]
}
```

**Screenshots**
Please see above.

**Which version of OpenCost are you using?**
 1.106.8-rc.3

**Comment by thomasvn** [comment]
@ajfoijsdoiafdgjoasld Could you try adding the label to a running workload? For example a pod, deployment, daemonset.
