### ISSUE TITLE
Opencost has wrong price for AWS p4d.24xlarge instance type starting 4/26/2024

### ISSUE THREAD

**Issue by jdaciuk** [opencost/opencost#2796]
**Describe the bug**
On the morning of 4/26 the metric `node_total_hourly_cost{job="opencost", instance_type="p4d.24xlarge"}` was reporting as 32.8, by 10AM PST it started reporting as 0.0320.

**To Reproduce**
Check the metric `node_total_hourly_cost{job="opencost", instance_type="p4d.24xlarge"}` on an EKS cluster with `p4d.24xlarge` nodes.

**Expected behavior**
Expected to get 32.8

**Screenshots**
<img width="2327" alt="Screenshot 2024-06-13 at 10 48 18 AM" src="https://github.com/opencost/opencost/assets/77847117/01e68f12-817f-412a-9667-5c51e02a03b8">

**Which version of OpenCost are you using?**
Helm chart 1.38.1

**Additional context**
Using EKS.

**Comment by thomasvn** [comment]
Hey @jdaciuk! Thanks for reporting. I believe this behavior is expected to be fixed by https://github.com/opencost/opencost/pull/2765

**Comment by jdaciuk** [comment]
@thomasvn Ah, yeah, that sounds like it. I'll wait for that one to merge, thanks!
