### ISSUE TITLE
Wrong pvcost calculated

### ISSUE THREAD

**Issue by drz9** [opencost/opencost#2798]
**Describe the bug**
My opencost webUI shows that opencost namespace itself has a high cost of PV. But there are no PVCs/PVs in that namespace.
Other namespaces seem to look fine calculation wise.

**Expected behavior**
Correct pvcost calculation

**Screenshots**
![grafik](https://github.com/opencost/opencost/assets/23116672/6cb15a55-3648-423e-8be8-4cdc5640ce40)

**Which version of OpenCost are you using?**
1.107.0 

**Additional context**
K8s Version 1.27

**Comment by mattray** [comment]
Could you please upgrade to 1.110.0 to see if the issue persists? There have been quite a few updates since that release.

**Comment by drz9** [comment]
Hi @mattray 
last friday I updated to 1.110.0 but things did not change. there is still pvcost for opencost namespace shown. Also, when selecting any other timerange than 7 days the sum does not work anymore (see screenshot):

![Bild](https://github.com/opencost/opencost/assets/23116672/8d36c582-3d97-4e98-bb82-0436dc180fa8)

**Comment by mattray** [comment]
That's really strange. 
```
kubectl get pv -A
```
doesn't return a PV that's used by OpenCost? What about 
```
curl -G http://localhost:9003/assets  -d window=7d | jq
```
Do you see the PV associated with that?

**Comment by drz9** [comment]
None of the PV's has a claim in OpenCost namespace. When I do 

`k get pv -A | grep opencost`

The result is empty.

However, the curl you provided me says for almost every volume:

`"claimNamespace": "opencost"`

Which is weird.

**Comment by mattray** [comment]
That's really odd. I'll raise it with Kubecost Engineering to see if anyone has suggestions.

**Comment by nikovacevic** [comment]
Hi @drz9 -- the following two Prometheus queries are related to our measurement of PV costs:
```
avg(avg_over_time(kube_persistentvolume_capacity_bytes{}[1d])) by (persistentvolume)
``` 
```
avg(kube_persistentvolumeclaim_info{volumename != ""}) by (persistentvolumeclaim, storageclass, volumename, namespace)[1d]
```
Are you able to run these queries and share the results?

**Comment by drz9** [comment]
Hi @nikovacevic 
for the first query you shared, this works, is shows me all PVC's (94) in that manner:

`{persistentvolume="pvc-00b70d57-1b66-43c3-898d-02fb0d12212c"} 53687091200`

The PVC Names and values for bytes seem to be correct for all of them.

2nd Query doesnt work, I had to remove the [1d] at the end. The result is interesting, as it has twice the amount of results (188). It also shows every PVC twice, one time with correct namespace and one time with "opencost" namespace, here is an example:
```
{namespace="dev", persistentvolumeclaim="keycloak-database", storageclass="longhorn", volumename="pvc-391fe451-4dea-4cc8-8f3b-a302ab710f1c"}
{namespace="opencost", persistentvolumeclaim="keycloak-database", storageclass="longhorn", volumename="pvc-391fe451-4dea-4cc8-8f3b-a302ab710f1c"}
```

So somehow I have twice the amount of metrics and one time it shows all the PVC's as if they belong to opencost nameapce?

**Comment by AjayTripathy** [comment]
You may need to set honor_labels=true in your opencost scrape configs. See honor_labels here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
```
 # honor_labels controls how Prometheus handles conflicts between labels that are
# already present in scraped data and labels that Prometheus would attach
# server-side ("job" and "instance" labels, manually configured target
# labels, and labels generated by service discovery implementations).
```

**Comment by drz9** [comment]
Hi @AjayTripathy 
you are indeed correct, after setting the label to true the query only shows the PVC's once and in the correct namespace.

I installed via HelmChart and just enabled ServiceMonitor:

```
opencost:
  metrics:
    serviceMonitor:
      enabled: true
```

The default value in HelmChart is also  `honorLabels: true` so I am not sure, why this was not enabled on my ServiceMonitor.

Anyways, the issue with PVCost is resolved so I close this ticket. Thank you for your support everyone
