### ISSUE TITLE
[might not be a bug] Does OpenCost support window of unix nanoseconds?

### ISSUE THREAD

**Issue by ghost** [opencost/opencost#2803]
**Describe the bug**
This might not be a supported feature, but does opencost support api calls with parameters for window of unix timestamps in nanoseconds? 

**To Reproduce**
<img width="1920" alt="image (10)" src="https://github.com/opencost/opencost/assets/170133328/efe7984c-eecc-49ab-ac03-48c2aad2161a">

**Expected behavior**
There is some granular support, maybe not for nanoseconds but for microsecond unix timestamps or millisecond unix timestamps.

**Screenshots**
Please see above. 

**Which version of OpenCost are you using?**
1.106.8-rc.3

**Comment by mattray** [comment]
No. OpenCost uses timestamps in the [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) format which is only granular to seconds. Given we record by the minute and most billing is hourly, nanoseconds don't seem like a feature we plan on supporting.
