### ISSUE TITLE
Get cost per pod for all pods with a specific label

### ISSUE THREAD

**Issue by ghost** [opencost/opencost#2817]
**Is your feature request related to a problem? Please describe.**
The opencost response gets pretty big when we want to get the cost per pod if there are a lot of pods on a cluster. 
I'm currently trying to get the cost of individual pods in a single namespace.
<img width="1222" alt="image" src="https://github.com/opencost/opencost/assets/170133328/eab6ef05-dda9-4e3c-ad61-6e46918aab38">

**Describe the solution you'd like**
A way to get the cost of pods with a specific label. Currently, I can do that for namespaces, but not for pods or for services.

**Describe alternatives you've considered**
1. I've tried adding a label to the specific namespace but that gives me the cost of the entire namespace. 
<img width="1081" alt="image" src="https://github.com/opencost/opencost/assets/170133328/7e06cba2-e9b5-4f0d-8780-3e208f85187c">
2. I've tried adding labels to the pods and then running `http://localhost:9003/allocation?aggregate:label=otel`
<img width="1447" alt="image" src="https://github.com/opencost/opencost/assets/170133328/edcc0c44-1859-4f33-ac4a-ae332ca90e19">
but that just gives me the cost of the entire cluster:
<img width="1202" alt="image" src="https://github.com/opencost/opencost/assets/170133328/a3ca83c8-e92c-4b89-824f-00336de4b51c">

**Additional context**
Please let me know if there is something I could try.

**Comment by mattray** [comment]
Try using `http://localhost:9003/allocation?aggregate:label:otel` (note the ":")

**Comment by ghost** [comment]
Thanks for your response! 
It still gives us all the pods from all the namespaces: 
<img width="1243" alt="image" src="https://github.com/opencost/opencost/assets/170133328/0ffe23c6-820d-4385-aa9f-2b5fab27cb81">

**Comment by mattray** [comment]
I don't use that application (I tested with Postman which is probably similar) and I don't have the `otel` label, but when I use `app` in the UI this works: 

http://localhost:9090/allocation?agg=label:app 

which is equivalent to 

`curl -G http://localhost:9003/allocation -d aggregate=label:app` 

Maybe try that?
