### ISSUE TITLE
Error 404 with internal Prometheus running

### ISSUE THREAD

**Issue by camsellem** [opencost/opencost#2820]
**Describe the bug**
I have deployed OpenCOst using Helm (fresh install) but I have error 404 when OC is querying the pods. The issue is that Prometheus API is reachable at `http://prometheus.hdx-sandbox.svc.cluster.local:9090/prometheus/api/v1/query` although following the helm command below, OpenCost wants to reach the API at `http://prometheus.hdx-sandbox.svc.cluster.local:9090/api/v1/query` (missing prometheus folder) - I can't find a setting to change that.

```
helm install opencost opencost/opencost \
  --namespace opencost \
  --create-namespace \
  --set opencost.exporter.cloudProviderApiKey='redacted' \
  --set opencost.prometheus.internal.enabled='true' \
  --set opencost.prometheus.internal.namespaceName='hdx-sandbox' \
  --set opencost.prometheus.internal.port='9090' \
  --set opencost.prometheus.internal.serviceName='prometheus'
```

**Which version of OpenCost are you using?**
v1.11 latest

![image](https://github.com/opencost/opencost/assets/3879044/23574a9e-ebcb-431e-9905-9d804987070f)

**Comment by mattray** [comment]
The offending code is [here](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/templates/_helpers.tpl#L94) and doesn't seem to have a ready way to change the folder (it's just building based off the existing pattern). I think you should be able to use the external Prometheus provider to override everything as necessary. Something along the lines of 
```
  --set opencost.prometheus.external.enabled='true' \
  --set opencost.prometheus.external.url='http://prometheus.hdx-sandbox.svc.cluster.local:9090/prometheus/api/v1/query' \
```
Please test and report back, you may need to tweak what gets passed into the external.url to get the right combination.

**Comment by camsellem** [comment]
Thank you @mattray this is what I ended up doing and it's working fine :)
