### ISSUE TITLE
Unable to find release notes for opencost v2.x

### ISSUE THREAD

**Issue by sathieu** [opencost/opencost#2831]
**Is your feature request related to a problem? Please describe.**

ghcr.io/opencost/opencost and ghcr.io/opencost/opencost-ui were updated, and tags were created, but I couldn't find the release notes (and breaking changes).

**Describe the solution you'd like**

github releases with release notes.

**Describe alternatives you've considered**

I've found this: https://github.com/kubecost/cost-analyzer-helm-chart/releases/v2.0.0, but this is about kubecost, and not opencost.

**Additional context**

Renovate: https://gitlab.com/kubitus-project/kubitus-installer/-/merge_requests/3148

**Comment by lmello** [comment]
Hi @sathieu , 

There is no opencost release 2.x, latest opencost is 1.111.0 released two week ago. 

KubeCost changed the release numbers to 2.X sometime ago, but this change was not followed by opencost.

**Comment by sathieu** [comment]
@lmello There are tags fro 2.x (for example [v2.3.2](https://github.com/opencost/opencost/tree/v2.3.2)) and images on ghcr (for example: [opencost/opencost:2.3.2](https://github.com/opencost/opencost/pkgs/container/opencost/238400709?tag=2.3.2)).

Something going weird in the tooling?

**Comment by cliffcolvin** [comment]
Yes, thank you for pointing this out. We had an issue with the opencost build (based on tags being pushed. Kubecost still pushes tags for pinning versions built. I'll resolve this but the opencost image there is still 1.111, just cut with a kubecost tag from an error in tooling.
