### ISSUE TITLE
Understanding Custom Pricing Configuration

### ISSUE THREAD

**Issue by JoshuaFurman** [opencost/opencost#2840]
I've deployed OpenCost on an On-Prem Kubernetes cluster and I'm trying to understand the units in the custom pricing configuration: 
```
{
    "provider": "custom",
    "description": "Default prices based on GCP us-central1",
    "CPU": "0.031611",
    "spotCPU": "0.006655",
    "RAM": "0.004237",
    "spotRAM": "0.000892",
    "GPU": "0.95",
    "storage": "0.00005479452",
    "zoneNetworkEgress": "0.01",
    "regionNetworkEgress": "0.01",
    "internetNetworkEgress": "0.12"
}
```

Primarily for: CPU, GPU, RAM and storage. 

When deploying with the default values, I'm seeing an absurdly high RAM cost, in the hundreds of millions... Which is obviously not accurate.
 
Are these dollar amounts per hour? The documentation isn't too clear on this and I'm trying to define a cost model for our on-prem infrastructure. If anyone could clarify this it would be greatly appreciated. 
Thank you!

**Comment by marciojpacheco** [comment]
I'm in the same page here... I'm trying to deploy opencost on my kubernetes cluster that is deployed on huawei cloud provider. But I didn't find how calculate and what is the units used here.

It would be great if anyone could help us.

**Comment by ffluegel** [comment]
This specification file should help: https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md

**Comment by JoshuaFurman** [comment]
Yeah so reading through that document its still not obvious to me what units are used for the values I'm suppose to provide in the config. Trying to standardize this across an on-prem environment is challenging without understanding these values.

**Comment by JoshuaFurman** [comment]
After re-reading the opencost-spec, i've realized my lack of understanding was a skill issue and i get it now. Thanks

**Comment by Raveen793** [comment]
> I'm in the same page here... I'm trying to deploy opencost on my kubernetes cluster that is deployed on huawei cloud provider. But I didn't find how calculate and what is the units used here.
> 
> It would be great if anyone could help us.

@marciojpacheco Did you find a solution?
