### ISSUE TITLE
Integration with my app

### ISSUE THREAD

**Issue by Tomerfi1210** [opencost/opencost#2843]
Hi,
I want to integration your metrics with my golang app.
Any idea how to start ?

Thanks

**Comment by kwombach12** [comment]
Hey @Tomerfi1210 What metrics were you thinking of using for your integration? You can see the APIs we have available [here](https://www.opencost.io/docs/integrations/api). Additionally, if you need help getting OpenCost installed, we have some setup instructions [here](https://www.opencost.io/docs/installation/install). Let me know if I can provide any other help or guidance!

**Comment by Tomerfi1210** [comment]
> Hey @Tomerfi1210 What metrics were you thinking of using for your integration? You can see the APIs we have available [here](https://www.opencost.io/docs/integrations/api). Additionally, if you need help getting OpenCost installed, we have some setup instructions [here](https://www.opencost.io/docs/installation/install). Let me know if I can provide any other help or guidance!

**Comment by Tomerfi1210** [comment]
Hey, thanks for answering !
I want full integration, but use your open cost as pkg instead.
Like, take the metrics calculation and use it in my promethous

@kwombach12 
is it optional ?

**Comment by Tomerfi1210** [comment]
@kwombach12 and do you need the client promethous to get all the costs ? or do you calculate it yourself ?

**Comment by mattray** [comment]
If you're familiar with Go already, you'll probably want to follow the `agent` path in the Cobra OpenCost CLI which provides only metrics exporting. 

https://github.com/opencost/opencost/blob/develop/pkg/cmd/agent/agent.go

I'm not sure how easy it would be to embed OpenCost as a library, but it's fairly modular so we'd definitely take patches to help make it easier to embed.
