### ISSUE TITLE
Running in Docker : /model/allocation/compute return 404

### ISSUE THREAD

**Issue by chandanrjit** [opencost/opencost#2845]
Describe the bug
The OpenCost UI returns a 404 Not Found error when trying to access the /model/allocation/compute endpoint. This issue seems to be related to the configuration or connectivity between the OpenCost UI and the cost model service.

To Reproduce

Follow the installation steps from [OpenCost Docker Installation Guide](https://www.opencost.io/docs/installation/docker).
Start the services using the provided podman-compose.yml file.
Open the OpenCost UI in a browser.
The request to http://localhost:9090/model/allocation/compute?window=6d&aggregate=namespace&step=1d&accumulate=false returns a 404 Not Found error.
Expected behavior
The /model/allocation/compute endpoint should return the expected data without a 404 error.

Screenshots
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/d4983be9-1974-4cc4-986d-ed2060094966">
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/6e021ea3-8144-4efb-9c18-dee3c6ff256b">

Which version of OpenCost are you using?

OpenCost cost model: ghcr.io/opencost/opencost:1.109.0
OpenCost UI: ghcr.io/opencost/opencost-ui:1.109.0
Additional context

The services are configured using the provided podman-compose.yml file.
Environment variable API_SERVER is set to host.docker.internal.
Kubernetes version and public clouds information (if applicable):
Kubernetes version: N/A (using Docker)
Public clouds: N/A (using local Docker setup)

**Comment by chandanrjit** [comment]
cloud-integration.json
```
{
    "azure": {
      "storage": [
        {
          "subscriptionID": "xxxxx-xx-xxxx-xxx",
          "account": "xxxxx",
          "container": "bill",
          "path": "",
          "cloud": "public",
          "authorizer": {
            "accessKey": "xxxxxx",
            "account": "xxxxx",
            "authorizerType": "AzureAccessKey"
        }
        },
        {
          "subscriptionID": "xxxxx-xx-xxxx-xxx",
          "account": "abc",
          "container": "bill",
          "path": "/",
          "cloud": "public",
          "authorizer": {
            "accessKey": "xxxxxx",
            "account": "xxxxx",
            "authorizerType": "AzureAccessKey"
        }
      }
      ]
    }
  }
```

**Comment by mattray** [comment]
The URL pattern you're requesting is for Kubecost, not OpenCost. The OpenCost URL should be 
http://localhost:9090/allocation?window=6d&aggregate=namespace&step=1d&accumulate=false

Note that "model" and "/compute" have been removed.
