### ISSUE TITLE
How to run opencost without promethous to get all data ?

### ISSUE THREAD

**Issue by Tomerfi1210** [opencost/opencost#2849]
Hi,
I want to use your opencost to get all the data but without provide promethoues.

How to do it ?

**Comment by lmello** [comment]
Thats not possible. 

prometheus is used to persist storage data for opencost. 
https://www.opencost.io/docs/installation/install#requirements
https://www.opencost.io/docs/installation/prometheus

If you have future questions feel free to ask and follow-up in the slack channel: 
https://www.opencost.io/docs/community

**Comment by AjayTripathy** [comment]
Technically you don't need Prometheus to get cloud cost data. But we can't get k8s data without it. https://www.opencost.io/blog/cloud-costs
