### ISSUE TITLE
Where does opencost store the data? How to config data persistence in helm file

### ISSUE THREAD

**Issue by drygoogle** [opencost/opencost#2850]
Where directoy does opencost store the data? How to  config  data persistence in helm file ？

Thanks a lot

**Comment by lmello** [comment]
Opencost persists all data in prometheus. 

The helm chart can deploy a prometheus server for you, or use an external prometheus service. 

please look at the documentation available here: 
https://www.opencost.io/docs/installation/prometheus 

if you have future enquiries you could use the slack channel for questions. 
https://www.opencost.io/docs/community
