### ISSUE TITLE
Support IAM Roles for Athena Access

### ISSUE THREAD

**Issue by knechtionscoding** [opencost/opencost#2869]
**Is your feature request related to a problem? Please describe.**

With a cloud-integration.json that looks something like:

```
{
    "aws": {
        "athena": [
            {
                "bucket": "s3://<bucket>",
                "region": "<region>",
                "database": "<db>",
                "table": "<table>",
                "workgroup": "<workgroup>",
                "account": "<account>"
            }
        ]
    }
}
```

We get the following error:

```
2024-08-13T17:43:04.385813727Z ERR MultiCloudWatcher: Error getting file '/var/configs/cloud-integration/cloud-integration.json': loadFile: Error reading json: unmarshalerDecoder: AthenaConfiguration: UnmarshalJSON: missing authorizer, error found in #10 byte of ...| ]
    }
}
|..., bigger context ...|t": "580663733917"
            }
        ]
    }
}
|...
```

But I don't really want to have to put a secret key into the secret.

**Describe the solution you'd like**

 I would prefer to use the IRSA role assigned to the SA directly like we do in other places.

**Describe alternatives you've considered**

**Additional context**

**Comment by knechtionscoding** [comment]
This appears to be a documentation issue rather than a code issue.

https://github.com/opencost/opencost/blob/develop/pkg/cloud/aws/authorizer.go appears to point at multiple authorizer types and that should be documented outside the code.

**Comment by AjayTripathy** [comment]
Provisioning your pod with IAM roles should be supported. That's outside of the context of opencost though; check the opencost helm chart repository or file an issue there?

**Comment by knechtionscoding** [comment]
The problem wasn't with the provisioning. It was trying to configure the cloud-integration.json that was the issue.


                "authorizer": {
                    "authorizerType": "AWSServiceAccount"
                }

Was required. But the cloud-integration.json documentation only lists a secretKey and accessKey option as the authorizer.

**Comment by AjayTripathy** [comment]
Sounds like we want to add this to documentation then, but closing here for now.

**Comment by JunaidChaudry** [comment]
It seems like the documentation is still missing as I could not find it. If not, can someone please provide the direct link?

**Comment by dgsamper** [comment]
It is still missing btw

**Comment by jcnsjr** [comment]
Still missing.
