### ISSUE TITLE
Support for Networking and Load Balancer Cost Calculation in Bare-Metal Environments

### ISSUE THREAD

**Issue by bnallapeta** [opencost/opencost#2871]
I'm currently running Kubernetes on a bare-metal server environment, using MetalLB for load balancing. I want to track and allocate networking costs, especially those related to load balancers, but it seems that OpenCost primarily supports cloud providers like AWS, GCP, and Alibaba from your documentation.

Does OpenCost support cost calculation for networking and load balancers in bare-metal environments? If yes, could you share links to the documentation for this? If not, do you have any advice on how to handle this, particularly in a setup using MetalLB?

Thank you!

**Comment by AjayTripathy** [comment]
Hey @bnallapeta we have a handful of these usecases, including extended support for bare-metal environments, supported in Enterprise versions. Would love to hear more about your usecase to get a sense of whether that's a fit.

**Comment by bnallapeta** [comment]
@AjayTripathy Thanks for the info.
