### ISSUE TITLE
Opencost reports wrong price for AKS Cluster with a node of type D4as V5

### ISSUE THREAD

**Issue by raghavendra-rafay** [opencost/opencost#2906]
**Describe the bug**
Opencost reports Windows pricing ($0.3560) for AKS nodes of type D4as V5 even though it's a Linux node.

**To Reproduce**
1. Create an AKS Cluster with a node of type D4as V5 in any region.
2. Install Opencost
3. execute `kubectl port-forward` command for opencost pod for 9003 port.
4. Access http://localhost:9003/metrics
5. find `node_total_hourly_cost` metric and check the value its reporting.

**Expected behavior**
node_total_hourly_cost for a node of instance type Standard_D4as_v5 should report a value of 0.1720

**Screenshots**
![Screenshot 2024-09-04 at 8 30 03 PM](https://github.com/user-attachments/assets/eb6289bf-29b1-48e1-a68e-ae751fbc326a)

**Which version of OpenCost are you using?**
v1.109.0

**Additional context**
No

**Comment by AjayTripathy** [comment]
Thanks for this and the followup PR @raghavendra-rafay ! We're investigating now.
