### ISSUE TITLE
csv export not working in local pv or azure blob

### ISSUE THREAD

**Issue by veldpworld** [opencost/opencost#2943]
opencost csv export not working, after configured its more than 2 days and its not generated anything in local pvc.

https://www.opencost.io/docs/integrations/csv-export  - we followed this.

**To Reproduce**
opencost helm chart v1.111
added the pvc for the csv
csv file path defined  /mnt/export/report.csv

**Expected behavior**
it should generated .csv file in the given location

**Screenshots**

**Which version of OpenCost are you using?**
opencost-ui:1.111.0@sha256:f7221e7a708d71663f5eca6c238268757eb4352f3e9f46b1029d33ab4e53fd8a

**Additional context**
I have configured using azure blob location also but it didn;t work, Again I tried with local mount using pvc for the csv.

 Environment:
      LOG_LEVEL:                                           info
      CUSTOM_COST_ENABLED:                                 false
      KUBECOST_NAMESPACE:                                  opencost
      API_PORT:                                            9003
      PROMETHEUS_SERVER_ENDPOINT:                          http://prometheus-server.monitoring.svc.cluster.local:80
      CLUSTER_ID:                                          default-cluster
      **EXPORT_CSV_FILE:                                     /mnt/export/opencost.csv**
      DATA_RETENTION_DAILY_RESOLUTION_DAYS:                15
      CLOUD_COST_ENABLED:                                  true
      CLOUD_COST_MONTH_TO_DATE_INTERVAL:                   6
      CLOUD_COST_REFRESH_RATE_HOURS:                       1
      CLOUD_COST_QUERY_WINDOW_DAYS:                        7
      CLOUD_COST_RUN_WINDOW_DAYS:                          1
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          aks-lab-infra
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        opencost (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              opencost-588979cf94-lp4vp (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        opencost
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  ghcr.io/opencost/opencost:latest
      NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME:       opencost
    Mounts:
      **/mnt/export from opencost-export (rw)**
      /var/configs/cloud-integration from cloud-integration (rw)
      /var/configs/db from db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bkdxj (ro)
      /var/secrets from service-key-secret (rw)

**Comment by AjayTripathy** [comment]
@veldpworld could you share logs? Any errors in the logs?

**Comment by veldpworld** [comment]
I can manage to work, this pv mount is not allowing write access. I added fsGroup and runAsUser as 1001 in securityContext and it worked.
