### ISSUE TITLE
__idle__ cost > workload cost and results in 0 total cost.

### ISSUE THREAD

**Issue by ojiwon-kenobi** [opencost/opencost#2945]
**Describe the bug**
__idle__ costs exceed the workload costs, and it shouldn't be.
<img width="1722" alt="Screenshot 2024-10-07 at 9 28 48 AM" src="https://github.com/user-attachments/assets/ae02b38f-308c-498d-9928-60a073cdd181">

**To Reproduce**
1. In a cluster with multiple namespaces, deploy opencost using the helm chart.
2. Port-forward the opencost UI and see if you can see a non-zero cost. 

**Expected behavior**
I expected non-zero cost breakdowns. 

**Screenshots**
Please see above.

**Which version of OpenCost are you using?**
OpenCost version: 1.111.0 (7afa352)

**Additional context**
The cluster is on Azure.

**Comment by AjayTripathy** [comment]
We're not able to repro this, can you please share how you've installed opencost and any logs?

**Comment by ojiwon-kenobi** [comment]
I ended up deploying my setup on a different cluster where the issue didn't happen again. I'll close this!
