### ISSUE TITLE
EBS attached volumes not accessible via PV are not counted in AWS costs

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#473]
It's possible to provision a node with an EBS volume attached that isn't reflected in a PV on AWS. Although instance storage is included in AWS node pricing (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) , these EBS volumes would not be.

1. The current behavior of setting local storage prices for the root volume on AWS should remain 0
2. We should add EBS volumes attached as local disks to our local storage prices.
3. This should be removed from local storage prices and added to PV price if they become reflected in a local persistent volume https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#what-is-a-local-persistent-volume

**Comment by michaelmdresser** [comment]
@AjayTripathy do you know if this is still a problem?

**Comment by AjayTripathy** [comment]
Yes, it still is.
