### ISSUE TITLE
allow disabling certain instance types

### ISSUE THREAD

**Issue by AFriemann** [opencost/opencost#511]
currently kubecost recommends a1 instances for most of our clusters - however migrating to those is a bit scary and I would like to see alternative recommendations.

would it be possible to add an option to filter certain instance types?

**Comment by dwbrown2** [comment]
Hi Aljosha! Great input, we've definitely discussed enabling this. Are there other node types/profiles that you would want filtered?

We have been trying to decide if manually filtering different node types or having us do this based on your context/profile is the right approach. @nikovacevic as FYI

**Comment by AFriemann** [comment]
the main reason why I would want to filter those is that it's arm based instances and I don't feel comfortable just switching over without extensive testing - so essentially allowing us to filter by glob/regex or (maybe even better) arch type would be amazeballs.

**Comment by AjayTripathy** [comment]
Hi @AFriemann just following up! There is a drop-down filter for ARM on our cluster sizing page: /cluster-sizing.html

Does that address your main issue about disabling instance types?

**Comment by DanTulovsky** [comment]
I think this would be useful for us as well. For example, we are not going to use GCP e1 instances, so it would be nice to disable recommendations for those.

Alternatively, it would be amazing if I could say (assuming right now we use n1 instance types): "What would this looks like if we were using n2d instance types instead?"

**Comment by dwbrown2** [comment]
@DanTulovsky thanks for sharing, let us take a look. Are there particular node classes that are not a fit? For example, would you not use e2 because they are shared-core?

**Comment by DanTulovsky** [comment]
Exactly!  I don't have any other examples though.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
