### ISSUE TITLE
direct-classification usage issues

### ISSUE THREAD

**Issue by shaikatz** [opencost/opencost#518]
Hi,

I've defined 2 subnets in my `direct-classification` values.yaml like that:
```
  networkCosts:
    enabled: true
    config:
      destinations:
        direct-classification:
        - region: us-east1
          ips:
          - "100.1.2.0/24"
        - region: us-east2
          ips:
          - "100.1.3.0/24"
```

Unfortunately, looking at the UI both subnets being treated as in-zone traffic for the same pod, which isn't correct of course.

*Edit*: looks like all my classifications didn't really take into account (I've configured much more then the above example, including zones for most of them), and everything which is kinda private becomes in-zone after those changes.
Did I configure something incorrectly?

**Comment by dwbrown2** [comment]
@shaikatz, can you share the following and we can investigate with you:

* What kubecost version / install path are you using?
* What regions/zones is your cluster in?

Note: not specifying zone in this classification definition defaults traffic to `in-zone` if source/destination are in the same region.

@mbolt35 as FYI

**Comment by shaikatz** [comment]
I'm using the latest helm chart installation.
I have clusters on both us-east regions. both of them don't get my configurations correctly and shows random in-zone/cross-zone info.
I can jump into zoom/slack session if you would like to investigate that live. (you can find me at shai@soluto.com)

**Comment by mbolt35** [comment]
Hey @shaikatz Can I just get you to verify that the configmap has the expected contents?

```bash
$ kubectl get cm -n kubecost network-costs-config -o yaml
```

**Comment by shaikatz** [comment]
This is the command output (with the IP replaced with some mocks)
```
apiVersion: v1
data:
  config.yaml: |
    destinations:
      cross-region: []
      direct-classification:
      - ips:
        - 100.77.176.0/22
        - 100.77.188.0/25
        - 100.77.189.128/26
        - 100.85.192.0/20
        - 100.85.240.0/24
        - 100.85.243.0/25
        region: us-east1
        zone: us-east1-a
      - ips:
        - 100.77.180.0/22
        - 100.77.188.128/25
        - 100.77.189.192/26
        - 100.85.208.0/20
        - 100.85.241.0/24
        - 100.85.243.128/25
        region: us-east1
        zone: us-east1-b
      - ips:
        - 100.77.184.0/22
        - 100.77.189.0/25
        - 100.77.190.0/26
        - 100.85.224.0/20
        - 100.85.242.0/24
        - 100.85.244.0/25
        region: us-east1
        zone: us-east1-c
      - ips:
        - 10.49.121.0/24
        region: us-east1
      - ips:
        - 100.77.112.0/22
        - 100.77.124.0/25
        - 100.77.125.128/26
        - 100.88.112.0/24
        - 100.88.115.0/25
        - 100.88.64.0/20
        region: us-east2
        zone: us-east2-a
      - ips:
        - 100.77.116.0/22
        - 100.77.124.128/25
        - 100.77.125.192/26
        - 100.88.113.0/24
        - 100.88.115.128/25
        - 100.88.80.0/20
        region: us-east2
        zone: us-east2-b
      - ips:
        - 100.77.120.0/22
        - 100.77.125.0/25
        - 100.77.126.0/26
        - 100.88.114.0/24
        - 100.88.116.0/25
        - 100.88.96.0/20
        region: us-east2
        zone: us-east2-c
      - ips:
        - 10.49.120.0/24
        region: us-east2
      in-region: []
      in-zone:
      - 127.0.0.1
      - 169.254.0.0/16
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
kind: ConfigMap
metadata:
  annotations:
  creationTimestamp: "2020-02-20T07:23:04Z"
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cost-analyzer
    argocd.argoproj.io/instance: kubecost
    helm.sh/chart: cost-analyzer-1.64.0
  name: network-costs-config
  namespace: costs
  resourceVersion: "260152932"
  selfLink: /api/v1/namespaces/costs/configmaps/network-costs-config
  uid: d5af085e-53b1-11ea-bd3c-022e84926bcf

```

**Comment by mbolt35** [comment]
I dropped this config into the network costs, and it does look like the classification component is working correctly. I ran several tests across multiple of the configured region/zones and they all returned expected results. This leads me to believe that the destination IPs are not matching any of the subnet IPs you've configured. This is only speculation of course, based on my limited test results, and we may be able to see the faulty classification in action:

Each `kubecost-network-costs` pod running has a logger that dumps that top 5 destinations (in egress data) from the host node every 30 minutes. So if you have a node running on `us-east1-c` and you know a pod is communicating via a subnet address for `us-east1-a`, then you can log the `kubecost-network-cost` pod on that node and see if it gives you incorrect classification.

The logs are formatted in the following:
```
Source: 10.142.15.223
[prometheus-to-sd-dpzrp,fluentd-gcp-v3.2.0-kw48b,kubecost-prometheus-node-exporter-dl99k,kubecost-network-costs-cpb59,kube-proxy-gke-bolt-1-default-pool-5b6a9277-6azi]
  -> Dest: 10.24.2.234, [RZ] Total Bytes: 63538871, Total GB: 0.06
     [metrics-server-v0.3.1-5c6fbf777-nmfpw]
  -> Dest: 10.142.0.8, [RZ] Total Bytes: 20876574, Total GB: 0.02
     [kube-proxy-gke-bolt-1-default-pool-5b6a9277-hno7,fluentd-gcp-v3.2.0-krwsp,kubecost-network-costs-jwm8c,prometheus-to-sd-n5wbm,kubecost-prometheus-node-exporter-rgssv]
  -> Dest: 173.194.216.95, [I] Total Bytes: 20503536, Total GB: 0.02
     [Unknown]
  -> Dest: 10.24.0.181, [RZ] Total Bytes: 14199083, Total GB: 0.01
     [heapster-gke-d4fd9f5fc-59cgf]
```

After each `-> Dest: <IP>` there will exist:
* `[]` for cross-region 
* `[R]` for cross-zone 
* `[RZ]` for in-zone 
* `[I]` for internet 

I just want to make sure that the IPs being used to resolve the direct classification are expected.

**Comment by shaikatz** [comment]
Thanks for the instructions.
I've took a look in one of the pods and here is a sample output:
```
2020-08-26 22:31:57 | I0826 19:31:57.833284       1 networktrafficlogger.go:77] [some-pod-name-99b977784-5s72d] -- | --
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833279       1 networktrafficlogger.go:76] Source: 100.84.199.51
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833273       1 networktrafficlogger.go:81]      [coredns-56678dcf76-2fldv]
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833267       1 networktrafficlogger.go:80]   -> Dest: 100.84.196.15, [] Total Bytes: 120844, Total GB: 0.00
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833263       1 networktrafficlogger.go:81]      [coredns-56678dcf76-zt9tf]
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833256       1 networktrafficlogger.go:80]   -> Dest: 100.84.238.240, [] Total Bytes: 128006, Total GB: 0.00
  |   | 2020-08-26 22:31:57 | I0826 19:31:57.833251       1 networktrafficlogger.go:81]      [prometheus-k8s-1]

```

Those are the relevant classifications from the config map:
```    
    - ips:
        - 100.84.192.0/20
        region: us-east1
        zone: us-east1-a
```

```
      - ips:
        - 100.84.224.0/20
        region: us-east1
        zone: us-east1-c
```

You can see that the source pod and the first destination are in the same zone, but we don't see the [RZ] tag.
Also, for the second destination, I expect seeing [R]

**Comment by mbolt35** [comment]
The classification mapping isn't used by the source, the source uses it's host node labels to determine region and zone:

ie:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
     ...
  labels:
    ...
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-b
    ...
```

Although, I'm guessing that node will be `us-east1-a` based on your report. If this isn't the case, let me know. It might be possible to use the classification map with the source IP as well. Will need to review a bit more.

I haven't tested against cilium yet, but as far as I know, it shouldn't cause any issues.

**Comment by shaikatz** [comment]
The labels are:
```
failure-domain.beta.kubernetes.io/zone=us-east-1c
failure-domain.beta.kubernetes.io/region=us-east-1
```

Which follows what written in Kubernetes [docs](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone)

I'll try to change the classification map to fit that and see if it helps.

**Comment by mbolt35** [comment]
Yeah, the difference in naming there is definitely what would cause that issue. 

With respect to the UI, I will need to look into how we're sending the data (it's sourced the same way), so it might just be a display bug. Thanks again for the feedback here. I'll let you know if I find anything with the UI.

**Comment by mbolt35** [comment]
@shaikatz Definitely a frontend UI label bug. We'll get that taken care of ASAP. Thanks for the feedback!

**Comment by treyhyde** [comment]
> The labels are:
> 
> ```
> failure-domain.beta.kubernetes.io/zone=us-east-1a
> failure-domain.beta.kubernetes.io/region=us-east-1
> ```
> 
> Which follows what written in Kubernetes [docs](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone)
> 
> I'll try to change the classification map to fit that and see if it helps.
> 
> Edit: it looks much better, the only gap is cross-region traffic, that marked as [] in the logs, and displayed as `In Zone` in the UI, probably a bug?

They WERE failure-domain.beta.kubernetes.io, they are now topology.kubernetes.io

**Comment by treyhyde** [comment]
Just a note for the discussion.   Same zone traffic incurs a cross-zone charge if it traverses a VPC boundary.    (actually, 2 charges, in and out)

Based on the docs, I was hoping that kubecost could do the classification based on auto-discovery.    It doesn't seem super effective in that.    Is the best place for documentation https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml?     Sounds like zone names should be AWS canonical and not something more unique?

**Comment by mbolt35** [comment]
> > The labels are:
> > ```
> > failure-domain.beta.kubernetes.io/zone=us-east-1a
> > failure-domain.beta.kubernetes.io/region=us-east-1
> > ```
> > 
> > 
> > Which follows what written in Kubernetes [docs](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone)
> > I'll try to change the classification map to fit that and see if it helps.
> > Edit: it looks much better, the only gap is cross-region traffic, that marked as [] in the logs, and displayed as `In Zone` in the UI, probably a bug?
> 
> They WERE failure-domain.beta.kubernetes.io, they are now topology.kubernetes.io

We now recognize the new and legacy labels in the latest network-costs image (v15.2)

**Comment by mbolt35** [comment]
> Just a note for the discussion. Same zone traffic incurs a cross-zone charge if it traverses a VPC boundary. (actually, 2 charges, in and out)
> 
> Based on the docs, I was hoping that kubecost could do the classification based on auto-discovery. It doesn't seem super effective in that. Is the best place for documentation https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml? Sounds like zone names should be AWS canonical and not something more unique?

The network-costs pod uses two auto-discovery methods to classify traffic: 
1) Graph of the Kubernetes network 
2) Kernel network route tables 

Right now, the implementation does not use any provider specific data for classification. It has been a discussion point, but the nuances across providers are not always 1-1. This is why we've provided the configuration options: to fill in the classification gaps where auto-discovery and assignment can't reach.

**Comment by treyhyde** [comment]
> Right now, the implementation does not use any provider specific data for classification. It has been a discussion point, but the nuances across providers are not always 1-1. This is why we've provided the configuration options: to fill in the classification gaps where auto-discovery and assignment can't reach.

For me, all traffic in the very simple cluster was showing as "in zone."  I'm struggling to form a custom config that would reflect how AWS would bill me.     Particularly difficult are use of ClusterIP services since they are magic and aren't clear how they map back to hosts and thus zones.

I'd really love for the data that shows up in the network container logs up in the kubecost UI (mapping IPs to container names).  Generally, speaking I get no source/destination data in the network UI or wrong.  Perhaps changes in the mappings really confuses the front end.  That's clearly just a guess.

**Comment by dwbrown2** [comment]
@treyhyde you can see a mapping between source pod name and destination IP / zone in the frontend UI (Allocation --> network drilldown). Is this view generally useful or are you looking for something else? I don't think we can get down to the container level currently.

**Comment by treyhyde** [comment]
> @treyhyde you can see a mapping between source pod name and destination IP / zone in the frontend UI (Allocation --> network drilldown). Is this view generally useful or are you looking for something else? I don't think we can get down to the container level currently. 

Yes, sometimes there be a mapping there, sometimes not, sometimes using older mapping rules.   Sometimes it will be a large cost and then show 4 MB in zone.     Again, my stab in the dark guess is it isn't dealing with mapping changes well (default everything in zone vs telling it about the subnet placements in the kube cost config after realizing the default doesn't do much useful as I'm primarily trying to hunt down inter zone traffic).     

Right mapping those IPs to pods would be the most useful, by the time I would ever look at this view the pods will all be gone and I'll just be guessing it grepping your own kube cost containers where the data already is (more or less)

**Comment by mbolt35** [comment]
@treyhyde What you're seeing the network-costs logs are similar to what you're seeing in the frontend UI. The view of the data is limited to the lifetime of the network-costs pod reporting the traffic. The costs are based on a query against the metrics based on timeframe of the query. So, we might only be showing 4mb emitted since the restart of that network-costs pod, but since prometheus counters continue where they left off, the cost may reflect a time period > the pod up time.

**Comment by treyhyde** [comment]
> @treyhyde What you're seeing the network-costs logs are similar to what you're seeing in the frontend UI. The view of the data is limited to the lifetime of the network-costs pod reporting the traffic. The costs are based on a query against the metrics based on timeframe of the query. So, we might only be showing 4mb emitted since the restart of that network-costs pod, but since prometheus counters continue where they left off, the cost may reflect a time period > the pod up time. 

Good to understand.   I can say that is definitely not what I see.  Uptimes of days and no data in kubecost other than 100s of GB of new net traffic (no from/to ip data in the UI, just in the daemonset logs)

**Comment by dwbrown2** [comment]
@treyhyde is there any more data that you can share to help us investigate? I'm not how to best move forward based on everything reported so far.

**Comment by mbolt35** [comment]
@treyhyde When you say no data in the UI, when you drill down into the costs from the allocation page, you're not seeing any line items?

**Comment by treyhyde** [comment]
Happy to provide anything.    The kubecost UI is devoid of anything really useful but the kubecost-network-costs-* logs are a treasure trove but difficult to reassemble.  I haven't yet looked at the data recorded into the kubecost prometheus.

**Comment by hgranillo** [comment]
EDIT: After re reading my entire post I've realized my mistake. I wrongly named the region in the direct-classification map as "us-east1" instead of "us-east-1" :man_facepalming: 

I will leave my post here as an example

---------------------
Hi Kubecost team, I'm also facing a similar case where some of my IP CIDR are not getting classified correctly and it seems that is tied to when the traffic belongs to a different zone in the same region.

The example below shows that traffic going from zone-a to zone-b, same region, gets classified as cross region `[]`

Configuration of my kubecost networkCosts component:
```
    networkCosts:
      enabled: true
      podMonitor:
        enabled: true
      config:
        services:
          amazon-web-services: true
        destinations:
          in-zone:
            # Loopback
            - "127.0.0.1"
            # IPv4 Link Local Address Space
            - "169.254.0.0/16"
          cross-region:
            - 10.2.0.0/16
            - 172.31.0.0/16
          in-region:
            - "172.27.16.0/21"
            - "10.0.0.0/16"
            - "10.1.0.0/16"
          direct-classification:
            - region: "us-east1"
              zone: "us-east-1a"
              ips:
                - "10.0.0.0/21"
                - "10.0.144.0/23"
                - "10.0.32.0/19"
            - region: "us-east1"
              zone: "us-east-1b"
              ips:
                - "10.0.146.0/23"
                - "10.0.64.0/19"
                - "10.0.8.0/21"
            - region: "us-east1"
              zone: "us-east-1c"
              ips:
                - "10.0.148.0/23"
                - "10.0.16.0/21"
                - "10.0.96.0/19"
```

Here's the log of the network cost component that's incorrectly tagging cross-zone traffic:
```
I0524 17:13:56.203506       1 networktrafficlogger.go:77] [kafka-cp-kafka-1]
I0524 17:13:56.203509       1 networktrafficlogger.go:80]   -> Dest: 10.0.66.197, [] Total Bytes: 6863117066, Total GB: 6.39
I0524 17:13:56.203514       1 networktrafficlogger.go:81]      [rtp-gateway-keyfigures-5f86f88cb6-6tp9b]
I0524 17:13:56.203518       1 networktrafficlogger.go:80]   -> Dest: 10.0.46.116, [Z] Total Bytes: 6860070615, Total GB: 6.39
I0524 17:13:56.203522       1 networktrafficlogger.go:81]      [rtp-gateway-keyfigures-5f86f88cb6-tzfsm]
I0524 17:13:56.203526       1 networktrafficlogger.go:80]   -> Dest: 10.0.115.186, [] Total Bytes: 3614107191, Total GB: 3.37
I0524 17:13:56.203531       1 networktrafficlogger.go:81]      [rtp-persister-keyfigures-5c4fffc5c5-jtdxd]
I0524 17:13:56.203535       1 networktrafficlogger.go:80]   -> Dest: 10.0.61.27, [Z] Total Bytes: 3607816429, Total GB: 3.36
I0524 17:13:56.203543       1 networktrafficlogger.go:81]      [rtp-persister-keyfigures-5c4fffc5c5-6vzjw,priips-api-cronjob-restart-1653375900-7lqqc]
I0524 17:13:56.203565       1 networktrafficlogger.go:80]   -> Dest: 10.0.122.125, [] Total Bytes: 1056581916, Total GB: 0.98
I0524 17:13:56.203573       1 networktrafficlogger.go:81]      [rtp-persister-redis-68cf6446db-j2wbq]
```

In that log I see that the traffic from the source pod `kafka-cp-kafka-1` (zone a) with destination `10.0.66.197` (rtp-gateway-keyfigures-5f86f88cb6-6tp9b) (zone b)  gets flagged as cross-region when it should be flagged as cross-zone (same region, different zone). 
I have the CIDR `10.0.0.0/16` in the in-region snippet, as this is my VPC range.
I also have in the `direct-classification` mapping the `10.0.64.0/19` CIRD (10.0.64.0 - 10.0.95.255) as region: `us-east1` and zone: `us-east-1b`.

The node running the source `kafka-cp-kafka-1` has topology the labels:
```
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1a
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1a
```

And the destination node running `10.0.66.197` (rtp-gateway-keyfigures-5f86f88cb6-6tp9b):
```
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1b
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1b
```
As a extra comment, I also observe that I have metrics with the labels belonging to this pod (kafka-cp-kafka-1) with the labels, `internet="false", sameRegion="false", sameZone="false"` which points to this traffic being classified as cross-region.
EDIT:
I also found that I have some traffic labeled as `sameZone="true", sameRegion="false"` if its same zone it should always be same region

Something that seems to be working fine is the classification when it belong to the same AZ as the `10.0.32.0/19` CIDR (10.0.32.0 - 10.0.63.255) gets correctly classified as [Z]
`Dest: 10.0.46.116, [Z] Total Bytes: 6860070615, Total GB: 6.39 [rtp-gateway-keyfigures-5f86f88cb6-tzfsm]`

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
