### ISSUE TITLE
Failed to find machine pool for vCPUs

### ISSUE THREAD

**Issue by andrijaperovic** [opencost/opencost#596]
Running AKS cluster on version 1.17.11 with two node pools, one with 3 nodes Standard_D2s_v3 and one with 2 nodes Standard_D32s_v3, getting the following error message in the `cost-model` container of kubecost-cost-analyzer.
I've followed the instructions for creating the custom role for access to Billing RateCard API (http://docs.kubecost.com/azure-config): 

```
I1107 00:36:18.958197       1 log.go:47] [Info] Allocation ETL: build complete
I1107 00:36:18.963568       1 clustersizing.go:197] error: recommend machines: single pool strategy: failed to find machine pool for vCPUs: 23.242635 (0.280616 DaemonSet); RAM: 79.041598 GB (0.616155 DaemonSet); max pod: 4.000000 vCPUs, 10.000000 RAM GB with buffer 1.333333, min nodes 2
I1107 00:36:18.963602       1 clustersizing.go:207] error: recommend machines: multi-pool strategy: multi: cannot find acceptable node type for vCPUs: 23.242635 (0.280616 DaemonSet); RAM: 79.041598 GB (0.616155 DaemonSet); max pod: 4.000000 vCPUs, 10.000000 RAM GB
```

**Comment by dwbrown2** [comment]
@andrijaperovic thanks for sharing! Are you just seeing any unexpected behavior in the Savings view on the frontend or just these logs?

**Comment by andrijaperovic** [comment]
Hi @dwbrown2 of course! Thank you for the quick reply. 
I am expecting to see recommended node types in cluster-sizing.html, but am seeing static/daemonset/maxpod resources:
https://imgur.com/sCJeauC

**Comment by andrijaperovic** [comment]
Hi @dwbrown2 @nikovacevic - any updates on this? I think last we spoke you mentioned it is a feature set being prioritized for a future sprint.

**Comment by dwbrown2** [comment]
Hi @andrijaperovic! This work is now complete + in final stages of reviews. It's expect to be merged any day now and in our next release. @Sean-Holcomb can you share updates once they're available?

**Comment by dwbrown2** [comment]
Shipped in v1.74! Let me know if we can get you anything else here. We will continue to make investments in this feature.

**Comment by dwbrown2** [comment]
Closing for now, but please feel free to re-open for feature requests!

**Comment by andrijaperovic** [comment]
@dwbrown2 can we re-open this? Looks like this breaks with newest version of the helm chart (v1.94.2).

```
http://localhost:9090/model/savings/clusterSizingETL?window=2d&targetUtilization=0.75&minNodeCount=2&allowSharedCore=false&architecture=&req=1654907540784

error fetching current cluster information: could not fetch node types for provider(s): could not find node types for provider Azure (cluster: [cluster-one]): node prices file [/var/configs/azurenodeprices.json] not found

```

@Sean-Holcomb

**Comment by AjayTripathy** [comment]
Hi @andrijaperovic is this specifically when loading the cluster sizing html page? If so @biancaburtoiu can you take a look? I think this json file got removed in favor of hitting the Azure APIs directly...is this error expected if that API call fails?

**Comment by biancaburtoiu** [comment]
hello @andrijaperovic! Thanks for flagging this. We're periodically caching Azure pricing data in the /var/configs/azurenodeprices.json file. Could you try to restart your cost-analyzer pod? That should create and start populating this cache file. Let us know if that solves the issue.

cc @AjayTripathy the Azure API is currently periodically called in the background, the cache file is initialized at startup.

**Comment by andrijaperovic** [comment]
Hi @AjayTripathy, apologies for the late reply lost track of this issue. Yes, this happens specifically when loading the cluster sizing HTML page. @biancaburtoiu I restarted the cost-analyzer pod but looks like the issue is still present:
```
2022-07-09T16:43:25.171250419Z ERR savings: cluster sizing: error reccomending cluster sizing for cluster cluster-one: failed to recommend single pool cluster sizing: node prices file [/var/configs/azurenodeprices.json] not found
```

I'm observing some additional error messages as well:
```
WRN no pricing data found for eastus,standard_d8as_v4,ondemand: &{map[agentpool:micservices beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:standard_d8as_v4 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:eastus failure-domain.beta.kubernetes.io/zone:0 ...
```
Let me know if you require any additional information.

EDIT: 

I also see the persistent volume is near capacity so I'm wondering if I need to do any cleanup there or maybe configure the PV as a slow-resizable?
```
kubectl exec kubecost-cost-analyzer-7bc6dbf9fc-r5f2n df -n kubecost
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "cost-model" out of: cost-model, cost-analyzer-frontend
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay              129900528 102475296  27408848  79% /
```

**Comment by andrijaperovic** [comment]
@biancaburtoiu any reason why this issue was closed?

**Comment by AjayTripathy** [comment]
I'm expecting this was closed because it will be fixed in an upcoming release, but will check in with @biancaburtoiu

**Comment by biancaburtoiu** [comment]
hello @andrijaperovic - as Ajay noted, the fix should be included in v1.95, which will be out shortly. Once updated, please let me know whether the page loads as expected. Thanks for your patience!

**Comment by andrijaperovic** [comment]
Hi @biancaburtoiu,

I just installed helm chart v1.95.1. The cluster sizing recommendations are displaying correctly:
<img width="1403" alt="Screen Shot 2022-07-28 at 6 43 38 PM" src="https://user-images.githubusercontent.com/496024/181665557-5392cf9f-0047-4cfc-8833-a3906e19eb14.png">

thank you for the quick fix 💯 !

**Comment by andrijaperovic** [comment]
I did see that node count is not showing up for current cluster setup due to not being able to fetch current cluster information. I'll reopen for now and wait for your confirmation on that before closing the ticket. thanks!

**Comment by andrijaperovic** [comment]
Seeing a lot of `WRN` messages `no pricing data found for eastus,standard_d8as_v4,ondemand:`. @biancaburtoiu 
Also seeing various error messages for numerous deployments on the cluster which are also `WRN` level indicating `WRN SummaryAllocation: detected invalid sharing coefficient for cluster-one`.

**Comment by biancaburtoiu** [comment]
hello @andrijaperovic, I'm glad to hear that the initial problem got solved! 

Thanks for flagging the subsequent problem. ~I've raised a separate issue here: https://github.com/kubecost/kubecost-cost-model/issues/897~ 

Separate issue: https://github.com/opencost/opencost/issues/1339

**Comment by andrijaperovic** [comment]
Hi @biancaburtoiu - thanks for creating the issue! However the URL which you shared returns a 404.
perhaps it's a private repository?

**Comment by biancaburtoiu** [comment]
Thanks for pointing that out @andrijaperovic, it was a miss on my side. Please see the public issue here: https://github.com/opencost/opencost/issues/1339

**Comment by andrijaperovic** [comment]
Thanks @biancaburtoiu ! Closing this issue for now. Will continue the conversation on #1339
