### ISSUE TITLE
Savings - Kubecost recommends draining the only Windows node with pods on it 

### ISSUE THREAD

**Issue by MattJeanes** [opencost/opencost#661]
I have a Windows node in my cluster with taints and pods with node selectors for os = windows and therefore if the Windows node was to be removed there would be un-schedulable pods, but kubecost says "Safe to drain" on this node when I believe it shouldn't.

 ![image](https://user-images.githubusercontent.com/2363642/104484838-a7f78e00-55c1-11eb-9934-45494ee96a18.png)

**Comment by dwbrown2** [comment]
@MattJeanes great feedback. Definitely see your point. I wonder if we'll ever be able to perfectly predict all scenarios where OS/taints/tolerations, etc. may impact schedulability. Our simulator takes certain cases into account but not all. I'm wondering if we should consider to support a `safeToDrain=false` node annotation or label. 

Any input on what you would ideally like to see here?  

cc @AjayTripathy

**Comment by MattJeanes** [comment]
Well from my point of view I believe it should be at least able to detect taints, tolerations and node selectors, that seems relatively simple all the information exists within the cluster already to calculate this, and just determine if the node was deleted if it would result in un-schedulable pods

For more advanced scenarios some kind of manual annotation might be useful for some, but generally shouldn't be needed

**Comment by dwbrown2** [comment]
Yep, I agree. But there are certain cases where this may be hard to simulate. For example, a custom validating webhook that applies internal business logic may be difficult to account for. 

We'll plan to investigate further in a future sprint! Let me know if you have any other ideas or input. Thanks again for sharing!

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
