### ISSUE TITLE
Paginate return values from cache

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#776]
Our caches over 1d/7d/30d can grow to be quite large on big clusters. We should not return all data but instead paginate the API responses by default.

**Comment by dwbrown2** [comment]
+1, what API(s) do you feel are highest priority?

**Comment by AjayTripathy** [comment]
Assets is very likely highest priority because we dump all cloud assets into cache as line items, which is very big.

**Comment by dwbrown2** [comment]
If we add _sort_ flag then this should be straightforward?
   
Then requests params of `pageSize`,`pageNum`,`sortField` seem reasonable to me.

**Comment by mattray** [comment]
This is probably worthwhile for all API endpoints.

**Comment by AjayTripathy** [comment]
Caching work is probably outside of the spec of opencost-- users can store data themselves and caching has been carefully implemented in the community edition of kubecost.
