### ISSUE TITLE
Teams Notification

### ISSUE THREAD

**Issue by wrighbr** [opencost/opencost#781]
It would be nice to have a teams Notification Channel via a web hook

cheers

Brett

**Comment by dwbrown2** [comment]
@wrighbr thanks for the request! Is there any more detail you can share on your use case? For example, how are you organizing teams today in your environment and what notification data would be most useful for you?

**Comment by wrighbr** [comment]
@dwbrown2 we would like to make developers aware of the cost/saving that could make within k8s cluster.
I was thinking via a notification ie, teams channel (we don't use slack)

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using

I'm also open to a better way of doing so we don't get notification fatigue.
As we have start on journey with backstage.io it could be really nice to have integration with backstage

**Comment by dwbrown2** [comment]
@wrighbr oh I see what you mean! We should support any generic webhooks in our [alerts](https://github.com/kubecost/docs/blob/master/alerts.md). Have you explored those?

Would be great to get your input on backstage. We're hearing the request more and more often!

**Comment by obowersa** [comment]
Slightly older issue, but came across it while looking for something related.

Teams has two forms of integrations, channel level webhooks and then bot integrations.

The main difference (aside from bots being interactive) is bots can also be added to private chats. A suprisingly common use case for a lot of orgs. With that said, most folk just use channels + webhooks as the MS bot framework side of things is a little painful.

All that said, the the alerts approach works great for the webhooks integration with teams.

I couldn't see any specific docs on setting it up with teams, would it be valuable to have how to configure alerts for specific providers documented ? I could knock together the teams steps involved based on what we've got running at the moment.

**Comment by kirbsauce** [comment]
@obowersa , thanks for the offer!  We'd love to have something to provide to users who are interested in sending our alerts to Teams.  Let us know how we can help!

**Comment by obowersa** [comment]
No problem at all!

The only thing I'm not sure on is where it would be best placed. The kubecost docs side of thing is a pretty flat structure at the moment (one of the drawbacks with the architect theme for docs ). I'll raise a seperate issue against the docs page to raise the question on where best to place these kinda specific implementation details.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
