### ISSUE TITLE
Feature request: AWS External cost filtered by projectID

### ISSUE THREAD

**Issue by pierluigilenoci** [opencost/opencost#785]
In the case of AWS Organizations, the CUR is generated at the root account level and contains the costs of all resources of all sub-accounts. It would be desirable that, within a Kubecost instance, it was possible to choose to filter only the costs related to the account defined through `kubecostProductConfigs.projectID`

**Comment by dwbrown2** [comment]
Hi @pierluigilenoci looking forward to exploring this! 

@SheepGotoHeaven @AjayTripathy would this be a good candidate for new global filters? https://github.com/kubecost/cost-analyzer-helm-chart/pull/862

@pierluigilenoci just curious, have you looked at the new option from AWS where you can generate CURs for linked accounts?

**Comment by pierluigilenoci** [comment]
@dwbrown2 nope, would you be kind enough to tell me where I can find information about it? 

I found just this https://aws.amazon.com/about-aws/whats-new/2020/12/cost-and-usage-report-now-available-to-member-linked-accounts/ but it is a bit lacking in details.

**Comment by dwbrown2** [comment]
That AWS link + embedded references are actually the only resource I've ever seen actually...

**Comment by BrewToR** [comment]
Hello @pierluigilenoci, did you find a way to solve this problem ?
thank you

**Comment by pierluigilenoci** [comment]
@BrewToR no sorry. I gave up.
Maybe @dwbrown2 can let you know if there is any news about it.

**Comment by dwbrown2** [comment]
A number of users are doing this with either athena views or filtered saved reports. @BrewToR would either meet your needs?

cc @AjayTripathy while I'm out on vacation

**Comment by BrewToR** [comment]
Yes, it could meet my needs but :

- Athena View: How do you link a view or a database to a cluster into Kubecost ? It seems to be only global to the kubecost instance settings.

- Filtered Saved Reports : The only way to get both cost allocation and external costs assets is to use Advanced Reporting that is in Alpha and doesn't support aggregation by account ID that host the EKS cluster

**Comment by AjayTripathy** [comment]
This guide should have more detail on how to link a database to kubecost: https://github.com/kubecost/docs/blob/main/cloud-integration.md

**Comment by AjayTripathy** [comment]
@teevans can you look into what it would take for advanced reporting to support aggregation by els cluster account Id?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
