### ISSUE TITLE
Spot Instance Configuration settings get copied to GCP setup

### ISSUE THREAD

**Issue by iamgeef** [opencost/opencost#791]
Followed the Install instructions as per https://www.kubecost.com/install.html#show-instructions : 
```
kubectl create namespace kubecost
helm repo add kubecost https://kubecost.github.io/cost-analyzer/
helm install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="bWNzaGFuZTEwMUBnbWFpbC5jb20=xm343yadf98"
```  
helm version: v3.5.4+g1b5edb6  
Using EKS v1.17  

I've been trying to get GCP and AWS external cost allocation configured, added the correct values to the individual config pages, but still wasn't getting any data.

Checked the console logs and saw a few calls to google that were failing:

```
Unable to complete cost model request: {"code":500,"status":"","data":null,"message":"Error: error computing aggregate cost model: Unable to parse shared cost ncau-tech-mgmt: strconv.ParseFloat: parsing \"<MY_GCP_PROJECT_ID\": invalid syntax"}, error, Internal Server Error, 500, http://localhost:9090/model/aggregatedCostModel?window=2d&offset=1m&aggregation=service&allocateIdle=default&etl=true&rate=monthly&efficiency=true&req=757812
``` 

Diagnostics show green except for Spot, so I went to set that up and noticed that my GCP project ID had been automatically created in the Spot config: 

<img src="https://user-images.githubusercontent.com/10751405/117096018-45621200-adab-11eb-86af-42a579c7a7b4.png" width="400">

I changed the account ID to our AWS billing account ID, and then when I went into the GCP config the Project ID had changed to the AWS billing account ID: 

<img src="https://user-images.githubusercontent.com/10751405/117096114-74788380-adab-11eb-947c-b4f974f337c5.png" width="400">

Updating the GCP project again and the Spot settings changed replacing the aws accout id with the gcp id.

I haven't changed any settings outside of trying to get the external cost allocation for AWS and GCP working.

**Comment by iamgeef** [comment]
I've just noticed that when I set this value in the values.yml file:

![image](https://user-images.githubusercontent.com/10751405/117100229-93304780-adb6-11eb-9a9c-f6d511bb8400.png)

It is being used for both AWS account ID value in Spot Feed Configuration **and** the GCP ProjectID value in the GCP config.

**Comment by AjayTripathy** [comment]
Hi @iamgeef -- thanks so much for this report. It sounds like you're trying to view AWS and GCP external costs on the same k8s cluster-- is that right? 

I'll get this prioritized. We can definitely do a better job supporting cross-cloud provider usecases here, but in the meantime as a workaround, does this work when not setting up the spotdatafeed?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
