### ISSUE TITLE
How to re-subscribe an email unsubscribed from the notification emails?

### ISSUE THREAD

**Issue by pierluigilenoci** [opencost/opencost#792]
At the bottom of the notification emails, there is the link to be removed from the notifications. By clicking, you end up on SendGrid, and you are unsubscribed. 

![Screenshot from 2021-05-05 16-24-59](https://user-images.githubusercontent.com/36044817/117158909-1dc97480-adc0-11eb-84c2-18af7ad73ad4.png)

If someone changes his mind, however, there is no way to be added again.
I tried reapplying the configuration with the setNamespaceAttributes API but without success.

How to solve?

**Comment by dwbrown2** [comment]
@pierluigilenoci you're right that this isn't self-serve today. You can email team@kubecost.com if you'd like to have yourself manually resubscribed. 

@AjayTripathy was going to investigate making this self-serve. Ajay, can share updates as they are available?

**Comment by pierluigilenoci** [comment]
@dwbrown2 thank you, but it is not so much for the email that has been unsubscribed, but for the fact that I would like end-users to be able to handle it without the need for external help.

I will wait until it can be managed on my own before implementing this in our clusters.

Please, keep me posted.

**Comment by dwbrown2** [comment]
Sounds good, @pierluigilenoci. Totally understand the need. Just let us know you do need manual help in the short-term, while @AjayTripathy investigates!

**Comment by pierluigilenoci** [comment]
@dwbrown2 wrote it in the Slack Support Channel. Thanks.

**Comment by pierluigilenoci** [comment]
@dwbrown2 any news about this?

**Comment by AjayTripathy** [comment]
No updates or ETA here, it's still on our list though.

**Comment by pierluigilenoci** [comment]
@AjayTripathy any update?

**Comment by dwbrown2** [comment]
We've not had a single request since yours @pierluigilenoci. Still low priority for now.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
