### ISSUE TITLE
Re-visit Abandoned Disks/Abandoned Loadbalancer features

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#794]
The Abandoned Disks/Abandoned Loadbalancer features need a revisit. They predate the Assets pipeline and multicluster kubecost views.

Option 1  could be to use the Assets pipeline on AWS and Azure by enumerating cloud data from the Assets pipeline and diffing it against the data on the Allocation pipeline.  This presents problems on GKE or any cloud provider where reconciliation is made difficult with nonmatching providerIDs, however.

Option 2 would be to expand our permissions to get ec2/computeengine access and diff the assets as they exist in your cloud provider with what we see in prometheus. This is what we do today, but it will need to be updated to use our new authentication paths (https://github.com/kubecost/cost-model/issues/266) and  use the multicluster promql endpoint where needed.

**Comment by dwbrown2** [comment]
Can you share what you view as the issues with the current implementation and why it need to be revisited?

**Comment by AjayTripathy** [comment]
1. It seems at the very least we need to make a change to migrate it to use a new authentication flow as reported in #266
2. Needs an expansion of permissions to view compute resources-- the less permissions users have to configure the better. I wanted to at least discuss the possibility of doing this fully through "reconciliation" of k8s data and the CUR-- that is, mark a a disk  or LB that hasn't been tagged and isn't auto-reconciled with k8s data for investigation.
3. On 2/3 cloud providers (those for which we support automatic reconciliation) we can do better at informing the users what's going on by looking at k8s for providerIDs. You may, for example, have an "orphaned" disk for which you've set a "retain" policy. That disk may not be truly be orphaned, but the context of the retain policy on the k8s side is meaningful.

**Comment by mattray** [comment]
@AjayTripathy @dwbrown2 do you think this is still relevant to OpenCost, or is this to be addressed on the Kubecost side?

**Comment by dwbrown2** [comment]
This isn't currently relevant to OpenCost, also I believe it's underway for Azure. cc @AjayTripathy

**Comment by AjayTripathy** [comment]
We are revisiting the API, but yes this is on the kubecost side.
