### ISSUE TITLE
Data doesn't persist more than one day?

### ISSUE THREAD

**Issue by DerrickMartinez** [opencost/opencost#806]
Not sure if this is intentional or just misconfiguration. But data (reports, assets etc) only seems to persist a single day. How long should it persist for the free community version?

**Comment by dwbrown2** [comment]
@DerrickMartinez should persist for 15-days by default. This assumes that PVs are enabled and no long-term storage setup. Happy to review a [bug report](http://docs.kubecost.com/bug-report) if you want to send one to support@kubecost.com or can provide input on this issue. Just let us know what is best!

**Comment by dwbrown2** [comment]
@DerrickMartinez can we help further here? Just let me know if we can!

**Comment by mattray** [comment]
Closing unless this is still a valid issue.
