### ISSUE TITLE
Grafana not loading data (missing "cluster" source)

### ISSUE THREAD

**Issue by kbrwn** [opencost/opencost#813]
![bad-grafana](https://user-images.githubusercontent.com/4100493/119704754-df4a3700-be0c-11eb-8f3a-94e0f98e4d63.gif)

gz#302

**Comment by dwbrown2** [comment]
I was able to reproduce this with @AjayTripathy. He's investigating.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/921
