### ISSUE TITLE
INR currency conversion not working

### ISSUE THREAD

**Issue by kbrwn** [opencost/opencost#822]
After selecting INR as the Currency in /setting.html and saving the only change in the kubecost UI is the currency symbol. The numbers are still in USD.

gz#359

**Comment by mattray** [comment]
@AjayTripathy @dwbrown2 Could you please confirm that currency is a descriptive label and no currency conversions are actually implemented?

From the Kubecost UI:
"Currency conversion applied to Azure cloud pricing, but currency codes shown for display purposes in other environments."

**Comment by AjayTripathy** [comment]
Confirmed; currency is a descriptive label. It is beyond the scope of the open source project to do currency conversions
