### ISSUE TITLE
Namespaces grouping

### ISSUE THREAD

**Issue by xhejtman** [opencost/opencost#834]
It would be great, if we can group all system namespaces into a single one aliased System, so we have a single item as system costs and we can focus on user's namespaces.

gz#398

**Comment by kbrwn** [comment]
hi @xhejtman this info is available in the "Totals" row when viewing cost allocation by namespace. You can also select "Cluster" from the breakdown menu which shows the combined cost of all namespaces across the cluster(s).

**Comment by xhejtman** [comment]
that is not exactly what we would like to see here. We would like to see something like permanently group some of namespaces. E.g., the system ones. So nowhere in overview you find kube-system ns. Only System ns.

**Comment by kbrwn** [comment]
@xhejtman you are able to create a cost allocation report with a filter on namespaces. I suggest you create one for the various "system" namespaces and then save it so you can go back and review regularly.

**Comment by xhejtman** [comment]
But I cannot do it for Overview and Cost allocation dashboard, can I?

**Comment by dwbrown2** [comment]
I agree with Kyle on filters being one good solution. You can also add _namespace labels_ and group by this this label. You can do both approaches on the the Cost allocation dashboard + Saved Reports. Not yet on Overview.

**Comment by xhejtman** [comment]
can I filter like *-ns ? to mach any namespace ending with -ns ?

**Comment by dwbrown2** [comment]
We currently support wildcards at the end of a filter string. 

cc @SheepGotoHeaven who is reviewing more advanced filter options.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
