### ISSUE TITLE
Support Tencent Cloud Provider's TKE  kubernetes

### ISSUE THREAD

**Issue by kitianFresh** [opencost/opencost#859]
Hi Team, recently i am developing [tencent cloud](https://cloud.tencent.com/) which is a top2 cloud provider in China.  

I can contribute the tencent cloud provider for kubecost. and now i am testing my code.

@AjayTripathy 

gz#503

gz#479

**Comment by dwbrown2** [comment]
That is great to hear, @kitianFresh! Looking forward to reviewing and helping you get this merged as soon as you are ready.

**Comment by ivankube** [comment]
@kitianFresh are you still working on this issue? Thanks!

**Comment by dwbrown2** [comment]
We're seeing a growing number of users ask for Tencent support!

@AjayTripathy weren't you working on a PR with @kitianFresh?

**Comment by AjayTripathy** [comment]
@kitianFresh just wanted to ping this in case you're ready to pick it back up and submit a PR! It would be a priority for us to review!

**Comment by kbrwn** [comment]
@kitianFresh If you have any code that you would like to share on this we would be happy to take a look. Even if you have not finished implementation. You can also email it to support@kubecost.com if you would prefer.
