### ISSUE TITLE
Allow asset queries to filter on null/undefined values

### ISSUE THREAD

**Issue by kaelanspatel** [opencost/opencost#876]
Currently there is no way to filter on a value that doesn't exist (i.e. it's not possible to agg and get only assets without a provider ID, cluster, account, etc). This also prevents drilling down into unallocated/undefined rows in the frontend.

gz#598

**Comment by Adam-Stack-PM** [comment]
@kirbsauce Still relevant or can we close?

**Comment by kirbsauce** [comment]
It appears all PRs are merged, so yes, let's close.
