### ISSUE TITLE
3rd Party Controller (Argo Rollouts) cost allocations

### ISSUE THREAD

**Issue by fujin** [opencost/opencost#879]
Hi,

I have recently setup kubecost in my work environment. We have it running in a single cluster (for evaluation), with external costs at GCP going into BigQuery.

Some of our software makes use of the [Argo Rollouts](https://argoproj.github.io/argo-rollouts/) projects and object (`Rollout`) for progressive delivery and canary analysis. It mostly works like a normal Deployment with additional facilities for experimentation or analysis, as well as phases; it "owns" replica sets.

I noticed that in the Controller Allocations chart, that kubecost is not currently recognising these controllers.
<img width="816" alt="Screen Shot 2021-07-28 at 8 16 17 AM" src="https://user-images.githubusercontent.com/6873/127221439-285d0dbd-5933-49b5-abb2-447e6f9820d8.png">

Is it possible to customize or extend the supported controllers here? Could it perhaps look at replicasets rather than deployments, such that any other system that manages replicasets/widths would be compatible?

cheers!

gz#615

**Comment by dwbrown2** [comment]
Hi @fujin, thanks for the report! It's my understanding that Argo deploys these pods with a CRD. Is there any chance you could share one your example YAML specs? Kubecost would be by default for ownerReferences/Kind directly in the spec. We should be able to leverage the ReplicaSet that is actually controlling but it may be using a custom defined field. 

Also, you should be able to compare/join costs for these rollouts by either label or annotation on other views of cost + efficiency metrics in Kubecost. 

cc @nikovacevic

**Comment by fujin** [comment]
I'm working on labelling/annotating things properly to suit the default configuration now. Unfortunately, I'm not able to share one of our complete Rollout specifications (proprietary).

Hopefully instead, this maybe helpful? I have Argo Rollouts in my local KinD cluster and created their sample Rollout, output follows.

```╰─ kubectl get rollout                                                                                                                                                                                                                                    ─╯
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE
rollouts-demo   5         5         5            5
╭─ ~ ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  kind-kind ○  14:11:30 ─╮
╰─ kubectl get replicaset                                                                                                                                                                                                                                 ─╯
NAME                       DESIRED   CURRENT   READY   AGE
rollouts-demo-6668595956   5         5         5       81s
╭─ ~ ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  kind-kind ○  14:11:33 ─╮
╰─ kubectl get pod                                                                                                                                                                                                                                        ─╯
NAME                             READY   STATUS    RESTARTS   AGE
rollouts-demo-6668595956-57rd9   1/1     Running   0          84s
rollouts-demo-6668595956-f9vhn   1/1     Running   0          84s
rollouts-demo-6668595956-glqvr   1/1     Running   0          84s
rollouts-demo-6668595956-jhjwh   1/1     Running   0          84s
rollouts-demo-6668595956-pkjxp   1/1     Running   0          84s
```

The Rollout object in YAML form here:
``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","metadata":{"annotations":{},"name":"rollouts-demo","namespace":"default"},"spec":{"replicas":5,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"rollouts-demo"}},"strategy":{"canary":{"steps":[{"setWeight":20},{"pause":{}},{"setWeight":40},{"pause":{"duration":10}},{"setWeight":60},{"pause":{"duration":10}},{"setWeight":80},{"pause":{"duration":10}}]}},"template":{"metadata":{"labels":{"app":"rollouts-demo"}},"spec":{"containers":[{"image":"argoproj/rollouts-demo:blue","name":"rollouts-demo","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"requests":{"cpu":"5m","memory":"32Mi"}}}]}}}}
    rollout.argoproj.io/revision: "1"
  creationTimestamp: "2021-07-28T02:10:11Z"
  generation: 1
  name: rollouts-demo
  namespace: default
  resourceVersion: "24242"
  uid: ade881f1-74be-46ea-afcd-55b676737064
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 10
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: rollouts-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
status:
  HPAReplicas: 5
  availableReplicas: 5
  blueGreen: {}
  canary: {}
  conditions:
  - lastTransitionTime: "2021-07-28T02:10:30Z"
    lastUpdateTime: "2021-07-28T02:10:30Z"
    message: RolloutCompleted
    reason: RolloutCompleted
    status: "True"
    type: Completed
  - lastTransitionTime: "2021-07-28T02:10:11Z"
    lastUpdateTime: "2021-07-28T02:10:30Z"
    message: ReplicaSet "rollouts-demo-6668595956" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-07-28T02:10:30Z"
    lastUpdateTime: "2021-07-28T02:10:30Z"
    message: Rollout has minimum availability
    reason: AvailableReason
    status: "True"
    type: Available
  currentPodHash: "6668595956"
  currentStepHash: f64cdc9d
  currentStepIndex: 8
  observedGeneration: "1"
  phase: Healthy
  readyReplicas: 5
  replicas: 5
  selector: app=rollouts-demo
  stableRS: "6668595956"
  updatedReplicas: 5
``` 
  
That is created from https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/basic/rollout.yaml

**Comment by dwbrown2** [comment]
Thanks, @fujin! This is what I expected.. CRD without direct owner reference in the spec. Kubecost will provide accurate cost calculations here when aggregated by label, namespace, annotation, etc. but let us explore options for owner/controller agg. 

Let us know if you have any suggestions on what you'd like to see!

**Comment by kbrwn** [comment]
@fujin We have more more info about argo+kubecost here: https://docs.google.com/document/d/1JmvkyJe0iJ8TFGX3fT5kP_S6jB_CJ6u_yn9H0YH03So/edit

**Comment by fujin** [comment]
@kbrwn thanks! though this issue is around [Argo Rollouts](https://argoproj.github.io/argo-rollouts/) (separate part of the "argo suite".).

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
