### ISSUE TITLE
Add additional breakdown and filter for cloud/location

### ISSUE THREAD

**Issue by srpomeroy** [opencost/opencost#921]
I feel there would be value in adding an additional breakdown and filter so I can view my clusters by what cloud or datacenter(on-prem) they reside in. Additionally, it would be nice if there was a quick visual indicator when viewing the breakdown by cluster to see where each is running.

Poor Example of visual indicator: 
![image](https://user-images.githubusercontent.com/15660532/132410639-75d0f9ab-e76d-4a84-8967-3755464eaf4d.png)

gz#774

**Comment by dwbrown2** [comment]
Love this idea! 

@Sean-Holcomb don't we already support breakdown by cloud provider? I thought we did but don't see it supported on our nightly build.

**Comment by Sean-Holcomb** [comment]
Break down by provider is supported for assets, although there are some slight caveats with this. Provider is not currently a field in allocation properties. To add this we would need to update Allocation properties and then emit the value in one of our pod metrics, once there it could be added to allocations in the ETL, where it could then be used for a breakdown. I believe this change would require a bingen update.

**Comment by AjayTripathy** [comment]
We should be able to guess based on providerID, no? You could have func() ClassifyProvider(Asset) that just takes a best guess...we'd be accurate in like 99% of cases.

**Comment by Sean-Holcomb** [comment]
There is probably a workaround here somewhere that involves a second query, but these are allocation cluster aggregates, they only keep properties that they all share (cluster in this case). Unfortunately cluster is an arbitrary string. It would have to be some sort of non-aggregated query, but it does look like there `func() ClassifyProvider(Allocation)` would be possible though if you did that.

**Comment by Sean-Holcomb** [comment]
There is a solution to this issue, but it is pending schema upgrade

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
