### ISSUE TITLE
Net Amortized Costs

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#954]
This feature request is to add net amortized costs calculations.  

Net amortized costs adds logic to amortize discount-related information, in addition to savings plans or reservation-related charges.  For example, it amortizes the upfront and monthly reservation fees while including discounts such as RI volume discounts.

gz#848<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/878'>Zendesk ticket #878</a>)<br>gz#878</i>

**Comment by dwbrown2** [comment]
@AjayTripathy would you be able to comment? I know you have a lot of expertise + wrote some documentation.

**Comment by AjayTripathy** [comment]
Yep! This was a request that seems pretty reasonable. Net unblended costs are incompatible with our model but this is relatively simple. We'll get this prioritized and done.. cc'ing @Sean-Holcomb who is refactoring some things here in our Assets schema to make this stuff simple.

**Comment by kbrwn** [comment]
goal: net amortized cost which includes also the EDP discount

in use: 

```
line_item_unblended_cost
savings_plan_savings_plan_effective_cost
reservation_effective_cost
```

need to use: 

```
line_item_net_unblended_cost
savings_plan_net_savings_plan_effective_cost
reservation_net_effective_cost
```

**Comment by dhoffman3** [comment]
I have a comment about it.
Starting 1/10/2021, I have a new EDP plan with full upfront.
Apparently, AWS has limitation that in this specific case, they use a manual mode for discount to update the billing and I just learned they pulled out the net fields from my schema.
AWS told me they plan to fix it also for this scenario.
As such, I suggest that you will have a checkbox in your setting indicating if to apply the net fields or not.
If you do that, your customers can select if they need to take into consideration the net fields or not and then you can support all cases.

**Comment by Sean-Holcomb** [comment]
Adding my comment from the ZD ticket here
> As far as I can tell 
> ```
> line_item_net_unblended_cost
> savings_plan_net_savings_plan_effective_cost
> reservation_net_effective_cost
> ```
> Are not real columns in the CUR, they do not exist in our CUR and they are not in any of the documentation.
See the section "Net amortized costs"[ on this AWS doc page](https://docs.aws.amazon.com/cost-management/latest/userguide/ce-advanced.html).
> 
> This page refers to an option in the Cost Explorer in the AWS console. The documentation for what is available in the CUR 

It is still unclear to me if the available information in the CUR can create the desired values

**Comment by Sean-Holcomb** [comment]
Revisited the CUR documentation today and saw that they have added the required "net" columns to implement this function. My proposal is to use these columns for pricing when they are available.

**Comment by srpomeroy** [comment]
Have we implemented, or are there any plans to implement the use of the net amortized costs?

**Comment by Adam-Stack-PM** [comment]
@Sean-Holcomb Could you confirm we have not implemented this yet ?@srpomeroy, if we have not, there is no current plans to add this. However, if you feel strongly about it please let me know.

**Comment by Sean-Holcomb** [comment]
We have not implemented it

**Comment by AjayTripathy** [comment]
Candidate for v1.98?

**Comment by keithhand** [comment]
Curious if this got implemented. I recently had another user mention this.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1869 Let's move tracking here. This is sort-of beyond the scope of opencost.
