### ISSUE TITLE
How can one use Kubecost to tune requests for Argo Workflows?

### ISSUE THREAD

**Issue by alexec** [opencost/opencost#969]
Our users often run workflows with large pods, the need lots of CPU/GPU/memory. 

I'd like to show users how to optimise these workflows. I'm not an expert on tuning requests, I'm more like a user myself. So as a user I want to know:

* How do I know which workflows are costly?
* How should I tune the workflow?
* How can I monitor cost change over time?

Would anyone be interested in help me out with this please?

**Comment by dwbrown2** [comment]
@alexec i'd absolutely love to see Kubecost support this and also provide content! 

have you seen the integration with spinnaker? https://blog.kubecost.com/blog/spinnaker-kubecost-integration/

i've talked with half a dozen join users that also expressed interest in something similar to this. let me know if'd want to chat about it or if there is more you can share!

**Comment by dwbrown2** [comment]
Great, I just grabbed time. Sorry for my delay... I recently had a kid, and have been... busy!

**Comment by dwbrown2** [comment]
@alexec saw this was meeting was canceled on the argo side. know if that was intentional?

**Comment by kbrwn** [comment]
agro v2.2 now has a more specific annotation to track resources:

```
  annotations:
    argocd.argoproj.io/tracking-id: my-app:apps/Deployment:default/nginx-deployment
 ```

**Comment by dwbrown2** [comment]
@alexec draft outline available here! https://docs.google.com/document/d/1JmvkyJe0iJ8TFGX3fT5kP_S6jB_CJ6u_yn9H0YH03So/edit

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
