### ISSUE TITLE
Support for additional regions in Azure

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#984]
The following region from Azure needs support:

norwayeast

#gz739

**Comment by dwbrown2** [comment]
@kirbsauce any input on priority here? Not sure if @Sean-Holcomb has taken a look yet.

**Comment by kirbsauce** [comment]
Yep...usgovvirginia is being addressed by https://github.com/kubecost/cost-model/issues/990, PR being https://github.com/kubecost/cost-model/pull/994 and is pending review.  interested parties updated earlier this morning.

**Comment by mattray** [comment]
Looks like it was fixed in https://github.com/opencost/opencost/pull/996
