### ISSUE TITLE
[FEATURE] Ingress Calculation

### ISSUE THREAD

**Issue by janlauber** [opencost/opencost#995]
Dear Kubecost Team/Community

Is there any ingress calculation planned?
Because it would be awesome to collect all ingress ressources and calculate them with a fix price per month per instance(team, namespace, whatever just like CPU/RAM/Storage).  

Thanks and greez

gz#1063

**Comment by kbrwn** [comment]
hello @janlauber thanks for the request. Are you thinking of a like a fixed price per ingress k8s resource or some other metric for allocation? Kubecost collects network and cloud metrics to allocate cost for ingress related objects such as load balancers. Cloud/LB cost are usually the variable cost associated with ingress resources.

**Comment by janlauber** [comment]
Hey @kbrwn 
I think about a fix cost we define for our onPrem cluster environment.
Since we are using the Citrix ADC in front of our clusters as an ingress/load balancer, we want to add a fixed amount to each ingress resource (we need to pay our license for the Citrix ADC o.c.).

**Comment by dwbrown2** [comment]
Hi @janlauber 

The network costs daemonset has actually been emitting ingress metrics for many releases. So you should be able to see these in raw prometheus metrics if interested in exploring. However, we don't yet consume it into our ETL pipelines yet. It's definitely something we'd like to consider in the future.

**Comment by korjek** [comment]
we are also interested in ingress cost, because AWS charges for both ingress and egress traffic from/to EC2 instance (sure, there are some exceptions like communication with ALB is free of charge, but still).

**Comment by dwbrown2** [comment]
We're going to discuss bringing this into ETL after this upcoming release... were the Prometheus metrics helpful here?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
